### ISSUE TITLE
Building Permits - RESBLDG - Condo Parent/Unit Sprinkler Requirements

### ISSUE THREAD

**Issue by JuanitaMiles** [dhenry-KCI/FredCo-Post-Go-Live-#10]
Parent AP # 192752
Unit AP #'s 192753; 192768
RESIDENTIAL BUILDING PERMIT - RESIDENTIAL CONDO

**The unit applications listed above have already been moved forward in the Production environment but the issue can be seen in the Test environment.

The two units are being held up for a Sprinkler Permit. Per Abbie's comments to Ashlye in the email below, units should not be held up for a sprinkler permit. For Condos the Parent structure should only carry this requirement. The Parent listed above has two Fire permits listed as child applications (one for fire suppression, and one for fire alarms).

![image](https://user-images.githubusercontent.com/31770504/70917255-fc10f700-1fea-11ea-8ef3-3022014a63f6.png)

**Unit Example:**
![image](https://user-images.githubusercontent.com/31770504/70916728-27471680-1fea-11ea-80d1-c40acf92707c.png)

![image](https://user-images.githubusercontent.com/31770504/70916787-3b8b1380-1fea-11ea-8d0c-041774a7b178.png)

![image](https://user-images.githubusercontent.com/31770504/70916836-4e9de380-1fea-11ea-9747-0ab4aaf4893c.png)

**Parent:**
![image](https://user-images.githubusercontent.com/31770504/70916958-7b51fb00-1fea-11ea-8368-3a930135cfc2.png)

![image](https://user-images.githubusercontent.com/31770504/70917023-9cb2e700-1fea-11ea-9d76-d6f9622aa564.png)

**Comment by megisys** [comment]
Need to move BP_SprinklerPermitChildPermitReq_SCF Tonight
