### ISSUE TITLE
BOND - Budget Numbers are wrong - DUSTIN

### ISSUE THREAD

**Issue by AReed327** [dhenry-KCI/FredCo-Post-Go-Live-#100]
Dustin - The budget numbers were not updated. There was supposed to be a table that you were going to update I believe.
REPORT: Planning - Daily Receipts/Road Escrow
![image](https://user-images.githubusercontent.com/58854333/71279514-fedf5500-2326-11ea-86e6-9e0ea7237006.png)

**Comment by megisys** [comment]
This is not a table. I spoke about this prior to go live. It isnt actually a budget number. It is a string field which someone decided to enter a budget number. These will need to be manually adjusted by the county.

Dan

**Comment by JuanitaMiles** [comment]
need someone to input the correct bond string. need to follow up.

**Comment by AReed327** [comment]
I will update as time allows. Closing ticket
