### ISSUE TITLE
Grading_Permits_-_Expiration_Notice Report showing SubReport Error

### ISSUE THREAD

**Issue by ScottVanSooy** [dhenry-KCI/FredCo-Post-Go-Live-#101]
[Grading_Permits_-_Expiration_Notice_HANSEN8_20191220_125138442.pdf](https://github.com/dhenry-KCI/FredCo-Post-Go-Live-/files/3989597/Grading_Permits_-_Expiration_Notice_HANSEN8_20191220_125138442.pdf)

**Comment by TaraF** [comment]
This is fixed.  @ScottVanSooy and @dhenry-KCI  - I am not sure who reported this, if it was Tiffany / Eric / Emily, - but can one of you contact the appropriate person so they can re-test?  Thanks!

**Comment by dhenry-KCI** [comment]
@TMARTIN0926 - this has been addressed. please retest.

**Comment by JuanitaMiles** [comment]
I have tested both of the expiration notice letter reports by running manually in IPS. Subreport error appears to be fixed. Closing for now. (JM 1/3/2020)

![image](https://user-images.githubusercontent.com/31770504/71733745-45997880-2e18-11ea-9e48-d028ec9e3ddc.png)

![image](https://user-images.githubusercontent.com/31770504/71733782-5f3ac000-2e18-11ea-8472-d404394cfd3a.png)
