### ISSUE TITLE
R4C slow 

### ISSUE THREAD

**Issue by ABonomo21** [dhenry-KCI/FredCo-Post-Go-Live-#102]
this is the customer that had a very very slow r4c- 

portal id - and9300@aol.com

**Comment by calequin** [comment]
We are going to do some clean up and rebuild tonight to hopefully fix some of the speed issues. Although, this customer has 21+ applications in the inspection milestone. This has been proven to cause slowness in rhythm and should be fixed with the January release of the product.

**Comment by ABonomo21** [comment]
closing this ticket for this applicant but i think R4C speed is an issue and will create a new ticket as we receive complaints and information from customers
