### ISSUE TITLE
Residential fee on a Non Residental permit- electrical permits

### ISSUE THREAD

**Issue by awhite806** [dhenry-KCI/FredCo-Post-Go-Live-#103]
The residental minimum fee is not applicable to a non residential permit.

![image](https://user-images.githubusercontent.com/58981029/71286237-276e4b80-2335-11ea-9615-e3bd83b43b5a.png)

**Comment by ABonomo21** [comment]
this needs to be corrected

**Comment by ScottVanSooy** [comment]
I removed it from the Electrical Permit.  I'd like clarification on what other Types to remove it from.  IE, Plumbing, etc.  Perhaps everything except RESBLDG?

**Comment by ABonomo21** [comment]
test in test environment

**Comment by ABonomo21** [comment]
This failed, tested 259817 still generated the residential min fee which is n/a

**Comment by calequin** [comment]
fixed in another ticket

**Comment by ABonomo21** [comment]
this is fixed 
![image](https://user-images.githubusercontent.com/47611580/72009947-e75c0380-3224-11ea-94a2-c407ac0e4767.png)
