### ISSUE TITLE
Inspection Requested after cutoff Time

### ISSUE THREAD

**Issue by emilypearl1** [dhenry-KCI/FredCo-Post-Go-Live-#104]
Plumbing Permit 257905 was requested for a gas final inspection on the portal @ 1:45. The system allowed the user to request it. I confirmed that the inspection showed up in IPS as requested in the portal for monday 12/23/19. This inspection was requested after the 12pm cutoff time.

**Comment by ScottVanSooy** [comment]
This is the formula: BP_ScheduleInspection_BU

This is the code block.  Debugging now

If oInspection.UserInfo.UserName = "RWEBUSER" Then
		' UserWarning will allow the event to continue processing
		res = New Result(0, ResultSeverity.Warning, String.Format("WEB INSPECTION REQUEST Server Date - {0}, CallDate - {1}", ServerApplication.GetDateNow(), oInspection.CallDateTime))
		If ServerApplication.GetDateNow().Hour > 12 Then
			Dim dt As Date = Date.Parse(oInspection.CallDateTime)
			Dim dateString = dt.ToShortDateString()
			Dim ndt As Date = Date.Parse(ServerApplication.GetDateNow().AddDays(1))
			Dim ndateString = ndt.ToShortDateString()
			If dateString = ndateString Then
				res = New Result(0, ResultSeverity.UserError, "Can't Schedule for Tomorrow the cut off is 12pm the day before")
				Return res
			End If
		End If
	End If

**Comment by ScottVanSooy** [comment]
Promote BP_ScheduleInspection_BU to Prod and rebuild

**Comment by ScottVanSooy** [comment]
Modified BP_ScheduleInspection_BU and USE_ScheduleInspection_BU In Prod 12/23/19

**Comment by ABonomo21** [comment]
have not received any further calls about inspections being scheduled after the cut off.
