### ISSUE TITLE
SRM - Building Permits - Lookup Applications - duplicate report to be removed

### ISSUE THREAD

**Issue by TaraF** [dhenry-KCI/FredCo-Post-Go-Live-#108]
Please remove "School and Library Impact Fees by Date Range" report from PROD, as it is a duplicated report and already present under another name.

See:  SRM - Building Permits - Lookup Applications
![image](https://user-images.githubusercontent.com/4104464/71366135-23c60900-256f-11ea-951c-07b10ac333d8.png)

**Comment by ScottVanSooy** [comment]
Changes made 12/23/19.

**Comment by JuanitaMiles** [comment]
Appears fixed (Tested by JM 1/2/20)

![image](https://user-images.githubusercontent.com/31770504/71676720-f20f2800-2d4e-11ea-891a-42993499ae28.png)
