### ISSUE TITLE
RESBLDG town house

### ISSUE THREAD

**Issue by ABonomo21** [dhenry-KCI/FredCo-Post-Go-Live-#109]
parent town house did not generate impact fess because the condition for the children to be issued before the parent can progress is at the wrong milestone- should go to add fees to generate the impact fees and then the condition should stop at pending issuance milestone 

![image](https://user-images.githubusercontent.com/47611580/71366786-0c881b00-2571-11ea-9ad4-d15acb3e91ff.png)

![image](https://user-images.githubusercontent.com/47611580/71366801-1742b000-2571-11ea-8c3d-eb5b378dc280.png)

**Comment by ABonomo21** [comment]
here is another one i had to supervisor override... 
![image](https://user-images.githubusercontent.com/47611580/71369188-faf64180-2577-11ea-8fcd-ce191c38d0d7.png)

**Comment by ScottVanSooy** [comment]
I moved this in Test,   Should I confer with Christian before making the changes in Prod?

Moved 
Child Permits must be Issued before Building Permit can progress 
From Under Review to Pending Issuance
Formula: BP_RESBLDG_ChildrenIssued_SCF

**Comment by ScottVanSooy** [comment]
Re-Apply to test

**Comment by ScottVanSooy** [comment]
add to related ticket

**Comment by calequin** [comment]
fixed in production

**Comment by ABonomo21** [comment]
259201 got stuck... 
![image](https://user-images.githubusercontent.com/47611580/72540987-bba5d280-384f-11ea-80d4-b3d0154ab85a.png)

**Comment by ABonomo21** [comment]
the condition needs to be moved to awaiting applicant payment to allow for the impact fees to generate

**Comment by calequin** [comment]
promote BP_RESBLDG_ChildrenIssued_SCF
create status check formula under Awaiting Applicant Payment milestone - formula name - BP_RESBLDG_ChildrenIssuedTown_SCF and unexpire status check

**Comment by calequin** [comment]
please test in TEST http://wh-ipsdevtst/IPS_test/ and then label Needs Promotion if it passed
