### ISSUE TITLE
Building Permits - Fire Permit - Electrical Permit Requirements

### ISSUE THREAD

**Issue by JuanitaMiles** [dhenry-KCI/FredCo-Post-Go-Live-#11]
FIRE PERMIT - RESIDENTIAL TOWNHOME
AP # 199259

**This permit has been progressed in the Production environment but the issue can be seen in the Test environment.

Emily reported that this permit is being held up for a Electrical permit when it should not. 

![image](https://user-images.githubusercontent.com/31770504/70919501-f4535180-1fee-11ea-946e-1a9866d8d636.png)

![image](https://user-images.githubusercontent.com/31770504/70919556-0d5c0280-1fef-11ea-8b24-06935426929f.png)

(per email Emily sent to Ashlye 12/13/19 8:40 am)

**Comment by megisys** [comment]
TO MIGRATE Tonight
'  Formula Name: FIRE_ElecChildPermReq_SCF
'  Description: Attach an electical child perm  
'  Created By: Supriya Bari
'  Created On: 07/21/2018
'
'  Revisions
'  ---------
'  SB - Initial Design
'  IM - fixed permit type reference to oFireAlaramDetail.FirePermitType

StateCheck = False

Dim childElec as boolean

For Each ChildBLD as Hansen.CDR.Building.IParentChildRelationship in oBldgApp.ChildrenRelationships

	If ChildBLD.ChildApplication.ApplicationType.ApplicationType = "ELECPERM" Then
	
		childElec = true
			
	Else 
	
		childElec = False
	
 	End If

Next

For each det as Hansen.CDR.Building.IApplicationDetail in oBldgApp.ApplicationDetails

	If det.ApplicationDetailType.ClassName = "InforClient.AgencyCDR.BuildingApplet.FireSuppressionReviewDetails"

		Dim oFireReviewDetail as InforClient.AgencyCDR.Building.FireReviewDetail
		oFireReviewDetail = InforClient.AgencyCDR.Building.FireReviewDetail.GetInstanceFromParent (det, res)
			
			For each gridItem as InforClient.AgencyCDR.Building.FirePmpGrd in oFireReviewDetail.FirePmpGrd
			
			If gridItem.Type.Code.Trim.ToUpper = "ELECTRIC" AND childElec = False
	
				StateCheck = True
	
			End If
Next

End if

NExt

For each det2 as Hansen.CDR.Building.IApplicationDetail in oBldgApp.ApplicationDetails

	If det2.ApplicationDetailType.ClassName = "InforClient.AgencyCDR.BuildingApplet.FireDetails"
		Dim oFireAlaramDetail as InforClient.AgencyCDR.Building.FireAlaramDetail
		oFireAlaramDetail = InforClient.AgencyCDR.Building.FireAlaramDetail.GetInstanceFromParent (det2, res)
		If (oFireAlaramDetail.HoodSuppression = True OR oFireAlaramDetail.FirePermitType.Code.Trim.ToUpper() = "ALARM") AND ChildElec = False
			StateCheck = True
Else

StateCheck = False
		End If
	End If
Next

**Comment by ScottVanSooy** [comment]
Promoted to Production 12/17/2019 8:30 PM
