### ISSUE TITLE
Temp Service Inspection 

### ISSUE THREAD

**Issue by ABonomo21** [dhenry-KCI/FredCo-Post-Go-Live-#111]
the service inspection has not been generating on heavy up for electrical. I added this one
![image](https://user-images.githubusercontent.com/47611580/71366977-8ddfad80-2571-11ea-90f3-a13a73ec1d77.png)
talk with Bob ensor for questions.

**Comment by ScottVanSooy** [comment]
This one is for Tuesday

**Comment by calequin** [comment]
the formula code is looking at the work type. If the work type = Alteration then it does not add. In this case application 258038 work type = ALTER. Should it be adding for alterations?

**Comment by ABonomo21** [comment]
bob will email list to christian

**Comment by calequin** [comment]
please promote ElectPerm_INspTemp_Aoc

**Comment by calequin** [comment]
promoted on 1.8.2020
