### ISSUE TITLE
Working without permit fee 

### ISSUE THREAD

**Issue by ABonomo21** [dhenry-KCI/FredCo-Post-Go-Live-#112]
please make sure all the working without permit fees in the system is $237.00 generating as $231.00
![image](https://user-images.githubusercontent.com/47611580/71367618-9b963280-2573-11ea-828e-77e4ab85cde3.png)

![image](https://user-images.githubusercontent.com/47611580/71367641-ac46a880-2573-11ea-85db-9f78412a7130.png)

**Comment by ABonomo21** [comment]
there are multiple in the system

**Comment by ScottVanSooy** [comment]
I've added new version to these 3 Fees.  Please retest.

INSPECTION FOR WORK WITHOUT PERMIT
DOLS - WORKING WITHOUT A PERMIT
ZONING CERT - INSPECTION FOR WORK WITHOUT A PERMIT

**Comment by ABonomo21** [comment]
corrected
