### ISSUE TITLE
resbldg - blanket plan

### ISSUE THREAD

**Issue by ABonomo21** [dhenry-KCI/FredCo-Post-Go-Live-#113]
this resbldg permit is asking for an approved blanket but it is not a blanket home. 
![image](https://user-images.githubusercontent.com/47611580/71368962-5ffd6780-2577-11ea-8ca2-09cd837984d6.png)

**Comment by JuanitaMiles** [comment]
Additional examples:

![image](https://user-images.githubusercontent.com/31770504/71380875-06a92e80-259f-11ea-905d-0ecb1636439e.png)

![image](https://user-images.githubusercontent.com/31770504/71380879-16287780-259f-11ea-9eaf-0f3bdbb38476.png)

**Comment by ScottVanSooy** [comment]
Promoting BP_BlanketReview tonight

**Comment by ScottVanSooy** [comment]
Added this code: Promoted 12/23/19.  Please retest

Dim bBlanket = False
StateCheck = False

If oBldgApp.ApplicationType.ApplicationType = "RESBLDG" Then
	For each oDetail as Hansen.CDR.Building.IApplicationDetail in oBldgApp.ApplicationDetails
		If oDetail.ApplicationDetailType.ClassName = "InforClient.AgencyCDR.BuildingApplet.SingleFamilyDwelling" Then
			Dim oResDetail as InforClient.AgencyCDR.Building.ResidentialDetail
			oResDetail = InforClient.AgencyCDR.Building.ResidentialDetail.GetInstanceFromParent (oDetail, res)
			bBlanket = oResDetail.BlanketApp
		ElseIf oDetail.ApplicationDetailType.ClassName = "InforClient.AgencyCDR.BuildingApplet.DuplexTwoFamilyDetail" Then		
			Dim oResDetail as InforClient.AgencyCDR.Building.ResidentialDetail
			oResDetail = InforClient.AgencyCDR.Building.ResidentialDetail.GetInstanceFromParent (oDetail, res)
			bBlanket = oResDetail.BlanketApp
		ElseIf oDetail.ApplicationDetailType.ClassName = "InforClient.AgencyCDR.BuildingApplet.TownhouseDetails" Then		
			Dim oResDetail as InforClient.AgencyCDR.Building.ResidentialDetail
			oResDetail = InforClient.AgencyCDR.Building.ResidentialDetail.GetInstanceFromParent (oDetail, res)
			bBlanket = oResDetail.BlanketApp
		End If
	Next	

	If bBlanket = True then
		StateCheck = True
		For each oProject As Hansen.CDR.Project.IProjectBuildingApplication in oBldgApp.AssociatedProjectApplications
			If oProject.ProjectApplication.ApplicationType.ApplicationType = "BLANKET"
				StateCheck = False
				Exit For
			End if
		Next
	End If
End If
