### ISSUE TITLE
square footage hold 

### ISSUE THREAD

**Issue by ABonomo21** [dhenry-KCI/FredCo-Post-Go-Live-#114]
why is this permit asking for a required field of sq. footage i have never seen this
![image](https://user-images.githubusercontent.com/47611580/71369025-7f949000-2577-11ea-8ff7-a1cc69130b5f.png)

**Comment by ScottVanSooy** [comment]
Ashlye:

This is because it's set as a required field.  Give me the OK to change it and I can do it without downtime.

![image](https://user-images.githubusercontent.com/58946969/71384632-4e2bbc80-2597-11ea-94c7-2f47d21e3b5b.png)

**Comment by megisys** [comment]
Removed Constraint. - Please Retest

**Comment by ABonomo21** [comment]
removed from permit.
