### ISSUE TITLE
adding review 

### ISSUE THREAD

**Issue by ABonomo21** [dhenry-KCI/FredCo-Post-Go-Live-#115]
trying to add an environmental health review to permit 190433 and it gives me this error. 
![image](https://user-images.githubusercontent.com/47611580/71369478-e2d2f200-2578-11ea-8ba3-82e0fc0f28fd.png)

**Comment by JuanitaMiles** [comment]
@ABonomo21 This error typically appears when more than one person is working the application. If someone has made a change (or if you changed it in a different window) since you opened this application it'll throw this error. Try closing the application and reopen and try adding the review again.

**Comment by ABonomo21** [comment]
I tried that before I logged the ticket..

**Comment by ScottVanSooy** [comment]
These can also be caused by a formula.  I'll take a look.

**Comment by megisys** [comment]
Formula Issue. Addressed

**Comment by ABonomo21** [comment]
i was able to add health to the permit
