### ISSUE TITLE
Permits Issued by Treasury 

### ISSUE THREAD

**Issue by emilypearl1** [dhenry-KCI/FredCo-Post-Go-Live-#116]
[Capture.pdf](https://github.com/dhenry-KCI/FredCo-Post-Go-Live-/files/3995606/Capture.pdf)

Permit 257969- Impact fees were paid by treasury staff. Shows that Dan Lewis (treasury) issued the permit. 

12/23/19 reviewed by Ashlye

**Comment by ABonomo21** [comment]
from Pdox - the issued name is blank! 
![image](https://user-images.githubusercontent.com/47611580/71370089-c1730580-257a-11ea-8a2d-797e001a8d31.png)


ashlye

**Comment by JuanitaMiles** [comment]
For Reference: In the past we had this setup to populate the Issued By with the person who resulted the completeness check. (See screenshot from an old ticket below). Currently it appears to be pulling the user who progressed the application to the next milestone.

![image](https://user-images.githubusercontent.com/31770504/71371884-bf13aa00-2580-11ea-9723-086c3e081088.png)

**Comment by ScottVanSooy** [comment]
I'm going to look at this one tomorrow while I work on Higher Priority issues..  it's going to take a little bit of digging in I think.

**Comment by ScottVanSooy** [comment]
Approved Completeness check should be the issued.
Checking with Dan

**Comment by calequin** [comment]
this formula exists in Trade. duplicating to permits

**Comment by calequin** [comment]
created addoncondition under SWM - Building
BP_PermitIssuedBySet_AOC

**Comment by calequin** [comment]
Promote to Prod
disable BP_PermitIssuedBySet_AOC
add under BuildingApplication before update - BP_SetPermitIssuedBy_BU

**Comment by calequin** [comment]
promoted on 1.9.2020

**Comment by ABonomo21** [comment]
Closing Ticket. thank you.
