### ISSUE TITLE
Town Reviews

### ISSUE THREAD

**Issue by AReed327** [dhenry-KCI/FredCo-Post-Go-Live-#117]
I received a BRUNSWICK plan PW257669 and when I went to PDOX it appears Brunswick is set up under User Name: BDell@Brunswickmd.gov. I believe it should be planner@brunswickmd.gov to match the town user list. We may need to check all towns to make sure this is set up correctly.
AREED

**Comment by dhenry-KCI** [comment]
@AReed327 - all Town review email addresses that were provided to the County were confirmed correct last week in IPS. Planner@brunswickmd.gov is configured correctly in both IPS and R4C. BDell has an account in Pdox as some town reviewer's email addresses were provided to Avolve earlier in the project. His account was not system generated. The only applicant on PW257669 is mdpermitting@clarkazar.com. We discussed before go-live the need for the applicant to add the notify additional applicants checkbox in Pdox. The other option would be to add town review accounts and manually associate with the correct project.

**Comment by AReed327** [comment]
I added the Town Reviewer as an applicant in IPS. I did not find the town reviewer in PDOX. It did appear that Bruce Dell-town planner would be able to view this project in PDOX with his own sign in.

**Comment by AReed327** [comment]
@dhenry-KCI We need to make sure the town emails that we were given are in PDOX. Do you need more from me on this? Ideally, the town would populate in PDOX automatically.

**Comment by AReed327** [comment]
I will add town emails as an applicant in PDOX.
