### ISSUE TITLE
SRM Reports - Cashiering - Register Transactions - 2 reports to move to Production

### ISSUE THREAD

**Issue by TaraF** [dhenry-KCI/FredCo-Post-Go-Live-#118]
Please move the following report deployments to Production (available in IPS_Test):

- Impact / Excise Fees Paid for Issued Permits 
- Impact / Excise Fees Paid for Unissued Permits 

Under SRM Reports - Cashiering - Register Transactions 

![image](https://user-images.githubusercontent.com/4104464/71372501-8ffe3800-2582-11ea-83ae-9348de8c1f23.png)

**Comment by ScottVanSooy** [comment]
Will promote tonight.

**Comment by ScottVanSooy** [comment]
Promoted 12/23/19.  Please test

**Comment by JuanitaMiles** [comment]
confirmed these have been deployed. (tested by JM 1/2/20)

![image](https://user-images.githubusercontent.com/31770504/71690986-3365fe80-2d74-11ea-89f4-59ddb38f74c8.png)
