### ISSUE TITLE
Building Permits - Hold for Missing Water/Sewer Details

### ISSUE THREAD

**Issue by JuanitaMiles** [dhenry-KCI/FredCo-Post-Go-Live-#119]
Would like to look into applying a hold condition/status check during the completeness check milestone for permits that do not have the Water/Sewer details populated. 

See email reference below:

![image](https://user-images.githubusercontent.com/31770504/71374525-09008e00-2589-11ea-8094-75414e58d47e.png)
![image](https://user-images.githubusercontent.com/31770504/71374539-161d7d00-2589-11ea-8994-c12179205086.png)

**Comment by megisys** [comment]
BP_WATERSEWER_SCF - Create in Production Please

**Comment by megisys** [comment]
![image](https://user-images.githubusercontent.com/47392306/72101865-b0085800-32f3-11ea-9195-07593060f74d.png)

Need to add Status Check to Completeness Check

**Comment by megisys** [comment]
Add RESBLDG, NONRESBLDG and RESUSES

**Comment by ScottVanSooy** [comment]
Promoted 2020-01-09
