### ISSUE TITLE
Building - Res Building Permit - Health Review Fee

### ISSUE THREAD

**Issue by dhenry-KCI** [dhenry-KCI/FredCo-Post-Go-Live-#12]
A Res. Building application (#258185) on well and septic did not generate the health review fee. 

Please generate the health review fee. 

Logged by Shannon Walters/ AShlye B.

**Comment by megisys** [comment]
It is there


![image](https://user-images.githubusercontent.com/47392306/70920450-a17a9980-1ff0-11ea-95d5-50b181fa5810.png)

**Comment by megisys** [comment]
@ju

**Comment by megisys** [comment]
@JuanitaMiles

**Comment by megisys** [comment]
Bug Here

**Comment by ABonomo21** [comment]
![image](https://user-images.githubusercontent.com/47611580/71023130-1a9cee00-20d0-11ea-8d90-57ae38ef2db0.png)
 another health missing fee- 

let me know if we need to revisit the code requirements for when health should generate.

**Comment by ABonomo21** [comment]
this is now high priority @megisys ! we have another one for a zoning cert that did not generate the health fee- ab 
![image](https://user-images.githubusercontent.com/47611580/71097376-e54ed980-217d-11ea-86bd-c364cd3ccd9b.png)

**Comment by ScottVanSooy** [comment]
This block of code on the fee is causing it to not be added.  Christian is reviewing whit the client

For each det in oBldgApp.ApplicationDetails
	If det.ApplicationDetailType.ClassName = "InforClient.AgencyCDR.BuildingApplet.ZoningCertDetails"
		Dim oZoningCertDetail as InforClient.AgencyCDR.Building.ZoningCertDetail
		oZoningCertDetail = InforClient.AgencyCDR.Building.ZoningCertDetail.GetInstanceFromParent (det, res)
		If oZoningCertDetail.NRCS = True
			AddOnCondition = False
			Return Res
		End If
	End If
Next

**Comment by calequin** [comment]
spoke with Ashlye. This code is correct and can be closed

**Comment by awhite806** [comment]
RE-OPENING- PERMIT 264855- permit property is on well/septic and the health review fee did not generate.
![Annotation 2020-02-13 HEALTH FEE](https://user-images.githubusercontent.com/58981029/74459177-dec89f80-4e58-11ea-9957-a977a81750e1.png)

**Comment by calequin** [comment]
hello the township code on this parcel is 02 therefore the fee did not add. The fee is only adding if township code is 00 and on well and septic. Do we need to allow other township codes?

**Comment by ABonomo21** [comment]
the township code should not have an impact on this- it is based on the water/sewer type as well and septic.

**Comment by calequin** [comment]
removed township from this formula- Tested on 263339
once approved please promoted formula below
RESBLDG_Fee_HealthReview_AOC

**Comment by calequin** [comment]
promoted on 2.23.2020
