### ISSUE TITLE
Building Permits - Leslie P Getting Server Error 

### ISSUE THREAD

**Issue by JuanitaMiles** [dhenry-KCI/FredCo-Post-Go-Live-#120]
Leslie Paretti is getting the following server error message:

![image](https://user-images.githubusercontent.com/31770504/71381111-31e04d80-25a0-11ea-9e75-a4bf567291e8.png)

Scott has responded with the following additional information about the error:

![image](https://user-images.githubusercontent.com/31770504/71381155-5b997480-25a0-11ea-8453-58a4e890c6d3.png)

**Comment by ScottVanSooy** [comment]
I'd like to find out from Leslie where she was when this happened.

**Comment by megisys** [comment]
What process is causing this. We need replication steps for this..

**Comment by ABonomo21** [comment]
i sent an email to leslie to confirm when she was getting this error and what she was doing.
