### ISSUE TITLE
Building Permits - Fire - Notification Error Message when Resulting COMPLETE Review

### ISSUE THREAD

**Issue by JuanitaMiles** [dhenry-KCI/FredCo-Post-Go-Live-#121]
FIRE PERMIT - RESIDENTIAL TOWNHOME
AP # 258644

This is an application in Walkersville. Leslie is receiving the following notification error message when trying to result the completeness check.

*This application has since been manipulated to progress forward.

![image](https://user-images.githubusercontent.com/31770504/71381359-25a8c000-25a1-11ea-8b9a-ebc8571d2d0c.png)

![image](https://user-images.githubusercontent.com/31770504/71381291-d95d8000-25a0-11ea-8d51-6fcfe89c6a4e.png)

**Comment by JuanitaMiles** [comment]
Appears to be a similar issue as #96

**Comment by ScottVanSooy** [comment]
I think I need more information about the Fees involved.  I'm not seeing the same thing,  I'm guessing I'm following a different set of steps/

**Comment by ScottVanSooy** [comment]
Duplicate issue, notification issue.  Will be deployed tonight.
