### ISSUE TITLE
planning- project reports not working in Chrome

### ISSUE THREAD

**Issue by MLWilkins** [dhenry-KCI/FredCo-Post-Go-Live-#122]
project reports are not working in Chrome.  They only work in Internet Explorer.

![image](https://user-images.githubusercontent.com/50637067/71476467-421c4680-27b3-11ea-9afb-eabe992a636c.png)

**Comment by JuanitaMiles** [comment]
@MLWilkins They're both opening in Chrome for me...I've tried this application and another to confirm.

![image](https://user-images.githubusercontent.com/31770504/71483587-8836d180-27d6-11ea-94cb-1e0a72470f65.png)

**Comment by MLWilkins** [comment]
@JuanitaMiles  I changed popup blocker setting in chrome.  Working now.
