### ISSUE TITLE
SYSTEM WIDE- PLANNING/PERMITTING  - ROAD Details GIS ADDRESS CLEAN UP 

### ISSUE THREAD

**Issue by AReed327** [dhenry-KCI/FredCo-Post-Go-Live-#123]
The road details are supposed to populate state or county road. If State is populated it is supposed to route to SHA. This parcel is not on a state highway but nothing populated.
![image](https://user-images.githubusercontent.com/58854333/71479365-16ed2380-27c2-11ea-9b52-d4741e243e62.png)

**Comment by dhenry-KCI** [comment]
12/27 - per discussion with Ashley R. will discuss with Dan upon his return.

**Comment by dhenry-KCI** [comment]
to be included in a ticket review meeting week of January 14th

**Comment by megisys** [comment]
This would be a GIS Issue. Not sure how I can assist @dhenry-KCI

**Comment by megisys** [comment]
Any Planning Application which has a SHA Review configured. (Except APFO). Please add a StateHighway Check box on Detail Page and adjust the Formula if not already there. Allow for both to work..  Either S in Code or the Checkbox is True.

**Comment by megisys** [comment]
This is a timely piece of work due to possible schema changes - Dan

**Comment by JuanitaMiles** [comment]
Everyone has an understanding that this is a lower priority item. The changes mentioned by Dan above will be addressed as time/budget allows and as higher priority tickets decrease. 

@dhenry-KCI - Need to confirm with GIS that this field can be accurately populated with the appropriate Road type: State, County, etc. This has been discussed in the past.

**Comment by JuanitaMiles** [comment]
@dhenry-KCI This is now identified as an issue for building permits and the spawning of driveway/grading permits. We need follow up with GIS to ensure we can get this field populated. Upgrading the priority of this issue.

**Comment by JuanitaMiles** [comment]
County GIS is currently working on this item. Will await progress reports from GIS.

**Comment by ABonomo21** [comment]
Source:
Repository: kcigeospatial / Fred_Co_Land-Management
Ticket #: 2063
Requested By: Project Team
Jump to this repository

Request:
We will need to continue to monitor the clean up needed on parcels/addresses. This issue originally references duplicate addresses only, but this can be expanded to:

Water/Sewer details
Changes in Water/Sewer designation due to new/future development
Subdivision updates
Road Details (county/sha)
Parcel/Address relationships

**Comment by JuanitaMiles** [comment]
Downgrading to a medium priority ticket. We know GIS is actively working on all tasks related to road details, subdivision, and address/parcel updates. We will continually reach out and request weekly status updates from the GIS team.

**Comment by ABonomo21** [comment]
Changing to a high priority ticket- permit 265084 for 3014 Roderick road is missing the road attribute- had it been county road it would have generated the fee as required and did not.

**Comment by ABonomo21** [comment]
![image](https://user-images.githubusercontent.com/47611580/74964738-e997ad00-53e1-11ea-86f2-50eb09ef4e26.png)

@JuanitaMiles do we need to create a github ticket for Infor, the driveway permit spawned on it's own maybe the fee is coded different.

**Comment by ABonomo21** [comment]
After speaking with Ash R we both agree that GIS has corrected the Road attribute coding to be reflective of what was in H7 and how the code was written to drive fees review etc. 

with that said there is still paces that need to be cleaned up and we have an expectation that GIS will continue this exercise

juanita will send follow up email
