### ISSUE TITLE
Residental Plumbing-Gas Appliance fee did not generate

### ISSUE THREAD

**Issue by awhite806** [dhenry-KCI/FredCo-Post-Go-Live-#124]
Permit #258680-the gas appliance fee did not generate. it should have generated the $88 fee.
![image](https://user-images.githubusercontent.com/58981029/71480345-94b32e00-27c6-11ea-8923-0ae8c79e8895.png)
![image](https://user-images.githubusercontent.com/58981029/71480348-9977e200-27c6-11ea-9137-7c833272bde6.png)

**Comment by megisys** [comment]
I believe Stove was added to the grid to late .

**Comment by megisys** [comment]
PLease reenter this into Test and LEt me know

**Comment by ABonomo21** [comment]
fees added in test 259816
