### ISSUE TITLE
IPS Employee Record - MEULIANO Needs Employee Contact Record Updated

### ISSUE THREAD

**Issue by JuanitaMiles** [dhenry-KCI/FredCo-Post-Go-Live-#125]
Meghan Euliano needs a First and Last Name and email address applied to her Employee ID record in IPS.

Her email address is:
MEuliano@FrederickCountyMD.gov

![image](https://user-images.githubusercontent.com/31770504/71480570-dd1f1b80-27c7-11ea-8b03-0e6a565cd850.png)

**Comment by ScottVanSooy** [comment]
Fixed
