### ISSUE TITLE
Returned Check FEE insertable 

### ISSUE THREAD

**Issue by emilypearl1** [dhenry-KCI/FredCo-Post-Go-Live-#126]
Permit #258336 - the payment for this application was returned due to the account string being incorrect- this payment was made online. Due to the payment being rejected a $25 returned check fee payment is now due.  Can we please have this fee added (allowable on ALL permit types and licenses, etc.) so that Treasury can capture the returned check fee?

The fee is $25.00 and the fee should be deposited into account# 10.98.998.999.47055.

**Comment by ABonomo21** [comment]
@dhenry-KCI

**Comment by megisys** [comment]
Added to Fire Permit for the urgent need. Leave this to County to address across the board.

**Comment by emilypearl1** [comment]
this also needs to be added to gaming as well.... g257789 - unable to add!!

This is high priority!!

**Comment by pooldaddy** [comment]
I need to know the following:
1. GL Account  is it the same for all ap types? 
2 Fee amt same for all ap types?
I assume that I need to create new RETURN CHK FEE in FEE library for each module.  IF yes, after creation how do I sync to R4C?  Need Infor guidance on this one.

**Comment by emilypearl1** [comment]
Yes- the account string is the same for all account and the fee amount is the same as well.

It needs to be available for all types of aps/ licenses/ anything that we accept a payment for.

**Comment by pooldaddy** [comment]
The following fee for returned checks is now available in PROD for all AP types:
Fee Code              Description                  Amt
RTNCHK          Returned Check Fee           25.00
