### ISSUE TITLE
Incorrect Reviews-Health Review generated instead of Capacity permit 

### ISSUE THREAD

**Issue by awhite806** [dhenry-KCI/FredCo-Post-Go-Live-#127]
Permit 258405-this property is on public water/sewer, a capacity permit should have auto generated instead. the health review that generated is not applicable to properties on public water/sewer and should not have generated
![image](https://user-images.githubusercontent.com/58981029/71482946-57a16880-27d3-11ea-96f9-aa8ab8d77fa3.png)
![image](https://user-images.githubusercontent.com/58981029/71482983-756ecd80-27d3-11ea-959d-c7c347a7bbbc.png)

**Comment by ABonomo21** [comment]
reviewed by ashlye

**Comment by ScottVanSooy** [comment]
Look at the Add On Condition for the Review EH

**Comment by megisys** [comment]
You need to pay the fees and it would have generated the Capacity Permit.. See this application in TEST..
