### ISSUE TITLE
Condition on Resuse 

### ISSUE THREAD

**Issue by ABonomo21** [dhenry-KCI/FredCo-Post-Go-Live-#128]
This resuse permit # 202838 has a condition that the res building permit must be issued but there is no resbldg permit attached?? 
![image](https://user-images.githubusercontent.com/47611580/71489012-875f6900-27f1-11ea-9b40-ded9646d36c7.png)

**Comment by ScottVanSooy** [comment]
I'll look into this.  The formula not working correctly is BP_RESUSES_BuildingIssued_SCF

**Comment by ScottVanSooy** [comment]
@ABonomo21   it looks like it Progressed due to Supervisor Override.  Can you verify what I'm seeing?

**Comment by ScottVanSooy** [comment]
This doesn't need a res building permit attached. Only if related to a RESBLDG application.

**Comment by ABonomo21** [comment]
did not work tested 259818 in test still have the condition.

**Comment by ScottVanSooy** [comment]
If there is an unattached Garage per detail page ResidentialUsesDetails , then make sure there is an Issued Date on an attached RESBLDG permit.

This works in  Test, @calequin  maybe a webex is in order

**Comment by ScottVanSooy** [comment]
Formula adjusted, restest.

**Comment by ScottVanSooy** [comment]
Promote 
BP_RESUSES_BuildingIssued_SCF
