### ISSUE TITLE
Plumbing Utility License-Inactive Date Removal and Grace Expiration Date

### ISSUE THREAD

**Issue by awhite806** [dhenry-KCI/FredCo-Post-Go-Live-#129]
For the Plumbing Utility License, we need a log to be able to remove the Inactive date so we may bring the license back to active status. The grace expiration date also generated incorrectly. It should be 90 days after the expiration date, not 30 days.
![image](https://user-images.githubusercontent.com/58981029/71489338-19b43c80-27f3-11ea-844a-30971e82cdd6.png)

**Comment by ABonomo21** [comment]
reviewed by ashlye

**Comment by ScottVanSooy** [comment]
@awhite806 I can make a log Type like i did for the other dates to remove it.  Is that a good option?

**Comment by ScottVanSooy** [comment]
@awhite806  - Sorry, I see you asked me to make a log type already, I'll do that, please ignore my previous question.

**Comment by ScottVanSooy** [comment]
Promote TL_ClearInactive_AAF to Prod.  Add CLINACTIVE Log Type to Prod

**Comment by ScottVanSooy** [comment]
Please test.

**Comment by awhite806** [comment]
I am unable to access the test enviroment and the log is not in IPS Prod. 

![image](https://user-images.githubusercontent.com/58981029/71671808-fda82200-2d41-11ea-8342-0624ab40cef7.png)

if this is not the correct test environment, please let me know. this is the only test link i have.
![image](https://user-images.githubusercontent.com/58981029/71671855-216b6800-2d42-11ea-91e7-a7fd70aa1bfa.png)

**Comment by calequin** [comment]
added CLINACTIVE to prod environment.

**Comment by ABonomo21** [comment]
emailed abbie to test

**Comment by awhite806** [comment]
fixed
![image](https://user-images.githubusercontent.com/58981029/71687457-da926800-2d6b-11ea-9e32-625685129d9c.png)
![image](https://user-images.githubusercontent.com/58981029/71687519-06ade900-2d6c-11ea-92a6-54baaee30fa7.png)
