### ISSUE TITLE
Building - Elec. / Plumbing Application - Town Review

### ISSUE THREAD

**Issue by dhenry-KCI** [dhenry-KCI/FredCo-Post-Go-Live-#13]
Town reviews should not generate on elec. / plumbing applications. See Ap 258071

![SnipImage (006)](https://user-images.githubusercontent.com/4129185/70921045-907e5800-1ff1-11ea-8f95-fc652bfb6d81.JPG)

From	Subject	Received	Size	Categories	
Henry, Dustin	FW: TOWN REVIEW ON PLUMBING AND ELECT	Fri 12/13	332 KB

**Comment by megisys** [comment]
Migrate BP_AddTownReviewer_AAF

**Comment by ABonomo21** [comment]
![image](https://user-images.githubusercontent.com/47611580/70939511-67bc8980-2016-11ea-9452-f13d15683e90.png)

**Comment by ABonomo21** [comment]
three more today... 
![image](https://user-images.githubusercontent.com/47611580/71108735-b3477280-2191-11ea-8450-7edcc02d3e2c.png)

![image](https://user-images.githubusercontent.com/47611580/71108753-be9a9e00-2191-11ea-9d98-b13f8f04dc80.png)

![image](https://user-images.githubusercontent.com/47611580/71108786-cfe3aa80-2191-11ea-892f-2a9024669e96.png)

**Comment by calequin** [comment]
@ABonomo21 the formula takes into effect new applications enter after thhis formula was active. The applications listed above were added on 12/17 right before this formula was prmotoed to prod. Going forward this formula will not add town reviewers for Elec and Plum
