### ISSUE TITLE
Additional Contacts not adding to permit

### ISSUE THREAD

**Issue by awhite806** [dhenry-KCI/FredCo-Post-Go-Live-#130]
When a customer adds an additional contact on their permit when applying, per Ashlye that additional contact should automatically add as an additional applicant to the permit. 
![image](https://user-images.githubusercontent.com/58981029/71517278-4ca21300-287b-11ea-9721-ab0a12e97d55.png)
![image](https://user-images.githubusercontent.com/58981029/71517281-4f9d0380-287b-11ea-9753-933792a92355.png)

**Comment by ScottVanSooy** [comment]
Researching

**Comment by ScottVanSooy** [comment]
@calequin , is the other contact added thru Rhythm?  I'm not sure how that would relate to Applicants.  Maybe we can go over it tomorrow.

**Comment by ScottVanSooy** [comment]
@calequin  Nevermind, I  found it.

**Comment by ScottVanSooy** [comment]
Need to debug BldCntctDtl_UpdateApplicants_AAC

**Comment by calequin** [comment]
added new formula under BuildingContactDetails - AfterAddCommitted
copy BldCntctDtl_UpdateApplicants_AAC
copy BldCntctDtl_UpdateApplicants_AA

**Comment by calequin** [comment]
promoted on 1.9.2020

**Comment by ABonomo21** [comment]
will close for now until an applicant submits
