### ISSUE TITLE
Permit did not progress 

### ISSUE THREAD

**Issue by ABonomo21** [dhenry-KCI/FredCo-Post-Go-Live-#131]
This permit application was approved by all agencies and did not progress to the awaiting fee payment milestone until i hit the check status button... 
![image](https://user-images.githubusercontent.com/47611580/71518599-b4f3f300-2881-11ea-8621-d2a30345a722.png)

**Comment by ScottVanSooy** [comment]
I'm  unclear of what Status Check or Condition to Review.  Leaving unassigned.

**Comment by megisys** [comment]
We can not solve this issue as it is not able to replicate. We need to close and ask you to stop if you hit this again please.
