### ISSUE TITLE
Revision fee did not generate 

### ISSUE THREAD

**Issue by ABonomo21** [dhenry-KCI/FredCo-Post-Go-Live-#134]
completed an applicant action from the milestone of awaiting applicant revisions and the revision fee did not generate i had to manually add it. 
![image](https://user-images.githubusercontent.com/47611580/71528241-f64dc800-28ac-11ea-8f94-98949a750bbc.png)

**Comment by ScottVanSooy** [comment]
The Add Revision Fees Milestone might be in  the wrong place.  It comes a couple Milestones before Awaiting Applicant Revisions.  It doesn't look like it goes back to that Milestone to regenerate the fees.

We need to review before I make any changes.

**Comment by ScottVanSooy** [comment]
Review with Christian

**Comment by ScottVanSooy** [comment]
Check Resubmit.

**Comment by ScottVanSooy** [comment]
@megisys  I need guidance in this one.

**Comment by megisys** [comment]
Lets Meet

**Comment by megisys** [comment]
It is because PWDR asked for a revision in the same cycle. and we dont charge revisions for PWDR review resubmits.

**Comment by ABonomo21** [comment]
if it was only one of the review agencies that we do not require a revision fee for that resulted as a resubmit then the fee should not add but an agency we do require a revision fee for also asked for the resubmit which was DPZ so it should have generated the fee

**Comment by megisys** [comment]
Added to BLDG_PWDRNoRevisionFee_AOC

**Comment by ABonomo21** [comment]
tested 188458 in test did not add the fee and DPZ had a resubmit

**Comment by megisys** [comment]
You were not under review . you took an application which was in the wrong mielstone

![image](https://user-images.githubusercontent.com/47392306/72991823-af29f880-3dc0-11ea-8b17-dffd9665c1b5.png)

**Comment by ABonomo21** [comment]
will manually add the fee when not in under review.
