### ISSUE TITLE
service requests 

### ISSUE THREAD

**Issue by ABonomo21** [dhenry-KCI/FredCo-Post-Go-Live-#135]
is there a way to add a status to the tool bar for service requests so we know which ones are resolved and which ones need action? i did not see that option under column cog

![image](https://user-images.githubusercontent.com/47611580/71528799-a45a7180-28af-11ea-8e31-f0db424d6c57.png)

**Comment by megisys** [comment]
![image](https://user-images.githubusercontent.com/47392306/71541089-9720ae00-29a7-11ea-8b2b-4ef35866e214.png)
