### ISSUE TITLE
Planning - Signature Set Review - not populating on My INFOR to do list

### ISSUE THREAD

**Issue by AReed327** [dhenry-KCI/FredCo-Post-Go-Live-#136]
Application 20085 - Signature Set not populating on reviewers to do list on My Infor Page. Graham's to do list is shown below. 
![image](https://user-images.githubusercontent.com/58854333/71528530-424d3c80-28ae-11ea-8443-306743591441.png)
Graham's to do list
![image](https://user-images.githubusercontent.com/58854333/71528552-5c871a80-28ae-11ea-8a6d-c305746a276e.png)

**Comment by megisys** [comment]
To Do List need to be refreshed. They refresh every 5 minutes. or you can just click refresh in the URL

**Comment by AReed327** [comment]
Application 20085 - This was due on December 10th. It is overdue. It is not on GHUBBARD's TODO List. I have provided an updated to-do list.
![image](https://user-images.githubusercontent.com/58854333/71633143-7abb8600-2be0-11ea-8aee-42e8b61769e9.png)
![image](https://user-images.githubusercontent.com/58854333/71633192-c1a97b80-2be0-11ea-817b-9a52fb97d80c.png)

**Comment by ScottVanSooy** [comment]
This is the To-DO list query. Analyzing now

exec sp_executesql N'SELECT TOP (@__Max) * FROM ( SELECT PLANREVIEW.APPLANREVIEWKEY, PLANREVIEWTYPE.REVIEWTYPE, PLANREVIEW.TYPENO, PLANREVIEW.SUSPDT, PLANREVIEW.ISSDTTM, PLANAPPL.APNO, PLANAPPLTYPE.APTYPE, PLANREVIEW.APPLANKEY, PLANAPPL.ADDRKEY, ADDRESS.ADDRTYPE, ADDRESS.ADDRESSSTATUS, ADDRESS.FULLSTNO, ADDRESS.STNO, ADDRESS.STNOHI, ADDRESS.PREDIR, ADDRESS.STNAME, ADDRESS.SUFFIX, ADDRESS.POSTDIR, ADDRESS.STSUB, ADDRESS.CITY, ADDRESS.STATE, ADDRESS.ZIP, ADDRESS.VERSION, ADDRESS.CURRADDR, ADDRESS.ALLOWDUPLICATESERVICES, ADDRESS.ST2PREDIR, ADDRESS.ST2NAME, ADDRESS.ST2SUFFIX, ADDRESS.ST2POSTDIR, ADDRESS.ST3PREDIR, ADDRESS.ST3NAME, ADDRESS.ST3SUFFIX, ADDRESS.ST3POSTDIR, ADDRESS.STNOSORTAS, ROW_NUMBER() OVER ( ORDER BY  PLANREVIEW.[APPLANREVIEWKEY] ASC ) AS __RowNumber FROM CDR_Planning.PLANREVIEW PLANREVIEW INNER JOIN CDR_Planning.PLANREVIEWTYPE PLANREVIEWTYPE ON (PLANREVIEW.[APPLANREVIEWTYPEKEY] = PLANREVIEWTYPE.[APPLANREVIEWTYPEKEY])  INNER JOIN CDR_Planning.PLANAPPL PLANAPPL ON (PLANREVIEW.[APPLANKEY] = PLANAPPL.[APPLANKEY])  INNER JOIN CDR_Planning.PLANAPPLTYPE PLANAPPLTYPE ON (PLANAPPL.[APPLANDEFNKEY] = PLANAPPLTYPE.[APPLANDEFNKEY])  INNER JOIN Property.ADDRESS ADDRESS ON (PLANAPPL.[ADDRKEY] = ADDRESS.[ADDRKEY])   WHERE PLANREVIEW.[ASSIGNTO]=@PARAM_0 AND PLANREVIEW.[RESULT]=@PARAM_1 AND (PLANAPPL.[EXPDTTM]>@PARAM_2 OR PLANAPPL.[EXPDTTM] IS NULL )  AND  NOT(PLANREVIEW.APPLANREVIEWKEY = 1)     ) AS __OriginalQuery WHERE __RowNumber >= @__Start 
 ORDER BY __RowNumber',N'@PARAM_0 nvarchar(7),@PARAM_1 nvarchar(1),@PARAM_2 datetime,@__Start int,@__Max int',@PARAM_0=N'HANSEN8',@PARAM_1=N' ',@PARAM_2='2020-01-03 00:00:00',@__Start=1,@__Max=100

**Comment by ScottVanSooy** [comment]
@AReed327  The reason the Review is not showing is because the AP it's under is expired.  Is that expected behavior?

**Comment by ScottVanSooy** [comment]
For Clarification Planning App 20085 is expired

**Comment by JuanitaMiles** [comment]
@ScottVanSooy how do you know this is expired. Im looking at in the prod and nothing tells me its expired.

**Comment by ScottVanSooy** [comment]
You are right.  It was only expired in test.  There must have been another change I made to allow it to show in Test.  Let me review in Prod, unfortunately, I have no way to see his dashboard to find out if my changes are correct.

**Comment by AReed327** [comment]
I see that. It must have been a carry over from a Bulk Add in Hansen. It should not be expired because it wasn't even submitted until December 3, 2019. I have removed the expiration date and it is now showing on GHubbards My Infor to do list. 
Closing Ticket. AREED

**Comment by AReed327** [comment]
I checked his dashboard, it was there. I closed the ticket.

Ashley Reed
Development Review Technician II
Department of Development Review
Frederick County Government
30 North Market Street
Frederick, Maryland 21701
(301)-600-1139
AReed@FrederickCountyMD.gov<mailto:AReed@FrederickCountyMD.gov>
