### ISSUE TITLE
Certificate of  Potability Condition

### ISSUE THREAD

**Issue by emilypearl1** [dhenry-KCI/FredCo-Post-Go-Live-#138]
![image](https://user-images.githubusercontent.com/58855801/71590250-bfb6be00-2af5-11ea-859c-fb18b5c0f184.png)

Karen Amoss approved the CERTPOT condition back on 12/11/19. Ron approved the final inspection today and the CERTPOT duplicated under conditions.

**Comment by emilypearl1** [comment]
permit #192942

**Comment by ABonomo21** [comment]
please correct the condition should generate after the issuance of the permit and can be resulted any time- once the condition is approved it should not duplicate.

**Comment by ScottVanSooy** [comment]
The Formula, BP_CertofPort_AOC, does not check for an existing Condition.  If I don't finish tonight, I  will finish on Thursday.

**Comment by ScottVanSooy** [comment]
Promote BP_CertofPort_AOC

**Comment by ABonomo21** [comment]
RE-opening ticket.

#196048 the CERTPOT condition generated this morning. The CERTPOT should generate after the issuance of the permit and can be resulted any time- once the condition is approved it should not duplicate.

![image](https://user-images.githubusercontent.com/47611580/72271620-345d2280-35f5-11ea-987f-7fd41e153d35.png)

**Comment by ScottVanSooy** [comment]
@ABonomo21 

What happened Ashlye, did it duplicate again?  Or did it Add the condition too soon?

**Comment by emilypearl1** [comment]
It added it at the wrong milestone.

**Comment by megisys** [comment]
No It is adding at the right place. These Application were issued along time ago.. We are Pending Certificate here. Not Pending Issuance.  The applications are old and about to close out.

**Comment by ABonomo21** [comment]
Dan can you please confirm for me what milestone this condition will add?

**Comment by ABonomo21** [comment]
@JuanitaMiles @dhenry-KCI @megisys 
not sure how to label a question back to Infor?

**Comment by ScottVanSooy** [comment]
@ABonomo21 
Right now it's set to Pending Certificate.

**Comment by ABonomo21** [comment]
Now the CERTPOT is gone #196116

![image](https://user-images.githubusercontent.com/47611580/72814395-fb473280-3c32-11ea-9a1d-993062074cc8.png)

![image](https://user-images.githubusercontent.com/47611580/72814426-0732f480-3c33-11ea-9957-fbe1b100ba67.png)

EP 1/21/2020

**Comment by calequin** [comment]
The condition does not get added until after inspection and under the Pending Certificate milestone which happens after inspections. Which is why application 196116 does not have the CERTPOT condition yet.

**Comment by ABonomo21** [comment]
The condition should generate after permit issuance.

**Comment by megisys** [comment]
So during INspections milestone then ?

**Comment by megisys** [comment]
@JuanitaMiles Please let us know if the Inspections milestone is the right place. and when it needs to be met

**Comment by ABonomo21** [comment]
yes once it gets to inspections the condition should be added, is should not stop progression of the permit unless the permit is at pending certificate. However, once the condition is approved it does not need to regenerate at any other milestone.

**Comment by ABonomo21** [comment]
tested 258185 in test

**Comment by emilypearl1** [comment]
REopening Ticket #196805 
CertPot is gone - this condition should be generated once permit is issued. This is migrated permit... however its not there.

![image](https://user-images.githubusercontent.com/58855801/73749890-387aec80-472a-11ea-887d-4d1139b46fab.png)

**Comment by megisys** [comment]
Emailed on this.. This has been sitting in this milestoen since go live.. Issue is for new permits. or old permits entering a milestone after issuance

**Comment by emilypearl1** [comment]
Permit 200023- issued prior to go live
The CertPot is not a condition on the permit. 
![image](https://user-images.githubusercontent.com/58855801/74737614-32553780-5223-11ea-84d3-b53c4aee4ec6.png)

Adding condition.  
Please confirm that this is correct for migrated permits?
