### ISSUE TITLE
RESIDENTIAL MINIMUM FEE GENERATING ON NON RES ELECTRIC PERMIT.

### ISSUE THREAD

**Issue by awhite806** [dhenry-KCI/FredCo-Post-Go-Live-#139]
Similar to issued #137 (however this is a different permit type) - this permit is for a non residential electrical permit and a residential electric minimum fee generated when it should not have generated at all. the fee amount is also wrong for a electric residential minimum fee. On Electric Residential Permits, the fee should be $49.
![image](https://user-images.githubusercontent.com/58981029/71623569-8b9dd480-2bab-11ea-90de-79e9b320a374.png)
![image](https://user-images.githubusercontent.com/58981029/71623573-90628880-2bab-11ea-8226-2fb0c1017355.png)

**Comment by ScottVanSooy** [comment]
This is the code that determines when the fee won't be added

if oBldgApp.Application.TotalUnpaidFees > Value then
	
	AddonCondition = False
	
End if

I need to add additional conditions.  I could use some help making sure I get it right.  Is it the Occupancy Field I need to look at?

**Comment by calequin** [comment]
please promote BP_ResMinFee_AOC

**Comment by ScottVanSooy** [comment]
Promoted 2020-01-05
