### ISSUE TITLE
Incorrect Gaming Fee

### ISSUE THREAD

**Issue by dhenry-KCI** [dhenry-KCI/FredCo-Post-Go-Live-#140]
The revision fee in the fy20 fee schedule is $30.00.  IPS is coming up as $26.00

![image](https://user-images.githubusercontent.com/4129185/71624192-4e3b4600-2baf-11ea-8909-0173fb8fc421.png)

per Shlye Bonomo and Shannon Walter

**Comment by ScottVanSooy** [comment]
Fixed in Prod and Test

**Comment by ABonomo21** [comment]
checked in prod - fixed
