### ISSUE TITLE
Fire Permit - Town Review 

### ISSUE THREAD

**Issue by ABonomo21** [dhenry-KCI/FredCo-Post-Go-Live-#141]
This permit skipped right over fee generation and went to under review. 

![image](https://user-images.githubusercontent.com/47611580/71625729-5f885080-2bb7-11ea-8c8b-05fbd818c674.png)
 

It generated an error just prior to skipping the milestones. 
![image](https://user-images.githubusercontent.com/47611580/71625766-8e062b80-2bb7-11ea-94a3-25ddeee9c4b2.png)

I did not override anything or roll it back because this is a pdox permit and i did not want it to mess up the pdox application.

**Comment by ABonomo21** [comment]
![image](https://user-images.githubusercontent.com/47611580/71625859-1d134380-2bb8-11ea-9fcb-5733969b422e.png)

**Comment by ScottVanSooy** [comment]
Ashlye, can we add a StopNot log to proceed?  That's my best guess, I'd like to consult with Christian on Thursday.

**Comment by calequin** [comment]
the town reviewer on this application has opted out of notifications causing the issue with the formula. Would need a stopnot log until we get the better notification solution in place.

**Comment by ABonomo21** [comment]
town review should not generate on fire permit in incorporated town

**Comment by calequin** [comment]
please promote BP_AddTownReviewer_AAF

**Comment by calequin** [comment]
promote 1.9.2020
