### ISSUE TITLE
Resulting Error

### ISSUE THREAD

**Issue by emilypearl1** [dhenry-KCI/FredCo-Post-Go-Live-#142]
When resulting a completeness check review as internal on permit 258797 I am getting the following error message:

**Comment by emilypearl1** [comment]
![Capture](https://user-images.githubusercontent.com/58855801/71626374-c9eec000-2bba-11ea-8221-0c1fcc67da2b.PNG)

**Comment by ABonomo21** [comment]
reviewed and needs to be corrected

**Comment by ScottVanSooy** [comment]
I think this has to do with Notifications.  I'll review with Christian on Thursday

**Comment by emilypearl1** [comment]
i have at least 3 permits that this is holding up currently.  EP 1/2/2020

**Comment by calequin** [comment]
It is a notification issue. The primary applicant opted out of notifications which iis causing the formula issues. Added a stopnot log for it to progress. Working on a better solution with @ScottVanSooy

**Comment by calequin** [comment]
added @emilypearl1 so that she can progress with a STOPNOT while a better solution is worked on

**Comment by emilypearl1** [comment]
i have done this on the ones that i was having problems with. EP

**Comment by emilypearl1** [comment]
leaving ticket open so that we can monitor and come up with a better solution (once more people choose the opt-out of notifications) this may become a bigger issue and needs a better fix.

**Comment by calequin** [comment]
dan fixed

**Comment by megisys** [comment]
Closing due to a week with no repeat.. Follow up solution deployed
