### ISSUE TITLE
ZONING FEE NOT GENERATING ON TANK PERMIT

### ISSUE THREAD

**Issue by awhite806** [dhenry-KCI/FredCo-Post-Go-Live-#143]
The $44 zoning fee did not generate for this tank permit. The property is not within an incorporated town so the fee should have generated.

![image](https://user-images.githubusercontent.com/58981029/71630919-c0be1d00-2bd3-11ea-9e2f-b8c61c9ced51.png)

**Comment by ABonomo21** [comment]
This needs to be corrected.

**Comment by ScottVanSooy** [comment]
There is no Work Type.  The Add On Formula, TANKS_Zoning_Fee_AOC,  looks for 

(oBldgApp.WorkType.Code = "INSTAL" OR oBldgApp.WorkType.Code = "REPLAC")
And oBldgApp.WorkType.Code <> "REMOVE"



I'm not sure if we need to fix the formula or add a work type to the App.  Please let me so I can adjust accordingly.

**Comment by awhite806** [comment]
Most likely it would be adding the work type to the app-I've just added it now. Which then brings the question to confirm with @ABonomo21 - it did not stop me for a work type, I was able to get the permit all the way to under review without that field being required, when it most likely should be.

**Comment by ABonomo21** [comment]
the work type needs to be a required field.

**Comment by calequin** [comment]
work type has been added as a required field in prod. please retest
