### ISSUE TITLE
Distributor Reports - Can't Save

### ISSUE THREAD

**Issue by mlibbey131** [dhenry-KCI/FredCo-Post-Go-Live-#144]
When inserting Distributor Reports you cannot save them. When I tried I received this error. 

![DR](https://user-images.githubusercontent.com/58980189/71668128-b0be4e80-2d35-11ea-9db0-42e7ab44bff7.png)

**Comment by calequin** [comment]
verfied on a call with Megan. Grid worked with one report added but Megan is going to verify by adding multiple ones on a report.

**Comment by ABonomo21** [comment]
emailed megan to test

**Comment by mlibbey131** [comment]
I was able to do one that didn't have as many Grid items and it worked, # DR257261. I then tried to test in the report Christian and I created earlier. We were able to make the report generate a permit number by saving it with only one Grid Line. I went back in and I added the additional items to the grid and when I tried to save the Grid I receive this error message. 

"General Database Error: String or binary data would be truncated. The statement has been terminated. CommandText: INSERT INTO AgencyCDR_BusinessLicense.DISTRIBUTOR2LICGRD ( [ADDBY], [APKEY], [DISTRIBUTORLICDETKEY], [DOLLARVALUE], [MODBY], [NAME], [NUMBAGS], [SALEDATE], [VALUEOFBAG] ) VALUES('MLIBBEY', @APKEY, @DISTRIBUTORLICDETKEY, @DOLLARVALUE, @MODBY, @NAME, @NUMBAGS, @SALEDATE, @VALUEOFBAG );SELECT SCOPE_IDENTITY(); at Hansen.Core.Data.Provider.SqlServer7.SqlServer7DataEngine.InsertAndReturnKey(DBStmtAndAll statement, String identityColumn, Boolean ignoreErrors, IEnumerable`1& key, Int32& rowsAffected) at Hansen.Core.Data.Engine.AbstractDataEngine.InsertAndReturnKey(DBStmtAndAll statement, String identityColumn, IEnumerable`1& keys) at Hansen.Core.Data.DataSource.Add(Component component, String sEmpID, Boolean bOverrideDefaultDateStamps) at Hansen.Core.Business.Component.AddInternal() at InforClient.AgencyCDR.BusinessLicense.Distributor2LicGrd.Add() at Hansen.UI.Web.VisualApplet.AddGridRows(GridState grid) at Hansen.UI.Web.VisualApplet.HandleAddGridRowsEvent(GridState gs) at Hansen.UI.Web.EnhContainedVisualApplet.HandleAddGridRowsEvent(GridState gs) at Hansen.UI.Web.Adapter.FromWindowAdapter.ProcessGrid(XmlTextReader xmlReader, Boolean isTreeGrid) at Hansen.UI.Web.Adapter.AppletAdapter.RouteStartElement(XmlTextReader xmlReader) at Hansen.UI.Web.Adapter.AppletAdapter.Parse() at Hansen.UI.Web.Adapter.AppletAdapter.ProcessXml() at Hansen.UI.Web.Adapter.FromWindowAdapter.ProcessXml() at Hansen.UI.Web.VisualApplet.GetAppletInstance(VisualApplet& visualApplet, VisualContext context, IAccessUser CurrentUser, Boolean bind) at Hansen.UI.Web.VisualApplet.CallEventProcDelegate(VisualContext context, String method, VisualDelegate parent, VisualApplet& va, Object[] args) at Hansen.UI.Web.Controls.CBlock.ProcessEvent(String aid, String dataset, String bases, String moniker, String fn, String src, String vid, Object[] args) at Hansen.UI.Web.Controls.CBlock.ProcessRequest(String req) at Hansen.UI.Web.Controls.CBlock.Page_Load(Object sender, EventArgs e) at System.Web.UI.Control.OnLoad(EventArgs e) at System.Web.UI.Control.LoadRecursive() at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint) at System.Web.UI.Page.ProcessRequest(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint) at System.Web.UI.Page.ProcessRequest() at System.Web.UI.Page.ProcessRequest(HttpContext context) at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() at System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step) at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) at System.Web.HttpApplication.PipelineStepManager.ResumeSteps(Exception error) at System.Web.HttpApplication.BeginProcessRequestNotification(HttpContext context, AsyncCallback cb) at System.Web.HttpRuntime.ProcessRequestNotificationPrivate(IIS7WorkerRequest wr, HttpContext context) at System.Web.Hosting.PipelineRuntime.ProcessRequestNotificationHelper(IntPtr rootedObjectsPointer, IntPtr nativeRequestContext, IntPtr moduleData, Int32 flags) at System.Web.Hosting.PipelineRuntime.ProcessRequestNotification(IntPtr rootedObjectsPointer, IntPtr nativeRequestContext, IntPtr moduleData, Int32 flags) at System.Web.Hosting.UnsafeIISMethods.MgdIndicateCompletion(IntPtr pHandler, RequestNotificationStatus& notificationStatus) at System.Web.Hosting.UnsafeIISMethods.MgdIndicateCompletion(IntPtr pHandler, RequestNotificationStatus& notificationStatus) at System.Web.Hosting.PipelineRuntime.ProcessRequestNotificationHelper(IntPtr rootedObjectsPointer, IntPtr nativeRequestContext, IntPtr moduleData, Int32 flags) at System.Web.Hosting.PipelineRuntime.ProcessRequestNotification(IntPtr rootedObjectsPointer, IntPtr nativeRequestContext, IntPtr moduleData, Int32 flags) : String or binary data would be truncated. The statement has been terminated."

**Comment by mlibbey131** [comment]
Tried to process another report with (15) Grid items. The Grid items saved but when I tried to save the permit it looks like the same error code generated. 

![image](https://user-images.githubusercontent.com/58980189/71696205-5ac3c800-2d82-11ea-8a38-81eba76d2cf7.png)


General Database Error: String or binary data would be truncated. The statement has been terminated. CommandText: INSERT INTO AgencyCDR_BusinessLicense.DISTRIBUTOR2LICGRD ( [ADDBY], [APKEY], [DISTRIBUTORLICDETKEY], [DOLLARVALUE], [MODBY], [NAME], [NUMBAGS], [SALEDATE], [VALUEOFBAG] ) VALUES('MLIBBEY', @APKEY, @DISTRIBUTORLICDETKEY, @DOLLARVALUE, @MODBY, @NAME, @NUMBAGS, @SALEDATE, @VALUEOFBAG );SELECT SCOPE_IDENTITY(); at Hansen.Core.Data.Provider.SqlServer7.SqlServer7DataEngine.InsertAndReturnKey(DBStmtAndAll statement, String identityColumn, Boolean ignoreErrors, IEnumerable`1& key, Int32& rowsAffected) at Hansen.Core.Data.Engine.AbstractDataEngine.InsertAndReturnKey(DBStmtAndAll statement, String identityColumn, IEnumerable`1& keys) at Hansen.Core.Data.DataSource.Add(Component component, String sEmpID, Boolean bOverrideDefaultDateStamps) at Hansen.Core.Business.Component.AddInternal() at InforClient.AgencyCDR.BusinessLicense.Distributor2LicGrd.Add() at Hansen.Core.Business.ComponentCollection.UpdateAll(Component oParentComp) at Hansen.Core.Business.Component.ProcessChildCollections() at Hansen.Core.Business.Component.AddInternal() at InforClient.AgencyCDR.BusinessLicense.DistributorLicDetail.Add() at Hansen.Core.Business.Component.ProcessChildCollections() at Hansen.Core.Business.Component.AddInternal() at Hansen.CDR.BusinessLicense.LicenseDetail.Add() at Hansen.Core.Business.ComponentCollection.UpdateAll(Component oParentComp) at Hansen.Core.Business.Component.ProcessChildCollections() at Hansen.Core.Business.Component.AddInternal() at Hansen.CDR.BusinessLicense.LicenseApplication.Add() at Hansen.CDR.BusinessLicense.BusinessLicenseApplet.OnSaveClick() at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor) at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments) at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) at Hansen.Core.MethodSet.Execute(String method, Object[] args) at Hansen.UI.Web.VisualApplet.CallEventProcDelegate(VisualContext context, String method, VisualDelegate parent, VisualApplet& va, Object[] args) at Hansen.UI.Web.Controls.CBlock.ProcessEvent(String aid, String dataset, String bases, String moniker, String fn, String src, String vid, Object[] args) at Hansen.UI.Web.Controls.CBlock.ProcessRequest(String req) at Hansen.UI.Web.Controls.CBlock.Page_Load(Object sender, EventArgs e) at System.Web.UI.Control.OnLoad(EventArgs e) at System.Web.UI.Control.LoadRecursive() at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint) at System.Web.UI.Page.ProcessRequest(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint) at System.Web.UI.Page.ProcessRequest() at System.Web.UI.Page.ProcessRequest(HttpContext context) at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() at System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step) at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) at System.Web.HttpApplication.PipelineStepManager.ResumeSteps(Exception error) at System.Web.HttpApplication.BeginProcessRequestNotification(HttpContext context, AsyncCallback cb) at System.Web.HttpRuntime.ProcessRequestNotificationPrivate(IIS7WorkerRequest wr, HttpContext context) at System.Web.Hosting.PipelineRuntime.ProcessRequestNotificationHelper(IntPtr rootedObjectsPointer, IntPtr nativeRequestContext, IntPtr moduleData, Int32 flags) at System.Web.Hosting.PipelineRuntime.ProcessRequestNotification(IntPtr rootedObjectsPointer, IntPtr nativeRequestContext, IntPtr moduleData, Int32 flags) at System.Web.Hosting.UnsafeIISMethods.MgdIndicateCompletion(IntPtr pHandler, RequestNotificationStatus& notificationStatus) at System.Web.Hosting.UnsafeIISMethods.MgdIndicateCompletion(IntPtr pHandler, RequestNotificationStatus& notificationStatus) at System.Web.Hosting.PipelineRuntime.ProcessRequestNotificationHelper(IntPtr rootedObjectsPointer, IntPtr nativeRequestContext, IntPtr moduleData, Int32 flags) at System.Web.Hosting.PipelineRuntime.ProcessRequestNotification(IntPtr rootedObjectsPointer, IntPtr nativeRequestContext, IntPtr moduleData, Int32 flags) : String or binary data would be truncated. The statement has been terminated.

**Comment by JuanitaMiles** [comment]
@calequin I have confirmed with Ashlye B and Megan. Please extend the allowed number of characters in the Name of Organization field of the Monthly Sales grid to at least 50. If this fix needs to be done after hours that it fine.

This will be even more important when this application type eventually goes on R4C, customers may run into errors entering longer names and will not know to abbreviate.

**Comment by calequin** [comment]
fixed in test.
need to deploy the following:
Schema Manager > Agency CDR.BusinessLicense > Distributor2LicGrd
Column Name change from 30 - 50
Synchronize table

**Comment by ScottVanSooy** [comment]
Deployed to Prod - 2020-01-05

**Comment by mlibbey131** [comment]
Issue Fixed DR257256
