### ISSUE TITLE
Report- Release County Escrow (Bond_CDR Common)

### ISSUE THREAD

**Issue by emilypearl1** [dhenry-KCI/FredCo-Post-Go-Live-#145]
![ap 98508 bt 3777](https://user-images.githubusercontent.com/58855801/71668918-dac54000-2d38-11ea-9d60-ec10d747e4a4.PNG)

I released the remainder of the bond #3777 related to permit 98508. I released $3324.50 (what was remaining under this bond) when i printed the release document- the TOTAL AMOUNT AUTHORIZED FOR RELEASE doesnt match the amount that I am releasing.....

**Comment by TaraF** [comment]
@emilypearl1 @ABonomo21  - fixed per discussion - line item is also the total amount.  Ready for re-test.

**Comment by emilypearl1** [comment]
Thank you! looks great. 

Closing Ticket
