### ISSUE TITLE
Townhouse Permits-children not issuing automatically after parent issues

### ISSUE THREAD

**Issue by awhite806** [dhenry-KCI/FredCo-Post-Go-Live-#146]
The parent permit #258266 issued on 12/30/2019. The four child permits 258255, 258256, 258260, 258263, did not issue until I manually hit check status and next staged them this morning, 1/2/2020. If the child permit is only waiting on the parent permit to be issued, then once the parent permit is issued, the child permits should automatically issue during the batch progression.
![image](https://user-images.githubusercontent.com/58981029/71668804-54a8f980-2d38-11ea-9be1-47b7b70b29c6.png)

![image](https://user-images.githubusercontent.com/58981029/71668784-45c24700-2d38-11ea-86b2-094b365b1367.png)

**Comment by calequin** [comment]
this should be fixed with the batch manager fix by @ScottVanSooy

**Comment by ABonomo21** [comment]
parent 258762
children 258766
258768
258769
258764

stuck in a loop and cannot issue

**Comment by ABonomo21** [comment]
capacity issue was resolved by christian but now the problem goes with ticket 53#

**Comment by megisys** [comment]
BP_RESBLDG_ChildrenIssued_SCF to be promoted

**Comment by megisys** [comment]
Add Formula P_UpdateChildApplications to Prod from TEST

**Comment by megisys** [comment]
Add new Condition as attached
![image](https://user-images.githubusercontent.com/47392306/72094967-85170780-32e5-11ea-866a-466fea98b2e8.png)

**Comment by ScottVanSooy** [comment]
Promoted 2020-01-09

**Comment by ABonomo21** [comment]
This did not work - Parent issued and the children are still stuck in pending issuance- had to check status to progress- does this need to wait for a batch manager to run ?? 

Test permits 259399
259400
259401
259403
259404

![image](https://user-images.githubusercontent.com/47611580/73274994-80db5d00-41b4-11ea-871c-fe8dae20aaab.png)

**Comment by calequin** [comment]
@ABonomo21 yes this needs to wait for the next milestone progression batch manager task to run nightly.
