### ISSUE TITLE
Grading Permit - DPZ Review

### ISSUE THREAD

**Issue by emilypearl1** [dhenry-KCI/FredCo-Post-Go-Live-#147]
Grading permit 258777 
Grading permits spawned from a SFD permit (#258763) should not generate a DPZ review. The DPZ review is already completed under the SFD permit and is not needed under the grading permit. 

![258777 DPZ review](https://user-images.githubusercontent.com/58855801/71670766-fcc1c100-2d3e-11ea-8f7f-64944cce55b1.PNG)

**Comment by megisys** [comment]
If Parent = RES Building AP Type then DPZ AddonCondition = False

**Comment by megisys** [comment]
GRADING_DPZ_Review_AOC


PLease Promote from TEST to PROD

**Comment by ABonomo21** [comment]
fixed. closing ticket. 1/8/2020 EP
