### ISSUE TITLE
Customer can not see attachments on their permit on R4C

### ISSUE THREAD

**Issue by awhite806** [dhenry-KCI/FredCo-Post-Go-Live-#148]
We have a customer that can not see their attachments on their electrical permit on their R4C account. She emailed me these screenshots to show the difference between her ResUse permit (which she could see attachments) and her electrical permit (which she can't)
![image](https://user-images.githubusercontent.com/58981029/71671433-06e4bf00-2d41-11ea-94d6-ce437cd4565e.png)
![image](https://user-images.githubusercontent.com/58981029/71671461-17953500-2d41-11ea-99be-9730c43fd10b.png)

**Comment by calequin** [comment]
@awhite806 I believe the customer is mistakenly looking up the record as public. I checked the Reuses application 257833 and it is using the contact md01permitrequest@vivintsolar.com for the portal. This contact is not being used for the Electrical Permit therefore they cant see the attachments online. Please add md01permitrequest@vivintsolar.com user as an applicant for them to see it on the portal as well.

**Comment by calequin** [comment]
The contact associated with the portal is SHANNON DELACRUZ

**Comment by awhite806** [comment]
added Shannon Delacruz. I asked Kelli to let me know if it happens again. closing this issue for now.
