### ISSUE TITLE
Gaming Permits-Can't Check Status

### ISSUE THREAD

**Issue by mlibbey131** [dhenry-KCI/FredCo-Post-Go-Live-#149]
When I try to Check the Status on any Gaming Permit I receive these error messages. Example Permit# 8818

![image](https://user-images.githubusercontent.com/58980189/71671330-cb49f500-2d40-11ea-8d7d-70d36ae5a43a.png)

![image](https://user-images.githubusercontent.com/58980189/71671335-d56bf380-2d40-11ea-99ac-e32f9b4df38f.png)

**Comment by calequin** [comment]
spoke with Megan. Seems to be an issue with expired Gaming permits only in Prod. I tried to replicate in Test. Working with @ScottVanSooy to identify the issue

**Comment by calequin** [comment]
copy over USE_DeniedReviewResult_AOC to prod

**Comment by mlibbey131** [comment]
Was able to Check Status and close permits 1/3/19-ML
