### ISSUE TITLE
Building Permits - Add AP Name to All Notifications

### ISSUE THREAD

**Issue by JuanitaMiles** [dhenry-KCI/FredCo-Post-Go-Live-#152]
The application **AP name** needs to be added to all building permit notifications. Customers that have a large volume of applications coming through the system are getting confused as to which emails are related to which permits.

![image](https://user-images.githubusercontent.com/31770504/71674429-25e74f00-2d49-11ea-9f9f-350f8bab70d5.png)

**Comment by calequin** [comment]
added to all building notifications
