### ISSUE TITLE
Building Permits - Capacity - Cannot Result DUSWM Review Due to Notification Error

### ISSUE THREAD

**Issue by JuanitaMiles** [dhenry-KCI/FredCo-Post-Go-Live-#153]
CAPACITY - RESIDENTIAL SINGLE FAMILY DWELLING
AP # 258810

Capacity permits continue to receive notification errors when trying to result reviews that might trigger a notification. This permit spawned from a REBLDG permit in Frederick County (not a town). Error occurs when trying to result the DUSWM review.

![image](https://user-images.githubusercontent.com/31770504/71675326-837c9b00-2d4b-11ea-9ae9-bb1594f16cec.png)

![image](https://user-images.githubusercontent.com/31770504/71675355-968f6b00-2d4b-11ea-9401-ee6d62520b2a.png)

**Comment by calequin** [comment]
same issue as the GRADING one with @emilypearl1 . The applicant has requested to not receive notification therefore the formula gets confused. Working a better solution with @ScottVanSooy . StopNOT log will allow progression for now

**Comment by megisys** [comment]
StopNot is the solution here..

**Comment by ABonomo21** [comment]
all notifications need to be fixed

**Comment by megisys** [comment]
SendNotifications - Promote to Production Please

**Comment by ScottVanSooy** [comment]
Promoted 2020-01-09

**Comment by JuanitaMiles** [comment]
Notified DUSWM. Requested that any further issues be reported. Closing for now.

**Comment by JuanitaMiles** [comment]
Reopening issue. Terry received the error message when trying to result the DUSWM review. (1/17/20 2:50 pm) AP#260605. 
![image](https://user-images.githubusercontent.com/31770504/72757524-2fbcdf00-3b9e-11ea-8e09-4d32d5d50579.png)

**Comment by megisys** [comment]
Please let me know the result so i can see this failure in action please.

Dan

**Comment by JuanitaMiles** [comment]
You can see in the screenshot, the result Terry was trying to input was Approved.

**Comment by megisys** [comment]
This application is now complete. the weird thing is it had a town reviewer added but it is a frederick address.

**Comment by megisys** [comment]
Now the town reviewer is gone. I wish this was in test for me to play around with but it isnt. I need to hit another one which is in test to finally solve this issue.

DAn

**Comment by JuanitaMiles** [comment]
@megisys I've replicated everything about application 260605 from prod in test with the exception of the two extra applicants. The test application # is 259381.

The application automatically added the TOWNR applicant as expected. 
I approved the completeness check and application moved to Under Review as it should.
Tried to Approve the DUSWM review and get the notification error message, the same Terry has above.

This is an application in the town of Walkersville. The parcel township code is 11 = Walkersville. I will leave this application in it's current state in TEST for you to test with.

**Comment by megisys** [comment]
See Application 259381. It approved for me no issue.. Can we jump on together today and replicate again.. Will need to be after 3:30pm

**Comment by megisys** [comment]
You got the issue as you are in TEst and the system has you with no valid contact. I updated you so you are right. TMay is set correctly in production

**Comment by megisys** [comment]
Has this happened lately ? we have addressed some changes around this please advise ?

**Comment by JuanitaMiles** [comment]
closing - for now will reopen until we see again.
