### ISSUE TITLE
Can't remove inspections during revisions

### ISSUE THREAD

**Issue by awhite806** [dhenry-KCI/FredCo-Post-Go-Live-#155]
Permit 258593- this permit had an inspection scheduled but then the customer started a revision and now we are unable to remove the inspection due to the fees being owed for the revision. We still need to be able to remove inspection requests/scheduled dates when the fees are owed so the inspections don't occur and they do not appear on our inspectors scheduled list.

**Comment by ABonomo21** [comment]
This needs to be completed

**Comment by calequin** [comment]
techs need to add INSPSCHED log in order to override the inspection schedule lock. This is in place since the formula shares the portal and we do not want to allows users to schedule online when fees are due.

**Comment by ABonomo21** [comment]
if there are fees on the permit such as a re-inspection fee or the revision fee this override via the log does not work to remove the inspection date.

**Comment by megisys** [comment]
Things here were done in the wrong order.. The inspection should have been cancelled and then the revision. If you do revision and then try and cancel the inspection this will happen. We need this to be this way to stop people scheduling inspections when fees are due. I suggest waiving the fee. Cancel inspection and then readd revision fee

**Comment by ABonomo21** [comment]
thank you
