### ISSUE TITLE
Planning-unable to move milestones-error message

### ISSUE THREAD

**Issue by MLWilkins** [dhenry-KCI/FredCo-Post-Go-Live-#156]
went to change a milestone and got this error.  never got to the point of selecting a new milestone

![image](https://user-images.githubusercontent.com/50637067/71684084-6dc6a000-2d62-11ea-93d2-d0da1d0e33ad.png)

tried a second time with same result
![image](https://user-images.githubusercontent.com/50637067/71684128-9a7ab780-2d62-11ea-89cc-ce812172fe25.png)

this was not an issue last week.

**Comment by calequin** [comment]
@MLWilkins is this still an issue? I tried in PROD by clicking the change milestone and it was allowing me to select. I also tried in test and it was succesful. I used AP #1138 to replicate.

**Comment by MLWilkins** [comment]
in prod I moved milestones on 1138 as well as 1159 with success.
