### ISSUE TITLE
Withdrawl Request not showing on dashboard

### ISSUE THREAD

**Issue by emilypearl1** [dhenry-KCI/FredCo-Post-Go-Live-#157]
Applicant submitted withdrawl (refund and void) requests for 5 permits. They are all showing up on the logs- however they are not showing up on dashboards!! We would not have known about this, however he came in to the office to verify.  

![withdrawl 258449](https://user-images.githubusercontent.com/58855801/71684526-ba5eab00-2d63-11ea-9217-bfd8190e7b2d.PNG)

![Dashboard](https://user-images.githubusercontent.com/58855801/71684527-bb8fd800-2d63-11ea-8615-268a6c8b029d.PNG)

Reviewed by Ashlye.

**Comment by JuanitaMiles** [comment]
@emilypearl1 There were two different "withdraw" log types. I've updated the dashboard to look for the "WITHREQ" log code type. This will require a manual dashboard refresh.

When I run the dashboard report I now see the WITHREQ logs. Please remember these will require a stop date to be input in order for them to come off the dashboard.

![image](https://user-images.githubusercontent.com/31770504/71685050-360d2780-2d65-11ea-8767-626a450eb7f1.png)

**Comment by emilypearl1** [comment]
Great!! Thank you!! Closing ticket

**Comment by emilypearl1** [comment]
RESOLVED!! Thank you!!
