### ISSUE TITLE
Customer is unable to upload attachments for a revision

### ISSUE THREAD

**Issue by awhite806** [dhenry-KCI/FredCo-Post-Go-Live-#158]
Our customer was unable to upload an attachment for her required resubmittal due to the permit being in the milestone of Under Review.  I have already done the revision for her and was able to get her to send me the screenshot of R4C not allowing her to upload an attachment. She was able to get the Applicant Actions sent to us for the revision but not the required attachment. The permit was in the "Awaiting Applicant Revisions and then Revision Assignment" milestone. it did not go back into Under Review milestone until i completed the revision in the back office
![screen shot](https://user-images.githubusercontent.com/58981029/71686191-699d8100-2d68-11ea-9c07-33fbebbf58da.png)

**Comment by ScottVanSooy** [comment]
OK, I'll review the Rhythm settings.

**Comment by calequin** [comment]
promote StopUploadAfterCompletenessCheck formula
