### ISSUE TITLE
Capacity Permit Requirement 

### ISSUE THREAD

**Issue by ABonomo21** [dhenry-KCI/FredCo-Post-Go-Live-#16]
Permit 202540 had a status check for a capacity permit being required but there is no plumbing and should not have had this status check. We override it to progress forward 
![SnipImage](https://user-images.githubusercontent.com/47611580/70922447-20bd9c80-1ff4-11ea-894a-b37d0ad854f6.JPG)

**Comment by megisys** [comment]
Can not fix this issue. It is an old permit and our formulas are look at the Non Res Intake page which isnt there as it is an old permit

**Comment by ABonomo21** [comment]
is the code set correctly for new permits? @megisys

**Comment by megisys** [comment]
Yes new are good.. This needs to just close out old ones
