### ISSUE TITLE
Hyrdo Inspection not generating 

### ISSUE THREAD

**Issue by ABonomo21** [dhenry-KCI/FredCo-Post-Go-Live-#161]
Fire Suppression permits should generate the hyrdo inspection at the same time as the visual/ insulation inspection.

**Comment by ScottVanSooy** [comment]
@ABonomo21 

I'm sorry Ashlye, what inspection type is the Hydro Inspection?

Thanks,

Scott

**Comment by megisys** [comment]
@ABonomo21 . Hi there. trying to address. Need a screenshot and a little more details here. No experience with Hydro Inspections.

Thanks

Dan

**Comment by ABonomo21** [comment]
get rid of visual and insulation only add hydro static inspection instead.

**Comment by calequin** [comment]
EXPIRED - FIRE-SPVLT in test 
EXPIRED - FIRE-INSUL
promote FIRE_SprinklerHydrostatic_Insp_AOC

**Comment by calequin** [comment]
promoted 1.9.2020
