### ISSUE TITLE
Grading Permit - Compliance Inspection

### ISSUE THREAD

**Issue by dhenry-KCI** [dhenry-KCI/FredCo-Post-Go-Live-#162]
The grading permit populated a guarantee release inspection after the notice to proceed inspection. the system should have a generated an ECS Compliance Inspection as the next scheduled inspection. 

AP#200374 
**NOTE THAT THE AP DOES HAVE AN ECS INSPECTION THAT WAS ADDED BY E. DODSON**

![image001](https://user-images.githubusercontent.com/4129185/71671653-968a6d80-2d41-11ea-99ff-2179aaaa466f.jpg)

**Comment by ScottVanSooy** [comment]
@dhenry-KCI 

Dustin, I tried in test and the ECS inspection did add just fine. I'm wondering if this was fixed in a different ticket.  Do we have another app we can test on?  I don't see any changes I can make.

**Comment by JuanitaMiles** [comment]
Spoke to Eric, he said he should have another one of these in a week or so to test this again. Closing this for now.
