### ISSUE TITLE
Milestone Progression Error- Fire Permit 

### ISSUE THREAD

**Issue by ABonomo21** [dhenry-KCI/FredCo-Post-Go-Live-#164]
Pdox review was resulted as a resubmit 
![image](https://user-images.githubusercontent.com/47611580/71727814-73c38c00-2e09-11ea-91cd-8dd8774ffcb5.png)
the milestone stayed in under review which is should have moved to awaiting application revisions, generated the $27.00 fee and then the applicant should have gotten a new task in PDox. 

![image](https://user-images.githubusercontent.com/47611580/71727881-a2d9fd80-2e09-11ea-96b6-c47d9b49cb61.png)
![image](https://user-images.githubusercontent.com/47611580/71727912-b71dfa80-2e09-11ea-9a75-f430bb549926.png)

I added the $27.00 fee but this did not follow any of the milestones we set up

**Comment by ABonomo21** [comment]
all of these permits were revised via pdox without ever being assessed fees in IPS or moving to the right milestones... 
![image](https://user-images.githubusercontent.com/47611580/71841503-8ea63280-308d-11ea-8a3d-cee2854f9fc3.png)

**Comment by megisys** [comment]
@ABonomo21  Are we only seeing this for Fire Applications ?? Or other Building Applications ? Or is Fire the only PDox type at this point ?

**Comment by ABonomo21** [comment]
![image](https://user-images.githubusercontent.com/47611580/71989226-41e26900-31ff-11ea-9094-ca96d626794c.png)

**Comment by megisys** [comment]
Suppression Detail are not complete. Do a Status Check on these guys

**Comment by ABonomo21** [comment]
when you are doing a resubmit... the details would not be completed it should overlook that condition on a resubmit.

**Comment by megisys** [comment]
BP_FireSuppressionDetails_SCF - Promote to Production

**Comment by ScottVanSooy** [comment]
Promoted 2020-01-09

**Comment by ABonomo21** [comment]
moved to awaiting applicant revisions- fee added 

did not recognize that there was a resubmit in pdox but i think it was because it happened prior to the ips fix so i will re-open is it happens in the future.
