### ISSUE TITLE
Gaming Permits-Not Closing out on their own

### ISSUE THREAD

**Issue by mlibbey131** [dhenry-KCI/FredCo-Post-Go-Live-#165]
There are some gaming reports that I approved the conditions prior to their expiration of 12/31/19. I have gone back to look at them and they did not close out on their own once they expired. Unless I hit the check status button to progress them they do not close out on their own if the conditions are approved and they are expired. Example Permit# 9010

![image](https://user-images.githubusercontent.com/58980189/71729873-d3706600-2e0e-11ea-9783-23eaff11ef49.png)

![image](https://user-images.githubusercontent.com/58980189/71729976-031f6e00-2e0f-11ea-9b55-4c5566a876c7.png)

![image](https://user-images.githubusercontent.com/58980189/71730276-bbe5ad00-2e0f-11ea-8c72-97e367d63624.png)

**Comment by calequin** [comment]
this is part of batch manager that needs to be restarted. @ScottVanSooy is working on it. Need go ahead from @dhenry-KCI
