### ISSUE TITLE
STOPNOT Log Functionality - Need to Add Correspondence to this

### ISSUE THREAD

**Issue by JuanitaMiles** [dhenry-KCI/FredCo-Post-Go-Live-#166]
I spoke with Christian to confirm whether or not the STOPNOT log prevents notifications AND correspondence from sending to applicants. He does not believe the code behind this log stops correspondence.

We need to add the functionality to this log to stop correspondence from sending as well.

![image](https://user-images.githubusercontent.com/31770504/71732644-c9059a80-2e15-11ea-8bcc-7f792f201ea3.png)

**Comment by megisys** [comment]
Just Notifications

**Comment by megisys** [comment]
This is a huge piece of change. Will need to be put as a delivery project piece

**Comment by megisys** [comment]
Please Promote

BP_COR_COO
BP_COR_DrivewayCoC_AOC
BP_CDR_GradingCoC_AOC
BP_ISSUE_BP
USE_ISSUANCE
USE_GAMING_PERMIT_ISSUE
BP_COC_GENERAL
PLUMB_ISSUE_P
PLUMBPERM_ISSUE_AOC
BP_COR_ELECPERM_ISSUE_AOC
ZONING_CERT_ISSUED_AOC
BP_Hold_Notification_AAF
BP_COR_COC_Driveway_AOC
BP_COR_PLUMBINGPERMIT_AOC
BP_COR_FIRE_PLACARD_AOC
BP_COR_Grading_Permit_AOC
USE_COR_GAMINGBINGO_PERMIT_ISSUE
USE_COR_PERMIT_ISSUE
USE_COR_TipJarOffPremise_PERMIT_ISSUE
USE_COR_TipJarOnPremise_PERMIT_ISSUE
USE_COR_RAFFLE_PERMIT_ISSUE
BP_COR_ZONING_CERTIFICATE_AOC
BP_ExtensionReviewSetDateFee_BUF
USE_COR_GAMING_PERMIT_ISSUE
BP_COR_COCDriveway_AOC
USE_PLACARDISSUANCE
GRADING_CorrespondanceIssue_AOC
TRAILER_ISSUE_BP
BP_OFFPLACARD_AOC
TANKS_ISSUE_BP
FRO_APPROVAL_LETTER_AOC
BP_OFFICIAL_ISSU_AOC
BP_PERM_TRAILER_COO_AOC
PRECON_MEETING_LETTER_AOC
BP_COR_FROPLACARD_ISSUE_AOC
FRO_OFFPLACARD_AOC
PRECON_INSP_CHKLST

**Comment by ScottVanSooy** [comment]
Still need to Promote BP_COR_FROPLACARD_ISSUE_AOC
