### ISSUE TITLE
Building Permits - Capacity - Mains Heights Subdivision Fees

### ISSUE THREAD

**Issue by JuanitaMiles** [dhenry-KCI/FredCo-Post-Go-Live-#167]
CAPACITY - RESIDENTIAL SINGLE FAMILY DWELLING
AP # 258889

The MAINS HEAIGHTS subdivision code 20S002 needs to automatically add the RESIDENTIAL SEWER FEE 20600 ($7509.00) when it is a residential occupancy type.

Terry manually added the incorrect fee to this application but she has confirmed it should be the RESIDENTIAL SEWER FEE 20600 fee.

![image](https://user-images.githubusercontent.com/31770504/71733317-42ea5380-2e17-11ea-9576-7881d1c539e0.png)

![image](https://user-images.githubusercontent.com/31770504/71733351-60b7b880-2e17-11ea-8970-e7a6f37cc325.png)

**Comment by ScottVanSooy** [comment]
I need assistance on this.  The formula involved does not look at the SubDivision field.  I need all the rules that should apply to this Fee.

Thanks,

Scott

**Comment by ScottVanSooy** [comment]
Promote  

CAPACITY_ResSewer20600_Fee_AOC 

to Production

**Comment by JuanitaMiles** [comment]
Will email DUSWM with confirmation that this issue has been fixed. Closing for now.
