### ISSUE TITLE
R4C- Slow

### ISSUE THREAD

**Issue by ABonomo21** [dhenry-KCI/FredCo-Post-Go-Live-#168]
Receiving complaints of portal taking a long time to load at any menu no matter if they are logged in or not, 

Gary and I tested without being logged in and it was very slow

**Comment by calequin** [comment]
@ABonomo21 it is working really fast on my end. Loading time is about 118 ms. I have asked Rick L to see if IIT was testing speed earlier today.

**Comment by ABonomo21** [comment]
received two new complaint and witnessed r4c being slow today.

**Comment by calequin** [comment]
@ABonomo21 can I get the username? I need to be able to see a couple of things and replicate them in test to determine what is causing the speed issue.

**Comment by ABonomo21** [comment]
MGraham@ramcopermits.com

**Comment by megisys** [comment]
Upgrade to be carried out on Tuesday and tested by the county in Test

**Comment by megisys** [comment]
Removing Christian and I . this is a Product Ticket . We believe this will be solved in latest release. Leave here until the County confirms latest release solved the issues.

**Comment by JuanitaMiles** [comment]
@ABonomo21 @AReed327 @MLWilkins  County testing staff please monitor during testing and advise if you are happy (or unhappy) with the speed of R4C. Assigning to all of you for input.

**Comment by ABonomo21** [comment]
Received feedback from a few customers over the past couple of days about how improved the speed is. More importantly Maddison provided feedback that her speed has been great. 

Mike and Ashley have you had any feedback @MLWilkins @AReed327

**Comment by ABonomo21** [comment]
mike okay with closing will monitor in the future.
