### ISSUE TITLE
Reporting - Building Permits - Plumbing - Building Application Details Comments Issue

### ISSUE THREAD

**Issue by JuanitaMiles** [dhenry-KCI/FredCo-Post-Go-Live-#169]
Plumbing Permit - AP # 188433

When running the Building Application Details report we've noticed that the comments from some inspections are coming through with some sort of html looking code.

![image](https://user-images.githubusercontent.com/31770504/71742187-ef83ff80-2e2e-11ea-84c5-4673541c730b.png)

It looks like it might be happening when there are line breaks in the Comments box on the Inspection.

![image](https://user-images.githubusercontent.com/31770504/71742148-ccf1e680-2e2e-11ea-9875-8b7635b172f5.png)

**Comment by ABonomo21** [comment]
Also doing this on home occupation official issuance H257738

**Comment by ABonomo21** [comment]
![image](https://user-images.githubusercontent.com/47611580/71827998-79221000-306f-11ea-9485-b7bc6f5e6962.png)

**Comment by TaraF** [comment]
Updated, ready for re-test.

**Comment by JuanitaMiles** [comment]
We are still seeing some issues with comments, a couple examples below:

AP # 190831 - RESUSES
![image](https://user-images.githubusercontent.com/31770504/72171488-14352580-33a1-11ea-89c7-e7b54c7814e0.png)

![image](https://user-images.githubusercontent.com/31770504/72171445-fd8ece80-33a0-11ea-9935-80e074cec323.png)

AP # 259261 - RESUSES
![image](https://user-images.githubusercontent.com/31770504/72171607-52324980-33a1-11ea-85df-c4bfb6fb5872.png)

![image](https://user-images.githubusercontent.com/31770504/72171548-33cc4e00-33a1-11ea-93ea-d5c550344fe4.png)

**Comment by TaraF** [comment]
Updated.  Ready for re-test (PROD).
