### ISSUE TITLE
Town reviewers on trade permits 

### ISSUE THREAD

**Issue by ABonomo21** [dhenry-KCI/FredCo-Post-Go-Live-#17]
we do not need town reviewers to generate on trade permits... 
![SnipImage](https://user-images.githubusercontent.com/47611580/70922512-3632c680-1ff4-11ea-84dc-0ff22ed24f79.JPG)

**Comment by ABonomo21** [comment]
duplicated

**Comment by calequin** [comment]
PROMOTE - BP_AddTownReviewer_AAF

**Comment by megisys** [comment]
Closing due to length of time open
