### ISSUE TITLE
Official Issuance sent out on an unissued permit 

### ISSUE THREAD

**Issue by ABonomo21** [dhenry-KCI/FredCo-Post-Go-Live-#171]
196110 is not issued and the official issuance documents sent after granting an extension on the application. 

It also sent multiple times?? 
![image](https://user-images.githubusercontent.com/47611580/71817367-a365d480-3053-11ea-8df4-018e15dc9120.png)
![image](https://user-images.githubusercontent.com/47611580/71817375-acef3c80-3053-11ea-8083-93f77a0b1e79.png)

**Comment by megisys** [comment]
We were told to resend new Placard and Issuance on Extensions. The details were no refined enough on the last request. So do we need to say only send Issued Correspondence if issued date is set.

**Comment by megisys** [comment]
BP_ExtensionReviewSetDateFee_BUF to be promoted
