### ISSUE TITLE
PLANNING - Fee applied by

### ISSUE THREAD

**Issue by AReed327** [dhenry-KCI/FredCo-Post-Go-Live-#172]
I'm concerned that the Fee applied by seems to be populating as the last person who accessed the file. This project # 19913 indicates that Alicia Evangelista with the health department applied planning fees to the project. 
Thoughts on the significance of the applied by person? I think it could lead to issues and confusion since the HEALTH dept would never be adding our fees. 
![image](https://user-images.githubusercontent.com/58854333/71824284-30feef80-3067-11ea-8530-674710f4f3d8.png)

**Comment by AReed327** [comment]
Turns out that the recalculate works if the fee was generated in IPS. Not if it was transferred from Hansen 7. It does not appear to give the update under the fee when it was recalculated. AREED

**Comment by megisys** [comment]
Hide that Column. This is whoever moves the application to the next milestone. If you don't like to see this, then dont look at it.

Dan

**Comment by megisys** [comment]
Hi There. 

I got feedback I was a little unclear or terse in my response. Please hide this column from your default view. It is there for troubleshooting purposes and holds no benefit to reporting. This is not view able by the applicant. Purely lets you know the user who forced a milestone update which resulted in fees being added. Ignore this column

Dan

**Comment by megisys** [comment]
Can we close this one @MLWilkins . There is no solution here other than the user either ignoring the column or hiding it

**Comment by MLWilkins** [comment]
explore possible solutions at Phase 1B or Phase 2

**Comment by megisys** [comment]
Will Add system Generated Column to Building, Planning, Trade, Use, License Fee Columns. to be done directly in Production as no outage is required for screen layout changes.

**Comment by megisys** [comment]
Please test in Production.

**Comment by MLWilkins** [comment]
checked multiple applications and types.  Looks good!


![image](https://user-images.githubusercontent.com/50637067/73094430-90a22b00-3eae-11ea-9b5d-fbb974b2b101.png)
