### ISSUE TITLE
Planning - Project Pending Letter - Missing Mylar Fee

### ISSUE THREAD

**Issue by AReed327** [dhenry-KCI/FredCo-Post-Go-Live-#173]
Mylar Fee is not populating on the PLANNING - Project Pending Letter report. It is showing th $59 in IPS but $0.00 on the fees owed when you populate the report
[16049 Project Pending Letter.pdf](https://github.com/dhenry-KCI/FredCo-Post-Go-Live-/files/4026585/16049.Project.Pending.Letter.pdf)
![image](https://user-images.githubusercontent.com/58854333/71826738-9e614f00-306c-11ea-8b58-46fb6125095b.png)

**Comment by TaraF** [comment]
This is fixed, ready for re-test.

**Comment by MLWilkins** [comment]
fixed


![image](https://user-images.githubusercontent.com/50637067/72079442-f1374280-32c8-11ea-8a46-ab9a05c12f7e.png)
