### ISSUE TITLE
Home occupation expiration date 

### ISSUE THREAD

**Issue by ABonomo21** [dhenry-KCI/FredCo-Post-Go-Live-#174]
Expiration date generated as 12.17.20- should be one year from the date of issuance. which was 1.6.20
![image](https://user-images.githubusercontent.com/47611580/71827836-14ff4c00-306f-11ea-9b0e-e81b6ad6a499.png)

**Comment by ScottVanSooy** [comment]
I looked in test and this was originally issued on 12/17/19 so the expiration sold be correct.  Does the Expiration need to change when a new Issued Date is assigned?

**Comment by ScottVanSooy** [comment]
Promote to  Production (New Formula on BuildingApplication  > BeforeUpdate)

BP_AdjustExpireDate_BU
