### ISSUE TITLE
Email Address on reports

### ISSUE THREAD

**Issue by ABonomo21** [dhenry-KCI/FredCo-Post-Go-Live-#175]
if there is no email address listed for an applicant can we leave it off reports, it does not look very clean. 

it would be any blank email or a "noemailaddress"... 
![image](https://user-images.githubusercontent.com/47611580/71827965-5f80c880-306f-11ea-9acf-cfa290ffbed9.png)

**Comment by TaraF** [comment]
@dhenry-KCI  -- adding you here to confirm what email text we should be looking for.  Note what is called out above is different than the standard:

noemail@noemail.com or noemail@frederickcountymd.gov

Thanks!

**Comment by megisys** [comment]
ANything which starts with noemail

**Comment by TaraF** [comment]
Assigned, in progress. Completed for Building Permit Official Issuance, will notify when other official issuance reports are done.

**Comment by TaraF** [comment]
This is updated as requested for the following:

- Building Permit - Official Issuance
- Plumbing Permit - Official Issuance
- Electrical Permit - Official Issuance
- Zoning Certificate
- Use Permit - Official Issuance

Please test (in Prod).  If there are other reports this is requested for, please identify which ones.

**Comment by ABonomo21** [comment]
![image](https://user-images.githubusercontent.com/47611580/73566531-159ebe80-4432-11ea-94f3-56b054884c31.png)
