### ISSUE TITLE
Electrical Restricted License not being accepted for permit

### ISSUE THREAD

**Issue by awhite806** [dhenry-KCI/FredCo-Post-Go-Live-#177]
This electrical permit is still stating it needs a active license even though one is already attached as the primary applicant.

![image](https://user-images.githubusercontent.com/58981029/71833862-de7bfe00-307b-11ea-8697-0f7348aa8df5.png)
![image](https://user-images.githubusercontent.com/58981029/71833906-f2bffb00-307b-11ea-8770-b67fd40bd2e8.png)
![image](https://user-images.githubusercontent.com/58981029/71833923-00758080-307c-11ea-8174-5f4e4f63fd4b.png)

**Comment by ScottVanSooy** [comment]
@awhite806 

I believe this is because the IsAgency Contractor check  box is not checked.  

![image](https://user-images.githubusercontent.com/58946969/71848597-c0ff6200-3084-11ea-9d97-ee5e4e7a01a6.png)

**Comment by ScottVanSooy** [comment]
Promote to Production
BP_ELEC_Check_SCF
