### ISSUE TITLE
PLANNING - PDOX FAIL -CUSTOMER WAITING

### ISSUE THREAD

**Issue by AReed327** [dhenry-KCI/FredCo-Post-Go-Live-#178]
Why did this fail? This person is waiting. I need to be able to send them their TEMP password in PDOX. 
![image](https://user-images.githubusercontent.com/58854333/71836728-9b715900-3082-11ea-8e8a-e088250e18c8.png)

**Comment by dhenry-KCI** [comment]
@JuanitaMiles - please take a look at this one first.

**Comment by JuanitaMiles** [comment]
We have resolved this error by removing the "illegal characters" from the Project/Phase Name field. I will create a new ticket for Infor to strip the illegal characters from the Project/Phase Name field. #180
