### ISSUE TITLE
SFD not progressing

### ISSUE THREAD

**Issue by ABonomo21** [dhenry-KCI/FredCo-Post-Go-Live-#179]
Permit #258793 - check status Under Review
![image](https://user-images.githubusercontent.com/47611580/71838084-0d976d00-3086-11ea-8b01-bfd33574491a.png)

All  children have either been voided, issued or closed- there are no pending issuance applications
![image](https://user-images.githubusercontent.com/47611580/71838157-33bd0d00-3086-11ea-8692-0ec1e12ef5c9.png)

Ashlye Reviewed

**Comment by ScottVanSooy** [comment]
I will look into this

**Comment by ScottVanSooy** [comment]
@ABonomo21 

The Formula looks for Child Application with an Issued Date.  It has those.  Moving on, it looks for a Relevant Review with a Result Code of "RESUBMIT".  It doesn't have that, so the application gets stopped.  Is that correct behavior?

Formula BP_RESBLDG_ChildrenIssued_SCF

**Comment by ScottVanSooy** [comment]
Promote
BP_RESBLDG_ChildrenIssued_SCF
To Production

**Comment by ABonomo21** [comment]
worked on test 259827 in test environment
