### ISSUE TITLE
Building Permits - RESBLDG - Pending Cert Parent Complete Status Check

### ISSUE THREAD

**Issue by JuanitaMiles** [dhenry-KCI/FredCo-Post-Go-Live-#18]
RESIDENTIAL BUILDING PERMIT - RESIDENTIAL TOWNHOME
AP # 188183

**This application has been progressed in the Production environment.

Emily reported that this permit was being held up at the Pending Certificate milestone because the parent permit needed to be completed. She overrided this requirement on this application in Prod. 

Per Emily, Town house Certificate of Occupancys can be released at any time and are not dependent on a "parent" to issue.

![image001](https://user-images.githubusercontent.com/31770504/70922275-cfada880-1ff3-11ea-870e-1f41c8447dbf.png)

![image002](https://user-images.githubusercontent.com/31770504/70922296-d89e7a00-1ff3-11ea-8ab5-5cea9bafcb7a.png)

(per email Emily sent to Ashlye 12/13/19 8:44 am)

**Comment by megisys** [comment]
The Parent is the Initial in ROw. Are we sure Ashlye is ok with this

**Comment by JuanitaMiles** [comment]
Emailed Emily and Ashlye requesting confirmation.

**Comment by ABonomo21** [comment]
I talked with Dan - Emily is correct.

**Comment by megisys** [comment]
'  Formula Name: RESBLDG_ParentAptCondo_SCF
'  Description: Apt/Condo - Units stay in pending issuance until parent permit receives COO			
'  Created By: Ibti Mazlout
'  Created On: 9/24/2018
'
'  Revisions
'  ---------
'  IM - Initial Design
'// Revision 1: Altered workflow to function with new R4C details.
StateCheck = True
	Dim ParentStruct As Boolean


If oBldgApp.OccupancyType.Code = "RESAPT" Or oBldgApp.OccupancyType.Code = "RESCON" Then

	Dim detailpage As Hansen.CDR.Building.IApplicationDetail


	Dim oResDets As InforClient.AgencyCDR.Building.ResidentialDetail

	For Each detailpage In oBldgApp.ApplicationDetails

		If detailpage.ApplicationDetailType.ClassName = "InforClient.AgencyCDR.BuildingApplet.TownhouseDetails" Then

			oResDets = InforClient.AgencyCDR.Building.ResidentialDetail.GetInstanceFromParent(detailpage, res)

			ParentStruct = oResDets.ParentStructure

			Exit For

		ElseIf detailpage.ApplicationDetailType.ClassName = "InforClient.AgencyCDR.BuildingApplet.RESBLDG_ADU_IntakePage" Then

			oResDets = InforClient.AgencyCDR.Building.ResidentialDetail.GetInstanceFromParent(detailpage, res)

			ParentStruct = oResDets.ParentStructure

			Exit For

		ElseIf detailpage.ApplicationDetailType.ClassName = "InforClient.AgencyCDR.BuildingApplet.DuplexTwoFamilyDetail" Then

			oResDets = InforClient.AgencyCDR.Building.ResidentialDetail.GetInstanceFromParent(detailpage, res)

			ParentStruct = oResDets.ParentStructure

			Exit For

		ElseIf detailpage.ApplicationDetailType.ClassName = "InforClient.AgencyCDR.BuildingApplet.MobileHomeDetail" Then

			oResDets = InforClient.AgencyCDR.Building.ResidentialDetail.GetInstanceFromParent(detailpage, res)

			ParentStruct = oResDets.ParentStructure

			Exit For

		ElseIf detailpage.ApplicationDetailType.ClassName = "InforClient.AgencyCDR.BuildingApplet.ApartmentAndCondoDetail" Then

			oResDets = InforClient.AgencyCDR.Building.ResidentialDetail.GetInstanceFromParent(detailpage, res)

			ParentStruct = oResDets.ParentStructure

			Exit For

		ElseIf detailpage.ApplicationDetailType.ClassName = "InforClient.AgencyCDR.BuildingApplet.ResidentialDetails" Then

			oResDets = InforClient.AgencyCDR.Building.ResidentialDetail.GetInstanceFromParent(detailpage, res)

			ParentStruct = oResDets.ParentStructure

			Exit For

		End If

	Next





End If

	'Check if this is the parent application
	If ParentStruct = False Then

		'Check parent relationships for parent application
	For Each parent As Hansen.CDR.Building.IParentChildRelationship In oBldgApp.ParentRelationships

			If parent.ParentApplication.ApplicationType.ApplicationType = "RESBLDG" Then

			
								If parent.ParentApplication.FinalizedDateTime > DateTime.MinValue  Then

			StateCheck = False

							End If

						End If

				Next


			End If


if  oBldgApp.ParentRelationships.Count = 0 then
	
	StateCheck = False
	
End if

if oBldgApp.OccupancyType.Code "RESTOW" then

StateCheck = False

End if

**Comment by ScottVanSooy** [comment]
Promoted to Production 12/17/2019 8:30 PM

**Comment by emilypearl1** [comment]
Re-opening. As of 12/18/19 @ 6:24am problem still exists

**Comment by emilypearl1** [comment]
[Capture 1.pdf](https://github.com/dhenry-KCI/FredCo-Post-Go-Live-/files/3978145/Capture.1.pdf)

[Capture 2.pdf](https://github.com/dhenry-KCI/FredCo-Post-Go-Live-/files/3978146/Capture.2.pdf)

12/18/19 EP

**Comment by megisys** [comment]
@emilypearl1 I am sorry on this one.. The Test refresh lost this change. Will do tonight

**Comment by emilypearl1** [comment]
Great- thank you

**Comment by ScottVanSooy** [comment]
Re-Deployed to Production 12/18/19
