### ISSUE TITLE
Planning - PDox Projects - Illegal Characters in Project/Phase Name Field

### ISSUE THREAD

**Issue by JuanitaMiles** [dhenry-KCI/FredCo-Post-Go-Live-#180]
Planning application SP257697 failed to push to PDox due to illegal characters being in the Project/Phase Name field. We have since changed the Project Name and removed the apostrophe to successfully send the application to PDox, however we need to implement the fix Dan created to strip the Project/Phase Name of all illegal characters so projects do not get hung up for this in the future.

![image](https://user-images.githubusercontent.com/31770504/71839196-9ca58480-3088-11ea-8e71-affafcaa827f.png)

**Comment by ScottVanSooy** [comment]
Assigning to Dan.

**Comment by megisys** [comment]
PLN_CleanUpIllegalCharacters to be added from TEST to PRod

**Comment by ScottVanSooy** [comment]
Promote to Production
PLN_CleanUpIllegalCharacter
BLDG_CleanUpApplicationName

**Comment by JuanitaMiles** [comment]
@AReed327 Assigning to Ashley so she can verify the issue has been resolved or just close.

**Comment by MLWilkins** [comment]
fixed per test.

![image](https://user-images.githubusercontent.com/50637067/72085238-fa2d1180-32d2-11ea-9012-ba400a98fa68.png)

![image](https://user-images.githubusercontent.com/50637067/72085290-0d3fe180-32d3-11ea-8744-9eac930f59f6.png)

**Comment by JuanitaMiles** [comment]
Ashley R had to remove extra spaces from the Project/Phase Name from project PW257720 which initially errored when trying to send to PDox. After remove the extra space the application went through. 

Can we please ensure that extra spaces are taken into consideration for the fix above.

**Comment by ScottVanSooy** [comment]
@JuanitaMiles 
Are you talking about spaces together, like "Project    Plan"  or an extra space at the end like "Project Plan "

**Comment by AReed327** [comment]
Like: Lot 201  202 (two spaces between 201 & 202)

Ashley Reed
Development Review Technician II
Department of Development Review
Frederick County Government
30 North Market Street
Frederick, Maryland 21701
(301)-600-1139
AReed@FrederickCountyMD.gov<mailto:AReed@FrederickCountyMD.gov>

**Comment by ScottVanSooy** [comment]
Added Code to remove stings of spaces "     " and strings of "-------" replacing them with 1

Promote to Production
PLN_CleanUpIllegalCharacter_BU
BLDG_CleanUpApplicationName

**Comment by ScottVanSooy** [comment]
This is ready to be closed.

**Comment by MLWilkins** [comment]
will monitor
