### ISSUE TITLE
Covered Porch Over 500 SqFt Fees.

### ISSUE THREAD

**Issue by awhite806** [dhenry-KCI/FredCo-Post-Go-Live-#181]
There are two Covered Porch Over 500 Sq Ft fees and both of them are the incorrect value. It should be $113

![image](https://user-images.githubusercontent.com/58981029/71842094-f1e49480-308e-11ea-8841-f5b1e5373533.png)
![image](https://user-images.githubusercontent.com/58981029/71842213-222c3300-308f-11ea-9fb4-28bd96073327.png)
![image](https://user-images.githubusercontent.com/58981029/71842144-06289180-308f-11ea-81fd-d06dd0385260.png)

**Comment by awhite806** [comment]
partially fixed in Prod. there are still two fees but now they both have the correct value of $113. we just need one fee.

prod:
![image](https://user-images.githubusercontent.com/58981029/71993576-54f83780-3205-11ea-8530-0da57e70bc81.png)
![image](https://user-images.githubusercontent.com/58981029/71993648-748f6000-3205-11ea-90ba-4e20994d7410.png)
![image](https://user-images.githubusercontent.com/58981029/71993695-87a23000-3205-11ea-86c5-0e9a6abbb717.png)

**Comment by calequin** [comment]
fixed in prod. expired BUILDING FEE - COVERED PORCH OVER 500 S
should only display one in the pick list

**Comment by ABonomo21** [comment]
![image](https://user-images.githubusercontent.com/47611580/72010018-0eb2d080-3225-11ea-9cee-b2e4a7214895.png)
