### ISSUE TITLE
PERMITS & PLANNING - CONTACT DETAILS - emails not sending to added contacts

### ISSUE THREAD

**Issue by AReed327** [dhenry-KCI/FredCo-Post-Go-Live-#184]
PL257695 - no notification sent to Gwen

![image](https://user-images.githubusercontent.com/58854333/71903600-6f151580-3132-11ea-83c1-e726e2f47ca7.png)
![image](https://user-images.githubusercontent.com/58854333/71903626-7c320480-3132-11ea-951b-c3cae2b62965.png)
![image](https://user-images.githubusercontent.com/58854333/71903734-b9969200-3132-11ea-84fb-bbda37c7c6b1.png)

**Comment by megisys** [comment]
Was not added to the applicants listing on the application. Should have auto added. Looked at this issue and it is working now

**Comment by megisys** [comment]
This issue has been addressed for GWEN. All new notifications will send. Please monitor for others. A good check is on completeness check to ensure they are listed as applicants if the keep informed is true

**Comment by calequin** [comment]
For promotion-
SWM > PlanContactDetails
disable - AfterAdd and change formula name to PlanCntctDtl_UpdateApplicants_AA
copy PlanCntctDtl_UpdateApplicants_AAC and add to AfterAddCommited

**Comment by calequin** [comment]
promoted on 1.9.2020

**Comment by AReed327** [comment]
I tested this to my personal email and it worked. Two thumbs up. Closing issue.
