### ISSUE TITLE
Planning - Site Type 3 - Health is never a reviewer on this Work Type.

### ISSUE THREAD

**Issue by AReed327** [dhenry-KCI/FredCo-Post-Go-Live-#185]
Remove Health as a reviewer on Site Plan Type 3. 
This has been correct before. Not sure why this is populating again. 
![image](https://user-images.githubusercontent.com/58854333/71904213-bb148a00-3133-11ea-95a8-2700a426bbd2.png)
![image](https://user-images.githubusercontent.com/58854333/71904233-c36cc500-3133-11ea-80a5-14320aaecaf3.png)

**Comment by megisys** [comment]
PLN_SITE_EH_AOC. There needs to be Promoted tonight

**Comment by MLWilkins** [comment]
created SP257687 and SP257688 in TEST.  Health did not populate. 

![image](https://user-images.githubusercontent.com/50637067/71981245-f8d6e880-31ef-11ea-8f94-5148efb5bbb2.png)
