### ISSUE TITLE
Building Permits - Grading - As-Built Inspection Results

### ISSUE THREAD

**Issue by JuanitaMiles** [dhenry-KCI/FredCo-Post-Go-Live-#187]
Comments from E. Dodson:

"Jacob attempted to enter an as-built inspection (599490) to permit # 109657 and received an error message- “inspection type is not effective” when doing a partial pass or fail. It appeared to function properly when it was simply a pass. We need to have all three options available."

Can we please confirm that this inspection type will accept a fail or partial pass result.

**Comment by calequin** [comment]
partial pass is no longer a result code. They need to select the partial check box and the result as passed.

**Comment by JuanitaMiles** [comment]
@calequin I've confirmed with Eric. They applied the partial pass result the correct way, checked the partial check box and selected passed, and got the error. They also tried resulting with Failed and got the error. Only passed was accepted for this inspection.

**Comment by megisys** [comment]
I changed this issue. Inspection Type was expired

**Comment by JuanitaMiles** [comment]
Eric reported this morning that Jacob is still having this issue. I have requested screenshots and details, Jacob should be sending soon.

**Comment by calequin** [comment]
waiting on juanita for screenshots

**Comment by JuanitaMiles** [comment]
@calequin A screenshot of the error provided by Jacob is below. I have also looked in the system, the inspection still appears to be expired in PROD

![image](https://user-images.githubusercontent.com/31770504/72169804-cbc83880-339d-11ea-8b5d-bec3aaccccc8.png)


![Step 3](https://user-images.githubusercontent.com/31770504/72169550-52c8e100-339d-11ea-9c32-43807eb7352d.png)

**Comment by calequin** [comment]
unexpired in prod. ready for retest

**Comment by JuanitaMiles** [comment]
TEST - 259383 - Was able to failed and partial pass ASBUILT inspection
