### ISSUE TITLE
Retaining Wall permit - wrong fees generated 

### ISSUE THREAD

**Issue by ABonomo21** [dhenry-KCI/FredCo-Post-Go-Live-#188]
![image](https://user-images.githubusercontent.com/47611580/71916442-f0c56d00-314b-11ea-94f5-195a822c1dc0.png)
the highlighted fees should not have generated on a retaining wall. 
![image](https://user-images.githubusercontent.com/47611580/71916473-0470d380-314c-11ea-9b12-5e97ff6fe547.png)

**Comment by megisys** [comment]
Which fee are we expecting please for a retainwall ?

**Comment by megisys** [comment]
Investigating

**Comment by megisys** [comment]
NONRESBLDG_Fee_SiteCompliance_AOC
NONRESBLDG_Fee_BLDGNewAddReplaceAcc_AOC
NONRESBLDG_Fee_LifeSafetyReview_AOC

Promote from Test to Prod

**Comment by ABonomo21** [comment]
![image](https://user-images.githubusercontent.com/47611580/72000341-17011080-3211-11ea-9ad2-2ce380684e55.png)
