### ISSUE TITLE
Inspection Cycle

### ISSUE THREAD

**Issue by ABonomo21** [dhenry-KCI/FredCo-Post-Go-Live-#19]
We had to add a ceiling inspection because the inspector did not partially pass the inspection. when we manually added the inspection again it did not keep the same cycle count which should have added the re-inspection fee so we had to manually add it. 

![image](https://user-images.githubusercontent.com/47611580/70922635-6e3a0980-1ff4-11ea-8671-d17f91b204d6.png)

**Comment by megisys** [comment]
Addressed
