### ISSUE TITLE
Building Application Details - On Demand

### ISSUE THREAD

**Issue by ABonomo21** [dhenry-KCI/FredCo-Post-Go-Live-#190]
Under Description of work there is funky stuff going on.... 

![image](https://user-images.githubusercontent.com/47611580/71920821-9c26ef80-3155-11ea-8f61-fe56612aed03.png)

Ashley Reviewed

**Comment by TaraF** [comment]
Updated, ready for re-test.

**Comment by ABonomo21** [comment]
![image](https://user-images.githubusercontent.com/47611580/72079398-d6fd6480-32c8-11ea-93fd-76c213344802.png)
