### ISSUE TITLE
PLANNING - Report (Planning - Project Pending Letter)

### ISSUE THREAD

**Issue by AReed327** [dhenry-KCI/FredCo-Post-Go-Live-#191]
Can we add the review # to this report? It is confusing because the reviews are listed multiple times. People are having trouble determining if they are approved or not. 

![image](https://user-images.githubusercontent.com/58854333/71921788-874b5b80-3157-11ea-8f17-ca635914fa8d.png)

**Comment by TaraF** [comment]
Added, ready for re-test.

**Comment by MLWilkins** [comment]
done


![image](https://user-images.githubusercontent.com/50637067/72079257-900f6f00-32c8-11ea-8df4-d632504b0808.png)
