### ISSUE TITLE
Building Permit Expiration and Notification 

### ISSUE THREAD

**Issue by ABonomo21** [dhenry-KCI/FredCo-Post-Go-Live-#192]
Batch manager needs to be turned on for 11 month and expired notifications

**Comment by megisys** [comment]
PLease create Batch_Expiration_BCT in Production from TEST
PLease create new batch manager task as set up in Test for this formula

![image](https://user-images.githubusercontent.com/47392306/72005215-18cfd180-321b-11ea-81d1-819253a2cd59.png)

**Comment by calequin** [comment]
promoted to prod 1.8.2020

**Comment by ABonomo21** [comment]
this is a very high priority ! we need to have the functionality of the system sending the correspondence and notification that the permits are going to and have expired. we have an obligation to notify our applicants this cannot wait any longer.

**Comment by ScottVanSooy** [comment]
This is scheduled to be fixed tonight.

**Comment by ScottVanSooy** [comment]
Promote Batch_Expiration_BCT after  verifying log type.

**Comment by megisys** [comment]
Update.. This is about 75% complete.. Large redesign element. We are working on it feverishly

**Comment by JuanitaMiles** [comment]
@megisys please ensure report components have been integrated into this fix. Tara has provided the items requested.

![image](https://user-images.githubusercontent.com/31770504/73294013-f6562600-41d2-11ea-9101-ab4a01327d4e.png)

**Comment by megisys** [comment]
So Granted Notification did not send at result of review.
Correspondence dates are old dates . Should generate after the building application is updated.

**Comment by megisys** [comment]
Also the Final Expiration Job. Didn't send the Final Correspondence

**Comment by ABonomo21** [comment]
meeting with Dan 1.28.20 he is working the two issues found

**Comment by ABonomo21** [comment]
Until there is a better fix - It should attach for each applicant. @megisys

**Comment by ABonomo21** [comment]
Re-opening ticket- 

Need clarification on when the 11 month run and for what days? a week.. one month etc? 
What logs are being generated? no logs are generating on building permits. 
How often are they set to send? - should send one time
Same question for expired noticed.
Is this supposed to be working for grading? see permit log for a/p 68005

**Comment by calequin** [comment]
Hi Ashlye, answers to your questions below
Need clarification on when the 11 month run and for what days? a week.. one month etc?  

> The 11 month task (BP_11 Month Process) runs weekly on Mondays and it looks for permits with less than 31 days until it expires.

What logs are being generated? no logs are generating on building permits.

> Log type of EXTREQ is added with a comment of Added by Batch Manager

How often are they set to send? - should send one time

> once a week and only sends one time. the code looks to see if a previous log was created. if created then it bypasses sending it

Same question for expired noticed.

> we fixed the duplicate correspondence sending with the formula on ticket #399 
>
 Is this supposed to be working for grading? see permit log for a/p 68005
> we fixed the duplicate correspondence sending with the formula on ticket #399 
>
