### ISSUE TITLE
DPZ Review on DW in Major Subdivision

### ISSUE THREAD

**Issue by ABonomo21** [dhenry-KCI/FredCo-Post-Go-Live-#193]
There should not be a DPZ review on DW permits (primary) within major subdivisions. 

DW #258474- there should be no zoning review.

**Comment by megisys** [comment]
How do I know what a Major subdivision is ? This seems like a new request to me ? Or did we discuss previously..  Is it that a sub division is listed.. Please explain :) @ABonomo21

**Comment by ABonomo21** [comment]
Dan you will know if it is a major subdivision if there is a subdivision code on the parcel that starts with an S

**Comment by megisys** [comment]
We never discussed this.. This is net new right ? No big deal but will need to be tested in Test.

**Comment by megisys** [comment]
DRIVEWAY_DPZ_Review_AOC  - Promote to Production from TEST

**Comment by ABonomo21** [comment]
I am not sure it if was discussed, I will have Emily jump in to test to check it now

**Comment by ABonomo21** [comment]
Retest failed. Tested in test #259828

![image](https://user-images.githubusercontent.com/47611580/72085281-0c0eb480-32d3-11ea-98bb-b626624a24d8.png)

**Comment by megisys** [comment]
Sorry I added it WAS needed it a major .. Not not needed. Addressed in TEST
DRIVEWAY_DPZ_Review_AOC - Promote to Production from TEST

**Comment by ABonomo21** [comment]
Closing Ticket- resolved. 

thanks for your hard work guys!
