### ISSUE TITLE
Condition on Building permit - Cannot progress 

### ISSUE THREAD

**Issue by ABonomo21** [dhenry-KCI/FredCo-Post-Go-Live-#196]
we have a condition on a resbldg permit that is stating the permit cannot issue until the child permit is issued but all permits are either issued or void... 
![SnipImage](https://user-images.githubusercontent.com/47611580/72068639-862f4100-32b3-11ea-94d2-e8c5e89a1be1.JPG)
![SnipImage](https://user-images.githubusercontent.com/47611580/72068642-87f90480-32b3-11ea-9148-79db66243a71.JPG)

**Comment by megisys** [comment]
Delete the association with the VOID Permit. Then issue is fixed.

**Comment by megisys** [comment]
It needs the children to be issued

**Comment by ABonomo21** [comment]
thanks
