### ISSUE TITLE
RESBLDG - impact fee generation 

### ISSUE THREAD

**Issue by ABonomo21** [dhenry-KCI/FredCo-Post-Go-Live-#197]
impact fees generated on a building permit before all the reviews were completed on the related child permits. 
![image](https://user-images.githubusercontent.com/47611580/72073572-2ab68080-32be-11ea-871f-de1877af0a97.png)
![image](https://user-images.githubusercontent.com/47611580/72073586-330ebb80-32be-11ea-8916-a9b67f79a2fa.png)

**Comment by megisys** [comment]
So it should have stayed under review until all child permits where issued ?? Please explain in more detail. Thanks

DAn

**Comment by ABonomo21** [comment]
That is correct, it should not move to added fees until all reviews are completed on all the related children it should remain in under review.

**Comment by megisys** [comment]
I tested this application in TEST and it is holding up..  Can you move it back to Under Review and waive the fees and see if it holds please.

![image](https://user-images.githubusercontent.com/47392306/72085108-c225ce80-32d2-11ea-8f55-60becc8e8881.png)

**Comment by megisys** [comment]
May need to put a STOPNOT on this one

**Comment by ABonomo21** [comment]
no it did not hold - it moved right back to awaiting applicant payment and duplicated my fees for this application 258240

**Comment by megisys** [comment]
I fixed it for you.. It is now under review awaiting children to be issued. Status Check was missing
