### ISSUE TITLE
Zoning Certification Extension

### ISSUE THREAD

**Issue by ABonomo21** [dhenry-KCI/FredCo-Post-Go-Live-#198]
Zoning Certificate #187023
I have inserted the "extreq" log under but the extension request did not generate under application details. 

Ashlye reviewed.

**Comment by megisys** [comment]
Was not applied to this AP TYpe. Please log out and back in and try again..

DAn

**Comment by ABonomo21** [comment]
Extension Request is now under application Details however when I select it I cannot do anything with it... blank screen.

![image](https://user-images.githubusercontent.com/47611580/72084752-12506100-32d2-11ea-9441-aee1f6d46fe8.png)

**Comment by megisys** [comment]
You didnt LOG OUT and Back in ?? LOL

**Comment by ABonomo21** [comment]
yes she did.

**Comment by ABonomo21** [comment]
dan emily said you were right... mark that one in the books :)
