### ISSUE TITLE
PLANNING - Remove or NA extra review PL257597

### ISSUE THREAD

**Issue by AReed327** [dhenry-KCI/FredCo-Post-Go-Live-#199]
I need this review to be resulted or removed so it doesn't cause issues with the progression of this plat. 
I tried to follow ticket #2208 from PRE-GOLIVE and did not see the same options populate under Employee InfoViewer. Do I need to add the override? How does it know which project to override? I need training on how to do this. 
![image](https://user-images.githubusercontent.com/58854333/72086702-5f820200-32d5-11ea-9560-7a1e8d60ff49.png)

![image](https://user-images.githubusercontent.com/58854333/72086551-17fb7600-32d5-11ea-92e6-d92310a9e21d.png)

https://github.com/kcigeospatial/Fred_Co_Land-Management/issues/2208

**Comment by megisys** [comment]
PRJ_ManageReview_BUF - Promote to Production

**Comment by megisys** [comment]
Can only be done by you. Not any user. Will need to wait until tomorrow will NA for you on this one

**Comment by ScottVanSooy** [comment]
Promoted 2020-01-09

**Comment by AReed327** [comment]
It is not working.
![image](https://user-images.githubusercontent.com/58854333/72164298-6bcc9480-3393-11ea-8636-04137f25877c.png)
![image](https://user-images.githubusercontent.com/58854333/72164315-75ee9300-3393-11ea-8e5b-77cb6ead9235.png)

**Comment by megisys** [comment]
PLease Log out of Production and try again please..

**Comment by AReed327** [comment]
It worked:)
