### ISSUE TITLE
R4C - PLANNING - need decimal place for Remaining Acres

### ISSUE THREAD

**Issue by AReed327** [dhenry-KCI/FredCo-Post-Go-Live-#2]
need decimal place for Remaining Acres
![image](https://user-images.githubusercontent.com/58854333/70808595-008ca400-1d8e-11ea-9f52-6eed193badb9.png)

**Comment by megisys** [comment]
Major Change. needs to be done in Outage

**Comment by megisys** [comment]
This has a number of flow on effects.. Will need to create a new field. Reports will need to be adjusted (If any). Data Migrated. Two like fields.. What is the impact here ?

**Comment by megisys** [comment]
Will Migrate and Convert Tonight
