### ISSUE TITLE
Zoning Use  on Minor Permits

### ISSUE THREAD

**Issue by ABonomo21** [dhenry-KCI/FredCo-Post-Go-Live-#20]
Minor permit should not require the zoning use to be completed because the zoning review is not generated on minor permits only building review 

![image](https://user-images.githubusercontent.com/47611580/70923762-68ddbe80-1ff6-11ea-82c3-5da1daeb1572.png)
![image](https://user-images.githubusercontent.com/47611580/70923772-6c714580-1ff6-11ea-9a1f-4341beaaa21a.png)
![image](https://user-images.githubusercontent.com/47611580/70923776-6f6c3600-1ff6-11ea-8551-ee5a73c244ba.png)

**Comment by ABonomo21** [comment]
![image](https://user-images.githubusercontent.com/47611580/71023710-4bc9ee00-20d1-11ea-88aa-a90bd363049b.png)

![image](https://user-images.githubusercontent.com/47611580/71023730-55535600-20d1-11ea-9294-0bae69b4bb06.png)

**Comment by ABonomo21** [comment]
still broken

**Comment by megisys** [comment]
PLease Migrate BP_CodeEdition_SCF

**Comment by ScottVanSooy** [comment]
Promoted to Production 12/17/2019 8:30 PM

**Comment by awhite806** [comment]
Re-opening - permit #258435 held up for zoning use even though it is not required. Had to override to get permit to issue.
![image](https://user-images.githubusercontent.com/58981029/71115543-2952d600-21a0-11ea-8e75-33e5b9340c63.png)
![image](https://user-images.githubusercontent.com/58981029/71115548-2d7ef380-21a0-11ea-953e-63a70a87eabf.png)
![image](https://user-images.githubusercontent.com/58981029/71115556-31127a80-21a0-11ea-9688-54d1dae67f4c.png)

**Comment by ABonomo21** [comment]
PLEASE MAKE SURE THIS IS COMPLETED- REVIEWED BY AB 12.19.19

**Comment by calequin** [comment]
migrate BP_CodeEdition_SCF
fixed mispelled code
