### ISSUE TITLE
PLANNING EH REVIEWER assigning to AVOLVE

### ISSUE THREAD

**Issue by AReed327** [dhenry-KCI/FredCo-Post-Go-Live-#200]
The EH reviewer should be assigning to the specific reviewer. This project is AEVANGELISTA. I previously thought it was because she hadn't signed into PDOX yet, but now - I know she has. I have been manually changing, but shouldn't have to.

![image](https://user-images.githubusercontent.com/58854333/72089173-8b9f8200-32d9-11ea-86dc-1f1fcdb437f8.png)

**Comment by megisys** [comment]
Changing Priority for now as it is no longer a pressing issue.. Looking at this.. Is this happening to other people. Need to check her set up in PDox. @dhenry-KCI  can you look into this one please

DAn

**Comment by dhenry-KCI** [comment]
missing ser metadata. please test again

**Comment by AReed327** [comment]
Corrected - See PL257683
AREED
