### ISSUE TITLE
Site Compliance  Inspection Error

### ISSUE THREAD

**Issue by ABonomo21** [dhenry-KCI/FredCo-Post-Go-Live-#201]
Permit #190964 - trying to add a Site Compliance Inspection receiving a server error

![image](https://user-images.githubusercontent.com/47611580/72095461-7ed55b00-32e6-11ea-957b-3ea0f26daa9c.png)

**Comment by megisys** [comment]
Can you replicate this again.. ??

**Comment by ABonomo21** [comment]
i just tried to add the site compliance inspection and it allowed me to add it. Closing ticket.
