### ISSUE TITLE
Spawned Capacity Permits

### ISSUE THREAD

**Issue by dhenry-KCI** [dhenry-KCI/FredCo-Post-Go-Live-#202]
The system is generating capacity permits for municipalities with town sewer and water which do not need a capacity permit. 

Please update the system so capacity permits do NOT generate for the following:

Brunswick, woodsboro, Emmitsburg and Thurmont.

**based on email from Ashlye B. **

**Comment by megisys** [comment]
The Township Code or the Name of the town. AS there is city limits etc.. Please be more specific.

**Comment by ABonomo21** [comment]
This can be determined by the township code. if it is within the township of :
Brunswick -01
Emmitsburg-03
Thurmont-10
Woodsboro-12

then a capacity permit does not need to be generated as it is served by town water and sewer.

**Comment by megisys** [comment]
Dan to update BP_CreateCapacityPermitasChild

**Comment by ABonomo21** [comment]
tested on permit 259388
