### ISSUE TITLE
Inserting Parent Permit Numbers-Receiving Error

### ISSUE THREAD

**Issue by mlibbey131** [dhenry-KCI/FredCo-Post-Go-Live-#203]
When I go to insert a Parent Permit number into related records and search it I receive and error code. If i just type in the permit number and save it I don't receive the error code. I logged out of the system, and all of my browsers twice and still receive the error code when searching the parent permit to insert in the related records. Example Permit 259218

![image](https://user-images.githubusercontent.com/58980189/72153459-091bce80-337c-11ea-8e77-1a8642197a36.png)

**Comment by megisys** [comment]
I can not replicate this issue. Can you force this to happen everytime ? Please let me know

Dan

**Comment by ABonomo21** [comment]
Dan we need to get you on a webex with Megan - This happens to her everytime.

**Comment by megisys** [comment]
Yes Lets do this first thing Monday morning. Today is a busyt day

**Comment by JuanitaMiles** [comment]
Megan indicated this issue is not currently happening as of Monday 1/13/20 11:12 am. Closing ticket.
