### ISSUE TITLE
DW- Bond Release Milestone

### ISSUE THREAD

**Issue by ABonomo21** [dhenry-KCI/FredCo-Post-Go-Live-#204]
Issued Driveway permits are at Bond Release Milestone without any inspections. 
DW-199189

![image](https://user-images.githubusercontent.com/47611580/72153534-4a13e300-337c-11ea-906e-002b6626c69a.png)

EP

**Comment by calequin** [comment]
this appears to be an in-life issue where it was moved to the incorrect milestone manually. Tested in test and it works with the correct status checks. Please monitor

**Comment by ABonomo21** [comment]
Will continue to monitor. Closing ticket... will re-open if I notice it happening again. 

Thanks Christian. EP1/10/2020
