### ISSUE TITLE
Certificate of Occupancy available before permit finalization 

### ISSUE THREAD

**Issue by awhite806** [dhenry-KCI/FredCo-Post-Go-Live-#205]
The Certificate of Occupancy is available in the documents before the final has been completed. 
![image](https://user-images.githubusercontent.com/58981029/72161083-7126e080-338d-11ea-975b-5f8edda3e6d2.png)

**Comment by TaraF** [comment]
This change has been made in Test.  This still needs an Infor resource to move it to production.

Details:  For on demand reports only, under Building Permits --> Application --> View Application --> Application Information -->  Building InfoViewer, the following 2 reports have Formula updates to accommodate request above:

-Certificate of Occupancy
-Certificate of Completion 

![image](https://user-images.githubusercontent.com/4104464/72745741-74388280-3b7e-11ea-9c05-87deadcb6a7f.png)

@megisys @JuanitaMiles

**Comment by JuanitaMiles** [comment]
Spoke with Tara. Will wait for county testing/confirmation of this. This item can be tested in TEST prior to promotion to PROD. Changing labels to Ready for Testing in Test.

**Comment by ABonomo21** [comment]
![image](https://user-images.githubusercontent.com/47611580/72989431-3f197380-3dbc-11ea-8aab-7c09b7f1f538.png)

retest failed - 205096

**Comment by megisys** [comment]
Ready for retest.. Tara created 2 new versions old version was available..

**Comment by ABonomo21** [comment]
![image](https://user-images.githubusercontent.com/47611580/72993162-ebf6ef00-3dc2-11ea-9d49-9c4902040d1f.png)

**Comment by JuanitaMiles** [comment]
@TaraF Certificate of Occupancy or Completion is not available for on demand printing once the application is finalized.

Emily Pearl reported this issue.

![image](https://user-images.githubusercontent.com/31770504/73655871-f6d04000-465c-11ea-96bd-7e52e78b0c0a.png)

![image](https://user-images.githubusercontent.com/31770504/73655899-02236b80-465d-11ea-92b3-764bed6bb27d.png)


![image](https://user-images.githubusercontent.com/31770504/73655963-21ba9400-465d-11ea-957f-a46d7a3da88c.png)

**Comment by emilypearl1** [comment]
This is a HUGE issue. At this point Certificate of Occupancy's and Completions cannot be issued- which will hold up settlements etc.

**Comment by megisys** [comment]
Log out and back in please. and retest. PRODUCTION !!

**Comment by megisys** [comment]
Emily.. Important Note here.. When you move an application with a jump.. You need to close it and reopen for the list of reports to refresh.. You cant jump and expect the reporting list to update based on the milestone.. This is known.. PLease reload the screen after a jump and wanting to see report links.

**Comment by emilypearl1** [comment]
I wasnt jumping it- I was approving the cert review.... i am now able to print them. 

Also- the initial ticket "The Certificate of Occupancy is available in the documents before the final has been completed." isnt resolved....permit #262005 issued the certificate of occupancy is available on demand.

**Comment by TaraF** [comment]
2/4/20 - just spoke with Emily - things are working as expected, except we will tweak the 3 COO/COC reports to only show on demand when they hit the "Pending Certificate" milestone.  I will update this thread when complete.

**Comment by TaraF** [comment]
@emilypearl1  - this is updated as we discussed (see note above).  Please test in TEST and verify all cases before we promote this change to prod.

**Comment by ABonomo21** [comment]
![image](https://user-images.githubusercontent.com/47611580/73977819-023f9780-48f9-11ea-9909-b4123f7a2d5f.png)

did not work

**Comment by TaraF** [comment]
@ABonomo21  this is correct.  Please discuss over with Emily.  202617 in TEST is a nonresbldg, with a construction type of Complete, and it is Issued.  That qualifies it to be one of the two cases Emily identified that should have a selection of either COC or COO, since it is a business process decision which cannot be determined by the system, which is what we are presenting.

@emilypearl1 tagging you for reference and clarification here.

**Comment by emilypearl1** [comment]
Tara- the COO/COC option is correct on this permit - however it is at wrong milestone. This permit is at the inspections milestone- the certificates should not be available until the Pending Certificate milestone.

**Comment by TaraF** [comment]
@emilypearl1 please re-test in test.

**Comment by emilypearl1** [comment]
In TEST: Checked on permit 263302-milestone Revision Assignment- able to print COO
![image](https://user-images.githubusercontent.com/58855801/74173209-b3974380-4bff-11ea-8e6a-4116bdbee06b.png)

permit 263290- worked 
![image](https://user-images.githubusercontent.com/58855801/74173437-1a1c6180-4c00-11ea-9e36-e4a8a9982f3c.png)


RESUSE permit 263153- able to print COC- milestone under review
![image](https://user-images.githubusercontent.com/58855801/74173317-ed684a00-4bff-11ea-8924-e041070845e3.png)

Permit 263282 worked
![image](https://user-images.githubusercontent.com/58855801/74173404-0bce4580-4c00-11ea-8b52-5bf55c3d76f1.png)

Why is working for some and not others??

**Comment by TaraF** [comment]
Update:   I am working with Infor on business object information since there isn't documentation available on it.  Once I have a resolution,  I will update the thread.

Related to the differences between objects for NonResidentialDetails and NonResIntake business objects, since the code needs to account for both.

![image](https://user-images.githubusercontent.com/4104464/74555031-d5a70380-4f28-11ea-8d8c-eade9be0d210.png)

**Comment by TaraF** [comment]
@emilypearl1, @ABonomo21  - ready for re-test in Test.  I have checked every scenario I am aware of, including the ones you noticed above, and all should be corrected.  There are many cases, so please let me know if you see something not showing correctly.

**Comment by ABonomo21** [comment]
Nonres 202617 -appears to be the only one that still failed 
![image](https://user-images.githubusercontent.com/47611580/74834997-8545f200-52ea-11ea-9aa5-ac53d0983d23.png)

**Comment by TaraF** [comment]
@ABonomo21  @JuanitaMiles 

After not seeing the issue, and working with Juanita on this, I believe what is happening is the script is correct, and the reports are showing if you get back into the samples in Test (202617, 263385) - but if you are actively moving through to the milestones, the application has to be refreshed to pick up the formula / script (or at the very least getting out of the AP and then back into it may work).

In Ashley's screen capture above, and in mine below, we do see the two reports that should show for a NONRESBLDG with a type of 'Complete'. 

![image](https://user-images.githubusercontent.com/4104464/75174371-77370d80-56fe-11ea-91cf-6f654768554f.png)

Please give details if you expect to see something different - thanks!
