### ISSUE TITLE
PLANNING-planning conditions-how to expire

### ISSUE THREAD

**Issue by MLWilkins** [dhenry-KCI/FredCo-Post-Go-Live-#206]
in TEST I added several planning conditions on a project.  Was trying to expire those conditions.  Filled in "expire date" but its still showing up as a unresolved condition.  Under status if I delete the "agree" and drop the box to choose something else (like "met" ) there are no options to choose from other than "agree".

![image](https://user-images.githubusercontent.com/50637067/72164463-b9e19800-3393-11ea-8ec7-a01507b90802.png)
![image](https://user-images.githubusercontent.com/50637067/72164620-062cd800-3394-11ea-87c8-d391a9cf9dc3.png)
![image](https://user-images.githubusercontent.com/50637067/72164673-22c91000-3394-11ea-83e1-53a50ea07193.png)

Is this a bug or a training issue?  If training please provide it.
we have project that wen to Planning commission this week that we need to enter conditions in asap.

**Comment by megisys** [comment]
Training Issue. Lets meet on Monday on this one..

Dan

**Comment by MLWilkins** [comment]
user error.  I figured it out.
