### ISSUE TITLE
Error in Project Dox when opening attachment

### ISSUE THREAD

**Issue by awhite806** [dhenry-KCI/FredCo-Post-Go-Live-#207]
Mark Bird is receiving this error when trying to open an attachment in PDox
![SnipImage](https://user-images.githubusercontent.com/58981029/72173999-bacff500-33a6-11ea-892a-be413495d3ba.JPG)

**Comment by JuanitaMiles** [comment]
@awhite806 does this error occur when he is using internet explorer as well? I know IE was the preferred browser especially for viewing and marking up documents.

**Comment by JuanitaMiles** [comment]
Emailed, Mark, Abbie and Ashlye to understand if this is happening in IE as well.

**Comment by JuanitaMiles** [comment]
confirmed with mark he is not seeing any additional issues. closing
