### ISSUE TITLE
PLANNING - CIP didn't waive fees

### ISSUE THREAD

**Issue by AReed327** [dhenry-KCI/FredCo-Post-Go-Live-#208]
CIP is supposed to automatically waive fees. This did not work for APFO EXEMPTION worktype
A257678
![image](https://user-images.githubusercontent.com/58854333/72179944-089f2a00-33b4-11ea-8dab-f7e7db491e23.png)
![image](https://user-images.githubusercontent.com/58854333/72179958-1654af80-33b4-11ea-94df-c8efe4efd4a1.png)

**Comment by megisys** [comment]
This is a gap since we created the EXECMPTION WorkType. Need to update waive condition formula to check the APFO Exemption detail page..

**Comment by megisys** [comment]
PLN_APFO_WaiveFees_AOC - Please Promote

**Comment by ScottVanSooy** [comment]
Promoted 2020-01-13

**Comment by AReed327** [comment]
A257721 Verified corrected in test
