### ISSUE TITLE
Health - Environmental Health Reviews

### ISSUE THREAD

**Issue by dhenry-KCI** [dhenry-KCI/FredCo-Post-Go-Live-#21]
The health department is requesting all Environmental Health reviews to be assigned to Karen Amoss. Karen will then assign reviews based on availability.  Discussed this change with Christian.

**Comment by megisys** [comment]
@calequin

**Comment by calequin** [comment]
Added to USE and Building Permits. @dan will add formula in production.
@dhenry-KCI  do we need to auto populate reviewers for case and business license?

**Comment by ABonomo21** [comment]
here is another example just want to make sure this is fixed 
![image](https://user-images.githubusercontent.com/47611580/70935723-d990d500-200e-11ea-940e-a2c92b11ab6e.png)

**Comment by mlibbey131** [comment]
Health Review Fee generated on permit# 258467, but Health Review did not generate

![image](https://user-images.githubusercontent.com/58980189/71181781-d41bd080-2242-11ea-9051-15617da80669.png)
![image](https://user-images.githubusercontent.com/58980189/71181811-e6960a00-2242-11ea-8224-c89cb256fc69.png)

**Comment by calequin** [comment]
migrate - RESBLDG_EH_Review_AOC

**Comment by megisys** [comment]
This hasnt appeared again in 7 days. Closing until seen again

**Comment by awhite806** [comment]
REOPENING-This property is on well/septic and the health fee was paid but the review did not generate. Then once I added the review in, it automatically generated a one week due date that I can not remove. We do not assign due dates to Health Dept.
![image](https://user-images.githubusercontent.com/58981029/71822869-fb0c3c00-3063-11ea-88c6-2bdbf13f5f48.png)
![image](https://user-images.githubusercontent.com/58981029/71822926-1f681880-3064-11ea-8dd0-6cda61c45e1f.png)

**Comment by megisys** [comment]
Due Dates is a new issue and this is a net new requirement. Due dates were always set.

**Comment by megisys** [comment]
Is this a High Priority .. ?? @ABonomo21  Original Issue resolved and what happens if all other reviews are set to 1 week ?

**Comment by ABonomo21** [comment]
they will have to have a due date for now based on priority code

**Comment by awhite806** [comment]
RE-OPENING- PERMIT 264856- Health review generated but did not automatically assign to Karen Amoss like it should
 
![1](https://user-images.githubusercontent.com/58981029/74459856-fce2cf80-4e59-11ea-910f-38e63261211d.jpg)

**Comment by calequin** [comment]
associated BP_APTypeAssignmentGroup with EH review in test and prod. Once tested please close

**Comment by ABonomo21** [comment]
permit #260914 auto assigned to karen- closing tickets will monitor.

**Comment by awhite806** [comment]
REOPENING-Permit 268149. Health review generated but did not auto assign to Karen Amoss.
![image](https://user-images.githubusercontent.com/58981029/76318175-b09d7a80-62b3-11ea-8b96-d53519414953.png)

**Comment by megisys** [comment]
No Code Change.. Updated in Production
