### ISSUE TITLE
Issue with Employee/User Record - THAFLER

### ISSUE THREAD

**Issue by JuanitaMiles** [dhenry-KCI/FredCo-Post-Go-Live-#210]
Tina Hafler exists in the system with an Employee Record, however, her User record (THAFLER) does not have the appropriate First, Last Name, and Email information and when I tried to add her employee ID to her User ID it does not find the employee id. From looking at the screenshot below, her employee record may be expired but it should not be.

Can we please un-expire her employee record, appropriately link it to the user record, and ensure First, Last Name, and Email address are input.

Tina Hafler
THafler@FrederickCountyMD.gov

![image](https://user-images.githubusercontent.com/31770504/72182021-9846d780-33b8-11ea-8853-0a22628045a9.png)
![image](https://user-images.githubusercontent.com/31770504/72182429-73069900-33b9-11ea-8b3a-6aa3ce87d729.png)

**Comment by megisys** [comment]
@JuanitaMiles - It shows as expired.. I unexpired and associated

**Comment by JuanitaMiles** [comment]
fixed
![image](https://user-images.githubusercontent.com/31770504/72261367-a8da9600-35e2-11ea-9627-a491dd01fef0.png)
