### ISSUE TITLE
DW Inspections not generating from Failed result

### ISSUE THREAD

**Issue by ABonomo21** [dhenry-KCI/FredCo-Post-Go-Live-#211]
DW permit 202908 DW Final inspection failed- did not generate DW Final Inspection #2 
![image](https://user-images.githubusercontent.com/47611580/72182817-47d07980-33ba-11ea-8ef0-db2c2cff52dd.png)

Also- this is showing at Bond Release Milestone- instead of final inspection milestone.

**Comment by megisys** [comment]
This has been addressed. the first inspection was not marked as relevant review.

**Comment by ABonomo21** [comment]
fixed 

1/16/2020 EP
