### ISSUE TITLE
DW Final Inspection (#2)

### ISSUE THREAD

**Issue by ABonomo21** [dhenry-KCI/FredCo-Post-Go-Live-#212]
DW 202908- didnt generate a second DW Final inspection after the 1st inspection failed. We manually added a second DWFINAL however it says that it is DWFINAL #1 (inspection 1061450) 

![image](https://user-images.githubusercontent.com/47611580/72183183-418ecd00-33bb-11ea-834a-8d85bc775d82.png)

**Comment by megisys** [comment]
LInked to other issue.. Closing as a duplicate issue..
