### ISSUE TITLE
PDOX - DUE Dates should not include weekend days

### ISSUE THREAD

**Issue by AReed327** [dhenry-KCI/FredCo-Post-Go-Live-#213]
Submitted on Friday 1/10/2020 at 4:28 and showing late on Monday morning. The due dates should not include weekends.
![image](https://user-images.githubusercontent.com/58854333/72257232-1b467880-35d9-11ea-8b1f-759ba7cb88eb.png)

**Comment by megisys** [comment]
Pdox Issue - Not IPS

**Comment by JuanitaMiles** [comment]
Emailed Robert - 1/13/20 10:09 am

**Comment by JuanitaMiles** [comment]
Robert will be making the change from calendar days to business days for Planning only.

![image](https://user-images.githubusercontent.com/31770504/72293231-12799500-3621-11ea-8f81-67b981d5e531.png)

![image](https://user-images.githubusercontent.com/31770504/72293271-291fec00-3621-11ea-9f9b-80b9523faace.png)

**Comment by AReed327** [comment]
Robert emailed me that this has been corrected. Closing ticked. AReed
