### ISSUE TITLE
IPS- log in name

### ISSUE THREAD

**Issue by ABonomo21** [dhenry-KCI/FredCo-Post-Go-Live-#214]
When Justin is logged in to IPS- different employees are showing in parenthisis next to his name.  This morning it was my name, now it is Shannon Walters

![SnipImage](https://user-images.githubusercontent.com/47611580/72263450-e0e3d800-35e6-11ea-8b4b-fa95aa928e3a.JPG)

Ashlye reviewed

**Comment by megisys** [comment]
I am not seeing this.. Strange..

![image](https://user-images.githubusercontent.com/47392306/72265890-43d76e00-35eb-11ea-94b3-42b099189b49.png)

**Comment by megisys** [comment]
PLease Log out and back in please

**Comment by ABonomo21** [comment]
RESOLVED. THANKS!

**Comment by ABonomo21** [comment]
Re-opening... it just happened again.

**Comment by ABonomo21** [comment]
This is now happening to Shannon Walters- she is Megan Libbey!!

**Comment by megisys** [comment]
Turned off the potential issue. will need to see how tomorrow goes to ensure this is the cause
