### ISSUE TITLE
Inspector Contact Information

### ISSUE THREAD

**Issue by ABonomo21** [dhenry-KCI/FredCo-Post-Go-Live-#215]
We originally discussed the ability for applicants to see who the inspector was assigned to their inspection for the day, this would include a picture of the inspector which we provided months ago.

Applicants have not been able to see who the inspector is on R4C so where can this information can be found, with the inspector photo...

**Comment by megisys** [comment]
Assigning to Christian.. We need to test this on the your next piece.

**Comment by calequin** [comment]
This functionality is not available on R4C. This is done via inspection scheduled notification. added the inspector name and phone number. Need to work out the picture on the email.
![image](https://user-images.githubusercontent.com/47603568/72466599-d5d3a800-379e-11ea-8a8c-4a3115c85bff.png)

**Comment by calequin** [comment]
added enhancement label for the picture portion. New ticket should be created to track after
