### ISSUE TITLE
Inspection Cancellation 

### ISSUE THREAD

**Issue by ABonomo21** [dhenry-KCI/FredCo-Post-Go-Live-#216]
when an applicant submits a cancellation request online - i was under the impression the inspector would be notified.. this functionality is not working.

**Comment by calequin** [comment]
the inspectors need to have their phone numbers listed in the employee record. Working with Bob on this to show him.

**Comment by calequin** [comment]
update formula
BP_InspectionChangeofDates_BU
BL_InspectionChangeofDates_BU
USE_InspectionChangeofDates_BU

**Comment by megisys** [comment]
Work this today. AAF on The Log Entry to send a notificaiton. SendNotify.BuildingApplication()

**Comment by calequin** [comment]
Please test by clearing having a record with a scheduled date and request date of todays date. Clear out request date and save.
Employee record for test must have your mobile number.

Once county approves we need to do the following:
PROMOTE - BP_InspectionChangeofDates_BU
Add Notification in Code Definition Management > Resources > NotificationType > BP_CANCEL
Add Notification in Configuration Editor in Application and Rest Services

**Comment by ABonomo21** [comment]
tested on inspection # 1060119 for permit 205096- waiting for confirmation from BOB

**Comment by JuanitaMiles** [comment]
@calequin Can you confirm whether or not we can test this in the Back Office by following the steps above or does this need to be tested through r4c?

**Comment by calequin** [comment]
@JuanitaMiles this can be done in backoffice. Making sure the inspector employee profile has the destination mobile number of the person testing

**Comment by ABonomo21** [comment]
confirmed with Bob that the test worked.
