### ISSUE TITLE
Building Permits - Capacity - Need to be able to waive all outstanding fees

### ISSUE THREAD

**Issue by JuanitaMiles** [dhenry-KCI/FredCo-Post-Go-Live-#218]
Capacity Permit 150112

This is an application that was finaled and reopened and generated a fee in error. Ashley tried to waived the full outstanding balance of $626.94 but it only allows you to waive the last fee on the list with an amount of $295.90. It appears the Partially Paid fee is causing the issue.

![image](https://user-images.githubusercontent.com/31770504/72271598-29a28d80-35f5-11ea-9de5-38fd63c65f92.png)

![image](https://user-images.githubusercontent.com/31770504/72271622-36bf7c80-35f5-11ea-8fd3-65c262641592.png)

**Comment by megisys** [comment]
THis is right.. You can not waive partially paid fees. I cant offer any system help here. It will need to be overridden until it is closed

**Comment by JuanitaMiles** [comment]
Please see Ashlye's response in the email screenshot. If permit/application is closed, and it should be closed, there should be a way to clear any outstanding fees.

![image](https://user-images.githubusercontent.com/31770504/72553890-a341b200-3867-11ea-86cc-07d8f7c52364.png)

**Comment by megisys** [comment]
They are outstanding. They were never paid . they were partially waived. They cant be cleared. If they are outstanding as a portion was partially waived and it is closed. What does it matter ?

**Comment by megisys** [comment]
Can I ask why they partially waived a fee if they never intended the person to pay the balance ?

**Comment by JuanitaMiles** [comment]
Need to confirm with Ashlye what she would like to do with this ticket. I don't think fees will be handled this way moving forward...
