### ISSUE TITLE
Building Permits - Fire Permit - Not Going to PDox (Batch Manager Error)

### ISSUE THREAD

**Issue by JuanitaMiles** [dhenry-KCI/FredCo-Post-Go-Live-#219]
Fire Permit - 258465

This permit has an error in the Project Dox Messages and will not go through PDox. From looking at the application it does not have the "PLANSUBMITTER" applicant added to the application like the other applications do. If the batch manager looks for this, then this could be tripping it up.

![image](https://user-images.githubusercontent.com/31770504/72273636-ae42db00-35f8-11ea-9490-54bd288558a6.png)

![image](https://user-images.githubusercontent.com/31770504/72273738-e0ecd380-35f8-11ea-9c5b-5b2cde086f8c.png)

**Comment by ScottVanSooy** [comment]
I'm going to reassign this to Dan as it deals with an external assembly I don't have access to.

**Comment by megisys** [comment]
This is fixed. Looks like someone removed this..

**Comment by JuanitaMiles** [comment]
fixed

![image](https://user-images.githubusercontent.com/31770504/72352430-3cc66380-36b0-11ea-9df8-7c43941e6879.png)
