### ISSUE TITLE
Building Permits - Capacity Permit - Hamptons West Subdivision Fees

### ISSUE THREAD

**Issue by JuanitaMiles** [dhenry-KCI/FredCo-Post-Go-Live-#22]
CAPACITY - RESIDENTIAL SINGLE FAMILY DWELLING
AP # 257976

The Hamptons West subdivision code 068295 needs to automatically add the RESIDENTIAL WATER FEE 11900 ($5380.00) and RESIDENTIAL SEWER FEE 20600 ($7509.00) when it is a residential occupancy type. 

Terry manually added these fees to the application in PROD.

![image](https://user-images.githubusercontent.com/31770504/70924779-21583200-1ff8-11ea-803a-3a4c9bc2deb9.png)

![image](https://user-images.githubusercontent.com/31770504/70924877-49479580-1ff8-11ea-9a61-c27e6c9f43a7.png)

**Comment by megisys** [comment]
CAPACITY_ResWater11900_Fee_AOC - Promote to Production
CAPACITY_ResSewer20600_Fee_AOC - promote to Production
