### ISSUE TITLE
PLANNING-PDOX-PLANS SLOW TO OPEN AND ie CRASHES

### ISSUE THREAD

**Issue by MLWilkins** [dhenry-KCI/FredCo-Post-Go-Live-#220]
The hamptons west final plats that came in have had some issues loading in ProjectDox .  Some open relatively quickly, while others take considerable time opening.  The main offender was “PL257653”…..it took several minutes to load and every single changemark Cody went to do took minutes for the screen to pop up that allows me to enter the comment.  A couple of the other ones loaded fine, but two other semi-slow ones are “PL257679” and “PL257663.”  These two have been slow and lagging with everything, however nothing like the first one listed.  If he waited to let it load (approximately 3-5 minutes) and then attempted to maximize the screen it would completely lock up.  

Cody opened PL 257653 and timed my steps.  From when he clicked on the plat to when it finally opened took 2 minutes 54 seconds.  To maximize the screen so he could see it took 1 minute and 28 seconds, then when he clicked “annotate” to do changemarks it locked up and  internet explorer crashed and he had to exit out of everything.  

This occurred on 1/9/20 and again on 1/13/20.

**Comment by MLWilkins** [comment]
Update: DLu in DUSWM is having trouble with these same APs.  I opened one and also experienced significant delays.

**Comment by JuanitaMiles** [comment]
Awaiting latest PDox upgrade to see if it helps to resolve this issue.

**Comment by JuanitaMiles** [comment]
@MLWilkins @AReed327 Keep an eye on these now that the PDox upgrade has been completed. If theses plans are now approved and past the point of being able to go back and open. Monitor speeds of new projects moving forward and close this ticket if you are not having additional problems.

**Comment by MLWilkins** [comment]
Closing ticket. Will reopen if improvement is not seen.
