### ISSUE TITLE
PLANNING - NID Review Result

### ISSUE THREAD

**Issue by AReed327** [dhenry-KCI/FredCo-Post-Go-Live-#221]
This should be > **50** new Trips 
It is showing 59. That is incorrect
![image](https://user-images.githubusercontent.com/58854333/72281354-5dd37980-3608-11ea-80c8-2d9cd6a4144f.png)

**Comment by megisys** [comment]
Was this really High Priority ?

**Comment by AReed327** [comment]
Verified Corrected.
![image](https://user-images.githubusercontent.com/58854333/72345294-56ac7a00-36a1-11ea-8a94-65d0d1a726cd.png)
