### ISSUE TITLE
Revision Reviews #2

### ISSUE THREAD

**Issue by ABonomo21** [dhenry-KCI/FredCo-Post-Go-Live-#222]
THe second reviews are not generating as #2.

Revision was done on 201970- inserted a plnrev & DOLS- both of these second reviews came in as #1 even though they are the #2 (second review) 

![image](https://user-images.githubusercontent.com/47611580/72281992-bd7e5480-3609-11ea-8a70-a381c75d4cb0.png)

Ashlye reviewed.

**Comment by megisys** [comment]
It is because the first review was denied. And it thinks the review is now not going ahead. This wont happen on new permits and i adjusted for other DENIED reviews which might be added back.
