### ISSUE TITLE
DW- Official Issuance and Placard

### ISSUE THREAD

**Issue by ABonomo21** [dhenry-KCI/FredCo-Post-Go-Live-#223]
DW permit 258956 - see attachments were all of these sent out??

![image](https://user-images.githubusercontent.com/47611580/72284474-0a185e80-360f-11ea-86fd-b2125ae8fac9.png)

Review by Ashlye

**Comment by ScottVanSooy** [comment]
This was caused by Scott VanSooy making multiple attempts to get these to send.  The client only recceived 1 set of emails, even though there are multiple attachments here.  We're taking steps to stop this from happening.

**Comment by megisys** [comment]
One time only issue. - apologies from me..

**Comment by ABonomo21** [comment]
I do not think this issue is closed, I just found the same issue occurring on 258514, which is a reuse permit. It appears all of the correspondence duplicate? 
![image](https://user-images.githubusercontent.com/47611580/72626251-5e298880-3918-11ea-8531-bc1a33aad805.png)

**Comment by ScottVanSooy** [comment]
@ABonomo21 

Ashlye, unfortunately, there were a bunch of permits around the 18th and 19th that we had to try to send several times before we got them to go.  Every attempt re-attaches new docs to the permit, but the customer only gets the one that was finally successful. These situations should be drastically reduced now, and I am monitoring correspondence carefully.

**Comment by emilypearl1** [comment]
Just happened again 1/22/20. I extended permit 185698. Multiple attachments.

![image](https://user-images.githubusercontent.com/58855801/72916707-7df1ef80-3d10-11ea-9a0c-ee3c858adf02.png)


1/22/20

**Comment by megisys** [comment]
Extentions is being addressed..

**Comment by megisys** [comment]
https://github.com/dhenry-KCI/FredCo-Post-Go-Live-/issues/192

Duplicate Issue. This is Extension and the issuing of New Placard and Issance after an extension grant
