### ISSUE TITLE
Capacity Permit Did Not Generate

### ISSUE THREAD

**Issue by mlibbey131** [dhenry-KCI/FredCo-Post-Go-Live-#224]
Capacity permit did not generate on Permit# 258970

![image](https://user-images.githubusercontent.com/58980189/72290286-d93e2680-361a-11ea-8ad9-c855bdcd30e3.png)

**Comment by megisys** [comment]
This has been addressed

**Comment by JuanitaMiles** [comment]
Reopening Ticket - There is another example of a ResBldg permit on public water and sewer that did not generate a capacity permit when it should have. AP#268621

![image](https://user-images.githubusercontent.com/31770504/77440001-22022080-6dbe-11ea-9718-c110d5398602.png)
