### ISSUE TITLE
PLANNING - Awaiting Applicant Payment - No fees due - Project will not progress

### ISSUE THREAD

**Issue by AReed327** [dhenry-KCI/FredCo-Post-Go-Live-#225]
SP257615 We have an active project we are trying to progress. The application is stuck in Awaiting Applicant Payment. There are no fees due. Why is it stuck? There are waived fees on this project. 
![image](https://user-images.githubusercontent.com/58854333/72347806-f15b8780-36a6-11ea-9ca9-97be9ef6d2ed.png)
![image](https://user-images.githubusercontent.com/58854333/72347836-03d5c100-36a7-11ea-95f5-19452ea381c8.png)

**Comment by megisys** [comment]
This has been addressed

**Comment by AReed327** [comment]
Verified milestone progressed. Closing
