### ISSUE TITLE
PDOX - Binder does not work

### ISSUE THREAD

**Issue by AReed327** [dhenry-KCI/FredCo-Post-Go-Live-#226]
I attempted to use the binder feature on PDOX and it does not work. I was able to open each page uploaded individually. I am using Internet Explorer. When I logged in under Google Chrome it worked.  Internet Explorer is the preferred browser for PDOX so the Binder should work.

![image](https://user-images.githubusercontent.com/58854333/72349681-fde1df00-36aa-11ea-909f-598f289fbb5b.png)

**Comment by JuanitaMiles** [comment]
Emailed Robert, 1/14/20 12:32

**Comment by JuanitaMiles** [comment]
Awaiting the latest PDox upgrade to determine if these issues are still occuring.

**Comment by AReed327** [comment]
email from robert 1/24 - corrected. Will view if an issue after PDOX upgrade 2.7.2020
