### ISSUE TITLE
Trying to remove a license from a contact 

### ISSUE THREAD

**Issue by ABonomo21** [dhenry-KCI/FredCo-Post-Go-Live-#228]
I am not able to delete the highlighted license that was added to this contact incorrectly. 
![image](https://user-images.githubusercontent.com/47611580/72356289-05a78080-36b7-11ea-829b-8f4fcc586a15.png)

![image](https://user-images.githubusercontent.com/47611580/72356276-ffb19f80-36b6-11ea-9d6c-c75c2b2350ad.png)

**Comment by megisys** [comment]
You cant delete it .. You can inactive it, or expire it.
