### ISSUE TITLE
Planning - IPS Generating Notifications for Eplans Application

### ISSUE THREAD

**Issue by AReed327** [dhenry-KCI/FredCo-Post-Go-Live-#229]
PW257661 - It appears Health was able to result their review in IPS for an EPlan application.  They system is not suppose to allow reviewers to do this.  Please fix this for health and any other agency reviewers (except Ashley Reed who needs this ability). 

This resulted in a notification being sent from IPS asking the applicant to resubmit but they cant because Health did not result their review in PDox.  IPS is not supposed to send notification like this for eplans!

![image](https://user-images.githubusercontent.com/58854333/72360050-65088f00-36bd-11ea-87ca-391479c88c76.png)

![image](https://user-images.githubusercontent.com/58854333/72360096-75b90500-36bd-11ea-8fce-a7724434632a.png)

Also, the notification that was sent out shows it was sent by VKapoor, but he wasnt the last person to result their review.

**Comment by megisys** [comment]
Are we sure this happened within IPS.. The last modifed user was ProjectD

**Comment by AReed327** [comment]
Appears review was resulted by Health in PDOX. 
![image](https://user-images.githubusercontent.com/58854333/72372145-cfc4c500-36d3-11ea-8ea4-978a1ba50f50.png)
It's possible that Kim pulled the task back after resulting the review. This would account for the task still showing in PDOX if she didn't complete it after pulling it back. 

What is not accounted for is why IPS sent the email out for "Frederick County Needs More Information" on an EPlan
![image](https://user-images.githubusercontent.com/58854333/72372698-cc7e0900-36d4-11ea-85cd-92389abd91f6.png)

**Comment by MLWilkins** [comment]
@megisys not sure the title change is accurate.  IPS should not have generated that email at all.

Mike

**Comment by megisys** [comment]
PLease deploy PLN_MoreInfoNotification

Thanks

**Comment by MLWilkins** [comment]
checked a couple of site plans.  IPS is sending resubmit notifications on Eplan reviews.  These were type 3 site plans so Health review was not involved.

IPS cannot send notifications to resubmit or notifications that a project is approved when it is an eplan review. It send applicants to the portal but they need to be directed by PDox to go to Pdox.

![image](https://user-images.githubusercontent.com/50637067/72559831-afcc0780-3873-11ea-8bc7-0bfad902ccb3.png)

**Comment by MLWilkins** [comment]
to be clear, these notifications should not go out for any Eplan for all application types, not just site.

**Comment by calequin** [comment]
@MLWilkins the formula was deployed on the night of 1/15. going forward the notification should not be sent. Can you monitor and see if any new ones sent out with a date after 1/15?

**Comment by MLWilkins** [comment]
confirmed working.  SP257595 and PL257655
