### ISSUE TITLE
Extention Details causeing Error

### ISSUE THREAD

**Issue by megisys** [dhenry-KCI/FredCo-Post-Go-Live-#23]
BP_ExtensionReview_BUF - Migrate.

See Extensions Permit #187140

Dan

**Comment by ABonomo21** [comment]
this needs to be a high priority i am not able to process any extension requests- i get an error on the extension details page.

**Comment by ABonomo21** [comment]
@megisys

**Comment by ABonomo21** [comment]
![image](https://user-images.githubusercontent.com/47611580/70935877-31c7d700-200f-11ea-98b5-10cd62c1de21.png)
