### ISSUE TITLE
Related record error

### ISSUE THREAD

**Issue by ABonomo21** [dhenry-KCI/FredCo-Post-Go-Live-#231]
look at BPMH257284 and the related records there are over 200 plus cases attached?

**Comment by megisys** [comment]
It listed all the non address cases.. I will address this out of hours.

**Comment by megisys** [comment]
Update to BLDG_ListOpenCases_AAF. Ensure address key is valid

**Comment by calequin** [comment]
please promote BLDG_ListOpenCases_AAF

**Comment by megisys** [comment]
I removed all the wrongly associated cases

**Comment by ABonomo21** [comment]
![image](https://user-images.githubusercontent.com/47611580/72548330-7340e180-385c-11ea-802f-6fbca52aa0ed.png)

**Comment by awhite806** [comment]
Reopening- Blanket permit BPMH257285 is now having the same issue. there are 763 related records that have nothing to do with this permit 
![image](https://user-images.githubusercontent.com/58981029/73290618-c3a92f00-41cc-11ea-90f0-d2268d6c1c30.png)

**Comment by megisys** [comment]
Stop this for Blanket Review Types.. Not needed as no address used
