### ISSUE TITLE
Building Permits - Capacity Permit - Incorrect Fee Value Generated

### ISSUE THREAD

**Issue by JuanitaMiles** [dhenry-KCI/FredCo-Post-Go-Live-#232]
Capacity Permit - 259059

This permit generated the fees incorrectly. See Lauren's email below. It appears the fees calculated at full value rather than the weighted value as indicated by the "W" on the detail page.

![image](https://user-images.githubusercontent.com/31770504/72369109-6b066c00-36cd-11ea-84c1-a6f1c986a5e1.png)

![image](https://user-images.githubusercontent.com/31770504/72369161-87a2a400-36cd-11ea-8b89-0abb51aeb34e.png)

**Comment by ScottVanSooy** [comment]
CAPACITY_PrelimFixtureSewer73720_VF

**Comment by ScottVanSooy** [comment]
The formula PRELIM FIXTURE SEWER FEE 20600  is calculating the fee as 750.90 * 9 = 6,758.1
 It was adjusted to 1081.30
What is supposed to happen? 

	Else If oCapacityDetail.FixValue.Trim.ToUpper() = "W"
				If oCapacityDetail.TlFixP <= 10
					PrelimVal = oCapacityDetail.TlFixP* Val737

**Comment by ScottVanSooy** [comment]
Checking with Juanita

**Comment by JuanitaMiles** [comment]
Followed up with Lauren, awaiting response.

**Comment by JuanitaMiles** [comment]
Information regarding fee calculation was provided by Lauren via email. Scott to implement tonight.

**Comment by ScottVanSooy** [comment]
Promote 
CAPACITY_PrelimFixtureSewer73720_VF
CAPACITY_PrelimFixtureWater52820_VF
