### ISSUE TITLE
Trade License 

### ISSUE THREAD

**Issue by ABonomo21** [dhenry-KCI/FredCo-Post-Go-Live-#233]
State license is expired on PM01627 and it shows as an active license also the confirm license details page did not clear or change once the renewal review was completed?

**Comment by ScottVanSooy** [comment]
@megisys 
Dan, I tried here, but I think I could use some help determining what is supposed to happen.  Seems like a batch task isn't working properly, but I'm not sure.

**Comment by ABonomo21** [comment]
PI00515 tech did confirm license details and it changed the status to active without fees or reviews.

**Comment by ABonomo21** [comment]
PI00360 same thing.

**Comment by calequin** [comment]
we have moved over pre-renew licenses to the awaiting renewal details milestone. This will allows the fees to calculate and renewal details to be submitted and follow the correct workflow.

**Comment by megisys** [comment]
Was a migration miss. Manually moved these to appropriate place

**Comment by JuanitaMiles** [comment]
Several staff have identified reports that notifications have went out to applicants that their licenses are now open for renewal. I have instructed staff to disregard (and let customers know to disregard if they do not wish to renew) as this was a result of the manual move. These are OK because they have not reached the Grace Exp date yet. (example: PM00568)

**Comment by megisys** [comment]
Thanks. we had no choice. If I had my time again , i should have put a stop not on there.

**Comment by megisys** [comment]
Can we close this now ??

**Comment by JuanitaMiles** [comment]
Leaving this issue open as we determine the best route to handle applications that have generated new fees with upcoming grace expiration dates but they have already renewed.

**Comment by JuanitaMiles** [comment]
closing this ticket. Ticket #384 has been opened requesting an overall meeting request to discuss trade licenses, what does work...what doesn't work, etc.
