### ISSUE TITLE
Migrated permit with no inspections

### ISSUE THREAD

**Issue by ABonomo21** [dhenry-KCI/FredCo-Post-Go-Live-#234]
permit 204580 did not generate any inspections, they had to be manually added?? 

![image](https://user-images.githubusercontent.com/47611580/72430610-d5b4b780-3760-11ea-81bd-24b688c38434.png)

![image](https://user-images.githubusercontent.com/47611580/72430629-df3e1f80-3760-11ea-91b8-ad76b6f773ef.png)

we need to make sure inspections generate on a migrated permit to eliminate the risk of permits progressing over the inspections milestone...

**Comment by megisys** [comment]
Hi Ashlye, I really don't know what we can do here. This problem will go as we grandfather out out permits. This permit was added on the weekend of go live.. Have we had others ? I think the issue is fixed by doing what was done. Please advise

**Comment by ABonomo21** [comment]
after speaking with Bob we are okay with manually adding the inspections that did not autogenerate on the migrated data. We will make sure all new permits are adding inspections correctly.
