### ISSUE TITLE
Permit stuck

### ISSUE THREAD

**Issue by ABonomo21** [dhenry-KCI/FredCo-Post-Go-Live-#235]
this electrical permit is stuck in pending issuance for the parent permit to be issued, but the parent permit is issued.. 
![image](https://user-images.githubusercontent.com/47611580/72430773-304e1380-3761-11ea-9041-81d686f81d86.png)
![image](https://user-images.githubusercontent.com/47611580/72430786-36dc8b00-3761-11ea-9d00-6a32fb749b79.png)
![image](https://user-images.githubusercontent.com/47611580/72430807-4065f300-3761-11ea-816d-85c9f5ac9bd6.png)

**Comment by megisys** [comment]
Doesn't have an issued Date. It looks for issued date

**Comment by megisys** [comment]
Megan Jumped the application past when the system would set this. PLease advise

**Comment by ABonomo21** [comment]
how do i get an issued date on the building permit now, she had to supervisor override because the zoning review was waived on the building permit and therefore did not need the zoning use detail page to be completed which called for the supervisor override...

**Comment by megisys** [comment]
It wasn't supervisor override.. It was jumped to another milestone. I have added these in now
