### ISSUE TITLE
R4C - Look Up feature - when you page back, it takes you all the way out of the search

### ISSUE THREAD

**Issue by AReed327** [dhenry-KCI/FredCo-Post-Go-Live-#236]
I have had several complaints about the Lookup Record function in R4C. When you have done a search and are in a project, then you use the back arrow, it takes you completely out of your search and back to the beginning. Many engineers and surveyors are using this to look up their old projects that are not linked to their account. 
There are also citizens that keep track of development that have struggled with this. 
There should be a way to get back to the previous screen.
 
![image](https://user-images.githubusercontent.com/58854333/72436820-609cae80-376f-11ea-87c6-e723187a0430.png)

**Comment by megisys** [comment]
Hi Ashley,

There is nothing we can do right now from a services stand point. This has been passed on to our product team

Thanks

Dan

**Comment by megisys** [comment]
Removing my name, as I can not assist here. Product issue. mark Oliver is best for this

**Comment by JuanitaMiles** [comment]
adding to future pahses list, closing per ashlye
