### ISSUE TITLE
Planning-conditions-reviewers not able to add conditions

### ISSUE THREAD

**Issue by MLWilkins** [dhenry-KCI/FredCo-Post-Go-Live-#238]
None of the DPZ staff can add conditions.  when they use the drop box to select status there are no options and "insufficient privileges" pops up.  **This is holding a dozen projects up as we cannot result the hearing milestone without adding conditions.**   

![image](https://user-images.githubusercontent.com/50637067/72441470-c17cb480-3778-11ea-885f-6261cfb923e4.png)

![image](https://user-images.githubusercontent.com/50637067/72441492-cfcad080-3778-11ea-8dfe-a0aa121e44a1.png)

**Comment by JuanitaMiles** [comment]
@MLWilkins Ashley Moore and I made progress on this. She is now able to add the planning condition to the application when she manually types in a code but when she clicks on the popup to view the Status code options, we get a server error. We'll need Infor to look into this.

@ScottVanSooy Christian mentioned you were good at working through these server errors. Ashley Moore got this error by:
1) Opening a planning application (20014).
2) Click on the the Conditions tab.
3) Add a Planning Condition.
4) Create a Planning Condition.
5) Selecting the popup search icon on the Status field.

As Admins Christian and I do not get this error so we are still thinking there could be an issue with permissions...

<img width="622" alt="servererror" src="https://user-images.githubusercontent.com/31770504/72461078-344b5700-379c-11ea-969a-e52222ccbf49.png">

**Comment by JuanitaMiles** [comment]
@ScottVanSooy The permissions we are looking at are on the REVIEWER_REGULAR role. Reviewers should have the permission to create a planning condition. So there be something were missing in permissions that is causing it. I'm not sure..

**Comment by ScottVanSooy** [comment]
There are 2 issues here I believe.  I need to apply a HotFix to Dev first.  I need to  schedule a moment of downtime with everyone.

**Comment by JuanitaMiles** [comment]
@ScottVanSooy Please coordinate this down time with Dan and Christian afterhours if it will cause an interruption for everyone.

**Comment by ScottVanSooy** [comment]
HOT-395 Deployed to Prod and  Test.  Please reset.  The server should go away.

**Comment by AReed327** [comment]
Cody Shaw still can not add conditions. Other reviewers are able to add now.

**Comment by JuanitaMiles** [comment]
@AReed327 Please have Cody log in and back out. I've added him to the correct group.

**Comment by AReed327** [comment]
It worked. Closing Ticket. AREED
