### ISSUE TITLE
PDOX - browser Issue

### ISSUE THREAD

**Issue by AReed327** [dhenry-KCI/FredCo-Post-Go-Live-#239]
I received a browser issue report from an engineer. I also have the same browser issue. 

![image](https://user-images.githubusercontent.com/58854333/72442592-ca6e8580-377a-11ea-9872-76307da40493.png)
![image](https://user-images.githubusercontent.com/58854333/72442616-d3f7ed80-377a-11ea-877c-2812e6647f55.png)

**Comment by JuanitaMiles** [comment]
Followed up with Robert on 1/16

**Comment by JuanitaMiles** [comment]
@AReed327 Robert has made a change on this. Please check once you have logged out and back in. Mine shows fine now see below.

![image](https://user-images.githubusercontent.com/31770504/72554156-22cf8100-3868-11ea-9c43-dd01be7610c7.png)

**Comment by AReed327** [comment]
Fixed in Production and verified
