### ISSUE TITLE
Expired permit did not change status

### ISSUE THREAD

**Issue by ABonomo21** [dhenry-KCI/FredCo-Post-Go-Live-#240]
![image](https://user-images.githubusercontent.com/47611580/72446475-a7939f80-3781-11ea-8b4d-8dc37b284636.png)

this permit expired 1.8.20 it did not send the expired permit correspondence and it did not change the status

**Comment by ABonomo21** [comment]
![image](https://user-images.githubusercontent.com/47611580/72446738-140e9e80-3782-11ea-85ec-f4cd2583fbf7.png)

**Comment by ScottVanSooy** [comment]
@ABonomo21 , @calequin 
This is happening because Inspections aren't resulted and other checks are stopping the progress.  Is this getting expired thru a batch manager task?

**Comment by megisys** [comment]
There is a batch job. Which should waive open fees. NA Reviews and Inspections

Batch_BP_Expiration_BCT needs that added.. @ScottVanSooy 



	If Res.IsSuccess And Not res.IsNoDataFound Then

		For Each oInspection As Hansen.CDR.Building.IInspection In oLog.BuildingApplication.Inspections

			If oInspection.InspectionResult.Code.IsNullOrWhiteSpace() Then

				oInspection.InspectionResult.Code = "WAIVED"

				oInspection.Comments = "Expired Application"

				oInspection.Update()

			End If

		Next

		For Each oReview As Hansen.CDR.Building.IReview In oLog.BuildingApplication.Reviews

			If oReview.ReviewResult.Code.IsNullOrWhiteSpace() Then

			oReview.ReviewResult.Code = "NA"

				oReview.Comments = "Expired Application"

				oReview.Update()

			End If

		Next

		For Each oFee As Hansen.CDR.IFee In oLog.BuildingApplication.Application.Fees

			If oFee.TotalUnpaidAmount > 0 Then

				Res = oFee.WaiveFee()

			End If

		Next

	End If

End If

**Comment by megisys** [comment]
Code added

**Comment by ABonomo21** [comment]
i have another plumbing permit that did not change status and expired 1.15.20
![image](https://user-images.githubusercontent.com/47611580/72556713-2f0a0d00-386d-11ea-9162-d896161413a7.png)

**Comment by ScottVanSooy** [comment]
This will be fixed and put in Prod tongiht.

**Comment by ScottVanSooy** [comment]
Need to set Batch Manager Task Expire Building Permits  to  run nightly.  I'll set to run 11:45 every night.

**Comment by ABonomo21** [comment]
Thank you Scott we will monitor this,
