### ISSUE TITLE
Planning-Planning application complete notification -need to add more direction

### ISSUE THREAD

**Issue by MLWilkins** [dhenry-KCI/FredCo-Post-Go-Live-#241]
multiple applicants are complaining that they are having difficulty finding the results of their application when they receive the "application complete correspondence", which simply tells them to go to the portal.  Can we add language that explains to them where and how to filter for "closed" applications, which is where these projects will be when this notification is sent out?

![image](https://user-images.githubusercontent.com/50637067/72448452-10c8e200-3785-11ea-82c6-18676be9146d.png)

**Comment by MLWilkins** [comment]
the above came from a verification letter but the issue is for all internal review applications.

**Comment by megisys** [comment]
Please provide the language you would like to have

**Comment by MLWilkins** [comment]
after "Please log into our portal", please add:

You will find this closed application on your dashboard by clicking Filter under the My Projects heading, select  "Closed Projects" , and search.

**Comment by MLWilkins** [comment]
looks good.
