### ISSUE TITLE
R4C test site not allowing log in

### ISSUE THREAD

**Issue by MLWilkins** [dhenry-KCI/FredCo-Post-Go-Live-#242]
keep clicking log in button but nothing happens.  Need it to resolve another ticket.

![image](https://user-images.githubusercontent.com/50637067/72453667-78832b00-378d-11ea-895e-bb31b31a8eed.png)

**Comment by calequin** [comment]
fixed. please retry.

**Comment by MLWilkins** [comment]
working now
