### ISSUE TITLE
Inspector Photo on inspection notification

### ISSUE THREAD

**Issue by ABonomo21** [dhenry-KCI/FredCo-Post-Go-Live-#245]
Based on ticket #215 - opening a new ticket to ensure the photo of the inspector is added to our notifications. 

This is not a new request this was supposed to be working prior to go-live only label option was enhancement.

**Comment by calequin** [comment]
received photos from Bob. Adding to notifications today 1.21.2020

**Comment by JuanitaMiles** [comment]
Leaving both Dan and Christian assigned to this ticket so it can be worked on during notification redesign efforts.

**Comment by megisys** [comment]
Closing due to linkage to #405  - These are one piece - Will not be missed. Linked

**Comment by JuanitaMiles** [comment]
Reopening per conversation with Dan and Ashlye on 2/26. This ticket will replace the overall notification redesign task. We have decided that we will move forward with the inspector photo design, and not the full notification redesign.

**Comment by megisys** [comment]
Hi All,

I have completed 90% of the Inspector Email piece. This is in TEST only at this point and works by the following. (See Below)

An Inspection must be scheduled with a date and assigned to an inspector

The inspector needs to have a photo on the webserver names as employeeid.png to show the image. (we have 90% otherwise you get blank)

Then open an inspection in Test and add a log of INSPBook (Inspection Booking).

Then I will need to know when we are triggering this ? IS this going to be for the Bob button only ? 

This last piece is not complete until I get your feedback.

Dan

**Comment by ABonomo21** [comment]
@JuanitaMiles - can you check me on this one as well
266632 scheduled inspection for today, assigned to bob who should have a photo- then added the INSPBOOK log - did not get any notification.

**Comment by ABonomo21** [comment]
@megisys - yes dan if this works once juanita double checks my testing - this notification should send when the inspection is scheduled and the notifiaction is sent via the Bob Button- assuming that is the only way we are processing these scheduled requests. @TheBobEnsor Bob can you confirm you are always using the Bob button?

**Comment by TheBobEnsor** [comment]
Yes I am always using the button

**Comment by ABonomo21** [comment]
Assigning back to Dan to get him the answer from Bob

**Comment by ABonomo21** [comment]
@megisys - did not get a notification from test 266632

**Comment by ABonomo21** [comment]
need log in the inspection not in the permit @ABonomo21

**Comment by megisys** [comment]
I updated the bob button for test.. you can now fully test

**Comment by ABonomo21** [comment]
tested with dan worked - Dan will write up instructions for jeff to know how to add photos @JuanitaMiles @megisys 
![image](https://user-images.githubusercontent.com/47611580/78364560-a5c0c780-758b-11ea-9f39-a424c29752dc.png)

**Comment by ABonomo21** [comment]
see instructions from dan in email to jeff ash and juanita on 4.3.20
We have implemented Inspector photos to be added to the morning Inspector to arrive email process. These will need to be maintained over time.
 
The process is once the inspector is created in IPS as a user and given an employeeID.
 
A PNG Photofile matching that employeeID will need to be placed in the following location (This is Test.., But production is the final resting place). Wh-ipsprdweb.
 
Test will not be used after this is promoted as the formula will create a URL to the production location from both prod and TEST.
![image](https://user-images.githubusercontent.com/47611580/78367169-a52a3000-758f-11ea-829c-51d04eab6dcb.png)
