### ISSUE TITLE
Planning - Mylar Review - unable to change due date

### ISSUE THREAD

**Issue by AReed327** [dhenry-KCI/FredCo-Post-Go-Live-#247]
When I change the due date, it changes back to 1 week. 
Is there some type of configuration to allow me to change due dates?
![image](https://user-images.githubusercontent.com/58854333/72562033-7b0e7f00-3878-11ea-99a7-72748b6d1b88.png)
![image](https://user-images.githubusercontent.com/58854333/72562047-88c40480-3878-11ea-9949-90ff101d4a3b.png)

**Comment by ScottVanSooy** [comment]
@AReed327 
This setting can be changed:

![image](https://user-images.githubusercontent.com/58946969/72572424-78b81f00-3890-11ea-96bf-ec53f773cf62.png)

**Comment by AReed327** [comment]
I can adjust regular reviews manually. I don't want the time frame to change for electronic plan submissions. The projects that are from the old system are being routed as paper and it takes longer. In the old system it was 14 day review due to the plans traveling to another building. I was only trying to change that review for that purpose. If for some reason I am unable to, I do not want to change the auto assign due date for all mylar reveiws.

**Comment by ScottVanSooy** [comment]
@AReed327 

There isn't an easy way to do this, except to remove the DueDate assignment all together.  It's set in Code as an exception to all the other reviews.

**Comment by megisys** [comment]
Need to test in Test.. 

PLN_ASSIGNREVIEWDUEDATE_BUF Changed for Mylar

**Comment by MLWilkins** [comment]
IPS is now setting mylars review at 3 weeks. We did not want to change the 1 week auto populated due date.  We just want to manually adjust the date when needed, just as we can do for any other review type.  In the second screen shot below you can see that we are now able to change the due date.  Thank you!  Now we just need to to auto populate a 1 week review again.


![image](https://user-images.githubusercontent.com/50637067/72986062-5bfe7880-3db5-11ea-8a24-8ea652f4f809.png)

![image](https://user-images.githubusercontent.com/50637067/72986206-b5ff3e00-3db5-11ea-9a90-81477214cf01.png)

**Comment by megisys** [comment]
ready for Retest - please see the application 19946

**Comment by MLWilkins** [comment]
the mylar reviews you added on 1/23 are showing as due on 2/2, which is more than 7 days and also on a Sunday.  One week from 1/23 is 1/30.  It this a bug???
![image](https://user-images.githubusercontent.com/50637067/73071140-1195fe00-3e80-11ea-8885-c55ea7c838d3.png)


However, i tested 19830 and it correctly populated a 1 week review and I was able to change it.
![image](https://user-images.githubusercontent.com/50637067/73071969-0f34a380-3e82-11ea-9412-ac662a79616e.png)
