### ISSUE TITLE
Contact and Property Browser - Viewing/Closing Parcel Error

### ISSUE THREAD

**Issue by JuanitaMiles** [dhenry-KCI/FredCo-Post-Go-Live-#249]
Lauren Englar was viewing this parcel in Contact and Property Browser, when she clicked the back arrow to close, she received the error.

![parcelerror](https://user-images.githubusercontent.com/31770504/72619541-86f75100-390b-11ea-8100-0bf252ec5def.jpg)

**Comment by ScottVanSooy** [comment]
@JuanitaMiles 

I think is a one-off situation, maybe due to network connectivity, just a glitch.  I tested 10 times in every different way and it works for me.  Could you have Lauren test again?  I  want to be sure it's not an access control issue.  Thanks

**Comment by JuanitaMiles** [comment]
@ScottVanSooy I had her try again just now. She got the same error. The only difference is this "8706" number.

![image](https://user-images.githubusercontent.com/31770504/72634980-c3d24080-3929-11ea-9d8a-ee5c657b2c84.png)

**Comment by ScottVanSooy** [comment]
Thanks, I'll get to the bottom of it.

**Comment by ScottVanSooy** [comment]
OK,  I'm stumped, can she Webex with me?  I tried using her user in test in both IE and Chrome and it works perfectly for me.

**Comment by ScottVanSooy** [comment]
Ah, never mind, I think I just duplicated it.

**Comment by ScottVanSooy** [comment]
@JuanitaMiles 

Until I get to the bottom of this, as a work around, she can right click on the Parcel in the left hand pane and pick Open Parcel.  Then closing it won't give the error

![image](https://user-images.githubusercontent.com/58946969/72636644-536cf480-3914-11ea-8374-98a9ec626160.png)

**Comment by calequin** [comment]
fixed in production.
missing permissions
![image](https://user-images.githubusercontent.com/47603568/72637800-b320cb00-3927-11ea-8562-19ac515a1113.png)
