### ISSUE TITLE
Re- inspection fee did not generate 

### ISSUE THREAD

**Issue by ABonomo21** [dhenry-KCI/FredCo-Post-Go-Live-#250]
This re-inspection fee for a 3 fire inspection did not generate... 
![image](https://user-images.githubusercontent.com/47611580/72631101-c16be880-3921-11ea-98a4-c2b2d87044c2.png)

**Comment by ABonomo21** [comment]
I will manually add but we need to understand why it did not generate

**Comment by ABonomo21** [comment]
![image](https://user-images.githubusercontent.com/47611580/72631180-e7918880-3921-11ea-9b3a-c269ab54ab4b.png)

**Comment by calequin** [comment]
promote BP_ManageInspection_BUF after county approval in test

**Comment by ABonomo21** [comment]
test accepted ap 183541
