### ISSUE TITLE
Notifications Not Sending

### ISSUE THREAD

**Issue by mlibbey131** [dhenry-KCI/FredCo-Post-Go-Live-#251]
Permit# 259086
Notifications not sending out after stop date inserted into "Stop Notification" Log
![image](https://user-images.githubusercontent.com/58980189/72642431-5aa6f900-393a-11ea-8fff-40d44b2f9e83.png)

**Comment by megisys** [comment]
You need to delete the log

**Comment by JuanitaMiles** [comment]
We were told adding a stop date would re-enable the notifications. We do not want to delete logs as this is used for tracking purposes. The stop date should enable notifications as the application moves forward.

**Comment by megisys** [comment]
I never said this.. Stop Not is a temporary thing and is not the means to track notifications sent and not sent. It is the Communications tab on the contact. they need to be deleted

**Comment by megisys** [comment]
https://github.com/kcigeospatial/Fred_Co_Land-Management/issues/2316

**Comment by ABonomo21** [comment]
Hi there Dan- 

We should not be deleting log, nor should everyone have permissions to remove logs. There has to be another solution. 

Thank you, 

Ashlye

**Comment by megisys** [comment]
SendNotifications Formula Custom Assembly Updated.

**Comment by ABonomo21** [comment]
test 197924 was able to get notifications after the stop not was added
