### ISSUE TITLE
Incorrect Fee Generated

### ISSUE THREAD

**Issue by mlibbey131** [dhenry-KCI/FredCo-Post-Go-Live-#252]
Permit# 260621; Incorrect fee generated; Non-Res Service >400-1000Amp should have been $139.00

[image](https://user-images.githubusercontent.com/58980189/72644136-4cf37280-393e-11ea-8a40-91df99428075.png)

**Comment by ScottVanSooy** [comment]
Promote 
ElecPerm_NonResServ400_1000amp

**Comment by ScottVanSooy** [comment]
deployed 01-17-2020
