### ISSUE TITLE
IPS test not allowing log in

### ISSUE THREAD

**Issue by MLWilkins** [dhenry-KCI/FredCo-Post-Go-Live-#253]
the log in button is blank.  Clicking it fails to load IPS.

![image](https://user-images.githubusercontent.com/50637067/72803031-160dad00-3c1b-11ea-9d1e-86ea8e43a674.png)

**Comment by MLWilkins** [comment]
hitting enter instead of log in button just causes system to spin

![image](https://user-images.githubusercontent.com/50637067/72803240-992f0300-3c1b-11ea-9222-010f30042710.png)

**Comment by MLWilkins** [comment]
works in IE but not Chrome

**Comment by megisys** [comment]
I am using  Chrome. Did you empty your browsing history and cookies ?

**Comment by MLWilkins** [comment]
Deleted a second time. All is well now.
