### ISSUE TITLE
Trailer Permit-Health Review did not generate

### ISSUE THREAD

**Issue by awhite806** [dhenry-KCI/FredCo-Post-Go-Live-#254]
The Health Review Fee generated for this permit but the actual review did not.
![image](https://user-images.githubusercontent.com/58981029/72817136-47947180-3c37-11ea-80b0-ce16a2b1a383.png)
![image](https://user-images.githubusercontent.com/58981029/72817174-5b3fd800-3c37-11ea-8230-dacceb26d9f5.png)

**Comment by calequin** [comment]
This permit address is on Public Water and Sewer, the detail page does not have portable listed in sanitary therefore the review did not populate. Should the fee have populated? The only difference in the code is that the health review is looking to see if the structure is Temporary. 
1. Should fee have been added?
2. Should review mimic the same as the fee code?

**Comment by calequin** [comment]
spoke to Abbie. Review should be added if trailer s type = T in the detail page

**Comment by calequin** [comment]
once tested and approved promote formula: TRAILER_EH_Review_AOC

**Comment by ABonomo21** [comment]
test accepted ap # 259384
