### ISSUE TITLE
Building Permits - NONRESBLDG - Revision Fees for Resubmittals

### ISSUE THREAD

**Issue by JuanitaMiles** [dhenry-KCI/FredCo-Post-Go-Live-#255]
NONRESBLDG Permit # 259223

This application generated a revision fee when PWDR and HEALTH-FD were the only ones to ask for a resubmittal on their reviews. It should not have generated the fee if they were the only ones to request a resubmit.

Revision fees should never automatically generate at the Awaiting Applicant Revisions milestone if HEALTH, HEALTH-FD, DUSWM, OR PWDR reviews are the only ones to ask for a resubmittal.

Ashlye B. has waived the fee and hidden it from the applicants view. The fee can be viewed on the Fees > Transactions tab of the application.

![image](https://user-images.githubusercontent.com/31770504/72832642-47a26a80-3c53-11ea-85af-8509f90f5980.png)

![image](https://user-images.githubusercontent.com/31770504/72833054-fc3c8c00-3c53-11ea-8ee6-4560c1fc3a94.png)

**Comment by pooldaddy** [comment]
Need help with this one.

**Comment by JuanitaMiles** [comment]
will schedule webex for dan/jeff to discuss

**Comment by megisys** [comment]
Leaving this as a Learning Opportunity.  I have this ear marked with Jeff. However this issue was addressed with the RESBLDG revision fix as they are the same formula. But Lets leave this for Dan to meet with Jeff

**Comment by ABonomo21** [comment]
@JuanitaMiles I would like to mark this as test accepted but i know we want to set up a meeting for Jeff and Dan so i am going to leave this to you to change the labels please.

**Comment by JuanitaMiles** [comment]
Marking as Test Accepted and allowing this to close once it is promoted. I have assigned Dustin the responsibility of coordinating a training session with County IIT and Infor. This training is to include updating formulas that drive when fees add to applications.

Dan please promote fix as normal.
