### ISSUE TITLE
Planning - email in error - not sending to new portal users added at intake

### ISSUE THREAD

**Issue by AReed327** [dhenry-KCI/FredCo-Post-Go-Live-#256]
In production I added a contact (the owner Matthew Kline) to SP257730. I immediately got the following email in my inbox. Why did I receive this email? Does this reflect that the email/contact Details are not working properly?

![image](https://user-images.githubusercontent.com/58854333/72896318-78cf7900-3ced-11ea-9297-cf2bb5a25f66.png)

![image](https://user-images.githubusercontent.com/58854333/72896356-9866a180-3ced-11ea-92df-ee5952a2dbb5.png)

**Comment by AReed327** [comment]
Who is this email going to? Every time I add a contact to the contact Details I am getting this email for the user that already has a portal account, not the person I created. It seems this email shouldn't be sending to the existing account holder.

**Comment by AReed327** [comment]
SP257755
![image](https://user-images.githubusercontent.com/58854333/72985339-cf06ef80-3db3-11ea-91b5-5dbeb89aaa0a.png)

**Comment by megisys** [comment]
Ready for test - PL_AddRthyhmAccounts_AAF will be to be promoted if accepted

**Comment by AReed327** [comment]
Tested in TEST on SP257727
Appears a LOG was entered but no email went out. I added Mike as a contact. it appears that is the blank email. 
My expectation is that an email should go out for a new user. 
![image](https://user-images.githubusercontent.com/58854333/73284743-02d28280-41c3-11ea-9749-4189ea31388b.png)
![image](https://user-images.githubusercontent.com/58854333/73284770-0b2abd80-41c3-11ea-9f8f-b10190d28808.png)

**Comment by AReed327** [comment]
the contact log for mike was also not transferred to the applicants.
![image](https://user-images.githubusercontent.com/58854333/73285234-b9cefe00-41c3-11ea-9cef-92b9a9250fe7.png)

**Comment by JuanitaMiles** [comment]
Dan said this is fixed. Ready for Retest

**Comment by AReed327** [comment]
There is nothing in the notification or communications log for Justin Reed. I see that a temporary password was added but do not see that it was ever communicated by email. 
![image](https://user-images.githubusercontent.com/58854333/73844410-848f6500-47ee-11ea-85b3-3cc5ad1be68d.png)

![image](https://user-images.githubusercontent.com/58854333/73844268-3bd7ac00-47ee-11ea-90f2-691abd8f56e0.png)
![image](https://user-images.githubusercontent.com/58854333/73844283-44c87d80-47ee-11ea-949c-efa38203917b.png)
![image](https://user-images.githubusercontent.com/58854333/73844444-953fdb00-47ee-11ea-966f-2960bd792397.png)
![image](https://user-images.githubusercontent.com/58854333/73844501-ae488c00-47ee-11ea-8b64-e93c194e8fa1.png)

You previously said _"The user without a portal account was automatically created one and emailed new details"_   - How can I confirm the new user was emailed since I looked under the portal account in test and there was no communications or notifications listed?

You also said _"I need to change it so this email goes to them and includes the Planning Application Number for reference"_  - I was not able to verify this.

**Comment by megisys** [comment]
This is the Communication - The log is letting you know they were notified of a new account. I can not add planning details as this is a system wide portal functionality. To see the ACTUAL email in produciton you would click on the application and look at communications. In Test we dont do this as we dont email real people

**Comment by AReed327** [comment]
Ok to push to production. Will verify in production after update. AREED

**Comment by calequin** [comment]
promoted on 2.16.2020
