### ISSUE TITLE
Notification Sent- Invalid Permit #259382

### ISSUE THREAD

**Issue by ABonomo21** [dhenry-KCI/FredCo-Post-Go-Live-#258]
Building Permit Issued Notification sent with invalid permit #259382
![image](https://user-images.githubusercontent.com/47611580/72901191-4aef3200-3cf7-11ea-9450-dd24130c7f1d.png)
![image](https://user-images.githubusercontent.com/47611580/72901163-3ad75280-3cf7-11ea-9a98-569a4285e0f4.png)

When searching for Permit #259382 - there are no records.
However a notification was sent out yesterday saying the permit was issued. 

![image](https://user-images.githubusercontent.com/47611580/72901290-7e31c100-3cf7-11ea-80a4-f858ee446732.png)

1/22/2020 EP

**Comment by megisys** [comment]
Email Sent to Abonomo. Isolated incident here
