### ISSUE TITLE
Fire Permit Placard-Permit Type/Type not generating 

### ISSUE THREAD

**Issue by awhite806** [dhenry-KCI/FredCo-Post-Go-Live-#259]
The "Permit Type" and "Type" on the Fire Permit Placard are generating as blank. They should be generating as follows: 
-Permit Type: (Suppression/Alarm/Smoke Control) Info taken from "Type of permit" on Fire Detail Page
-Type: (New/Mod) Info taken from "Work Type" on Job Description Page
![image](https://user-images.githubusercontent.com/58981029/72986851-18a50980-3db7-11ea-80f1-738833fc209c.png)

**Comment by TaraF** [comment]
Assigned, in progress.

**Comment by TaraF** [comment]
@awhite806 - this is now updated (new detail page), but please note that the Type criteria changed from what you have outlined above - the work type (which was the original) to now show the Type of Suppression check box selected.  That decision was made a few months ago by @ABonomo21.   

Please review together and let me know if that should be revert back to Work Type.

Ready for re-test (in Prod).

**Comment by ABonomo21** [comment]
![image](https://user-images.githubusercontent.com/47611580/73566405-c8bae800-4431-11ea-9d9f-3e59cd4581e7.png)
