### ISSUE TITLE
MPDU Fee Missing 

### ISSUE THREAD

**Issue by ABonomo21** [dhenry-KCI/FredCo-Post-Go-Live-#26]
We have a subdivision S1175 for Woodlands and the mpdu fee did not generate for permit applications 258229 and 258238

also it is not an insert able fee

**Comment by ABonomo21** [comment]
also missing Preserve at Long Branch which is Rayburn S1172 is an available fee but did not automatically add.

**Comment by megisys** [comment]
I need the fee information here. @dhenry-KCI  This is urgent.  I need fee names and budget numbers.

Might as well get me all the numbers inbetween S1172 and S1175 too

**Comment by megisys** [comment]
@pooldaddy  Can you please let me know the SubDivisions above and their New Budget Numbers please

**Comment by megisys** [comment]
Ignore this please @pooldaddy  I am researching it

**Comment by megisys** [comment]
Send to our GDS Team to research

**Comment by megisys** [comment]
This Ticket is with Kuwar

**Comment by ABonomo21** [comment]
what is the status of this. we have applicants waiting to pay these fees - ab @dhenry-KCI

**Comment by calequin** [comment]
manually added this to the fee library because of urgency.

**Comment by awhite806** [comment]
Permit #258795, the Rayburn MDPU did not auto generate. Was able to manually add it, but it should auto generate.
![image](https://user-images.githubusercontent.com/58981029/71597442-21385600-2b11-11ea-9227-336d6ebc0b12.png)
![image](https://user-images.githubusercontent.com/58981029/71597467-3dd48e00-2b11-11ea-9f2d-f89f706c2591.png)

**Comment by dhenry-KCI** [comment]
for the short-term the fees have been added so the County can add them when needed. Will need to wait until Dan gets back for status of auto-populating.

**Comment by ABonomo21** [comment]
Keep this assigned to Dan until we get theses fees fixed - we will need to do a check of all the MPDU fees.

**Comment by calequin** [comment]
@ABonomo21 what is the logic for adding these automatically? This way we can work on a formula that can add it

**Comment by ABonomo21** [comment]
the fees are generated based on the subdivision code related to the parcel- the following list of subdivision codes have fees that must be automatically generated with the application fees. Majority of them are MPDU
[MPDU DEVELOPER OBLIGATIONS 10.22.19.xlsx](https://github.com/dhenry-KCI/FredCo-Post-Go-Live-/files/4027321/MPDU.DEVELOPER.OBLIGATIONS.10.22.19.xlsx)

**Comment by megisys** [comment]
Hi There the address has the wrong subdivision code. 

![image](https://user-images.githubusercontent.com/47392306/71917924-3b94b400-314f-11ea-9c7f-cfe48cb11bdd.png)

**Comment by ABonomo21** [comment]
jeff and dustin will work with mary to resolve this

**Comment by JuanitaMiles** [comment]
Reopening this ticket. Per email from Austin WIlliams, GIS is still updating the sudivision codes. Once GIS has confirmed this task is complete the ticket can be closed. (Conversation with dhenry 1/16 2pm)

**Comment by ABonomo21** [comment]
We still have Woodlands at Urbana Permits not generating the MPDU fees, these fees should generate at the time of application fees. 
![image](https://user-images.githubusercontent.com/47611580/72636998-46f59580-392e-11ea-9e10-1a31b22ab120.png)

**Comment by pooldaddy** [comment]
Not sure is subdivison is correct , surrently S1175.  That said even if it is there is no formula defined to apply the fee see attached.
[Github#26.docx](https://github.com/dhenry-KCI/FredCo-Post-Go-Live-/files/4078755/Github.26.docx)

**Comment by calequin** [comment]
added formula RESBLDG_Fee_WoodlandsMPDUFil_AOC
application workflow - fees - woodlands mpdu - ADD ON = Add Plan Review Fees
Add on condition formula create in prod = RESBLDG_Fee_WoodlandsMPDUFil_AOC

**Comment by calequin** [comment]
@pooldaddy working on it in test. just need to finish testing this

**Comment by pooldaddy** [comment]
subsdivision of s1175 is correct

**Comment by calequin** [comment]
FIXED. Need to deploy the above to production

**Comment by ScottVanSooy** [comment]
Deployed 01-17-2020
