### ISSUE TITLE
Inspection count did not increase 

### ISSUE THREAD

**Issue by ABonomo21** [dhenry-KCI/FredCo-Post-Go-Live-#260]
see in test permit 183541 after failing the # 5 fire final, a new one generated which is correct however it is also listed as #5. 

It should have progressed the count to #6 
![image](https://user-images.githubusercontent.com/47611580/72988210-d9c48300-3db9-11ea-9a4c-ee1788148215.png)
![image](https://user-images.githubusercontent.com/47611580/72988244-e3e68180-3db9-11ea-91a5-a1d7da80fab1.png)

**Comment by JuanitaMiles** [comment]
issue identified while testing issue #250

**Comment by ABonomo21** [comment]
will monitor in production

**Comment by emilypearl1** [comment]
Re-opening ticket #125855

![image](https://user-images.githubusercontent.com/58855801/75040725-31bdda80-5489-11ea-84ce-8b2bd0453538.png)

Partial As Built 1072780 should be #5

**Comment by calequin** [comment]
This is correct. The inspection process was completed in the correct cycle. This inspection is not seen as related to the last cycle. Working as standard product design

**Comment by JuanitaMiles** [comment]
@calequin are you saying this because the fourth cycle of the inspection was passed and not partial? I think we always had the understanding that if another review or inspection was added at any point the system would recognize the cycle and follow suit.

This plumbing permit for example. The utility inspection was passed and not partial and people have since added a utility inspection and the cycle has continued to increase.
![image](https://user-images.githubusercontent.com/31770504/75051616-36d85500-549c-11ea-8aca-64ba369f0441.png)

Just trying to understand if this is an odd thing with grading only?

**Comment by calequin** [comment]
this is a difference between 7 and 11. The above inspection existed in 7 the next one was in 11. v7 wouldve seen it as a completed cycle. the life started a cycle in 11 with the new one.

**Comment by JuanitaMiles** [comment]
@emilypearl1 Emily - I was able to replicate the issue you found on this specific application in the test environment. However, I tried adding the inspection on a couple other old applications in test and the inspection count increased as it should have. If we haven't seen this on any other applications, can we close and monitor this? If we see again we can re-open and investigate further. 

![image](https://user-images.githubusercontent.com/31770504/75204668-7ecad680-573f-11ea-9466-d1f63c3069a6.png)
![image](https://user-images.githubusercontent.com/31770504/75204701-96a25a80-573f-11ea-9396-6cd9f7b2eb6b.png)

**Comment by emilypearl1** [comment]
Sure! Let’s close and monitor.

Sent from my iPhone

On Feb 24, 2020, at 7:56 PM, Juanita Miles <notifications@github.com> wrote:

﻿
[EXTERNAL EMAIL]


@emilypearl1<https://github.com/emilypearl1> Emily - I was able to replicate the issue you found on this specific application in the test environment. However, I tried adding the inspection on a couple other old applications in test and the inspection count increased as it should have. If we haven't seen this on any other applications, can we close and monitor this? If we see again we can re-open and investigate further.

[image]<https://linkprotect.cudasvc.com/url?a=https%3a%2f%2fuser-images.githubusercontent.com%2f31770504%2f75204668-7ecad680-573f-11ea-9466-d1f63c3069a6.png&c=E,1,cITtq7Sa21gvx8VnxHcP-S29nD8ulF41SmLaMJgDOeE4ZLh4QQsEbsgk2mzMe9Eo0_HfPeq6AoAirhz2P4bCuQ5zSva4lfJBJaYPUOTRA0dKmnhPPHZ5qQ,,&typo=1>
[image]<https://linkprotect.cudasvc.com/url?a=https%3a%2f%2fuser-images.githubusercontent.com%2f31770504%2f75204701-96a25a80-573f-11ea-9396-6cd9f7b2eb6b.png&c=E,1,pQSMme5XNaJGbVu0al8P0DNNP3673HnXWVnNaat8J3f0jXbdf8BcKhNtd4oX49096qOtLOaHHe2hrmt8d-65uO3oeqqpo4UcPOQpd2N9ylK4rsW3PJGQFyLZTg,,&typo=1>

**Comment by JuanitaMiles** [comment]
If we see another instance of this we will reopen the ticket.
