### ISSUE TITLE
ResUse Permit - Missing Health Review 

### ISSUE THREAD

**Issue by ABonomo21** [dhenry-KCI/FredCo-Post-Go-Live-#261]
Resuse permit on well and septic did not generate a health review 

![image](https://user-images.githubusercontent.com/47611580/72988616-9585b280-3dba-11ea-97a4-61aa723fac42.png)

Related to ticket #217 217

Properties served by Well and or Septic should have a health review, unless priority code of exp  then the health fee and review Should not generate on resuse, see below 

P1 should require a health fee - that would have been prior to our priority code rule changes we made. Remember a P1 used to be a walk through permit, and not it is a 1 week review.

the code should have been updated when we changed the priority code reviews to generate due dates.

now if it a priority code of exp then it should not generate a hd review.

also for non-res food service is not the only reason a hd review and fee should generate, do we need to have a larger conversation.

**Comment by megisys** [comment]
RESUSES_EH_Review_AOC was changed

**Comment by ABonomo21** [comment]
![image](https://user-images.githubusercontent.com/47611580/72991208-91a85f00-3dbf-11ea-849a-95fa950544b9.png)
259392
