### ISSUE TITLE
Home Occupation-Address not required to submit

### ISSUE THREAD

**Issue by awhite806** [dhenry-KCI/FredCo-Post-Go-Live-#262]
We had a Home Occupation submitted through the R4C portal and it was able to go through without an address being added to the permit. Confirmed with Ashlye that address should be required for Home Occupation Permit Applications.  When checking the application on R4C, there is no Required Red Asterisk for the Site Location.
![image](https://user-images.githubusercontent.com/58981029/72989014-7176a100-3dbb-11ea-8848-98d62fbc0413.png)
![image](https://user-images.githubusercontent.com/58981029/72989118-a256d600-3dbb-11ea-866d-e44322d23618.png)

**Comment by megisys** [comment]
They entered it into the location field. See screenshot..

**Comment by megisys** [comment]
You can either rejected it as a resubmit or add for them during completeness check

**Comment by calequin** [comment]
fixed in test. please promote USE_ValidatePortalInfo_CVPI once approved in test
