### ISSUE TITLE
PLANNING - BOE Reviewer not registering from PDOX

### ISSUE THREAD

**Issue by AReed327** [dhenry-KCI/FredCo-Post-Go-Live-#264]
Juanita - please update so that IPS recognizes the reviewer that is sent from PDOX. We had to do this recently for the EH review. I am going to update this one manually in IPS.

![image](https://user-images.githubusercontent.com/58854333/73085257-66e00880-3e9c-11ea-9f92-a51a14b755fb.png)

**Comment by JuanitaMiles** [comment]
Will follow up with Dustin to understand how this was fixed in the past.

**Comment by JuanitaMiles** [comment]
Added Holly Nelson's IPS username to the Hansen ID field in PDox Production. Her name should now appear in IPS moving forward. Please confirm and/or close.

**Comment by JuanitaMiles** [comment]
@AReed327 You can confirm in Prod the next time you get a BOE review required. I did not do this in TEST yet.

**Comment by AReed327** [comment]
Ok to close. I will advise if this happens again.
