### ISSUE TITLE
Business License - Liquor License - License Fees Not Generating

### ISSUE THREAD

**Issue by JuanitaMiles** [dhenry-KCI/FredCo-Post-Go-Live-#265]
Liquor License - 258412

This application did not generate the appropriate License and Endorsement fees. License type was "Other" and Endorsement was "Barbershop". The application is skipping over the license fees and moving straight to Active.

![image](https://user-images.githubusercontent.com/31770504/73096534-001a1980-3eb3-11ea-9cbc-c2b63f8a50db.png)

**Comment by JuanitaMiles** [comment]
See email from Ashley identifying which fee should have added.
![image](https://user-images.githubusercontent.com/31770504/73106627-d7514e80-3ec9-11ea-8d7e-96ea525eeace.png)

**Comment by calequin** [comment]
added add on condition to endorsement fee in test. Once tested please promote LIQUORLIC_Barbershop_AOC

**Comment by JuanitaMiles** [comment]
Requested Ashley K to test

**Comment by JuanitaMiles** [comment]
Ashley K has confirmed the fee generates correctly. See email below for AP # used in test.

![image](https://user-images.githubusercontent.com/31770504/73273171-8be0be00-41b1-11ea-830a-d96be6bb2ade.png)
