### ISSUE TITLE
Planning-IPS upgraded view-missing SDAT button 

### ISSUE THREAD

**Issue by MLWilkins** [dhenry-KCI/FredCo-Post-Go-Live-#266]
Missing SDAT button in all Planning AP types

![image](https://user-images.githubusercontent.com/50637067/73109065-21d5c980-3ed0-11ea-8a9c-5834c7270822.jpeg)

**Comment by MLWilkins** [comment]
SDAT button not working.  This example from YD257731.  None have worked on various application types.
![image](https://user-images.githubusercontent.com/50637067/73186435-b79a7000-40ed-11ea-93b2-328725c46a07.png)

**Comment by MLWilkins** [comment]
Is this ready for retest? @megisys

**Comment by megisys** [comment]
yes sorry

**Comment by MLWilkins** [comment]
opened one of every Planning application and SDAT button works on all.
