### ISSUE TITLE
Building Permits - Grading and Driveway Fees

### ISSUE THREAD

**Issue by ABonomo21** [dhenry-KCI/FredCo-Post-Go-Live-#269]
We need the Minor Grading Fee, Minor SWM Standard Plan Fee, the SCD and the Driveway fee to generate on ResBldg permits when applicable. 

We had originally separated these fees out because we created spawned permits that would generate the fees however, it has become very problematic for our customers. Primarily because many of the builders are assessed a fee for each check they have to have processed and they now have to have multiple checks cut. Many of the builders do not want to pay via credit card or e-check because of the fee. Additionally, they pay permit runners to process their permits and because the fees on a driveway and grading permit do not generate until such time the fees are paid on the Resbldg permit and it moves to under review. Therefore, the permit runners would have to potentially come down to the office 3-4 times to make payments on the applications which is not practical or more efficient for our customers. 

With all of that said, I have a solution to the problem and how we would like to proceed. 

The Driveway fee should generate on a RESBLDG permit when the new Driveway apron on the building details page under site information is marked yes and is an OPEN section and the property (based on the parcel detail) is located on a County Road (driveway permit show still spawn automatically which is also based on these requirements), then there needs to be check box on the driveway permit details page on the driveway permit that the tech can check at completeness check of the driveway application that waives the initial permitting fees because the fee was paid under the building permit. This should work similar to the CIP check box.  Label for the check box (Fee on Associated BP)

The Minor Grading, Minor SWM standard plan fee and the SCD fee should generate on the RESBLDG permit when the occupancy type is RESSFD this is for New and Replacement, in the event we need to waive any of those fees for replacement dwellings we will complete the fee waiver manually because it will need to be evaluated by staff. Then there needs to be check box on the grading permit details page on the grading permit that the tech can check at completeness check of the grading application that waives the initial permitting fees because the fee was paid under the building permit. This should work similar to the CIP check box. Label for the check box (Fee on Associated BP) Grading permit should still spawn automatically. 

We are having the same problem with Resuse permits primarily for swimming pools. Would also like to resolve this issue, 

On building permit types of RESUSE with a construction type of POOLIN (Inground pool) we would like the minor grading and SCD fee to generate on the RESUSE permit. The grading permit should spawn automatically and the tech again can use the check box on the grading permit details to waive the initial permitting fees. 

It is possible that we will need to do this for other applications and work types in the future however, we will have to evaluate them on a case by case basis, this may be a good one for you to record the fix on so that IIT can assist us with a change like this in the future. I would like to talk with Gary more and possibly wait for customer feedback prior to making those changes because, possible other applications would include RESBLDG with occupancy type of RESADU, when marked on the details page as addition or stand alone and the grading or driveway details meet the requirements to spawn those subsequent application types. Additionally RESUSE, with a Construction type of Addition or Accessory when the grading or driveway details meet the requirements to spawn those subsequent application types. Also NONRES, new, addition, accessory when the grading or driveway details meet the requirements. However, we will continue with the current process on those application types for now. 

If we need to set up a meeting to discuss this please let Juanita know and she can arrange something for us.

**Comment by ABonomo21** [comment]
I have screenshots to add that I was not able to add on my laptop, will add on Monday.

**Comment by megisys** [comment]
I would like to work on this together, whilst onsite tomorrow and Wednesday please. - Dan

**Comment by ABonomo21** [comment]
![Driveway](https://user-images.githubusercontent.com/47611580/73179857-31c4f780-40e2-11ea-97ad-0252a973d584.PNG)
![grading details](https://user-images.githubusercontent.com/47611580/73179860-32f62480-40e2-11ea-8712-daffe27efbd2.PNG)

**Comment by JuanitaMiles** [comment]
Per discussion with Ashlye, changing this label to high priority. Can discuss while Dan is on-site

**Comment by megisys** [comment]
PARENT - Added as a Condition on GRADING and DRIVEWAY.
Unexpire these Fees on RESBLDG

**Comment by megisys** [comment]
For Each oCondition as Hansen.CDR.Building.ICondition in oBldgApp.Conditions

If oCondition.ConditionType.Code = "PARENT" then

if oCondition.ApprovalCode.Code.toUpper() = "YES" then
	
	AddOnCondition = False
	
End if


End if

Next

Add to the Grading and Driveway Child Fees

**Comment by megisys** [comment]
BP_Driveway_Parent

**Comment by megisys** [comment]
Double check set up of RESBLDG , GRADING and Driveway from TEST

**Comment by megisys** [comment]
BP_AwaitingResubmitNotification

**Comment by ABonomo21** [comment]
works great for resuse - inground pools and resbldg thank you dan for all of your hard work and for being awesome
