### ISSUE TITLE
Pdox- report errors

### ISSUE THREAD

**Issue by MLWilkins** [dhenry-KCI/FredCo-Post-Go-Live-#27]
Planning staff is getting errors on a number of reports under  “project reports”.  

![image](https://user-images.githubusercontent.com/50637067/70938969-4a3af000-2015-11ea-95cd-c1d365216c7d.png)

**Comment by dhenry-KCI** [comment]
issue resolved. Retest.

**Comment by MLWilkins** [comment]
fixed



![image](https://user-images.githubusercontent.com/50637067/71117528-4ee1de80-21a4-11ea-8de4-4c4b1309983f.png)
