### ISSUE TITLE
R4C upgrade-unable to pay fees in Test

### ISSUE THREAD

**Issue by MLWilkins** [dhenry-KCI/FredCo-Post-Go-Live-#271]
![image](https://user-images.githubusercontent.com/50637067/73175403-16ed8580-40d8-11ea-8962-279472954e2a.png)

**Comment by JuanitaMiles** [comment]
This is currently a know item. Dustin is working with Suzanne to get the test govolution site setup. Emails were exchanged this morning 1/27 regarding this.

**Comment by JuanitaMiles** [comment]
Suzanne has provided Dan and Dustin with the information needed to setup govolution payments in Test.

@megisys - Dan please refer to email from Suzanne on 1/27 for information.

**Comment by JuanitaMiles** [comment]
reassigning, as i am not testing the system

**Comment by megisys** [comment]
https://github.com/dhenry-KCI/FredCo-Post-Go-Live-/issues/307

**Comment by megisys** [comment]
![image](https://user-images.githubusercontent.com/47392306/73304327-09bebc80-41e6-11ea-8ed5-213711f29ec7.png)
