### ISSUE TITLE
Planning-IPS upgrade-APFO (and others?)-unable to open attachments

### ISSUE THREAD

**Issue by MLWilkins** [dhenry-KCI/FredCo-Post-Go-Live-#273]
added attachment.  The was unable to open attachment
See A257728
![image](https://user-images.githubusercontent.com/50637067/73181404-24f5d300-40e5-11ea-9354-5e3a3c9ab1d8.png)

**Comment by JuanitaMiles** [comment]
IPS TEST Upgrade ticket. Assigning to Dan.

**Comment by MLWilkins** [comment]
verified fixed on ap above as well as A257753
