### ISSUE TITLE
Contacts Duplicating

### ISSUE THREAD

**Issue by mlibbey131** [dhenry-KCI/FredCo-Post-Go-Live-#274]
Brent Madison was not a contact until we went Live with the New System, he created a portal account and that was the only contact he had about a month ago. 
However I have noticed that each time he is added as a contact under the contact grid on the portal a new contact is created. But if you look at his information under the Applicants it is linking it to his portal account contact correctly. 

Example Permit# 260657
![image](https://user-images.githubusercontent.com/58980189/73180881-325e8d80-40e4-11ea-8c67-5521c823a635.png)
![image](https://user-images.githubusercontent.com/58980189/73181290-efe98080-40e4-11ea-8aba-096c52ff33ac.png)
![image](https://user-images.githubusercontent.com/58980189/73181350-098ac800-40e5-11ea-805b-523019c2ee22.png)
![image](https://user-images.githubusercontent.com/58980189/73181398-20c9b580-40e5-11ea-80f5-8e599f132dac.png)

However if you look at the permits for James Rollins (Rollins Repairs) it does not duplicate his contact the same way it does for Brent Madison. Example# 260638

**Comment by calequin** [comment]
I tried to replicate this in test and it is working correctly. Were all of the applications created in the portal? or was he added in back office to the applications after the application was created?

**Comment by mlibbey131** [comment]
@calequin There may be one or two that we added him onto in the beginning. As far as I am aware the majority of them were done through the portal. I was not the one who reviewed them all, but on the ones that I completed the other day I did not add him.

**Comment by megisys** [comment]
@calequin can you please investigate deeper on this please and let me know. I feel this should be able to happen. Lets look at the date and times this happened etc

**Comment by ABonomo21** [comment]
discussed with Dan- 1.28.20

**Comment by calequin** [comment]
once tested and approved please promote the following:
Disabled BldCntctDtl_UpdateApplicants_AAC and BldCntctDtl_UpdateApplicants_AA
update BldgAppDtl_CreateAppLogsDetail_AA

**Comment by ABonomo21** [comment]
I created a new permit 259528 and used the same contact Brent Maddison as above and it did not create a new one so seems to be working.

**Comment by ABonomo21** [comment]
are all of those duplicate contact records going to be cleaned up? @calequin
