### ISSUE TITLE
Health Review and Fees on Above Ground Tanks

### ISSUE THREAD

**Issue by mlibbey131** [dhenry-KCI/FredCo-Post-Go-Live-#275]
A/P# 259425 The Health Review Fee and the Health Review should not generate on Above Ground Tanks even if they are on Well and Septic. 

![image](https://user-images.githubusercontent.com/58980189/73182132-7b174600-40e6-11ea-9382-08484d5ef0a0.png)
![image](https://user-images.githubusercontent.com/58980189/73182231-a732c700-40e6-11ea-981d-680e5ba12821.png)
![image](https://user-images.githubusercontent.com/58980189/73182279-c598c280-40e6-11ea-8966-f52f275126bd.png)

**Comment by pooldaddy** [comment]
Looking at workflow.  Is the reason the Health Review not generated due to # days till due set to zero. ?See below:
![image](https://user-images.githubusercontent.com/47391482/73203239-a90e8180-410a-11ea-98d9-7b9c04a86adc.png)

**Comment by pooldaddy** [comment]
Christian your thoughts on above.

**Comment by calequin** [comment]
@pooldaddy from a quick look it seems like there is no add on condition formulas so it is adding at all times. The number of days column would not affect this. This field only affects the due date field. set to zero means no due date will be set.

**Comment by pooldaddy** [comment]
@calequin  think I fixed it see below
![image](https://user-images.githubusercontent.com/47391482/73207133-32758200-4112-11ea-9e96-c5911f5ed5e0.png)

**Comment by pooldaddy** [comment]
@calequin please verify, if ok I will set to retest

**Comment by calequin** [comment]
Added logic to exclude if tank is above ground. once test is approved please promote
TANKS_Health_Fee_AOC
TANKS_EH_Review_AOC
add Add onUnder Review for EH and unexpire

**Comment by ABonomo21** [comment]
tested 259424
