### ISSUE TITLE
RESBLDG - R4C - Detail Page Update

### ISSUE THREAD

**Issue by ABonomo21** [dhenry-KCI/FredCo-Post-Go-Live-#276]
Townhouse details page is missing the blanket plan number field, should be like Ressfd detail page for applicants to submit on r4c
![image](https://user-images.githubusercontent.com/47611580/73183737-4eb0f900-40e9-11ea-968d-4e23e984568b.png)
![image](https://user-images.githubusercontent.com/47611580/73183787-62f4f600-40e9-11ea-9cd6-a5f34ad8568c.png)

we will also need this on apartment/condo for applicants to submit on the portal

**Comment by JuanitaMiles** [comment]
IPS TEST Upgrade ticket. Assigning to Dan

**Comment by JuanitaMiles** [comment]
This is new work requested as Ashlye looks to tweak R4C details for an upcoming release of RESBLDG permits on rhythm. This will not be a top priority for Dan as optimization of the IPS/R4C upgrade. Assigning Christian to work on.

**Comment by calequin** [comment]
added in test

**Comment by ABonomo21** [comment]
need to move blanket number up by blanket plan check box 
![image](https://user-images.githubusercontent.com/47611580/73280179-2b0ab300-41bc-11ea-8927-08c4812b6d15.png)

**Comment by calequin** [comment]
fixed in test.

**Comment by ABonomo21** [comment]
![image](https://user-images.githubusercontent.com/47611580/73304818-f7914e00-41e6-11ea-90cb-6b6420840c29.png)
