### ISSUE TITLE
RESBLDG - R4C- Detail Page Update

### ISSUE THREAD

**Issue by ABonomo21** [dhenry-KCI/FredCo-Post-Go-Live-#277]
under the building details page for Resbldg permits next to building area please add text that reads 

"For non-blanket applications only"

![image](https://user-images.githubusercontent.com/47611580/73185379-f8918500-40eb-11ea-80fe-62a605150aec.png)

**Comment by JuanitaMiles** [comment]
IPS TEST Upgrade ticket. Assigning to Dan.

**Comment by JuanitaMiles** [comment]
This is new work requested as Ashlye looks to tweak R4C details for an upcoming release of RESBLDG permits on rhythm. This will not be a top priority for Dan as optimization of the IPS/R4C upgrade. Assigning Christian to work on.

**Comment by calequin** [comment]
Added label to detail page

**Comment by ABonomo21** [comment]
thank you
