### ISSUE TITLE
IPS Upgrade-rendering issue

### ISSUE THREAD

**Issue by MLWilkins** [dhenry-KCI/FredCo-Post-Go-Live-#278]
Couldnt see SDAT button without scrolling right.  When c licking SDAT button and closing unable to scroll back to the left to see the left side of the screen.  going to a new table and/or refresh doesnt fix it.

![image](https://user-images.githubusercontent.com/50637067/73185741-9c7b3080-40ec-11ea-9b31-e11e8943c248.png)

**Comment by JuanitaMiles** [comment]
IPS TEST Upgrade optimization issue. Assigning to Dan.

**Comment by MLWilkins** [comment]
here is a shot showing that the SDAT button cant be seen on the right side

![image](https://user-images.githubusercontent.com/50637067/73188985-aeab9d80-40f1-11ea-9699-e6bf6c0e98a7.png)

**Comment by megisys** [comment]
Hi There,

Can you tell me what you screen zoom is set at.

Dan

**Comment by megisys** [comment]
It has been moved, just in case

**Comment by MLWilkins** [comment]
100%

**Comment by MLWilkins** [comment]
button moved but the w/s fields disappeared and SDAT button does not work (both separate tickets)
