### ISSUE TITLE
RESBLDG- R4C - Cannot Upload Attachments

### ISSUE THREAD

**Issue by ABonomo21** [dhenry-KCI/FredCo-Post-Go-Live-#279]
Missing the ability to add attachments in r4c  on a RESBLDG Permit 
![image](https://user-images.githubusercontent.com/47611580/73185813-c2a0d080-40ec-11ea-97bc-c35682ccbb9e.png)

**Comment by JuanitaMiles** [comment]
IPS TEST Upgrade optimization issue. Assigning to Dan

**Comment by megisys** [comment]
See issue #272 - Closing as duplicate issue regarding attachments in Rhtyhm
