### ISSUE TITLE
PDox-JMuir-needs batch stamp

### ISSUE THREAD

**Issue by MLWilkins** [dhenry-KCI/FredCo-Post-Go-Live-#28]
Jerry Muir doesnt have the stamp tool

**Comment by MLWilkins** [comment]
add Craig Terry and Ashley Moore to the list.  Need to check Cody Shaw too.

**Comment by dhenry-KCI** [comment]
Resolved. Ready for Retest

**Comment by MLWilkins** [comment]
All users listed above have confirmed fix.
