### ISSUE TITLE
RESBLDG- R4C- Detail Page Update 

### ISSUE THREAD

**Issue by ABonomo21** [dhenry-KCI/FredCo-Post-Go-Live-#280]
![image](https://user-images.githubusercontent.com/47611580/73186502-d39e1180-40ed-11ea-8310-ba7229d11995.png)
Need an option "none" under fireplace

**Comment by JuanitaMiles** [comment]
IPS TEST UPGRADE ticket. Assigning to Dan.

**Comment by JuanitaMiles** [comment]
This is new work requested as Ashlye looks to tweak R4C details for an upcoming release of RESBLDG permits on rhythm. This will not be a top priority for Dan as optimization of the IPS/R4C upgrade. Assigning Christian to work on.

**Comment by calequin** [comment]
Added the code of NONE to code definintion. 
![image](https://user-images.githubusercontent.com/47603568/73230476-10e0be80-4143-11ea-9def-76df8037182e.png)

**Comment by ABonomo21** [comment]
![image](https://user-images.githubusercontent.com/47611580/73275727-9309cb00-41b5-11ea-90f1-e2328c0f9a45.png)
