### ISSUE TITLE
RESBLDG- R4C- Detail Page Update

### ISSUE THREAD

**Issue by ABonomo21** [dhenry-KCI/FredCo-Post-Go-Live-#281]
![image](https://user-images.githubusercontent.com/47611580/73186714-3a232f80-40ee-11ea-9396-2b047745c2fd.png)

Need an option for "site not served by septic"

**Comment by JuanitaMiles** [comment]
IPS TEST Upgrade ticket. Assigning to Dan.

**Comment by JuanitaMiles** [comment]
This is new work requested as Ashlye looks to tweak R4C details for an upcoming release of RESBLDG permits on rhythm. This will not be a top priority for Dan as optimization of the IPS/R4C upgrade. Assigning Christian to work on.

**Comment by calequin** [comment]
Does this new option have logic/formula attached to it? or just for data capturing/ manual purposes?

**Comment by ABonomo21** [comment]
No it does not need to have logic, it would ultimately be on public

**Comment by ABonomo21** [comment]
@calequin and @JuanitaMiles 

This one should go back to Christian.

**Comment by calequin** [comment]
spoke to Dan about this: Need to park until after upgrade release to further discuss the ramifications of adding a table

**Comment by megisys** [comment]
Hotifx required here. Dan to find out date

**Comment by ABonomo21** [comment]
There looks like there is a drop down field now for site served by septic ? but there is nothing to drop down...

**Comment by megisys** [comment]
Need hotfix for Checkboxes. and the dropdown removed.

**Comment by megisys** [comment]
Hotfix is in place

**Comment by ABonomo21** [comment]
Where does this stand, it is an important option needed for applicants submitting on R4C @JuanitaMiles

**Comment by calequin** [comment]
im in process of it now actually

**Comment by calequin** [comment]
added in test and prod

**Comment by ABonomo21** [comment]
![image](https://user-images.githubusercontent.com/47611580/74368350-75d22080-4da1-11ea-9419-0f09797c4438.png)

**Comment by calequin** [comment]
promoted on 2.16.2020
