### ISSUE TITLE
Building - Applications Not Going Into PDox

### ISSUE THREAD

**Issue by JuanitaMiles** [dhenry-KCI/FredCo-Post-Go-Live-#282]
These two applications are not going through PDox.

260644/260742 - The application says it is an "EPlans" application but it is not showing in PDox messages at all. We don't know what is preventing them from moving through.

![image](https://user-images.githubusercontent.com/31770504/73191681-e288c200-40f5-11ea-850c-ae2d9e655a42.png)

![image](https://user-images.githubusercontent.com/31770504/73191719-f3393800-40f5-11ea-8efe-662b1a0488d0.png)

**Comment by JuanitaMiles** [comment]
Also an issue with 260896.

**Comment by calequin** [comment]
upon review it looks like they originally got resulted as intrnal and changed after the fact.
need to create an OPDOX Log that will override any mistakes on a completeness check and send it to pdox.

Once tested please promote BP_OverridePDOXCreateLog_AAF
add OPDOX LOG to code definition manangement
add formula on SWM under Lofg AA

**Comment by ABonomo21** [comment]
closing.

**Comment by calequin** [comment]
opening to keep track of log formula promotion to prod

**Comment by JuanitaMiles** [comment]
@calequin Is there anything you need me or the County to do here? Or are you using this for your promotion purposes only? If this is only for your tracking please self assign, and let us know if you need us to do anything.

**Comment by calequin** [comment]
This needs promotion to prod for whomever is promoting this week
