### ISSUE TITLE
PLANNING - ALL PLANNING Applications need Water/Sewer box - UPGRADE

### ISSUE THREAD

**Issue by AReed327** [dhenry-KCI/FredCo-Post-Go-Live-#283]
EXAMPLES: PL257733/SP257729 and all other types
![image](https://user-images.githubusercontent.com/58854333/73193366-76f42400-40f8-11ea-9ba8-af31e13204b0.png)
I observed no water/sewer in the application header
I expect the water/sewer in the application header as we currently do in production.

**Comment by MLWilkins** [comment]
this was there but went away when  ticket 268 (moved the SDAT button) was addressed.

**Comment by JuanitaMiles** [comment]
IPS TEST Upgrade optimization issue. Assigning to Dan

**Comment by megisys** [comment]
![image](https://user-images.githubusercontent.com/47392306/73210296-f47b5c80-4117-11ea-9e42-f7153fbedfbd.png)

I am worried you screen is in zoom.. See my screenshot

**Comment by MLWilkins** [comment]
looked at all planning ap types in test and all have the w/s field.
