### ISSUE TITLE
Planning-R4C/IPS upgrade- all APs-need to establish what is visible to applicant

### ISSUE THREAD

**Issue by MLWilkins** [dhenry-KCI/FredCo-Post-Go-Live-#285]
this is a preplat example, but things we dont want the applicant to see are coming over to the portal.  These preferences need to be set before this is pushed to production.  

![image](https://user-images.githubusercontent.com/50637067/73198728-8a57bd00-4101-11ea-8e14-b453335a640f.png)

**Comment by JuanitaMiles** [comment]
IPS TEST Upgrade ticket. Assigning to Dan.

**Comment by megisys** [comment]
This is the same as production. Status Checks can not be turned off for Portal. All that can be done is a language change. This is not an TEST Issue really. It is a Production Enhancement one

**Comment by JuanitaMiles** [comment]
This is understood by Mike and Ashley. Will add this as an enhancement to explore further in a different tracking repository. Closing ticket.
