### ISSUE TITLE
Planning-APFO-IPS Upgrade-APFO notification "hansen.core" language

### ISSUE THREAD

**Issue by MLWilkins** [dhenry-KCI/FredCo-Post-Go-Live-#286]
all of the APFO notifications has the hansen core stuff on it.  Please remove that {{sentence}}.

![image](https://user-images.githubusercontent.com/50637067/73201851-e3c2ea80-4107-11ea-95e2-3c49b60ae5fe.png)

![image](https://user-images.githubusercontent.com/50637067/73201974-1ec51e00-4108-11ea-8f03-04ebe04c4d63.png)

![image](https://user-images.githubusercontent.com/50637067/73202010-356b7500-4108-11ea-9019-c6aef0078562.png)

**Comment by JuanitaMiles** [comment]
IPS TEST Upgrade ticket. Assigning to Dan

**Comment by MLWilkins** [comment]
just need to remove }} at end of project number

![image](https://user-images.githubusercontent.com/50637067/73283252-d584d500-41c0-11ea-9cb3-2187042c1bea.png)

**Comment by megisys** [comment]
removed 
![image](https://user-images.githubusercontent.com/47392306/73286160-1bdc3300-41c5-11ea-89f8-1a4cd1d061ef.png)
