### ISSUE TITLE
Planning-FRO-IPS UPgrade- base date and time line on fee notification

### ISSUE THREAD

**Issue by MLWilkins** [dhenry-KCI/FredCo-Post-Go-Live-#287]
please fix the 1/1/0001 12am line or make it populate correct date/time

![image](https://user-images.githubusercontent.com/50637067/73202317-c2aec980-4108-11ea-9580-1c5d22af0d77.png)

**Comment by JuanitaMiles** [comment]
IPS TEST Upgrade optimization issue. Assigning Dan

**Comment by MLWilkins** [comment]
fixed
