### ISSUE TITLE
Planning-IPS Upgrade- Plat notification issues

### ISSUE THREAD

**Issue by MLWilkins** [dhenry-KCI/FredCo-Post-Go-Live-#288]
strange date and time at top of plat fee email

![image](https://user-images.githubusercontent.com/50637067/73202451-17524480-4109-11ea-9aa2-8ac362219182.png)

**Comment by JuanitaMiles** [comment]
IPS TEST Upgrade optimization issue. Assigning Dan

**Comment by MLWilkins** [comment]
looks good now
