### ISSUE TITLE
Planning-IPS Upgrade-Site notification issues

### ISSUE THREAD

**Issue by MLWilkins** [dhenry-KCI/FredCo-Post-Go-Live-#289]
Payment required- bad date/time

![image](https://user-images.githubusercontent.com/50637067/73202866-f76f5080-4109-11ea-8a50-524eb5b319cc.png)

Project Complete notification didnt send.  Below exampe from Prod.
![image](https://user-images.githubusercontent.com/50637067/73203194-9136fd80-410a-11ea-80ca-71feb2776fb4.png)

**Comment by JuanitaMiles** [comment]
IPS TEST Upgrade optimization issue. Assigning Dan

**Comment by AReed327** [comment]
SP257759 - verified corrected.
