### ISSUE TITLE
Grading Extensions 

### ISSUE THREAD

**Issue by emilypearl1** [dhenry-KCI/FredCo-Post-Go-Live-#29]
How do I run the grading extensions by batch?

**Comment by megisys** [comment]
'// Workflow formula: Batch_BP_Expiration_BCT
'// By: Don Goggans
'// Created: 4/19/2019
'// Purpose: Sets permit status to Expired for all Building Permits if the expiration date has passed.
Dim Res As Result
Dim monthsTime as DateTime = ServerApplication.GetDateNow.AddDays(31)
Dim DontAdd as Boolean = False

Dim oBuildingPermits As Hansen.CDR.Building.IBuildingApplicationCollection = ServerApplication.NewComponent(Of Hansen.CDR.Building.IBuildingApplicationCollection)()

Dim oWhere As New DBOperativeCollection()

oBuildingPermits.MaxRecords = 0

oWhere.Add(New IDOperativeByCommonID("CDR.Building", "BuildingApplication.ExpireDateTime", ComparisonOperator.LessThan, monthsTime))

oWhere.Add(New IDOperativeByCommonID("CDR.Building", "BuildingApplication.ApplicationType.ApplicationType", ComparisonOperator.Equal, "GRADING"))

Res = CType(oBuildingPermits, Hansen.Core.Business.ComponentCollection).Load(oWhere, True)

For Each oBuildingApplication As Hansen.CDR.Building.IBuildingApplication In oBuildingPermits


For Each oLog as Hansen.CDR.Building.ILog in oBuildingApplication.Log

if oLog.LogType.Code = "EXTR" and oLog.StartDateTime > ServerApplication.GetDateNow.AddDays(-31) then
	
	DontAdd=True
	
End if

Next


if DontAdd = False then
	
	Dim oAddLog as Hansen.CDR.Building.ILog = ServerApplication.NewComponent(of Hansen.CDR.Building.ILog)()
	oAddLog.LogType.Code = "EXTR"
	oAddLog.StartDateTime = ServerApplication.GetDateToday()
	oAddLog.BuildingApplication = oBuildingApplication
	oAddLog.Comments = "Added by Batch Manager"
	oAddLog.StartedBy.EmployeeID = "Hansen"
	
	oAddLog.Add()
	
	
End if


	Res = oBuildingApplication.Update()


Next

**Comment by megisys** [comment]
'// Workflow formula: Batch_BP_Expiration_BCT
'// By: Don Goggans
'// Created: 4/19/2019
'// Purpose: Sets permit status to Expired for all Building Permits if the expiration date has passed.
Dim Res As Result
Dim monthsTime as DateTime = ServerApplication.GetDateNow.AddDays(31)
Dim DontAdd as Boolean = False

Dim oBuildingPermits As Hansen.CDR.Building.IBuildingApplicationCollection = ServerApplication.NewComponent(Of Hansen.CDR.Building.IBuildingApplicationCollection)()

Dim oWhere As New DBOperativeCollection()

oBuildingPermits.MaxRecords = 0

oWhere.Add(New IDOperativeByCommonID("CDR.Building", "BuildingApplication.ExpireDateTime", ComparisonOperator.LessThan, monthsTime))
oWhere.Add(New IDOperativeByCommonID("CDR.Building", "BuildingApplication.ExpireDateTime", ComparisonOperator.GreaterThan,ServerApplication.GetDateNow()))

oWhere.Add(New IDOperativeByCommonID("CDR.Building", "BuildingApplication.ApplicationType.ApplicationType", ComparisonOperator.Equal, "GRADING"))

Res = CType(oBuildingPermits, Hansen.Core.Business.ComponentCollection).Load(oWhere, True)

For Each oBuildingApplication As Hansen.CDR.Building.IBuildingApplication In oBuildingPermits


For Each oLog as Hansen.CDR.Building.ILog in oBuildingApplication.Log

if oLog.LogType.Code = "EXTR" and oLog.StartDateTime > ServerApplication.GetDateNow.AddDays(-31) then
	
	DontAdd=True
	
End if

Next


if DontAdd = False then
	
	Dim oAddLog as Hansen.CDR.Building.ILog = ServerApplication.NewComponent(of Hansen.CDR.Building.ILog)()
	oAddLog.LogType.Code = "EXTR"
	oAddLog.StartDateTime = ServerApplication.GetDateToday()
	oAddLog.BuildingApplication = oBuildingApplication
	oAddLog.Comments = "Added by Batch Manager"
	oAddLog.StartedBy.EmployeeID = "Hansen"
	
	oAddLog.Add()
	
	
End if


	Res = oBuildingApplication.Update()


Next

**Comment by emilypearl1** [comment]
I have no idea  what any of this mean?

**Comment by megisys** [comment]
@emilypearl1 - its for me to move tonight

**Comment by megisys** [comment]
Batch Manager job needs to be created also

**Comment by megisys** [comment]
Add formula called -- Batch_Grading_Expiration_BCT

**Comment by ScottVanSooy** [comment]
Promoted to Production 12/17/2019 8:30 PM

**Comment by emilypearl1** [comment]
How do I run this?

12/18/19 EP

**Comment by megisys** [comment]
Emily. You need to search fro all grading permits which will expire in next 30 days. Add the fees you need to add.

Then gointo Batch Manager SBM (Form Code)

Run the Grading Expiration JOb

![image](https://user-images.githubusercontent.com/47392306/71093034-64401400-2176-11ea-8496-f45adbad059a.png)

**Comment by ABonomo21** [comment]
See permit 53079 - still added $49.00 building fee 

![image](https://user-images.githubusercontent.com/47611580/72178608-3d5db200-33b1-11ea-80a7-6f196fd2c258.png)

**Comment by ABonomo21** [comment]
Also- the Grading Permit Expiration Notice that was generated after I added the Log  needs to be modified:
![image](https://user-images.githubusercontent.com/47611580/72178779-9d545880-33b1-11ea-8372-5b828e117420.png)

Please change to Emily Pearl at 301-600-6721

**Comment by ABonomo21** [comment]
3rd Item- an updated Placard with the new expiration date was not sent out.

**Comment by ScottVanSooy** [comment]
I believe all the Correspondence has been sent now.  I’d like to run a script to verify the email addresses.

**Comment by ABonomo21** [comment]
permit 149962 added the Building ext fee of $49.00. I had manually inserted the grading renewal fees as instructed.... when i approved the ext review- the system generated the building ext fee in error. 

![image](https://user-images.githubusercontent.com/47611580/72371180-cf2b2f00-36d1-11ea-89fe-e66483c79924.png)

Emily

**Comment by ScottVanSooy** [comment]
According to the formula below, it will add the fees unless certain values are checked on a Non Residential Intake Detail page.  This application does not have a Non Residential Intake Detail page, so the fee is getting added.

BP_ExtensionReviewSetDateFee_BUF

For Each oDetail As Hansen.CDR.Building.IApplicationDEtail In oReview.BuildingApplication.ApplicationDetails

If oDetail.ApplicationDetailType.ClassName = "InforClient.AgencyCDR.BuildingApplet.NonResIntake" Then

Dim oNonResidentialDetail As InforClient.AgencyCDR.Building.NonResidentialDetail

oNonResidentialDetail = InforClient.AgencyCDR.Building.NonResidentialDetail.GetInstanceFromParent(oDetail, res)

If oNonResidentialDetail.CIPProject Or oNonResidentialDetail.CIPFEES Or oNonResidentialDetail.MUNFEES Or oNonResidentialDetail.MunicipalProject Then

DontCharge = True

Exit For
End If
End If
Next

**Comment by ScottVanSooy** [comment]
Ashlye and Juantia recommended this change. 

If oBuildingApplication.ApplicationType = "GRADING" Or  oBuildingApplication.ApplicationType = "FRO" Then
DontCharge = True
End If

**Comment by ScottVanSooy** [comment]
Promote BP_ExtensionReviewSetDateFee_BUF

**Comment by ABonomo21** [comment]
fixed. working now

1/16/2020 ep
