### ISSUE TITLE
PLANNING - UPGRADE, wrong DUE DATES - PWCONSTRUC 

### ISSUE THREAD

**Issue by AReed327** [dhenry-KCI/FredCo-Post-Go-Live-#290]
Observed behavior - Improvement Plan Due Date is setting to 1 week. 
Expected behavior - It should be 3 weeks on first submission, then 2 weeks every re submission after that. 
PW257735
![image](https://user-images.githubusercontent.com/58854333/73203603-66997480-410b-11ea-8aeb-e5758cdbea75.png)

**Comment by JuanitaMiles** [comment]
IPS TEST Upgrade optimization issue. Assigning Dan

**Comment by AReed327** [comment]
Corrected PW257743

**Comment by AReed327** [comment]
test accepted
