### ISSUE TITLE
PLANNING - IPS Upgrade- PWConst- Milestone not holding for fees DUE now and Fees not showing in DUE NOW

### ISSUE THREAD

**Issue by AReed327** [dhenry-KCI/FredCo-Post-Go-Live-#291]
Observed behavior - Application went back under review without fees being paid. DUE NOW should show the outstanding fees 
Expected behavior - I expect fees to show in due now and that the application will not go under review again before the fees are paid.
PW257735
![image](https://user-images.githubusercontent.com/58854333/73203984-28e91b80-410c-11ea-8578-68d750bbe643.png)

![image](https://user-images.githubusercontent.com/58854333/73203839-d445a080-410b-11ea-8940-b03192898a3d.png)

**Comment by JuanitaMiles** [comment]
IPS TEST Upgrade optimization issue. Assigning Dan

**Comment by AReed327** [comment]
Fees Due and did not hold from going under review on resubmission from PDOX. Discussed with MWilkins. With no communication back and forth with PDOX on 2nd review. They way it is set up now will keep it from going out of sync. Intake will need to check IPS to make sure no fees owed before routing PDOX resubmission

![image](https://user-images.githubusercontent.com/58854333/73282481-b6397800-41bf-11ea-978f-d674524cf670.png)

![image](https://user-images.githubusercontent.com/58854333/73282524-c3eefd80-41bf-11ea-90f0-21ff7200614d.png)

**Comment by AReed327** [comment]
test accepted
