### ISSUE TITLE
Planning-IPS Upgrade- Rezone- error when trying to pay fee back office

### ISSUE THREAD

**Issue by MLWilkins** [dhenry-KCI/FredCo-Post-Go-Live-#292]
RZ257737

![image](https://user-images.githubusercontent.com/50637067/73204177-82e9e100-410c-11ea-90b4-3b839236dce7.png)

**Comment by JuanitaMiles** [comment]
IPS TEST Upgrade optimization issue. Assigning Dan.

**Comment by megisys** [comment]
Not a TEST Issue. This was happening in Production too. I have fixed in Test. Will need to be promoted
PLN_REZONE_StateHighwayReview_AOC

**Comment by MLWilkins** [comment]
was able to pay fee

![image](https://user-images.githubusercontent.com/50637067/73281624-424aa000-41be-11ea-9e2b-d5fd96146a26.png)
