### ISSUE TITLE
Incorrect Building Minimum Fee

### ISSUE THREAD

**Issue by awhite806** [dhenry-KCI/FredCo-Post-Go-Live-#293]
The building minimum fee for a resbldg final only building permit should be $118 not $115
![image](https://user-images.githubusercontent.com/58981029/73204488-099ebe00-410d-11ea-8377-5b4479d64dcc.png)
![image](https://user-images.githubusercontent.com/58981029/73204690-6306ed00-410d-11ea-9a82-81705f54c7f8.png)

**Comment by megisys** [comment]
Changed to 118

**Comment by ABonomo21** [comment]
![image](https://user-images.githubusercontent.com/47611580/73283760-9905a900-41c1-11ea-9e11-91cf791ed6c9.png)
