### ISSUE TITLE
Planning-IPS Upgrade-water/sewer-notification issues

### ISSUE THREAD

**Issue by MLWilkins** [dhenry-KCI/FredCo-Post-Go-Live-#294]
Payment notification-bad date/time 

![image](https://user-images.githubusercontent.com/50637067/73204991-0c4de300-410e-11ea-9847-a8018935f53a.png)

same with under review
![image](https://user-images.githubusercontent.com/50637067/73205040-2ab3de80-410e-11ea-926c-2fe4f1043ac1.png)

**Comment by JuanitaMiles** [comment]
IPS TEST Upgrade optimization issue. Assigning to Dan.

**Comment by MLWilkins** [comment]
tested both notifications.  look good
