### ISSUE TITLE
PLANNING - UPGRADE - PWCONSTRUC - Due dates populating before plans received in PDOX

### ISSUE THREAD

**Issue by AReed327** [dhenry-KCI/FredCo-Post-Go-Live-#295]
Project Number - PW257740
Observed behavior - Due Dates populating after fees are paid. 
Expected behavior - Due Dates should not populate until plans submitted and accepted in Project Dox
Screenshot - 
![image](https://user-images.githubusercontent.com/58854333/73205928-f17c6e00-410f-11ea-9c86-0048a1061396.png)
![image](https://user-images.githubusercontent.com/58854333/73206266-9eef8180-4110-11ea-81ef-652453d7e7ba.png)

**Comment by JuanitaMiles** [comment]
IPS TEST Upgrade optimization issue. Assigning to Dan

**Comment by AReed327** [comment]
Verified Corrected PW257746

**Comment by AReed327** [comment]
ok to promote
