### ISSUE TITLE
Homebuilder License is not being accepted.

### ISSUE THREAD

**Issue by awhite806** [dhenry-KCI/FredCo-Post-Go-Live-#296]
This permit is not progressing because it is stating a homebuilder license is required. I have both the license holder and company as applicants and the license is available on both contacts. I even tried changing the applicant type from builder to contractor and nothing would get rid of this fulfilled requirement. I had to supervisor override to get the permit to move forward.

![image](https://user-images.githubusercontent.com/58981029/73203434-0a365500-410b-11ea-9a5b-27fd53a232c8.png)

![image](https://user-images.githubusercontent.com/58981029/73203537-42d62e80-410b-11ea-9b4a-3fa1ecf1c74d.png)
![image](https://user-images.githubusercontent.com/58981029/73203466-18847100-410b-11ea-8a0d-0537ba9cc9bc.png)

**Comment by megisys** [comment]
It is because the same license was listed twice. Please update the license with the new date. Please don't add the same license with a new date as we now have duplicates to test.

**Comment by ABonomo21** [comment]
reviewed with Dan have to inactive one of the licenses when there are multiple.

![image](https://user-images.githubusercontent.com/47611580/73301554-f8bf7c80-41e0-11ea-98da-f20b8ccb2964.png)

@awhite806 @mlibbey131 Just as an FYI this is how we can fix it moving forward.

**Comment by calequin** [comment]
Reopening per issue this morning @ABonomo21 
I fixed formula and needs promotion
RESBLDG_LicReqResubmit_Req

**Comment by calequin** [comment]
promoted on 2.9.2020
