### ISSUE TITLE
Electrical Homeowner license is not being accepted

### ISSUE THREAD

**Issue by awhite806** [dhenry-KCI/FredCo-Post-Go-Live-#297]
For permit 262056, the electrical homeowner license was not accepted and we had to supervisor override the permit. see old github ticket #2173- the original ticket states the code still needed to be completed

**Comment by megisys** [comment]
License Type starts with EHO needs to be added here

**Comment by calequin** [comment]
Please test. once approved promote
BP_ELEC_Check_SCF

**Comment by ABonomo21** [comment]
confirmed on the tested application 259437 - satisfied requirement 
![image](https://user-images.githubusercontent.com/47611580/73301928-c2363180-41e1-11ea-8f79-41727dc216dd.png)

**Comment by awhite806** [comment]
REOPENING-This issue has not been resolved. permit  265223 has the homeowner with the license on his contact and the permit still will not progress stating it needs a license.
![1](https://user-images.githubusercontent.com/58981029/74977587-f96ebb80-53f8-11ea-8018-c10627ff7287.jpg)
![2](https://user-images.githubusercontent.com/58981029/74977590-fa9fe880-53f8-11ea-8e8f-24136ec82f43.jpg)

**Comment by megisys** [comment]
This was previously addressed, however we hit an unexpected issue after move to production.

BP_ELEC_Check_SCF to be changed again.

**Comment by megisys** [comment]
BP_ELEC_Check_SCF  To be promoted once accepted

**Comment by ABonomo21** [comment]
tested 
![image](https://user-images.githubusercontent.com/47611580/75069792-ebd03900-54bf-11ea-8518-9413d0ee6c50.png)

**Comment by calequin** [comment]
promoted on 2.23.2020
