### ISSUE TITLE
Plumbing permit Official Issuance-First page entirely blank

### ISSUE THREAD

**Issue by awhite806** [dhenry-KCI/FredCo-Post-Go-Live-#298]
Spoke with Ashlye to see if this was a true issue or not and we both decided to log it just to check on it.

this plumbing permits first page is blank. the information for the permit does not start until page 2 where it then has normal formatting
[262035-first page fully blank.pdf](https://github.com/dhenry-KCI/FredCo-Post-Go-Live-/files/4122552/262035-first.page.fully.blank.pdf)

**Comment by TaraF** [comment]
Assigned, investigating cause.

**Comment by TaraF** [comment]
This should be fixed.  Please re-test (Prod), and please let us know if you encounter it again.

**Comment by ABonomo21** [comment]
corrected re-checked 262035
![image](https://user-images.githubusercontent.com/47611580/73849069-434f8300-47f7-11ea-8d05-0acd3c1065a9.png)
