### ISSUE TITLE
RESBLDG - Revision Fee- TEST 

### ISSUE THREAD

**Issue by ABonomo21** [dhenry-KCI/FredCo-Post-Go-Live-#299]
Revision fee did not generate  automatically when a revision was submitted - zoning had resulted the review as a resubmit and it should have triggered the revision fee. Application went straight to revision assignment. 

TEST 259399

![image](https://user-images.githubusercontent.com/47611580/73274515-addb4000-41b3-11ea-8779-8cbda05179a1.png)

**Comment by calequin** [comment]
from looking at the logs it looks the application went into awaiting revision fee payment and the applicant paid at 9:18 on 1/21 then it went into the awaiting applicant revisions and correctly into the revision assignment on 1/23. I dont think there is an issue here as it looks to have gone through the correct workflow.

I also created a test one 263310 and it flowed correctly

**Comment by ABonomo21** [comment]
tested under permit 263215 in test and it did not progress to awaiting applicant resubmit due to check status condition the building permit should only check for this status at pending issuance. 
![image](https://user-images.githubusercontent.com/47611580/73978119-ac1f2400-48f9-11ea-9d2d-a3a6f6b8a535.png)

**Comment by calequin** [comment]
fixed in test and production. Expired this status check and made sure pending issuance had the correct status check
