### ISSUE TITLE
Building Permits - Capacity - Woodlands @ Urbana Subdivision Fees

### ISSUE THREAD

**Issue by JuanitaMiles** [dhenry-KCI/FredCo-Post-Go-Live-#30]
CAPACITY - RESIDENTIAL SINGLE FAMILY DWELLING
AP # 258233

The Woodlands @ Urbana subdivision code 061175 needs to automatically add the RESIDENTIAL WATER FEE 10500 ($5380.00) and RESIDENTIAL SEWER FEE 20600 ($7509.00) when it is a residential occupancy type.

Terry manually added these fees to the application in PROD.

![image](https://user-images.githubusercontent.com/31770504/71008386-81151280-20b6-11ea-8711-ee184b1055f2.png)

![image](https://user-images.githubusercontent.com/31770504/71008634-ecf77b00-20b6-11ea-8039-4f4baffba7b7.png)

**Comment by megisys** [comment]
Migrate -  CAPACITY_ResSewer20600_Fee_AOC

and

CAPACITY_ResWater10500_Fee_AOC

**Comment by ScottVanSooy** [comment]
Promoted to Production 12/17/2019 8:30 PM
