### ISSUE TITLE
Building/Use Permits - Inspection Requests Coming in On Weekends for Next Business Day

### ISSUE THREAD

**Issue by JuanitaMiles** [dhenry-KCI/FredCo-Post-Go-Live-#300]
This issue is being reported by Bob Ensor.

Bob has noticed that customers are logging in to R4C on the weekend/holiday and requesting an inspection for the next business day. For example, on Sunday morning someone will request an inspection for Monday. This should not be allowed. 

For weekends: A customer must submit their inspection request prior to noon Friday in order to request for Monday. If the request is submitted past noon Friday or over the weekend the inspection would be pushed to Tuesday.

For holidays: the same logic applies. A customer cannot login on a holiday and request their inspection for the next business day.

**Comment by megisys** [comment]
BP_ScheduleInspection_BU to be tested and if successful needs to be promoted to Production

**Comment by TheBobEnsor** [comment]
I'm assuming I need to wait until Friday after 12:pm and or Saturday to test, is there a way to change date in test?
Thought about it Sunday evening which was after 12:pm and it would only allow me to schedule Tuesday

**Comment by ABonomo21** [comment]
I will get into test this weekend and try to schedule an inspection.,

**Comment by TheBobEnsor** [comment]
In Test R4C on Sunday morning at 10:46 (before Noon) and requested inspection for permit 259370 for Monday Am and it allowed me to make the request.  Then verified in Test IPS  
**Anything after Noon on any giving business day should be forced to two business days out**

**Comment by ABonomo21** [comment]
@3:52pm sunday I was not able to schedule for Monday – but when I tried to schedule for Tuesday on Sunday I got this error…. 
![image](https://user-images.githubusercontent.com/47611580/74654148-a88c6800-5157-11ea-9e6b-6ccbad8acbfa.png)

**Comment by calequin** [comment]
please test on weekend, if accepted please promote

BP_ScheduleInspection_BU

**Comment by ABonomo21** [comment]
was just able to request and inspection for Monday in test 
![image](https://user-images.githubusercontent.com/47611580/75067726-af9ad980-54bb-11ea-8f81-22f19f70af24.png)

**Comment by ABonomo21** [comment]
test permit 263327

**Comment by calequin** [comment]
Please test the following scenarios:
On Friday after 12pm try to request for Monday
Saturday try requesting for Monday
Sunday try requesting for Monday

if approved please promote
BP_ScheduleInspection_BU

**Comment by TheBobEnsor** [comment]
did not try on Friday
Saturday at 6:30 pm tried to schedule for Monday and it appeared to be correct, I received an error that told me I needed to pick a future date, but when I tried to schedule for Tuesday I got the same message. I also tried to set it for Wednesday and received the same message.  I then tried to reschedule one that was already scheduled for Tuesday for Monday and it gave me the same message which would be correct. but then I tried to move the same one already scheduled for Tuesday to Wednesday and received  the same message saying that I must pick a future date?
It appears that I can't schedule anything on Saturday for any date in the future 
Bob

**Comment by TheBobEnsor** [comment]
Sunday morning 
Seamed to be working, was not able to schedule for Monday and was able to schedule for Tuesday?
Bob

**Comment by JuanitaMiles** [comment]
Reopening Ticket per Bob Ensor. See his comments below:

![image](https://user-images.githubusercontent.com/31770504/81094695-e46ed800-8ed1-11ea-98c0-df67f1f049ef.png)

**Comment by megisys** [comment]
BP_ScheduleInspection_BU - To be promoted once accepted

**Comment by JuanitaMiles** [comment]
@TheBobEnsor @ABonomo21 Bob and/or Ashlye if you are able. Please test this Friday afternoon and over the weekend to see if you can request inspections on Monday and/or Tuesday. (Monday is Memorial day so Tuesday would be the next business day.)

**Comment by JuanitaMiles** [comment]
Test result from Bob 5/29 3:08pm
![image](https://user-images.githubusercontent.com/31770504/83296358-a8701f80-a1be-11ea-838b-276fea3884d3.png)

**Comment by megisys** [comment]
BP_ScheduleInspection_BU

Cleaned up 
		If (ServerApplication.GetDateNow().Hour >= 12 and oInspection.CallDateTime.DayofWeek = 1 and ServerApplication.GetDateNow().DayofWeek = 5) or (ServerApplication.GetDateNow().DayofWeek = 6 or ServerApplication.GetDateNow().DayofWeek = 0 and oInspection.CallDateTime.DayofWeek = 1) Then

			Dim dt As Date = Date.Parse(oInspection.CallDateTime)

			Dim dateString = dt.ToShortDateString()

			Dim ndt As Date = Date.Parse(ServerApplication.GetDateNow().AddDays(1))

			Dim ndateString = ndt.ToShortDateString()

			If dateString = ndateString Then

					res = New Result(0, ResultSeverity.UserError, "Can't Schedule for Monday the cut off is 12pm Friday before")

				Return res

			End If

**Comment by ABonomo21** [comment]
tested 6.6.20 in test a/p 278148 in test inspection number 1097263- Failed I was able to request 6.8.20

**Comment by ABonomo21** [comment]
![image](https://user-images.githubusercontent.com/47611580/83947868-a2de8f00-a7e7-11ea-9795-ed15c2649bf2.png)

**Comment by ABonomo21** [comment]
I was not able to submit a request on sunday for monday 278148 inspection 1097264

I also rescheduled the previous inspection tested yesterday and was able to schedule for rescdule for 6.9.20 but was not able to reschedule again for 6.8.20

**Comment by megisys** [comment]
I will test it myself this weekend. As I can not see an issue in the code and will need to debug this. Sorry for the delay.
