### ISSUE TITLE
Upgrade - R4C-Attachments- Correspondence 

### ISSUE THREAD

**Issue by ABonomo21** [dhenry-KCI/FredCo-Post-Go-Live-#302]
Applicant has the ability to edit the Title, description, of an attachment from R4C

![image](https://user-images.githubusercontent.com/47611580/73278102-1a0c7280-41b9-11ea-8f80-27b4a439f38f.png)

**Comment by megisys** [comment]
Adding Christian as he is working on Attachments for me as this is in the R4C domain

**Comment by ABonomo21** [comment]
![image](https://user-images.githubusercontent.com/47611580/73281349-d700ce00-41bd-11ea-91ef-7fb6b09c2918.png)

should this attribute be viewable

**Comment by calequin** [comment]
we disabled the update. ready for retest

**Comment by ABonomo21** [comment]
![image](https://user-images.githubusercontent.com/47611580/73283594-580d9480-41c1-11ea-824e-f63e9a1da3c8.png)


unable to edit details
