### ISSUE TITLE
Smart Phone Attachments 

### ISSUE THREAD

**Issue by ABonomo21** [dhenry-KCI/FredCo-Post-Go-Live-#303]
Attachments are viable and editable from a IPhone and Android 
![image](https://user-images.githubusercontent.com/47611580/73278358-7a031900-41b9-11ea-849f-9f9ee9522a37.png)

however, you cannot open them

![image](https://user-images.githubusercontent.com/47611580/73278528-b898d380-41b9-11ea-837a-ca3e4b57bea2.png)

**Comment by JuanitaMiles** [comment]
IPS TEST Upgrade issue.

**Comment by megisys** [comment]
Can you download them ?

**Comment by ABonomo21** [comment]
![image](https://user-images.githubusercontent.com/47611580/73279690-82f4ea00-41bb-11ea-8cdf-ad4992394635.png)


no i am not able to download from apple or android.

**Comment by megisys** [comment]
This is correct behavior as per Mark call. In a future release you will be able to download. Can you edit from a phone ??

**Comment by megisys** [comment]
Please do not mark anything from Test as High Priority. This is  linked to the SLA. It is High importance to the upgrade, but this issue is not impacting County Business Processes currently

**Comment by ABonomo21** [comment]
Future Release- Juanita can you add to another Repository? @JuanitaMiles
