### ISSUE TITLE
Building Permits - Grading Permits - Inspection Report "Violation Date" Field Name

### ISSUE THREAD

**Issue by JuanitaMiles** [dhenry-KCI/FredCo-Post-Go-Live-#304]
Issue reported by Eric Dodson.

The "Violation Date" field name on the inspection reports appears to be misleading as this field is just showing the inspection date. It seems these reports are used for Passed inspection results as well, so can we change the Violation Date field name to "Inspection Date:"

Report examples below:
[Arcadia Business Park Lot 5 1-24-20 (1).pdf](https://github.com/dhenry-KCI/FredCo-Post-Go-Live-/files/4123154/Arcadia.Business.Park.Lot.5.1-24-20.1.pdf)
[Bush Creek 1-9-20 (2).pdf](https://github.com/dhenry-KCI/FredCo-Post-Go-Live-/files/4123158/Bush.Creek.1-9-20.2.pdf)

**Comment by TaraF** [comment]
Assigned, in progress.

**Comment by TaraF** [comment]
Updated, ready for re-test (Prod).

**Comment by JuanitaMiles** [comment]
Appears fixed based on attachment Eric sent via email on 1/31/20. Closing
![image](https://user-images.githubusercontent.com/31770504/73761748-425a1b00-473d-11ea-94df-dccf9fb62bfc.png)
