### ISSUE TITLE
R4C- Test upgrade - Create new link

### ISSUE THREAD

**Issue by ABonomo21** [dhenry-KCI/FredCo-Post-Go-Live-#305]
Able to create links on R4C that relate other records in the back office, this could get very messy we need to disable this function on r4c.

**Comment by ABonomo21** [comment]
![image](https://user-images.githubusercontent.com/47611580/73280042-f7c82400-41bb-11ea-8159-beb7fcac9566.png)

**Comment by ABonomo21** [comment]
test permit 259419

![image](https://user-images.githubusercontent.com/47611580/73280505-9d7b9300-41bc-11ea-8276-69d9403484db.png)

applicant was able to delete the spawned capacity and add a paid completed capacity from R4C

![image](https://user-images.githubusercontent.com/47611580/73280578-bd12bb80-41bc-11ea-87a9-836b0872250e.png)

**Comment by megisys** [comment]
You can do this now in Production too.

**Comment by megisys** [comment]
Please Investigate here

**Comment by ABonomo21** [comment]
You can do this now but it is very bad when applicants can do it, as discussed :)

**Comment by megisys** [comment]
Need to set-up Meeting with Mark Oliver to talk about what the County would like to see here.

**Comment by megisys** [comment]
Juanita,

Can you find a couple of dates next week for Ashlye to meet with myself and Mark Oliver.

**Comment by JuanitaMiles** [comment]
Will follow up with Dustin as he is helping me coordinate sessions with outside stakeholders.

**Comment by ABonomo21** [comment]
Discussed with Dan and Christian yesterday - turned off the function on the portal for applicants to view related records due to the fact that applicants can delete and create new links to related records which could be problematic for both planning and permitting applications. Dan and Christian to work on a fix @JuanitaMiles

**Comment by megisys** [comment]
Awaiting Devleopment

**Comment by JuanitaMiles** [comment]
Appears a temporary work around is in place. Closing and tracking as an enhancement to limit related record functionality on R4C.
