### ISSUE TITLE
Resbldg - Capacity Permit did not generate - - Test 

### ISSUE THREAD

**Issue by ABonomo21** [dhenry-KCI/FredCo-Post-Go-Live-#306]
A capacity permit did not spawn on a resbldg permit on public

![image](https://user-images.githubusercontent.com/47611580/73282915-5099bb80-41c0-11ea-91d2-6edab5677d8f.png)

**Comment by megisys** [comment]
BP_CreateCapacityPermitasChild - Updated to allow for duplicate Parcels on an address
