### ISSUE TITLE
Business License - Liquor License - New "Arena" License Class

### ISSUE THREAD

**Issue by JuanitaMiles** [dhenry-KCI/FredCo-Post-Go-Live-#308]
Liquor Board staff has requested that a new License Class of "CLASS A -B ARENA" be added to the options on the License Class field on the detail page. This license class should add the Arena fee automatically. Ashley K has cited state law requirement that this license class should be listed on the printed license for Arenas.

A follow up meeting may be required to ensure all requirements surrounding fees, endorsements, etc are documented properly when implementing. 

Emails were sent 1/28/20 to Christian/Juanita/Tara/Jeff W/Dustin regarding this request.

**Comment by JuanitaMiles** [comment]
Awaiting Dustin to setup requirements session for Christian to discuss with Liquor Board

**Comment by JuanitaMiles** [comment]
Juanita met with Liquor Board on 2/19/20 without Infor in attendance to gather as much information as possible surrounding these requests. Next steps will be for Infor to provide a level of effort to complete. Documentation attached below.

[LiquorBoard_Requirements 2.19.20.docx](https://github.com/dhenry-KCI/FredCo-Post-Go-Live-/files/4233300/LiquorBoard_Requirements.2.19.20.docx)

**Comment by ABonomo21** [comment]
moved to the future phase repository for phase 2 - set up a meeting with the LB to discuss
