### ISSUE TITLE
Business License - Liquor License - Arena Fee Value Incorrect

### ISSUE THREAD

**Issue by JuanitaMiles** [dhenry-KCI/FredCo-Post-Go-Live-#309]
Ashley K has identified that the value of the ARENA PERMIT fee is incorrect. It is currently at a value of $1.00. The value should be updated to be  $1,500.00.

![image](https://user-images.githubusercontent.com/31770504/73307996-4cd05e00-41ed-11ea-9b53-c3f12032de9b.png)

**Comment by pooldaddy** [comment]
Changed in TEST
![image](https://user-images.githubusercontent.com/47391482/73364290-50f58d80-4278-11ea-9f74-e6f7ecc61a24.png)

**Comment by JuanitaMiles** [comment]
Requested Ashley K to test.

**Comment by pooldaddy** [comment]
Changed rate in PROD
![image](https://user-images.githubusercontent.com/47391482/73471108-d9e2f680-4356-11ea-88a5-6e4f54ebb413.png)

@calequin  to verify

**Comment by calequin** [comment]
@pooldaddy looks good

**Comment by JuanitaMiles** [comment]
marking as "deployed to production" and closing.
