### ISSUE TITLE
Building Permits - Capacity - Update "Preserve" Subdivision Description

### ISSUE THREAD

**Issue by JuanitaMiles** [dhenry-KCI/FredCo-Post-Go-Live-#31]
Please update the description of subdivision code 061172 to read:

Preserves @ Long Branch

![image](https://user-images.githubusercontent.com/31770504/71009684-a276fe00-20b8-11ea-8411-c04d83f5670e.png)

![image](https://user-images.githubusercontent.com/31770504/71009718-b1f64700-20b8-11ea-9c1f-0a7d8c8aeafb.png)

**Comment by megisys** [comment]
No @ Symbols
