### ISSUE TITLE
Business License - Liquor License - License Template Updates

### ISSUE THREAD

**Issue by JuanitaMiles** [dhenry-KCI/FredCo-Post-Go-Live-#310]
Ashley K has identified a number of changes that are needed on the license templates. Copying her comments and example attachments below:

**Arena License**
We need a Class B-A after looking into state law, this is the class that needs to be listed on the license for Arenas.  As it states on the attachment, the wording in the first paragraph needs to be:

“is licensed by the STATE OF MARYLAND to sell BEER and WINE at retail, at one or more outlets on campus of the described Institution for on premises consumption only.”

**Barber Shop License**
Attached is the license for Barber Shop license.  There are two licenses in this document.  The first license is from Hansen 7, the wording is 100% correct and needs to reflect on the template that IPS is using.  Please note the hours are also wrong on the IPS template but correct on the license from Hansen 7.

**DBR License**
The first paragraph on the license generated by IPS is incorrect.  The Hansen 7 license is correct.  In this attachment, the Hansen 7 license is the second license in the document, please use it to correct the license template for IPS.

**Distillery Permit**
We talked some time ago about our Distilleries and them being a Permit and not a license.  I think it is something you said that will be addressed in “phase 2”.                We have processed 2 of our distilleries and noticed there isn’t a license category listed on the license because.  Is it possible to add a code under License Category for Liquor Only so it will print on the license?  And the endorsement for Distillery Tasting Room should have “Permit” at the end of it as this is a permit and not a license.  In the attachment, please see the Hansen 7 license (listed first in the document) for the correct verbiage.  

**Hotel Lobby License**
The Hansen 7 license is listed 2nd on this attachment and the wording is 100% correct.  Please update the IPS template for Hotel Lobby (listed 1st in this document)

**Stadium License**
We have not entered this one but we know the template is going to be incorrect.  Please use the attached Hansen 7 license to update the IPS Template.

[Arena License.pdf](https://github.com/dhenry-KCI/FredCo-Post-Go-Live-/files/4124782/Arena.License.pdf)
[Barber Shop License.pdf](https://github.com/dhenry-KCI/FredCo-Post-Go-Live-/files/4124784/Barber.Shop.License.pdf)
[DBR.pdf](https://github.com/dhenry-KCI/FredCo-Post-Go-Live-/files/4124788/DBR.pdf)
[Distillery Permit.pdf](https://github.com/dhenry-KCI/FredCo-Post-Go-Live-/files/4124791/Distillery.Permit.pdf)
[Hotel Lobby.pdf](https://github.com/dhenry-KCI/FredCo-Post-Go-Live-/files/4124794/Hotel.Lobby.pdf)
[Stadium.pdf](https://github.com/dhenry-KCI/FredCo-Post-Go-Live-/files/4124795/Stadium.pdf)

**Comment by TaraF** [comment]
Requested meeting for clarification.  Dustin will set up appointment time.

**Comment by TaraF** [comment]
Notes from meeting 2/3/20
Classes:
A - wording needs to be fixed based on example provided
B - wording needs to be fixed based on example provided
        Endorsement changes:
                          - Arena - based on wording on example provided
C -  (ex: 258520) - wording needs to be fixed based on examples provided
      -Endorsements:  
                   -Cultural Arts is changing to "Theatre", the language also changes in body
                   -Performance Art language is also slightly different (see example, almost same as Theatre)
DBR - no endorsements drive it, just fix the main wording based on the example provided
O - this wording needs to change per endorsement type:
              Endorsements:
                                  -Distillery Tasting Room - changes the wording see example provided
                                  -Barbershop - see example provided 
                                  -Stadium - see example provided
                                  -Hotel Lobby - see example provided
   
Rules to follow will be class/ endorsement type combo to drive it and if multiple the first endorsement wins.

**Comment by TaraF** [comment]
Updated and ready for testing in Test.  Email was sent to the LB team 2/25/20.

**Comment by JuanitaMiles** [comment]
Liquor Board has provided one minor comment. I have confirmed with Tara that the refresh planned to take place on Monday 3/2 will not impact these report changes. These can be promoted to production at a later time.

**Comment by JuanitaMiles** [comment]
Email from Dawn S below:

![image](https://user-images.githubusercontent.com/31770504/75586244-ecc61500-5a41-11ea-980c-648163b35ade.png)

**Comment by TaraF** [comment]
Assigned, in progress.

https://github.com/kcigeospatial/fredCo_landMgt/issues/49

**Comment by TaraF** [comment]
Ready for re-test.  Stakeholders have been emailed.

**Comment by JuanitaMiles** [comment]
@TaraF I believe Dawn has provided confirmation that this wording issue has been accepted. Email snippet below. Marking as Test Accepted and assigning to Tara for any promotion to production needs. Once promoted, please close ticket.

![image](https://user-images.githubusercontent.com/31770504/76975985-ac074080-6909-11ea-97ba-af1c7608917d.png)
