### ISSUE TITLE
Business License - Liquor License - License Report State Not Printing

### ISSUE THREAD

**Issue by JuanitaMiles** [dhenry-KCI/FredCo-Post-Go-Live-#311]
Dawn Shuggars identified that the "MD" state is not appearing on the printed license report. License # and address used are in the screenshot.

![image](https://user-images.githubusercontent.com/31770504/73312956-f7e61500-41f7-11ea-9e3b-81987bdd16e6.png)

**Comment by TaraF** [comment]
Assigned, in progress.

**Comment by TaraF** [comment]
Ready for re-test (in Prod).

**Comment by JuanitaMiles** [comment]
Dawn S has confirm fixed. Closing.
