### ISSUE TITLE
Notifications Not Sending on Hansen7 Permits

### ISSUE THREAD

**Issue by mlibbey131** [dhenry-KCI/FredCo-Post-Go-Live-#313]
Permit# 205266 and 205267 
Notifications not sending on these permits, applicants are receiving notification on others.
I have also heard from a couple other contractors that this is happening too. When I check the contacts the permits that are receiving notifications have the same contacts as the ones that are not. If they created them in Hansen 7 are they not receiving notification now? 

![image](https://user-images.githubusercontent.com/58980189/73357061-a7a79b00-4269-11ea-86f0-6415f4760fdc.png)

**Comment by megisys** [comment]
It hasnt moved anywhere for Notifications. It has been in Inspection Milestone since we went live.

DAn
