### ISSUE TITLE
Hold Letter not showing reviewer comments

### ISSUE THREAD

**Issue by awhite806** [dhenry-KCI/FredCo-Post-Go-Live-#314]
Permit 258890-The reviewer comments are showing under the review but they are not generating on the letter that is sent to the customer
[258890 hold letter.pdf](https://github.com/dhenry-KCI/FredCo-Post-Go-Live-/files/4128072/258890.hold.letter.pdf)
![image](https://user-images.githubusercontent.com/58981029/73359030-e8a1ae80-426d-11ea-9573-55048900009d.png)

**Comment by TaraF** [comment]
Assigned and investigating issue.

**Comment by TaraF** [comment]
Please note that the criteria for this report was to only show comments when the RESULT was set to 'DENIED'.  Based on this issue, we have updated that to include RESULT with'DENIED or 'RESUBMIT'.

Please review and test all cases to make sure this is the correct update for the report. Thanks!

Ready for re-test (in Prod).

**Comment by awhite806** [comment]
reopening-Home Occupation hold letter is not showing the reviewer comments.
![image](https://user-images.githubusercontent.com/58981029/74967456-01256480-53e7-11ea-8448-983aee0b5e8e.png)
[Use Permit - Hold Letter.pdf](https://github.com/dhenry-KCI/FredCo-Post-Go-Live-/files/4232442/Use.Permit.-.Hold.Letter.pdf)

**Comment by ABonomo21** [comment]
@TaraF - they just made it so the holds entered as logs become conditions, if your hold report is looking for a condition instead of a log it works but is it not capturing all of the holds, 

see hold report on permit in test 263374

![image](https://user-images.githubusercontent.com/47611580/75070702-ca704c80-54c1-11ea-8786-24f835e38871.png)
@JuanitaMiles

**Comment by TaraF** [comment]
@ABonomo21 - thanks, I have a few follow up questions:

1) Currently the logic is pulling from Conditions tab, with a Condition Type of "PIHOLD".  Should we continue to pull from the Conditions tab, or should we switch and pull from the Logs tab, where the log type is "PIHOLD"?

2) In Dec 2019, we were instructed to change the logic to only show PIHOLD values.  If that has changed, please provide the full list of Condition (or Log) types needed to be included on this report. 

3) Do the changes above also apply to the Use Hold Letter (which is a different report)?  

@awhite806 - we will also make the logic change to Use Hold Letter use you are asking for above ( to include RESULT with'DENIED or 'RESUBMIT') - like we did with the building hold letter.   

Thanks.

**Comment by ABonomo21** [comment]
See my comments below in bold 

Currently the logic is pulling from Conditions tab, with a Condition Type of "PIHOLD". Should we continue to pull from the Conditions tab, or should we switch and pull from the Logs tab, where the log type is "PIHOLD"?- **Now that the P&I and U&O holds are creating conditions you should continue to pull from the conditions tab.** 

In Dec 2019, we were instructed to change the logic to only show PIHOLD values. If that has changed, please provide the full list of Condition (or Log) types needed to be included on this report. **P&I and U&O holds should print on this report**

Do the changes above also apply to the Use Hold Letter (which is a different report)?
**The same rules should apply for use.** 

@awhite806 - we will also make the logic change to Use Hold Letter use you are asking for above ( to include RESULT with'DENIED or 'RESUBMIT') - like we did with the building hold letter.

**Tara just to confirm - is the hold letter also pulling those results that are denied or resubmit for building and use permits?** 

Thanks.

**Comment by TaraF** [comment]
Assigned, In progress.

**Comment by TaraF** [comment]
These updates have been made to Test.  Ready for re-test.

**Comment by ABonomo21** [comment]
![image](https://user-images.githubusercontent.com/47611580/76444683-b15d0c00-639a-11ea-883b-f5d7578a3ce6.png)

![image](https://user-images.githubusercontent.com/47611580/76444774-ce91da80-639a-11ea-9b31-27dc31da4cf6.png)
