### ISSUE TITLE
Planning-R4C-site plan-intake detail for number of building

### ISSUE THREAD

**Issue by MLWilkins** [dhenry-KCI/FredCo-Post-Go-Live-#315]
this should be "greater than 0".  otherwise it would be requiring 2 or more buildings.

![image](https://user-images.githubusercontent.com/50637067/73372016-8dc78180-4284-11ea-94c8-c83e35a89fab.png)

**Comment by MLWilkins** [comment]
above shot from test.  below from prod.  Both have same issue.

![image](https://user-images.githubusercontent.com/50637067/73373924-5f977100-4287-11ea-8407-9b24c1805435.png)

**Comment by MLWilkins** [comment]
the only change being requested is to change the note.  The system does accept a 1 already but the "greater than 1" note should be "greater than 0" to prevent confusion.

**Comment by calequin** [comment]
fixed in test and prod.

**Comment by MLWilkins** [comment]
tested in test. Closing ticket since it is noted this was fixed in Prod already.
