### ISSUE TITLE
R4C- Logs showing in the portal 

### ISSUE THREAD

**Issue by ABonomo21** [dhenry-KCI/FredCo-Post-Go-Live-#316]
Logs should not show in the R4C portal. This is turned off in the current system but they are on in test. Can you turn them off please?

**Comment by calequin** [comment]
removed from test site

**Comment by ABonomo21** [comment]
![image](https://user-images.githubusercontent.com/47611580/73386122-549b0b80-429c-11ea-8310-e2264433995f.png)

**Comment by calequin** [comment]
promoted to prod 2.1.2020
