### ISSUE TITLE
R4C - Look Up Record

### ISSUE THREAD

**Issue by ABonomo21** [dhenry-KCI/FredCo-Post-Go-Live-#318]
in lookup record, ID 201607, Electrical permit - click view details, it takes you to the log in screen and you cannot look up while logged in or it logs you out

![image](https://user-images.githubusercontent.com/47611580/73385689-95deeb80-429b-11ea-9625-7f27569d669e.png)

**Comment by calequin** [comment]
Fixed:
Chnged home screen to record details on portlet config
![B0DB8CD9-B03A-4DAF-9958-52478DF9CC05](https://user-images.githubusercontent.com/47603568/73387139-b310bb80-4295-11ea-8143-b9781c19517f.jpeg)

**Comment by ABonomo21** [comment]
Seems to be working :)
![image](https://user-images.githubusercontent.com/47611580/73564238-20a32000-442d-11ea-8136-f0661047a6fc.png)

**Comment by calequin** [comment]
promoted to prod 2.1.2020
