### ISSUE TITLE
Guarantee Release Inspection - On Demand 

### ISSUE THREAD

**Issue by emilypearl1** [dhenry-KCI/FredCo-Post-Go-Live-#319]
The guarantee release inspection is printing out with coding.

![image](https://user-images.githubusercontent.com/58855801/73465115-e6af1c80-434d-11ea-8203-3ffdecab6be7.png)

1/30/20 EP

**Comment by TaraF** [comment]
Assigned, in progress.

**Comment by TaraF** [comment]
@emilypearl1 , @JuanitaMiles  Updated, ready for re-test (in Prod).

**Comment by emilypearl1** [comment]
perfect!!
