### ISSUE TITLE
Building Permits - Capacity - Preserves @ Long Branch Subdivision Fees

### ISSUE THREAD

**Issue by JuanitaMiles** [dhenry-KCI/FredCo-Post-Go-Live-#32]
CAPACITY - RESIDENTIAL SINGLE FAMILY DWELLING
AP # 258313

The Preserves @ Long Branch subdivision code 061172 needs to automatically add the RESIDENTIAL WATER FEE 11900 ($5380.00) and RESIDENTIAL SEWER FEE 20600 ($7509.00) when it is a residential occupancy type.

Terry manually added these fees to the application in PROD.

![image](https://user-images.githubusercontent.com/31770504/71010087-54aec580-20b9-11ea-9545-f83eb1dcebbf.png)

![image](https://user-images.githubusercontent.com/31770504/71010153-698b5900-20b9-11ea-8ba2-431bf0d2d8e4.png)

**Comment by megisys** [comment]
Migrate CAPACITY_ResWater11900_Fee_AOC and CAPACITY_ResSewer20600_Fee_AOC

**Comment by ScottVanSooy** [comment]
Promoted to Production 12/17/2019 8:30 PM
