### ISSUE TITLE
Building Permits - Mobile Code Violations Missing

### ISSUE THREAD

**Issue by JuanitaMiles** [dhenry-KCI/FredCo-Post-Go-Live-#323]
Bob Ensor has identified an issue where it appears that electrical code violations appear on some permits but are missing on others. An example of this in the screenshots below.

![image](https://user-images.githubusercontent.com/31770504/73554289-753ca000-4419-11ea-9a85-be78920861dd.png)

![image](https://user-images.githubusercontent.com/31770504/73554320-82598f00-4419-11ea-975c-867c7de9e1b9.png)

**Comment by calequin** [comment]
UPDATE: researching our current configuration of 100 visible on the mobile page and testing out a possible download of all violations when sychronizing in the mornings.

**Comment by calequin** [comment]
should we have all code violations download in the morning on the inspector profile?

**Comment by TheBobEnsor** [comment]
I would like all violation downloaded, however that may lead to long load time due to the fact that fire violations are in the 1200 count range 
I think we need to look at moving OLS out of fire and into their own violation data base?
??

**Comment by calequin** [comment]
reaching out to Rick M which level of effort and availability

**Comment by calequin** [comment]
Infor Xtreme ticket has been created 14355465

**Comment by calequin** [comment]
follow up sent to support for an update.

**Comment by ABonomo21** [comment]
@megisys is this another one that was to be addressed with the patch?

**Comment by calequin** [comment]
@ABonomo21 yes also should have been addressed in the 11.2.2003 update
