### ISSUE TITLE
Building Permits - Capacity Permit - U&O Fee Should Not Add on NonRes Permits

### ISSUE THREAD

**Issue by JuanitaMiles** [dhenry-KCI/FredCo-Post-Go-Live-#324]
The U&O fee is currently configured to automatically add on applications with select subdivision codes regardless of the Occupancy Type. Lauren Englar has indicated that the U&O fee should only generate for the Residential occupancy types and should not generate for the NonResidential occupancy types.

![image](https://user-images.githubusercontent.com/31770504/73559428-006e6380-4423-11ea-9250-bd16ed47ac4c.png)

**Comment by calequin** [comment]
fixed in test. only allowing Fee - U AND O FEE on Res occupancy types. Once accepted please promote

CAPACITY_UOFEE_AOC

**Comment by JuanitaMiles** [comment]
Tested by group adding the application above with a NonRes Occupancy type and no U&O fee added. Then tested with a Res Occupancy Type, and the U&O fee added. Marking as Test Accepted.
![image](https://user-images.githubusercontent.com/31770504/74189132-dafd0900-4c1d-11ea-9499-6fcd3f45bdc9.png)
![image](https://user-images.githubusercontent.com/31770504/74189108-cfa9dd80-4c1d-11ea-9cfc-64d50e7f46df.png)

![image](https://user-images.githubusercontent.com/31770504/74189170-ed774280-4c1d-11ea-9863-86bc501086cd.png)
![image](https://user-images.githubusercontent.com/31770504/74189191-f700aa80-4c1d-11ea-8e10-390bbbe81101.png)

**Comment by calequin** [comment]
promoted on 2.16.2020
