### ISSUE TITLE
Building Permits - Inspections Configuration Matrix - ELECTRICAL PERMIT

### ISSUE THREAD

**Issue by JuanitaMiles** [dhenry-KCI/FredCo-Post-Go-Live-#325]
Bob will generate a matrix that will contain the rules for when inspections should be generating.

**Awaiting matrix to be completed for Infor to configure.

**Comment by ABonomo21** [comment]
can we assign this to bob @JuanitaMiles

**Comment by JuanitaMiles** [comment]
See email from 2/7 1:47pm. Dustin will need to add bob to the repository when he creates his account, then I will assign all inspection issues to bob.

**Comment by JuanitaMiles** [comment]
[Inspections to generate.xlsx](https://github.com/dhenry-KCI/FredCo-Post-Go-Live-/files/4199449/Inspections.to.generate.xlsx)

![image](https://user-images.githubusercontent.com/31770504/74455357-3106c200-4e53-11ea-9cf4-45a5882e6df0.png)

**Comment by ABonomo21** [comment]
Would like to set up a meeting with Dan when he is on site next to work through the inspections that were in air table and look at the coding in the system, this could be a full day task - should be Ashlye, Jeff and Bob. @dhenry-KCI @JuanitaMiles - okay per meeting with Ashlye, Gary and Juanita 3.4.2020

**Comment by megisys** [comment]
Removing Appril 11th Release. as Pushed

**Comment by ABonomo21** [comment]
Adding Grading inspection information on to this ticket per email on 4.13.20

2a. For those minor grading permits related to a SFD located in a rural area - not within a subdivision, there needs to be a pre-con inspection performed to ensure those sediment erosion control measures are in place. 
Can someone review the code to let me know if that inspection type is available to generate? It is not currently generating. See example # 267912. 

2b. At the time of building final the SFD, the building inspectors need to also perform the substantial completion inspection for the minor grading permit to ensure the site is stabilized.  Would it be possible to set up the system to automatically schedule the ECS-SUBCOM inspection when the building final is request for those MN permits related to a SFD app not within a Major Subdivision (defined by the S-code in the Parcel details)?

**Comment by JuanitaMiles** [comment]
Initial Electrical Permit Inspection Matrix. We will use this as our pilot to complete the initial configuration, and testing. If there are any clarifications needed from the attached spreadsheet, we can make adjustments to the format/details as needed.

[Inspections_Matrix_v2.xlsx](https://github.com/dhenry-KCI/FredCo-Post-Go-Live-/files/4518684/Inspections_Matrix_v2.xlsx)

**Comment by megisys** [comment]
Ready for Test in Test. See Code Definition Management Under Shared for the set-up here.

**Comment by JuanitaMiles** [comment]
@megisys I feel you'll need to review the work that has been done in test in comparison to the matrix we've provided. I tested 5 residential electrical detail types and 3 of those did not generate the inspections that were indicated in the matrix. The 5 applications are as follows:

CONSTSERV - 278179 (initial inspection generated correctly)
ALTADDACC - 278180 (initial inspections did not generate correctly)
DEMO - 278181 (initial inspections did not generate correctly)
HEAVYUP - 278182 (initial inspection generated correctly)
INPOOL - 278183 (initial inspections did not generate correctly)

From looking into the configuration, if we take INPOOL as an example:

- The spreadsheet said a Residential INPOOL with a work type other than REAPFL should have a ELEC-BOND, ELEC-TRNCH & ELEC-POOL. 

- However, when I look at the Code Definition table, INPOOL is defined to add ELEC-DECK, ELEC-BOND & ELEC-UNDGR. These seem like the old configuration inspections that generated? 

![image](https://user-images.githubusercontent.com/31770504/82604408-455d0800-9b82-11ea-83d0-c5d22d1ba2c0.png)

- ELEC-POOL and ELEC-TRNCH do not appear to have been included in the Code Definition table at all, and are also no longer associated to the Inspections milestone on ELECPERM. I can also see that the AOC on the general inspections list for ELECPERM has the old formula still attached.
![image](https://user-images.githubusercontent.com/31770504/82605455-f617d700-9b83-11ea-89fb-fa7f3299cbed.png)
![image](https://user-images.githubusercontent.com/31770504/82606200-b0a7d980-9b84-11ea-8d52-ce36837875f4.png)

Before I have the county perform extensive testing, I'll need some clarification or confirmation that proper QC has been completed on the configuration.

**Comment by megisys** [comment]
@JuanitaMiles - Those inspections are not in the matirx document and also there is no work type break down in this spreadsheet.. Where are you seeing that 
![image](https://user-images.githubusercontent.com/47392306/82666758-88f85600-9c04-11ea-97e1-8a7e7baf6b53.png)

**Comment by megisys** [comment]
@JuanitaMiles - I was looking at the original spreahseet and sent this to David Lucier as the target. This is my fault.. Let me re adjust

**Comment by JuanitaMiles** [comment]
Retested the 5 applications I previously tested above and we've taken a step backward. Now inspections are not generating correctly for ANY of the applications below:

CONSTSERV - 278187 (Inspections did not generate correctly per matrix.)
ALTADDACC - 278186 (Inspections did not generate correctly per matrix.)
DEMO - 278188 (Inspections did not generate correctly per matrix.)
HEAVYUP - 278189 (Inspections did not generate correctly per matrix.)
INPOOL - 278190 (Inspections did not generate correctly per matrix.)

Each application has the same five inspections generating, and the INPOOL has an additional two inspections because I called it out as an example above.

**Comment by megisys** [comment]
Coding error was adjusted.

**Comment by JuanitaMiles** [comment]
**Residential, Work Type <>REAPFL:**

- Tested 9 electrical detail types and all PASSED on both initial inspections and final inspections. Will continue to test additional types as time allows. (278215, 278214, 278216, 278217, 278219, 278218, 278222, 278220, 278221)

**Residential, Work Type = REAPFL:**

- Tested 2 electrical detail types and each PASSED. Final inspection only generated as expected. Will continue to test additional types as time allows.(278223, 278224)

**Comment by JuanitaMiles** [comment]
I discovered an oversight on our part of 5 nonres electrical detail types didn't have the ELEC-FINAL inspection checked off. Confirmed with Ashlye, all types should have a final inspection. I have amended the spreadsheet and have attached version 2.1 below. Sorry Dan.
[Inspections_Matrix_v2.1.xlsx](https://github.com/dhenry-KCI/FredCo-Post-Go-Live-/files/4703300/Inspections_Matrix_v2.1.xlsx)

**NonResidential, Work Type <>REAPFL:**

- Tested 4 electrical detail types:
1) DEMO 278225 - Failed. After fees were paid, the application went straight to closed. This type DID have final inspection marked in the matrix.
2) HEATAC 278227 - Passed for initial inspections. This detail was missing the final inspection marked off but will need the final per amendment to the spreadsheet.
3) LOWV 278228 - Passed for initial inspections. Failed for final. Was marked off in matrix but application progressed to closed after initial inspections were passed.
4) POOL 278229 - Passed for initial inspections. Failed for final. Was marked off in matrix but application progressed to closed after initial inspections were passed.

**The final inspection not generating appears it will be a consistent issue for all detail types. Please ensure that issue gets fixed overall for NonRes.

**Comment by megisys** [comment]
Adjustments made by Dave Lucier

**Comment by JuanitaMiles** [comment]
NonRes - DEMO - 278230 -  No Change. Still went straight to closed with no final inspection generating.
NonRes - HEATAC - 278231 - No change. Passed on initial inspections, but did not generate a final inspection.
NonRes - LOWV - 278232 - No change. Passed on initial inspections, but did not generate a final inspection.
 NonRes - POOL - 278233 - No change. Passed on initial inspections, but did not generate a final inspection.

**Comment by megisys** [comment]
Hi Juanita,

Please Retest.. CHanges were made

**Comment by JuanitaMiles** [comment]
All applications and scenarios I have tested for electrical have now passed. I am now generally comfortable with the new electrical inspection configuration. I will however, continue to test the other electrical detail types to confirm they all work as expected.

I will meet with Ashlye and Bob to determine the next application type to undergo configuration and thorough testing. ResUse was due to be next in the queue.

I am also dedicating this ticket to ELECTRICAL ONLY. I will open a new ticket as we begin each new AP Type. This will allow for easier tracking of each AP and potential issues with the staggered implementation to production. 
 
**NonResidential, Work Type <>REAPFL:**
DEMO - 278236 - Passed. Stopped in final inspection.
HEATAC - 278237 - Passed on initial and final inspections.
LOWV - 278238 - Passed on initial and final inspections.
POOL - 278239 - Passed on initial and final inspections.
HEATAC & LOWV - 278240 - Confirmed if multiple elec detail types that required the same inspection types, duplicate inspections do not generate.

**NonResidential, Work Type = REAPFL:**
POOL - 278241 - Passed. Generated final inspection only.
LOWV - 278242 - Passed. Generated final inspection only.

**Comment by JuanitaMiles** [comment]
Marking as test accepted. Continued testing of the remaining electrical types will be ongoing, but we feel comfortable enough to promote the electrical configuration. 

Please ensure any configuration done on Plumbing does not get promoted as we did not provide any documentation for the required inspections and no testing was completed.

![image](https://user-images.githubusercontent.com/31770504/83899145-eec8ff80-a725-11ea-8131-546ac49c1c21.png)

**Comment by JuanitaMiles** [comment]
Once promoted this ticket can be closed. A new ticket will be created for the next AP type to be configured. This ticket will be reopened for any electrical permit inspection related issues only.

**Comment by megisys** [comment]
@JuanitaMiles, We did this based off the formulas.  I will ensure it is not put into place.

**Comment by JuanitaMiles** [comment]
@megisys FYI upon further testing, we get this error when trying to result the Completeness Check review on the following permit in TEST. It looks like a .dll error message so I would assume this would be addressed upon syncing the environment, but want to bring to your attention as you look to promote tickets this weekend.
NONRES - REAPFL
PNECIRC AP#278284

![image](https://user-images.githubusercontent.com/31770504/85913061-81c5f880-b7ff-11ea-85cb-47bee5c68981.png)

**Comment by megisys** [comment]
@JuanitaMiles - Above issue is about a fee calculation and nothing to do with this piece. I checked the fomula. Will need to debug more
