### ISSUE TITLE
Building Permits - Capacity Report - DBA Field Issue

### ISSUE THREAD

**Issue by JuanitaMiles** [dhenry-KCI/FredCo-Post-Go-Live-#326]
Copying text straight from email sent from Lauren Englar. (1/31/20 8:50 AM)

Tara,

Here is an example.  Why is is pulling some DBA and not others.  All residential should also be filled in, the whole column should be filled

![image](https://user-images.githubusercontent.com/31770504/73572197-34a34d80-443e-11ea-9bf7-0c9cc710e5dc.png)

**Comment by TaraF** [comment]
Updated, along with Lauren's latest request for Business class showing the coded value.  Ready for re-test in Prod.

**Comment by JuanitaMiles** [comment]
emailed lauren for confirmation 2/10/20 4:05pm

**Comment by JuanitaMiles** [comment]
Requested confirmation of fix from DUSWM twice and have received no response. Closing ticket. Fixes appear to be made in Prod so no migration is needed.
