### ISSUE TITLE
Building Permits - Notifications Sending to IPS User 

### ISSUE THREAD

**Issue by JuanitaMiles** [dhenry-KCI/FredCo-Post-Go-Live-#327]
IPS notifications are sending to the County IPS users rather than applicants. Leslie Paretti asked for a resubmit and pushed an application to awaiting fee payment and she got all of these emails.

![image](https://user-images.githubusercontent.com/31770504/73656301-d8b70f80-465d-11ea-830e-9d736112c4d0.png)

![image](https://user-images.githubusercontent.com/31770504/73656318-e40a3b00-465d-11ea-8e57-1368e7392021.png)

![image](https://user-images.githubusercontent.com/31770504/73656346-ef5d6680-465d-11ea-90b7-9265e1c7c85b.png)

![image](https://user-images.githubusercontent.com/31770504/73656372-f97f6500-465d-11ea-9c8e-e8469186233a.png)

**Comment by megisys** [comment]
Due to the nature of this issue.. Some Users may have experienced Rhtyhm Issues for a space of 2 minutes. This is far from optimal. But couldn't wait until end of day

**Comment by megisys** [comment]
Send Notifications to be promoted..  Monitored Inbox going to Users for Building Applications

**Comment by JuanitaMiles** [comment]
This is still an issue. Received an email from Dan Lewis in treasury indicating that the cashiers are getting the emails for permit issuance after fees are paid. I've checked the permit in question and the Primary applicant has a valid email address and has received emails from the system in the past but the notification did not send to the applicant. All three notifications went to Jyothi in treasury.

![image](https://user-images.githubusercontent.com/31770504/73678710-ee8cfa80-4686-11ea-8ef1-ece81cf273f2.png)

![image](https://user-images.githubusercontent.com/31770504/73678745-fcdb1680-4686-11ea-99f2-a79d551fa520.png)

![image](https://user-images.githubusercontent.com/31770504/73678775-10867d00-4687-11ea-9fc8-cf95c95ed6ad.png)

**Comment by megisys** [comment]
See 258312

**Comment by JuanitaMiles** [comment]
Reopening. Emily received an email for an applicant that either had "noemail" in the email field or for one that had a blank email field (AP #258208). Matt Rowley/Abbie White also received emails because all of the applicants on his application have a blank email field (AP#201970).

It appears that applicants with valid emails are now receiving their notifications. Dan just needs to figure out the final piece of when the email field is blank.

**Comment by megisys** [comment]
@JuanitaMiles I cant see any notifications which send in error for 201970. Please advise

**Comment by JuanitaMiles** [comment]
The three highlighted show they were all sent to Abbie this morning.

![image](https://user-images.githubusercontent.com/31770504/73768688-72a6b700-4747-11ea-91a0-245cabe38ae6.png)

![image](https://user-images.githubusercontent.com/31770504/73768888-ca452280-4747-11ea-98ac-8190b9b95654.png)

![image](https://user-images.githubusercontent.com/31770504/73769020-024c6580-4748-11ea-8b1a-28f0a7806e2e.png)

**Comment by megisys** [comment]
This is no longer an issue

**Comment by JuanitaMiles** [comment]
This is an issue again as of 2/18 8:26AM. Reported by Terry May, screenshot below.

![image](https://user-images.githubusercontent.com/31770504/74741787-6c2a3c00-522b-11ea-84de-9c506fd8c3ba.png)

**Comment by JuanitaMiles** [comment]
Ticket 415 was created for this. closing as a duplicate.
