### ISSUE TITLE
PLANNING Reports - APFO School Test Fees

### ISSUE THREAD

**Issue by AReed327** [dhenry-KCI/FredCo-Post-Go-Live-#329]
Fees showing were refunded because they were paid on a voided application. I processed the refund overpayment on January 9th. This shouldn't be populating on the report.
A/P 19989
[January 2020 APFO School Test Fees.pdf](https://github.com/dhenry-KCI/FredCo-Post-Go-Live-/files/4148215/January.2020.APFO.School.Test.Fees.pdf)

![image](https://user-images.githubusercontent.com/58854333/73659052-74974a00-4663-11ea-8172-4c18b31c04a5.png)
My Log
![image](https://user-images.githubusercontent.com/58854333/73659078-811ba280-4663-11ea-99fb-78cb3199eea2.png)

**Comment by TaraF** [comment]
Assigned, in progress.

**Comment by TaraF** [comment]
@AReed327  - this ready to test (in Prod).  Please test other cases that you know of like this to verify.

**Comment by AReed327** [comment]
This information is still showing on the report in production and in test. 
![image](https://user-images.githubusercontent.com/58854333/74161106-6f4e7800-4bec-11ea-8485-8d88e55bdf01.png)
![image](https://user-images.githubusercontent.com/58854333/74161441-f0a60a80-4bec-11ea-8b1f-b7ea74a42822.png)

**Comment by TaraF** [comment]
Something got out of sync with the set up of test on Friday.  Requesting a redeploy for this report with the fixes, assigned.  Will update when available.

**Comment by TaraF** [comment]
@AReed327  - ready for re-test - this was deployed to both Prod and Test (because it happened prior to the test move).

**Comment by MLWilkins** [comment]
fixed in test and prod.


test
![image](https://user-images.githubusercontent.com/50637067/74440296-c1d1a380-4e3b-11ea-8f8b-47c4938ba13a.png)

Prod
![image](https://user-images.githubusercontent.com/50637067/74440386-ec236100-4e3b-11ea-86bd-fa5f6f02a03f.png)
