### ISSUE TITLE
Extensions marked as N/A 

### ISSUE THREAD

**Issue by emilypearl1** [dhenry-KCI/FredCo-Post-Go-Live-#33]
Extensions marked as N/A are sending out denial notifications

**Comment by ABonomo21** [comment]
![image](https://user-images.githubusercontent.com/47611580/71014062-57acb480-20bf-11ea-8ff0-a1365378451c.png)

**Comment by megisys** [comment]
BP_ExtensionReviewSetDateFee_BUF - Migrate to Production

**Comment by ScottVanSooy** [comment]
Promoted to Production 12/17/2019 8:30 PM
