### ISSUE TITLE
Building Extension Fee not generating

### ISSUE THREAD

**Issue by emilypearl1** [dhenry-KCI/FredCo-Post-Go-Live-#330]
169585 - extension fee not generate

![image](https://user-images.githubusercontent.com/58855801/73660876-0eacc180-4667-11ea-9bb1-fb6262b2bc50.png)
![image](https://user-images.githubusercontent.com/58855801/73660898-179d9300-4667-11ea-90e0-6aca4d94d898.png)
![image](https://user-images.githubusercontent.com/58855801/73660923-25ebaf00-4667-11ea-9aa8-f24fbf2f52f3.png)

**Comment by emilypearl1** [comment]
We have manually inserted the fee.

**Comment by megisys** [comment]
OK.. So many issues here. It is already Expired.. The fee doesn't add until after the review is resulted.

Please test in TEST to ensure you have the process right.

Dan

**Comment by emilypearl1** [comment]
Did the process change?

**Comment by megisys** [comment]
Yes

**Comment by megisys** [comment]
You need to have a request on a non expired application. Applicant requests the length of time.. It is then reviewed.. If approved.. Fee is added. Once paid.. the expired date will move..
