### ISSUE TITLE
Building Permits - Official Issuance Correspondence Sending Early and to IPS User

### ISSUE THREAD

**Issue by JuanitaMiles** [dhenry-KCI/FredCo-Post-Go-Live-#333]
Permits 263288 & 263289

Neither of these permits have reached the point of issuance yet but Ashlye and Abbie have received the correspondence email with the official issuance attachment. This should not send until permit issued.

In addition, this report is available in the on demand reports too early. It shouldn't be available until issuance.

Also the correspondence is sending to the IPS user similar to issue #327 

![image](https://user-images.githubusercontent.com/31770504/73670298-fba1ed80-4676-11ea-9400-7aec3c50710c.png)

![image](https://user-images.githubusercontent.com/31770504/73670328-09577300-4677-11ea-9ba8-0ca42655a733.png)

![image](https://user-images.githubusercontent.com/31770504/73670444-399f1180-4677-11ea-849f-1059c79bea1b.png)

**Comment by megisys** [comment]
You are confusing Production and TEST !!

DAn

**Comment by JuanitaMiles** [comment]
There is a real issue here...In the TEST environment Ashlye created permit 263288. Address is 5554 Hidden Waters Ln. AP Name: Subdivision Lot Number Property Owner.

She progressed this application to issued. Correspondence added the Official Issuance attachment to the application and sent to ABONOMO. However the correspondence is populated with permit information from permit 263288 in the PRODUCTION environment. The Production application has an 10384 Springside Terrace address, AP Name: Spring Hollow Holly Hills Lot 8 Wormald. The Production application has has not even reached issuance yet.

![image](https://user-images.githubusercontent.com/31770504/73682226-f308e180-468d-11ea-96f8-8f8d367b18a4.png)

![image](https://user-images.githubusercontent.com/31770504/73683500-57c53b80-4690-11ea-8f1e-c7b00de0ae53.png)
![image](https://user-images.githubusercontent.com/31770504/73682182-d5d41300-468d-11ea-8966-4b9434e282ca.png)
![image](https://user-images.githubusercontent.com/31770504/73682200-e3899880-468d-11ea-8e6c-fb4d42cdca08.png)

![image](https://user-images.githubusercontent.com/31770504/73682388-4c711080-468e-11ea-8d3b-320e177c05e5.png)

**Comment by JuanitaMiles** [comment]
Technically the correspondence ran as it was supposed to since reports only ever point to production data, but caused a panic as it was an outcome of this morning's public outreach training. We need KCI and County IIT to discuss the impacts of having multiple SSRS instances that point to test and prod.

Training sessions will continue be held regularly with the public moving forward and inaccurate data on the reports may cause confusion and a lack of confidence in the eyes of the public during these training sessions.

**Comment by JuanitaMiles** [comment]
Meeting scheduled for 2/5 1:00 PM to discuss this.

**Comment by JuanitaMiles** [comment]
@TaraF @pooldaddy Can either of you advise when the new Test ssrs environment has been setup so we can confirm and close this issue.

**Comment by TaraF** [comment]
@JuanitaMiles  - Dave D. is currently working on it.  Based on our discussions back and forth, it should be ready likely sometime tomorrow.  I will update this thread when it is complete, and also send out an email so everyone is aware.

**Comment by TaraF** [comment]
@JuanitaMiles  - the environment is up and working.  See email sent yesterday evening.

**Comment by JuanitaMiles** [comment]
confirmed many of the reports in TEST are running and with TEST data. Closing ticket.
