### ISSUE TITLE
Electrical Permit-Error message when check status

### ISSUE THREAD

**Issue by awhite806** [dhenry-KCI/FredCo-Post-Go-Live-#336]
when trying to check the status of this permit, Liz, Juanita, and myself are all getting the same error messages. Electrical permit 263334
![image](https://user-images.githubusercontent.com/58981029/73684936-2c901b80-4693-11ea-8df2-f5115c1b6340.png)
![image](https://user-images.githubusercontent.com/58981029/73684951-3580ed00-4693-11ea-8841-89ba7471d6a8.png)

**Comment by JuanitaMiles** [comment]
To be fixed when dan resolved issue #332
