### ISSUE TITLE
PLANNING  and Permitting- email type Attachments won't open

### ISSUE THREAD

**Issue by AReed327** [dhenry-KCI/FredCo-Post-Go-Live-#337]
Project Number - SP258790
Observed behavior - Attachment added but will not open. It will open when I upload it before saving, but will not open after saved. 
Expected behavior - I expect the added attachment to open
Screenshot - ![image](https://user-images.githubusercontent.com/58854333/73685798-cad0b100-4694-11ea-8c89-707d249d53bc.png)

**Comment by megisys** [comment]
This is an email. you dont want to open this..

**Comment by megisys** [comment]
Getting Clarification from County IT. Will update when i hear back from Rick LIttle

**Comment by ABonomo21** [comment]
I am unable to open email attachments as well and absolutely need this functionality as we have a number of permits and code enforcement cases with emails as attachments. 
![image](https://user-images.githubusercontent.com/47611580/73744724-60188780-471f-11ea-921e-e1120d7d580c.png)

**Comment by ABonomo21** [comment]
@JuanitaMiles - can you please make sure this gets addressed with someone.

**Comment by JuanitaMiles** [comment]
@pooldaddy Jeff, assigning this to you so you can follow up on County IIT allowing Emails to be attached and opened in IPS. This is something the county has utilized before would like to continue to do so. From Dan's comments above it looks like he contacted Rick Little about it. Please follow up with Rick.

**Comment by JuanitaMiles** [comment]
@calequin To look into the possibilities of allowing emails to be opened and attached to applications in back office only.

**Comment by megisys** [comment]
Still Awaiting Rick Little confirmation. Also did you check with Gary and he and I had a call on this yesterday. And he said t leave with him and he was the only one to give the go ahead on this.

Dan

**Comment by megisys** [comment]
Advice sent via email on how to open these attachments

**Comment by JuanitaMiles** [comment]
copying Gary's final comments with direction on path forward.

![image](https://user-images.githubusercontent.com/31770504/74055857-d2eb6200-49ae-11ea-9c23-8bf4108ec2a5.png)

**Comment by JuanitaMiles** [comment]
assigning to Dan as he indicated through email, he will make the change.

**Comment by ABonomo21** [comment]
We are not able open email attachments 193710

Checked other permits- Not able to view any email attachments in any module.

**Comment by pooldaddy** [comment]
@megisys works for pdf & jpg but not msg since 5/8 upgrade.  my guess is a setting to allow msg file types

**Comment by JuanitaMiles** [comment]
Found these old email instructions from Dan regarding opening existing email attachments and tried it on Ashlye's application above, but even this won't work because the description doesn't have the web address piece on it.

 
![image](https://user-images.githubusercontent.com/31770504/82366084-a13b5b80-99df-11ea-9057-efbfbc7c85bd.png)
![image](https://user-images.githubusercontent.com/31770504/82366108-ad271d80-99df-11ea-8380-cf498486ddd5.png)

**Comment by JuanitaMiles** [comment]
Dan working on getting a hot fix for this again. His update below:

![image](https://user-images.githubusercontent.com/31770504/82571011-58ef7b00-9b50-11ea-8e3c-288deac0855c.png)

**Comment by MLWilkins** [comment]
tested in test. Email attachments still wont open and now PDF attachments also will not open.  See SP260042 and SP260031 as examples

Also unable to add new attachments. See error below.
![image](https://user-images.githubusercontent.com/50637067/82667430-dc1ed880-9c05-11ea-969f-6c03bc461308.png)

**Comment by megisys** [comment]
Hi Mike,

This is my fault.. You can not add attachments or open attachments on new type records in test. As when we refresh we do not copy over the attachment catalogs. If you create a new application and add attachments, you will be able to test properly. Apologies for the lack of direction here

**Comment by MLWilkins** [comment]
@megisys Ashley Reed tried adding an attachment but got an error message.  See my comment above.
![image](https://user-images.githubusercontent.com/50637067/82672598-8c90da80-9c0e-11ea-9dc3-073ec62b20b4.png)

**Comment by AReed327** [comment]
attachment added on a new project and it worked. Also tested uploading and opening email and it worked.SP260052

![image](https://user-images.githubusercontent.com/58854333/82684549-c66adc80-9c20-11ea-9e93-6c2b3ef8b0e9.png)
