### ISSUE TITLE
PDOX Batch Job Is Not Running Automatically

### ISSUE THREAD

**Issue by JuanitaMiles** [dhenry-KCI/FredCo-Post-Go-Live-#338]
Project Dox Batch Task is not running automatically. It has not run since 2/3/20 8:39AM.

Need to fix this so it runs automatically every 5 minutes.

![image](https://user-images.githubusercontent.com/31770504/73692470-61f03580-46a2-11ea-85f5-510e14bab808.png)

**Comment by megisys** [comment]
Need to hand off to JEff. Running
