### ISSUE TITLE
Planning-in life projects showing up in portal

### ISSUE THREAD

**Issue by MLWilkins** [dhenry-KCI/FredCo-Post-Go-Live-#339]
In life projects are showing up in the portal. See 17812 as an example, where applicant was able to submit a withdraw request.  Planning notes that during serval conversations about this many months ago we did not want in-life projects showing in the portal. Giving applicants the ability to resubmit, pay fees (that may be 12+ years out of date), submit via the portal vs paper submission, etc on these project (many of which have expired) will lead to many problems that we wanted to avoid.

**Comment by megisys** [comment]
They will only show up if building permitting team. Add that applicant to a portal account for building permit purposes. You will need to talk with Ashlye B on this

**Comment by MLWilkins** [comment]
I don’t understand how Ashlye B is suppose to fix this?????
