### ISSUE TITLE
Business License - Liquor Board Changes (Endorsement/License Type)

### ISSUE THREAD

**Issue by JuanitaMiles** [dhenry-KCI/FredCo-Post-Go-Live-#341]
Copying email text directly from Ashley K below. A session is needed to discussed the full requirements surrounding these items.

Christian/Dustin;

After meeting with Tara today, we have a few changes that we would like

•	Due to law changes of July 2019, could you change the endorsement “Cultural Arts” to “Theatre”.
•	License Category we need to add a Liquor Only Option

**Comment by JuanitaMiles** [comment]
Awaiting Dustin to setup a meeting for Christian and Liquor Board to discuss full requirements.

**Comment by JuanitaMiles** [comment]
Juanita met with Liquor Board on 2/19/20 without Infor in attendance to gather as much information as possible surrounding these requests. Next steps will be for Infor to provide a level of effort to complete. Documentation attached below.

[LiquorBoard_Requirements 2.19.20.docx](https://github.com/dhenry-KCI/FredCo-Post-Go-Live-/files/4233306/LiquorBoard_Requirements.2.19.20.docx)

**Comment by ABonomo21** [comment]
Moving to the phase 2 repository - will set up a meeting with the LB to discuss when Juanita is on site next week. Okay per Meeting with gary and Ash 3.4.2020

**Comment by ABonomo21** [comment]
Closing in this repository - moved to future phases and sent meeting request to LB
