### ISSUE TITLE
Building Permits - Official Issuance Available Too Early

### ISSUE THREAD

**Issue by JuanitaMiles** [dhenry-KCI/FredCo-Post-Go-Live-#342]
Permit number 263288 is currently Awaiting Plan Review Payment and has not been issued, however the Building Permit - Official Issuance report is available on-demand for printing. 

Please update when this is made available per the rules outlined previously.

![image](https://user-images.githubusercontent.com/31770504/73773055-69b9e380-474f-11ea-9776-9d46f34b0405.png)

**Comment by TaraF** [comment]
@JuanitaMiles  please test this in TEST.  If confirmed, this will need to be pushed to prod by Infor - as a formula update on the On Demand report.

**Comment by JuanitaMiles** [comment]
@TaraF is there a specific formula name that Infor will look for to push to production once test accepted? If so please provide.

**Comment by TaraF** [comment]
The system generated formula name is AR_4:

![image](https://user-images.githubusercontent.com/4104464/74183446-f7e00f00-4c12-11ea-9f1b-e674b1e54558.png)

![image](https://user-images.githubusercontent.com/4104464/74183527-1ba35500-4c13-11ea-9139-1555964f3af2.png)

**Comment by ABonomo21** [comment]
looks fixed 
![image](https://user-images.githubusercontent.com/47611580/74370052-70c2a080-4da4-11ea-8270-4ba127fa72ed.png)

**Comment by calequin** [comment]
promoted on 2.16.2020
