### ISSUE TITLE
Planning-system generated mylar reviews on 100+ applications 

### ISSUE THREAD

**Issue by MLWilkins** [dhenry-KCI/FredCo-Post-Go-Live-#343]
On or about 1/4/20 the system generated 100+ mylar reviews, as shown in the report below.  They all have a due date of 1/11/20. This error needs to be corrected to eliminate all of these erroneous reviews.  Its overloading people's dashboards with tasks

![image](https://user-images.githubusercontent.com/50637067/73773900-0466f200-4751-11ea-8f67-5f7dac0db995.png)
![image](https://user-images.githubusercontent.com/50637067/73773923-0fba1d80-4751-11ea-962b-7134f7a93147.png)
![image](https://user-images.githubusercontent.com/50637067/73773943-1a74b280-4751-11ea-95c1-b16953da6d2c.png)
![image](https://user-images.githubusercontent.com/50637067/73773965-26607480-4751-11ea-808b-39509b102845.png)
![image](https://user-images.githubusercontent.com/50637067/73773982-30827300-4751-11ea-885d-feae94858b1f.png)
![image](https://user-images.githubusercontent.com/50637067/73773996-3b3d0800-4751-11ea-8a9f-1ec0332c262e.png)
![image](https://user-images.githubusercontent.com/50637067/73774019-44c67000-4751-11ea-9986-ffeeb1418d6d.png)

**Comment by megisys** [comment]
Hi THere, I Waived all of these. Please TEST in test and let me know if you are happy with the ouotcome and I will apply to Production ASAP

**Comment by MLWilkins** [comment]
thanks for the quick fix!  Tested 8 random APs with the PZMylar review due on 1/11/20 and all were waived.

**Comment by megisys** [comment]
Seems Ashley Reed did this another way in Production.. She voided them

**Comment by JuanitaMiles** [comment]
Please advise if Dan still needs to make any adjustments here or if Ashley's void in production has solved the problem.

**Comment by MLWilkins** [comment]
@JuanitaMiles  @megisys 
Ashley did not void or close all of the items listed above.  Ashley is working on closing all applications from 2010 back.  Many of the APs that generated that PZMylar review on 1/4/20 are still legitimate projects that are currently active and valid so we do not want to close or void those.  This ticket is just to n/a those PZMYLAR reviews listed above, not to close any APs.  Please move forward with deploying, specifically for those APs that are OPEN with the 1/11/20 PZMYLAR review due date.

**Comment by megisys** [comment]
Hi Mike there were 17 left behind. These are now NA in Production

**Comment by MLWilkins** [comment]
@JuanitaMiles  not sure what to do with this.  Im done with this ticket but not sure how to label it, or if to close it on not.

**Comment by JuanitaMiles** [comment]
@MLWilkins It looks like Dan marked those 17 outliers as NA in production, so i think they've all been taken care of. Ashley's voiding and Dan's NA solution were both done in Production so no testing needs to be done. I think if you are satisfied with the state of the errant PZ Mylars, lets close the ticket.
