### ISSUE TITLE
Planning - PDF Attachment didn't upload

### ISSUE THREAD

**Issue by AReed327** [dhenry-KCI/FredCo-Post-Go-Live-#344]
Project Number - SP258792
Observed behavior - PDF didn't upload in Test
Expected behavior - PDF needs to upload.
Exact PDF is attached below
Screenshot -
![image](https://user-images.githubusercontent.com/58854333/73843498-c3242000-47ec-11ea-8bba-e26b1ab42c6d.png)
[20191031150149271.pdf](https://github.com/dhenry-KCI/FredCo-Post-Go-Live-/files/4159557/20191031150149271.pdf)
![image](https://user-images.githubusercontent.com/58854333/73843550-db943a80-47ec-11ea-9c7e-02d100abcb8f.png)

**Comment by calequin** [comment]
tested on SP258796 and it is uploading correctly. used the attached pdf

**Comment by MLWilkins** [comment]
tested in test on SP258797.  Successfully attached a a PNG and PDF and was able to open in IPS
