### ISSUE TITLE
Extension Fees are not generating 

### ISSUE THREAD

**Issue by emilypearl1** [dhenry-KCI/FredCo-Post-Go-Live-#345]
Extension fees are not automatically generating after the EXT review is resulted. 

Examples: 189192, 189194, 189391.

I have manually inserted the Building Extension Fee on them.

**Comment by megisys** [comment]
BP_ExtensionReviewSetDateFee_BUF to be promoted..

**Comment by ABonomo21** [comment]
WORKED WHEN TESTING THE OTHER TICKET RELATED

**Comment by ABonomo21** [comment]
TESTED ON PERMIT 263249 WORKS GOOD THANKS

**Comment by calequin** [comment]
promoted on 2.9.2020
