### ISSUE TITLE
Planning - Notification Error - Portal Access Details Notification

### ISSUE THREAD

**Issue by AReed327** [dhenry-KCI/FredCo-Post-Go-Live-#346]
Project Number - SP258792
Observed behavior - Not pulling project information - code writing is showing. Various other errors in language and grammar.
Expected behavior - It should "You recently applied for a Planning Application with Frederick County" 
Period should be added at the end of Your details are below. 
Letter should be signed same as all others (Department of Development Review and Planning)
[Frederick County - Portal Account Registered.pdf](https://github.com/dhenry-KCI/FredCo-Post-Go-Live-/files/4159684/Frederick.County.-.Portal.Account.Registered.pdf)

Screenshot -
![image](https://user-images.githubusercontent.com/58854333/73846763-126d4f00-47f3-11ea-92b0-a0f7730f2d2d.png)

**Comment by megisys** [comment]
This is shared across Building and Planning.. Please come up with language which suits both

**Comment by calequin** [comment]
Once accepted please promote
Template ID: PORTALC

@AReed327 this email template is shared across all modules for Rhythm therefore making it specific to Planning is not possible. However, I did remove the date code writing and fixed the language/grammar issues.

**Comment by AReed327** [comment]
Expected behavior - It should read "You recently applied for a Permit, License, or Planning Application with Frederick County"
Period should be added at the end of Your details are below.
Letter should be signed: From the Division of Planning and Permitting

**Comment by calequin** [comment]
![image](https://user-images.githubusercontent.com/47603568/73962700-85022b80-48d4-11ea-88b5-e5de8344627f.png)
![image](https://user-images.githubusercontent.com/47603568/73962714-8cc1d000-48d4-11ea-8d51-fc5d56de80f0.png)
Once accepted please promote
Template ID: PORTALC

**Comment by AReed327** [comment]
Screen shot to show changes. Closing ticket.

**Comment by AReed327** [comment]
Verified correct. Test Accepted.

**Comment by calequin** [comment]
promoted on 2.16.2020
