### ISSUE TITLE
DUSWM Review on building permit on Town W/S

### ISSUE THREAD

**Issue by ABonomo21** [dhenry-KCI/FredCo-Post-Go-Live-#347]
DUSWM review generated on a non-res permit for a property served by town water and sewer, the capacity permit did not spawn which is correct but the reviews should not be populating.

**Comment by ABonomo21** [comment]
![image](https://user-images.githubusercontent.com/47611580/73849671-5151d380-47f8-11ea-8c08-8ea3f6742251.png)

**Comment by megisys** [comment]
NONRESBLDG_DUSWMF_Review_AOC - To be promoted if accepted

**Comment by ABonomo21** [comment]
TESTED ON 263320 WORKED THANKS

**Comment by calequin** [comment]
promoted on 2.9.2020
