### ISSUE TITLE
Extensions- Date not updating 

### ISSUE THREAD

**Issue by emilypearl1** [dhenry-KCI/FredCo-Post-Go-Live-#348]
Once the fees are paid on an extension - the expires date is not updating 

Permit #189194 they paid the extension fee (had to be manually inserted- placed a seperate github ticket)
Fees paid 
Expires date - no change! - this should automatically update once the fee is paid based off of the resulted EXT review.

**Comment by emilypearl1** [comment]
![image](https://user-images.githubusercontent.com/58855801/73853799-74cc4c80-47ff-11ea-802a-049b200ad53d.png)

**Comment by megisys** [comment]
Check the formula here in Dev - After Fee Payment

**Comment by megisys** [comment]
Fee_ProcessExtension_BU to be promoted once accepted

**Comment by ABonomo21** [comment]
TESTED ON PERMIT 263249 WORKS GOOD THANKS

**Comment by calequin** [comment]
promoted on 2.9.2020
