### ISSUE TITLE
PLANNING - X/Y Coordinates

### ISSUE THREAD

**Issue by AReed327** [dhenry-KCI/FredCo-Post-Go-Live-#35]
Need the ability to submit PWCONSTRUC under X/Y coordinates. 
Ability from back office for map to load the X/Y Coordinates to show site location.

**Comment by megisys** [comment]
PLN_ValidatePortalInfo_CVPD - from Test to Prod

**Comment by ScottVanSooy** [comment]
Promoted to Production 12/17/2019 8:30 PM
