### ISSUE TITLE
Soil Conservation fee not generating on Inground Pool Permits.

### ISSUE THREAD

**Issue by awhite806** [dhenry-KCI/FredCo-Post-Go-Live-#350]
The Soil Conservation fee is not generating on Inground permits and is not available to add.
![image](https://user-images.githubusercontent.com/58981029/73864095-127b4800-480f-11ea-9ac7-73692f5368f1.png)

 Per Ashlye, the code from the Minor Grading fee should be copied over to the SCD Review Fee (which is incorrectly labeled as SDC Review Fee)
![image](https://user-images.githubusercontent.com/58981029/73864216-43f41380-480f-11ea-9199-5b2577884377.png)
![image](https://user-images.githubusercontent.com/58981029/73864228-49e9f480-480f-11ea-94ce-356513cca120.png)
 

marking this as high priority and assigning to Christian per Abonomo.

**Comment by calequin** [comment]
fixed the name in test and prod and associated the correct formula in both instances. Ready for test

**Comment by ABonomo21** [comment]
tested 263319 in test worked thanks! okay to push

**Comment by calequin** [comment]
promoted on 2.9.2020
