### ISSUE TITLE
Waived/cancelled inspections causing re-inspection fees

### ISSUE THREAD

**Issue by awhite806** [dhenry-KCI/FredCo-Post-Go-Live-#351]
A Waived/Cancelled should not generate a re-inspection fee (and it's coresponding email notifications.)
![image](https://user-images.githubusercontent.com/58981029/73865251-f8426980-4810-11ea-95df-37ced3841816.png)
![image](https://user-images.githubusercontent.com/58981029/73865388-2a53cb80-4811-11ea-9eac-14945f6ff7b2.png)

**Comment by megisys** [comment]
BP_ManageInspection_BUF - To be promoted if successful

**Comment by ABonomo21** [comment]
tested 263249 worked thanks

**Comment by calequin** [comment]
promoted on 2.9.2020
