### ISSUE TITLE
Second Temporary Certificate of Occupancy

### ISSUE THREAD

**Issue by mlibbey131** [dhenry-KCI/FredCo-Post-Go-Live-#352]
When processing a Second Temporary Certificate of Occupancy the details page does not clear out in order to process the new Temporary Certificate of Occupancy. Example A/P 190964

![image](https://user-images.githubusercontent.com/58980189/73867132-21b0c480-4814-11ea-84b8-c92da2f219fa.png)

**Comment by megisys** [comment]
BLDG_TEMPCOO - Table needs new field added in Production - MOVETOLOG Boolean.

Formula - Needs to copy to a Log the details.

**Comment by ABonomo21** [comment]
Please change the log type to the temp coo issued. I will document the changes that one the review is signed off on the review the tech will need to click on the save to archive log 

![image](https://user-images.githubusercontent.com/47611580/73975317-1208ad00-48f4-11ea-9f07-a60046a9c5f4.png)

**Comment by ABonomo21** [comment]
once log type is change it can be pushed

**Comment by JuanitaMiles** [comment]
@megisys assigning back to you since you originally worked this issue.

**Comment by megisys** [comment]
Changed logtype

**Comment by megisys** [comment]
Make Sure TCOOIS log type in Building is not expired

**Comment by calequin** [comment]
promoted on 2.9.2020
