### ISSUE TITLE
Planning-R4C-remove "create new link" in related records

### ISSUE THREAD

**Issue by MLWilkins** [dhenry-KCI/FredCo-Post-Go-Live-#353]
we cannot allow applicants to add related records in the portal.  This must be a back office function.  On SP258797 I was able to add a plat as a child through the portal.  The create a new link button must be removed on all Planning applications
![image](https://user-images.githubusercontent.com/50637067/73867869-6ab54880-4815-11ea-8862-27363717ed80.png)

![image](https://user-images.githubusercontent.com/50637067/73867899-7d2f8200-4815-11ea-93d9-157e138c2075.png)

**Comment by calequin** [comment]
turned off in both environments. Development is working on a fix to make these read only but for now we have turned it off

**Comment by MLWilkins** [comment]
Realize the bigger issue is covered under another ticket.
