### ISSUE TITLE
PLANNING - MASS close of applications - ERROR, AssignedTo is not Effective

### ISSUE THREAD

**Issue by AReed327** [dhenry-KCI/FredCo-Post-Go-Live-#354]
Project Number - FRO, SITE, & PWCONSTRUC Projects processed on or BEFORE 12/30/2010
Observed behavior - Error message when trying to move to closed or precomplete. Error message says "AssignedTo is not effective
Expected behavior - Expect to be able to move these applications to closed so they do not show on any applicants R4C and any unresulted reviews are not on dashboards

Please note, I was able to close apfo, plat, boa, rezone, and preplat. Issues only with FRO, SITE and PWCONSTRUC
[CLOSING PLAN ISSUES.docx](https://github.com/dhenry-KCI/FredCo-Post-Go-Live-/files/4161174/CLOSING.PLAN.ISSUES.docx)

Screenshot -
![image](https://user-images.githubusercontent.com/58854333/73868525-9d137580-4816-11ea-9ea5-35fc9692eb19.png)

**Comment by megisys** [comment]
The employees on these applications are expired as they have left Frederick County.  Are you using the VOID log ? Just moving via a status cchange will not waived reviews. If it is due to old staff this will be a county fix

**Comment by AReed327** [comment]
Based on a Plat that I closed yesterday by moving the milestone, the reviews were automatically resulted to NA

**Comment by megisys** [comment]
That's fine.. I think we handle both..  What do you need me to do.. I cant help with the old staff. these will just need to be handled as a rainy day task

**Comment by AReed327** [comment]
I closed 4889, 3995 on 2/5/2020 and many others that have old staff on them. My concern is that these projects can end up on the portal so we need to get this cleaned up. 
We need to find a work around. There are too many for a rainy day activity. 
![image](https://user-images.githubusercontent.com/58854333/73976341-1afa7e00-48f6-11ea-8913-6669082f3396.png)
![image](https://user-images.githubusercontent.com/58854333/73976867-30bc7300-48f7-11ea-8e49-55345fac7fbc.png)

7065 - this one will not close but has weird reviews. 
![image](https://user-images.githubusercontent.com/58854333/73977639-b391fd80-48f8-11ea-842a-98f526c5cf4f.png)

**Comment by megisys** [comment]
Those are reviews added bu the county. I dont know what you would like me to do here. It is a case by case thing. If you want me to NA any reviews on a Closed Application I can. But the bottom one is open.

Dan

**Comment by AReed327** [comment]
Those reviews are causing at least part of the issue. I tried to result them as N/A and it gives me the same  AssignedTo error
![image](https://user-images.githubusercontent.com/58854333/73978016-737f4a80-48f9-11ea-8b2b-6562a3e6bfe4.png)

My expectation is that I can close old projects.

**Comment by AReed327** [comment]
I can't void these because they are likely approved plans that have reviews on them that were never resulted. I just want to close them.

**Comment by megisys** [comment]
THese reviews are now gone and that ap moved. ANy others

**Comment by AReed327** [comment]
Figured out how to make it work. Need to go in and assign the unassigned reviews on the projects that give error. By using process of elimination, I have closed all applications I needed to.  AREED
