### ISSUE TITLE
Health Review fee did not generate on Non Res Permit

### ISSUE THREAD

**Issue by awhite806** [dhenry-KCI/FredCo-Post-Go-Live-#355]
The Food Related box was checked, but the $50 Health Review fee did not generate
![image](https://user-images.githubusercontent.com/58981029/73869311-165f9800-4818-11ea-90f0-c49c9016d3d4.png)
![image](https://user-images.githubusercontent.com/58981029/73869379-27100e00-4818-11ea-8bc2-50b3d85bf40e.png)

**Comment by megisys** [comment]
NONRESBLDG_Fee_HealthReview_AOC - If Successful - push this

**Comment by ABonomo21** [comment]
Do not push, the health review fee should not generate if the box is checked. Only the health review should generate when the food service box is checked. 

This ticket should be closed.

**Comment by JuanitaMiles** [comment]
dan reverted his change while i was on the phone with him. closing ticket
