### ISSUE TITLE
PLANNING - Project needs pushed to EPLANS

### ISSUE THREAD

**Issue by AReed327** [dhenry-KCI/FredCo-Post-Go-Live-#356]
Project Number - **SP2578779** - **APPLICANT WAITING**
Observed behavior - Plan didn't go to PDOX because the applicant requested a withdraw. Applicant paid fees but project didn't move to PDOX. Withdraw log has been deleted.
Expected behavior - Projects needs to go to PDOX and we need to have a way to override this in the future
Screenshot -

![image](https://user-images.githubusercontent.com/58854333/73869649-b3bacc00-4818-11ea-82e0-a5e17b42efd6.png)

**Comment by JuanitaMiles** [comment]
@calequin there was some sort of log that was created for permits that would override a result and push the project through to project dox. Will this log accomplish what needs to happen here?

**Comment by calequin** [comment]
added OPDOX Log to allow us to resend the planning application to pdox. Please test in test environment
Once approved promote the following:
1. Add OPDOX Log in Code Definition Management - CDR - Planning - Logtype
2. SWM go to CDR - Planning - Log - After Add and add the following formula PL_OverridePDOXCreateLog_AAF

**Comment by calequin** [comment]
@AReed327  instructions: anytime we add a OPDOX log to an application it will resend this job.

**Comment by calequin** [comment]
deployed on 2.5.2020

**Comment by AReed327** [comment]
Worked on SP258779. Closing ticket as it is already deployed. areed
