### ISSUE TITLE
Site -Inspection Assignment 

### ISSUE THREAD

**Issue by ABonomo21** [dhenry-KCI/FredCo-Post-Go-Live-#359]
zoning certificate 258596 generated a site-inspection but it did not automatically assign to Kathy Evans. I have manually assigned. 
![image](https://user-images.githubusercontent.com/47611580/73939363-4d38bb00-48b7-11ea-8226-deb92cd39563.png)

**Comment by calequin** [comment]
Zoning Certificates have no ElectDistrict/Subdivision/APTYPE assigned to an inspector 
I need a list of who the SITE-INSP - SITE INSPECTION goes to and which assignment areas.

![image](https://user-images.githubusercontent.com/47603568/73962504-32287400-48d4-11ea-9e47-09bd68e96e3e.png)

**Comment by JuanitaMiles** [comment]
@calequin @ABonomo21 When Christian's questions above has been answered, please do not assign back to Christian. This task needs to go to Jeff Wisner.

**Comment by ABonomo21** [comment]
They all go to Kathy Evans.

**Comment by ABonomo21** [comment]
@JuanitaMiles

**Comment by pooldaddy** [comment]
Added all election districts to TEST
![image](https://user-images.githubusercontent.com/47391482/74241086-4d66fb00-4ca9-11ea-9ef8-ea252d5ab53c.png)

![image](https://user-images.githubusercontent.com/47391482/74241136-62dc2500-4ca9-11ea-89c2-d52b96ef4668.png)

**Comment by calequin** [comment]
PROMOTED ON 2.16.2020
