### ISSUE TITLE
R4C anonymous viewing

### ISSUE THREAD

**Issue by emilypearl1** [dhenry-KCI/FredCo-Post-Go-Live-#36]
When using Look up Applications (under anonymous)- citizens are unable to inspections, reviews, etc.

EX 201510

in IPS11 there have been multiple inspections performed.

**Comment by ABonomo21** [comment]
![image](https://user-images.githubusercontent.com/47611580/71020912-3782f280-20cb-11ea-9622-208ed5e280b5.png)

reviewed by Ashlye

**Comment by calequin** [comment]
fixed
![image](https://user-images.githubusercontent.com/47603568/71023445-5df35e80-20c8-11ea-88b8-c88d3eeff320.png)
