### ISSUE TITLE
Service Request - Inspection comments

### ISSUE THREAD

**Issue by ABonomo21** [dhenry-KCI/FredCo-Post-Go-Live-#360]
There is no where to view inspector comments from a service request. 
![image](https://user-images.githubusercontent.com/47611580/73953202-115d2000-48ce-11ea-8f71-2b83a0ff0686.png)

**Comment by megisys** [comment]
![image](https://user-images.githubusercontent.com/47392306/73954538-f1c6f700-48cf-11ea-8d4d-3abe567d63c2.png)

**Comment by megisys** [comment]
Spoke to Ashlye this was a miss
