### ISSUE TITLE
Pool Electrical issued when Building Permit Under Review

### ISSUE THREAD

**Issue by emilypearl1** [dhenry-KCI/FredCo-Post-Go-Live-#363]
Building #264492 under review
Electrical #264514 issued

![image](https://user-images.githubusercontent.com/58855801/73971646-42008200-48ed-11ea-8114-1f82fb9bf3be.png)

electrical permit related to building permit should not issue prior to building permit issuance

**Comment by calequin** [comment]
The parent permit was related after the pending issuance milestone, therefore it didnt know a parent was added.
No issue here just need to related the permit before issuance
![image](https://user-images.githubusercontent.com/47603568/74050857-741ced00-499c-11ea-8bd5-c0fb6c3294d4.png)

**Comment by ABonomo21** [comment]
I will remind staff they need to relate records before resulting the completeness check and make sure they are checking the back office parent required check box. Emily please send an email.
