### ISSUE TITLE
Batch Manager - Progress Trade Task Error

### ISSUE THREAD

**Issue by JuanitaMiles** [dhenry-KCI/FredCo-Post-Go-Live-#364]
Jeff Wisner has identified the error below. Everyday this Progress Trade task runs it runs with the same error. It appears to reference license # PM599 however there are no licenses in the system with this exact license number. I have included a screenshot with all applications with "599" in them all of which have licensees. 

Can we please identify what is causing this error and resolve so the batch task can run clean?

![image](https://user-images.githubusercontent.com/31770504/73974185-e7b5f000-48f1-11ea-8fbb-31ccb1d29282.png)

![image](https://user-images.githubusercontent.com/31770504/73974256-0a480900-48f2-11ea-868f-db59f39f732c.png)

**Comment by megisys** [comment]
This task really doesnt need to be run daily. I would also say that the out of the box progress formulas are not perfect and it is best we design our own.. Disabling for now.
