### ISSUE TITLE
Unable to print Cut-Ins

### ISSUE THREAD

**Issue by mlibbey131** [dhenry-KCI/FredCo-Post-Go-Live-#365]
When we try to print the cut in reports we receive this error-High Priority Per Ashlye

![image](https://user-images.githubusercontent.com/58980189/74030835-04980500-497e-11ea-9ca6-399bb1b78f64.png)

**Comment by pooldaddy** [comment]
Related to SSRS report issue.  Dave & Tara investigating.

**Comment by megisys** [comment]
County advises this issue is addressed

**Comment by pooldaddy** [comment]
Closing issue. Cause was ssrs server outage
