### ISSUE TITLE
Unable to open Documents for permits

### ISSUE THREAD

**Issue by awhite806** [dhenry-KCI/FredCo-Post-Go-Live-#366]
We are unable to open any documents for permits. When clicking the Document button, this error pops up. High Priority per Ashlye!
![image](https://user-images.githubusercontent.com/58981029/74030825-fd70f700-497d-11ea-9001-e631fcf92acc.png)

**Comment by megisys** [comment]
Dave Desai says this issues is addressed

**Comment by pooldaddy** [comment]
Closing this issue as it was related to SSRS server outage

**Comment by pooldaddy** [comment]
Close
