### ISSUE TITLE
PORTAL ACCOUNT LINK ERROR

### ISSUE THREAD

**Issue by ABonomo21** [dhenry-KCI/FredCo-Post-Go-Live-#368]
I have two customers that have their portal account linked accurately and we are not able to see them within their portal 

their dashboards are blank
recelectric@verizon.net - should have a trade license number em257820 showing up 
alecproakis@gmail.com- should have demo permit number 261914

Is the a larger issue how do we get it corrected??

**Comment by calequin** [comment]
Fixed - Electrical Trade status of Processing was not enabled to display in the OPEN Filter for Prod
![image](https://user-images.githubusercontent.com/47603568/74042079-7ecf8600-498c-11ea-9bfb-a52089b6ac3c.png)


Demolition - did not find an issue here and it displayed correctly in my portal in prod and test

![image](https://user-images.githubusercontent.com/47603568/74041645-a96d0f00-498b-11ea-80c5-d8e9c2ee518f.png)

**Comment by megisys** [comment]
I cant even see a demo permit of  261914 . ??

**Comment by calequin** [comment]
When searching for alecproakis@gmail.com in contact and property browser the demolition permit listed is 261964

**Comment by ABonomo21** [comment]
That is correct christian.

**Comment by JuanitaMiles** [comment]
@calequin is this ready for retest now?? can't tell if there is still an outstanding question...

**Comment by awhite806** [comment]
Megan's customer for REC Electric is working! I have emailed my customer Alec to confirm his portal is linked as well. Closing for now unless I hear back from Alec that the portal is not linked.
