### ISSUE TITLE
Migration of Unpaid Fees 

### ISSUE THREAD

**Issue by emilypearl1** [dhenry-KCI/FredCo-Post-Go-Live-#369]
Permit #57444 was unpaid in hansen 7

![image](https://user-images.githubusercontent.com/58855801/74041250-4f704780-4993-11ea-963b-abdf3ef0f669.png)

In IPS the fee is showing as waived. 
![image](https://user-images.githubusercontent.com/58855801/74041294-63b44480-4993-11ea-817d-6b7e7e0e421a.png)

currently - the permitting fees for this permit are UNPAID!!

**Comment by emilypearl1** [comment]
IPS shows an unpaid amount of $0.00

**Comment by megisys** [comment]
The Application is closed. Please advise

**Comment by emilypearl1** [comment]
Dan - FRO permits do not expire and therefore, this application should not have been apart of the migration push for in-life mapping. The in life mapping push was set to waive fees, reviews, inspections etc on permits that "expired". These fees should not be waiving for FRO, we have two examples
52199 and 57444

What we need from you is to remove all expiration dates from FRO permits so the mapping we have established does not have this effect on these applications. 
And All new Fro permits should not generate an expiration date. 
Additionally, is there a way for me to know which fro permits had fees waive on them because of this occurring ?

**Comment by megisys** [comment]
Email sent. County able to adjust these as required. No Issue for Infor to address.

**Comment by ABonomo21** [comment]
Emily and I will try to move to the correct milestones and adjust as we find them. @emilypearl1
