### ISSUE TITLE
Project Dox - Server Error

### ISSUE THREAD

**Issue by ABonomo21** [dhenry-KCI/FredCo-Post-Go-Live-#37]
application failed for server error. Need this to go through... 
![SnipImage](https://user-images.githubusercontent.com/47611580/71021464-6baae300-20cc-11ea-9be5-c11e39d69e41.JPG)

**Comment by megisys** [comment]
I got the planning one through.. Building is stuck @dhenry-KCI

**Comment by megisys** [comment]
Fixed.. Project Name had a ' in it....
