### ISSUE TITLE
Related Record Error

### ISSUE THREAD

**Issue by ABonomo21** [dhenry-KCI/FredCo-Post-Go-Live-#370]
related to issue #231 

processing BP # 264591 there are a number of cases being related as an other records that are unrelated. had this issue previously. 

![image](https://user-images.githubusercontent.com/47611580/74050452-155b7180-49a4-11ea-8eed-f779b5c4b1e1.png)

**Comment by calequin** [comment]
somehow this application was added without an address and then fixed after. How was this application created? group add etc?
![image](https://user-images.githubusercontent.com/47603568/74051248-39678480-499d-11ea-86e2-965228da8f80.png)

**Comment by calequin** [comment]
all cases have been cleared now

**Comment by megisys** [comment]
BLDG_ListOpenCases_AAF - Issue found needs to be promoted urgently.. Test by Dan Grendon

**Comment by ABonomo21** [comment]
here is another one.

**Comment by ABonomo21** [comment]
![image](https://user-images.githubusercontent.com/47611580/74061449-07b0e680-49ba-11ea-97fc-99c7bc946e38.png)

**Comment by ABonomo21** [comment]
@calequin

**Comment by calequin** [comment]
formula fix will need to be promoted after hours BLDG_ListOpenCases_AAF

**Comment by calequin** [comment]
promoted on 2.9.2020
