### ISSUE TITLE
Zoning Use Details 

### ISSUE THREAD

**Issue by emilypearl1** [dhenry-KCI/FredCo-Post-Go-Live-#371]
Permit #202731 didnt have a zoning use details tab-  Justin went to add the details when he chose Zoning Use Details it acted like it was going to save but did not save. 

I had to manually add it myself since he was unable to get it to save.
![image](https://user-images.githubusercontent.com/58855801/74055847-ce26ae00-49ae-11ea-948c-0aeb7e9df95f.png)

**Comment by JuanitaMiles** [comment]
i'll look at the permissions to see if the permission for him to add detail pages is in effect.

**Comment by JuanitaMiles** [comment]
I don't see anything in the permissions that would be preventing Justin to add this detail page. Perhaps christian will have more information.
![image](https://user-images.githubusercontent.com/31770504/74066946-20bf9480-49c6-11ea-94d8-a628f370be8e.png)

**Comment by calequin** [comment]
could not replicate. can we try again? Couldve been a cached screen taking long if it was his first time adding a detail page.

**Comment by emilypearl1** [comment]
Closing ticket
