### ISSUE TITLE
Treasury - Time Out Issues

### ISSUE THREAD

**Issue by JuanitaMiles** [dhenry-KCI/FredCo-Post-Go-Live-#373]
Dan Lewis in Treasury has reported time out issues again for his staff. Kristi Lewandowksi in DUSWM was also trying to hit the "Receipt" button to complete a transaction and received an error. I believe these issues are related from what I see of Kristi's error below.

![image](https://user-images.githubusercontent.com/31770504/74057065-1d6dde00-49b1-11ea-9f47-fc8ae44734a5.png)

![image](https://user-images.githubusercontent.com/31770504/74057125-3ececa00-49b1-11ea-8db4-599f7ffa3c57.png)

**Comment by megisys** [comment]
Closing this.. This was due to accidental update.. System is back..
