### ISSUE TITLE
Plumbing License Renewal Review error 

### ISSUE THREAD

**Issue by awhite806** [dhenry-KCI/FredCo-Post-Go-Live-#374]
When trying to result a renewal review, this error is generating.  Not sure what it is referring too??
PM001350
![image](https://user-images.githubusercontent.com/58981029/74057451-f663dc00-49b1-11ea-893a-77f92bf8ae44.png)

**Comment by JuanitaMiles** [comment]
Not sure if this is related to the broader errors occurring in the system in general. Christian please take a look when you are able to confirm.

**Comment by megisys** [comment]
PLease Try Now.. Also what result are you trying to result it

**Comment by JuanitaMiles** [comment]
You can see in the screenshot it says approved.

**Comment by megisys** [comment]
You have good eyes.. LOL Did it work now.

**Comment by awhite806** [comment]
Leslie got it to approve! closing the issue
