### ISSUE TITLE
Planning - IPS created 3rd review cycle before resubmit in PDOX

### ISSUE THREAD

**Issue by AReed327** [dhenry-KCI/FredCo-Post-Go-Live-#375]
Project Number - SP257690

Observed behavior - I received the 3rd submission in PDOX. Before routing I reviewed IPS. IPS already had the 3rd review cycle populated. When I routed the 3rd submission from PDOX, IPS kept the due date that it originally populated on 2/3/2020 when it added in error. IPS added the 3rd cycle when the last reviewer resulted their review on the 2nd cycle. 

Expected behavior - The 3rd review cycle should not populate until reviews received from PDOX. 

Screenshots - 
![image](https://user-images.githubusercontent.com/58854333/74061879-046a2a80-49bb-11ea-8344-0519619d0e6d.png)
![image](https://user-images.githubusercontent.com/58854333/74061885-07fdb180-49bb-11ea-9752-1e6fc74a19a0.png)
![image](https://user-images.githubusercontent.com/58854333/74061896-0af8a200-49bb-11ea-9a6d-a17302c60566.png)
![image](https://user-images.githubusercontent.com/58854333/74061906-0e8c2900-49bb-11ea-8d8a-0275eb6835ef.png)

**Comment by JuanitaMiles** [comment]
@calequin will likely need Dan's support as he has worked extensively with these reviews and communication to and from PDox.

**Comment by megisys** [comment]
IPS didn't add this review 3. It was initiated by Project Dox check the far right column within IPS.  Do we know what happened in Pdox. Not sure we can help here too much. Will need Robert to assist

**Comment by megisys** [comment]
@JuanitaMiles

**Comment by AReed327** [comment]
There was no re submission in PDOX until 2/7/2020 as you can see in the screenshot above. We have been unable to replicate. Changing to will monitor and closing.
