### ISSUE TITLE
PLANNING - Town Review - Emmitsburg didn't add

### ISSUE THREAD

**Issue by AReed327** [dhenry-KCI/FredCo-Post-Go-Live-#376]
Project Number - PW258818
Observed behavior - Town not adding as an applicant. I will add manually on this one. 
Expected behavior   - Towns/Municipalities will add as applicant based on Parcel Details
![image](https://user-images.githubusercontent.com/58854333/74064833-7fceda80-49c1-11ea-8089-c605b3983831.png)

**Comment by calequin** [comment]
please test and if accepted promote 

BldgAppDtl_CreateAppLogsDetail_AA

**Comment by calequin** [comment]
please test and promote once accepted
PLN_AddTownReviewer_AAF

**Comment by MLWilkins** [comment]
retest failed.

![image](https://user-images.githubusercontent.com/50637067/74439309-03614f00-4e3a-11ea-8932-fe56fd895fd1.png)

**Comment by calequin** [comment]
@MLWilkins there seems to be an issue with that parcel. I see 15339454 listed as Township code 00 which is frederick county but the parcel details show it as water type Town. Can you try with a different parcel and @JuanitaMiles can GIS look into this one 15339454.

**Comment by JuanitaMiles** [comment]
Per County Procedure - Mike or Ashley will need to create a ticket through the GIS ticketing system if the Township or Water/Sewer is incorrect so GIS can update.

**Comment by MLWilkins** [comment]
this one in Thurmont worked.

![image](https://user-images.githubusercontent.com/50637067/74454853-7f679100-4e52-11ea-9d07-638b0d9239c1.png)


Also tested one for Walkersville and it worked too.

![image](https://user-images.githubusercontent.com/50637067/74455009-b8a00100-4e52-11ea-9a08-b6e9c7b89fb4.png)

**Comment by calequin** [comment]
promoted on 2.16.2020

**Comment by AReed327** [comment]
Project Number - PW258871
Observed behavior - Town Emmitsburg did not add as APPLICANT
Expected behavior - Town will add when Township code is populated
Screenshot -
![image](https://user-images.githubusercontent.com/58854333/75045482-5fa71d00-5491-11ea-8bf7-f09669e91f6b.png)

![image](https://user-images.githubusercontent.com/58854333/75045460-57e77880-5491-11ea-9d7c-80a4eb608336.png)

**Comment by AReed327** [comment]
Why is ABonomo's email attached to Emmitsburg?
![image](https://user-images.githubusercontent.com/58854333/75046179-a5b0b080-5492-11ea-889c-d01632482379.png)

**Comment by AReed327** [comment]
It appears Emmitsburg and New Market have not been set up with Portal Accounts.

Emmitsburg should be zgulden@emmitsburgmd.gov 
NewMarket should be Clerk2Council@townofnewmarket.org

**Comment by calequin** [comment]
added emmitsburg and new market as requested in production. These will add for Building permit as well. Is this correct for Building Permits @ABonomo21

**Comment by calequin** [comment]
@AReed327  can we get an email for emmitsburg and new market that is not an individuals email? This allows us to have a town reviewer emmitsburg contact.

**Comment by calequin** [comment]
this has been added in test and prod.

**Comment by AReed327** [comment]
PW258836 Worked for Emmitsburg
![image](https://user-images.githubusercontent.com/58854333/75165605-a8104600-56f0-11ea-88c0-0d4caae51034.png)
PW258837 Does not appear to be correct for New Market. There is no email associated to New Market under the Town Reviewer contact in Production and there is no portal account associated in Test. It does not match the test I ran with an Emmitsburg parcel. 
Test PW258837
![image](https://user-images.githubusercontent.com/58854333/75166751-5a94d880-56f2-11ea-9bdb-fcf3278734f6.png)
Contact in Production 
![image](https://user-images.githubusercontent.com/58854333/75166830-7a2c0100-56f2-11ea-97e9-75e6940276bc.png)

**Comment by calequin** [comment]
fixed in production. Created a portal account for New Market using their email for credentials.

![image](https://user-images.githubusercontent.com/47603568/75168155-0b4ba980-56ec-11ea-8576-1fc5c8f85632.png)

**Comment by calequin** [comment]
i have also fixed it in test but the portal account will not be associated because of test records. I used my email in test so that the town reviewers do not get test emails sent

**Comment by AReed327** [comment]
Verified New Market and Emmitsburg emails are linked under Town Reviewer in Production.

PW258838 & PW258839 Under both of these in test, only one email went out. This is different from the Emmitsburg application PW258836 that I tested yesterday. It does not appear the notification is being sent to the town. I understand that it would not actually send in test, but I am expecting it to show in the Event Log.
![image](https://user-images.githubusercontent.com/58854333/75279312-5f808780-57d9-11ea-9d79-5e333a78f16b.png)
![image](https://user-images.githubusercontent.com/58854333/75279336-6c04e000-57d9-11ea-9c9e-217117772d05.png)

Emmitsburg example
![image](https://user-images.githubusercontent.com/58854333/75279378-80e17380-57d9-11ea-8f69-739e561dbf63.png)

**Comment by megisys** [comment]
New market was set for all communications to be opted out. This is a data issue against the contact. I removed planning notification opt outs if you would like to retest in Test.. 

New Issue - Not related to the original issue request but understand why this was considered a retest fail

**Comment by AReed327** [comment]
It's not clear why New Market would have ever been set to be opted out of all communications as they are a Municipality that we review projects for. I do not see this as a new issue.

New Market didn't add. It just TownR with no info. 
![image](https://user-images.githubusercontent.com/58854333/75567777-13735400-5a20-11ea-8112-f850ae1c5fa7.png)
![image](https://user-images.githubusercontent.com/58854333/75567854-33a31300-5a20-11ea-8609-ce23be3b339d.png)
