### ISSUE TITLE
Planning-waived fee but wouldnt move past awaiting plan review payment

### ISSUE THREAD

**Issue by MLWilkins** [dhenry-KCI/FredCo-Post-Go-Live-#377]
waived fees on this site plan to test PDox upgrade but systems still requires fee payment.  Had to supervisor override this one to test PDox.

![image](https://user-images.githubusercontent.com/50637067/74152312-0bbc4e80-4bdc-11ea-819c-64f121291395.png)
![image](https://user-images.githubusercontent.com/50637067/74152338-1b3b9780-4bdc-11ea-900d-77d413762434.png)

**Comment by megisys** [comment]
Cause this was moved unable to see fault. Is it possible we can try and replicate in Test

**Comment by MLWilkins** [comment]
see SP258806 in TEST

![image](https://user-images.githubusercontent.com/50637067/74156457-5c37aa00-4be4-11ea-9e63-7ee41a6e88f4.png)

**Comment by megisys** [comment]
Thanks so much Mike.. Issue is addressed in Test and Production. Was a hold up on Wavied

**Comment by MLWilkins** [comment]
tested in TEST and it works.  Thanks!


![image](https://user-images.githubusercontent.com/50637067/74157130-c00ea280-4be5-11ea-8873-efa87b5a5bf2.png)
