### ISSUE TITLE
Building Permits - RESBLDG - Placard Not Generating in TEST

### ISSUE THREAD

**Issue by JuanitaMiles** [dhenry-KCI/FredCo-Post-Go-Live-#378]
In the TEST system. When trying to run the Building Permit - Official Placard on-demand, the placard does not generate. It's just a white screen.

Abbie to attach screen shot....

**Comment by awhite806** [comment]
![image](https://user-images.githubusercontent.com/58981029/74163526-84c5a100-4bf0-11ea-9b9f-92ea92dafb0e.png)
![image](https://user-images.githubusercontent.com/58981029/74163539-88592800-4bf0-11ea-95e5-f4b6fc8dfc02.png)

**Comment by TaraF** [comment]
Working - please test in test again.

**Comment by JuanitaMiles** [comment]
Confirmed the placard generates on-demand in both environments. Closing ticket.

![image](https://user-images.githubusercontent.com/31770504/74171838-2eab2a80-4bfd-11ea-84ff-083cbcee08b2.png)

![image](https://user-images.githubusercontent.com/31770504/74171878-41256400-4bfd-11ea-88c7-2def81b6305b.png)
