### ISSUE TITLE
Planning - Wrong milestone on Site Plan. Awaiting Applicant Payment after all reviews approved

### ISSUE THREAD

**Issue by AReed327** [dhenry-KCI/FredCo-Post-Go-Live-#379]
SP258819
Application went to Awaiting Applicant Payment after all reviews were completed.
Expectation is that application will not stop at this milestone when there is no payment due. There should not be a fee owed on this application type at this milestone.
![image](https://user-images.githubusercontent.com/58854333/74164766-34e7d980-4bf2-11ea-80fc-625db79e49d7.png)

**Comment by megisys** [comment]
Addressed in Prod

**Comment by MLWilkins** [comment]
tested in IPS and Pdox TEST.  SP258806.  Project went to schedule hearing as expected.

![image](https://user-images.githubusercontent.com/50637067/74183773-98363380-4c13-11ea-94ba-d965cee14408.png)
