### ISSUE TITLE
Issued Permit - Blank

### ISSUE THREAD

**Issue by ABonomo21** [dhenry-KCI/FredCo-Post-Go-Live-#38]
Issued permit name is blank... 
![image](https://user-images.githubusercontent.com/47611580/71022488-95650980-20ce-11ea-8ddd-860dab918890.png)

**Comment by megisys** [comment]
Who was the user in at the time ?

Dan

**Comment by calequin** [comment]
this was system driven and push through by Hansen8. Therefore no name will be available since Hansen8 doesnt have an employee record
