### ISSUE TITLE
Grading Details Page

### ISSUE THREAD

**Issue by emilypearl1** [dhenry-KCI/FredCo-Post-Go-Live-#380]
Permit #264598
the applicant completed the Grading Details Intake however they did not copy over to the Grading Details page 
![image](https://user-images.githubusercontent.com/58855801/74172185-cc065e80-4bfd-11ea-8fc7-ab6f03588c9f.png)
![image](https://user-images.githubusercontent.com/58855801/74172211-d4f73000-4bfd-11ea-97e6-c15e1c5bc8c5.png)

**Comment by calequin** [comment]
please test and if accepted promote 

BldgAppDtl_CreateAppLogsDetail_AA

**Comment by ABonomo21** [comment]
tested on 263317 did not generate the intake details to the grading details

**Comment by calequin** [comment]
i created application 263348 from start application and it worked. Was permit 263317 created via a group add or under start application?

**Comment by ABonomo21** [comment]
new permits created 264977- grading details intake page completed in r4c - grading details did not generate automatically at intake review. IN PRODUCTION.

**Comment by calequin** [comment]
@ABonomo21 this was not promoted yet to production. Can this be tested in test please.

**Comment by ABonomo21** [comment]
Tested from scratch started a resbldg permit in r4c , permit 263361, it spawned grading permit 263363. the grading permit automatically goes to awaiting applicant resubmit for the applicant to complete the grading intake details, which I completed and resubmitted back to the county. grading permit is in intake review and the grading intake details did not copy over to the grading details page like they should have. 
![image](https://user-images.githubusercontent.com/47611580/74969832-45b2ff00-53eb-11ea-95a4-df75a416f0b6.png)

**Comment by calequin** [comment]
please test if accepted promote:
GRADING_UpdateGradingDetails_BU

**Comment by ABonomo21** [comment]
unable to test in test - getting an internal server error
![image](https://user-images.githubusercontent.com/47611580/75068496-47e58e00-54bd-11ea-8e49-753be2979a43.png)

**Comment by ABonomo21** [comment]
was trying to test 263372

**Comment by ABonomo21** [comment]
@JuanitaMiles @calequin

**Comment by calequin** [comment]
had to resync r4c. please try again

**Comment by ABonomo21** [comment]
retest failed 
tested permit 263372

![image](https://user-images.githubusercontent.com/47611580/75069269-d9a1cb00-54be-11ea-9f74-ee71298e8c15.png)

![image](https://user-images.githubusercontent.com/47611580/75069238-c989eb80-54be-11ea-8211-fda713df7245.png)

**Comment by calequin** [comment]
TESTED ON R4C WITH RESBLDG 263381 it spawned the grading permit 263383. I added the details intake, clicked save and the information copied over to the grading details.
Please test and if accepted:
Create and AfterAdd formula under GradingDetail
Formula name: GRADING_CopyIntake_AA

**Comment by ABonomo21** [comment]
Tested on grading permit 263395 and details page copied over.

**Comment by ABonomo21** [comment]
Did not mean to close- should be test accepted to push on March 9
