### ISSUE TITLE
Grading Permit - Condition Bypass

### ISSUE THREAD

**Issue by ABonomo21** [dhenry-KCI/FredCo-Post-Go-Live-#381]
It is not allowing me to do a resubmit at intake review for grading permit 262030 because it is being blocked by the condition for the related to a parent. 

Like all other conditions this one should be bypassed if the result of an intake review is a resubmit 

![image](https://user-images.githubusercontent.com/47611580/74172324-0a038280-4bfe-11ea-8387-d2b6dc1c9ec9.png)

**Comment by calequin** [comment]
added formula GRADING_ParentCondition2_SCF to the "All Condition(s) must be Resulted" status check

**Comment by ABonomo21** [comment]
tested 263344 did not bypass the condition

**Comment by calequin** [comment]
tested on 263347
once approved please promote GRADING_ParentCondition3_SCF

**Comment by calequin** [comment]
PROMOTED ON 2.16.2020

**Comment by emilypearl1** [comment]
Reopening Ticket #264958  Status Check- All Conditions must be Resulted. Condition has been resulted. 

![image](https://user-images.githubusercontent.com/58855801/74676507-27979580-5184-11ea-941b-95e722977dbc.png)

![image](https://user-images.githubusercontent.com/58855801/74676465-1d759700-5184-11ea-97c5-6e8d146faee3.png)

Going to supervisor override it to get it out of being stuck

**Comment by ABonomo21** [comment]
261981- this needs to be addressed no the condition even tho it is marked yes will not progress the permit either.... 
![image](https://user-images.githubusercontent.com/47611580/74753572-4eb29d80-523e-11ea-8fb3-4fdeba4bb2a2.png)

![image](https://user-images.githubusercontent.com/47611580/74753631-65f18b00-523e-11ea-9469-b693010b7d32.png)

**Comment by ABonomo21** [comment]
@calequin

**Comment by calequin** [comment]
TESTED ON 263348. Once tested and approved please promote
GRADING_ParentCondition4_SCF

**Comment by emilypearl1** [comment]
Tested in test- Worked! please promote to PRODUCTION

**Comment by calequin** [comment]
promoted on 2.23.2020
