### ISSUE TITLE
Grading Permit spawned from a Non Res BLDG 

### ISSUE THREAD

**Issue by ABonomo21** [dhenry-KCI/FredCo-Post-Go-Live-#382]
grading permit 262030 appears to have spawned from a non-res permit, which was correct 

however, it went to intake review instead of awaiting application resubmit like it should have , thoughts? 
![image](https://user-images.githubusercontent.com/47611580/74172493-5484ff00-4bfe-11ea-916d-0daf34bfffc9.png)

**Comment by megisys** [comment]
IT is linked to the other issue

![image](https://user-images.githubusercontent.com/47392306/74177838-826f4100-4c08-11ea-8c33-85fba95658ec.png)

**Comment by calequin** [comment]
fixed the formula on issue 381 and fixes this one.

**Comment by calequin** [comment]
tested with 263332

**Comment by ABonomo21** [comment]
tested 263285

**Comment by ABonomo21** [comment]
![image](https://user-images.githubusercontent.com/47611580/74359862-07d22d00-4d92-11ea-8c03-e428643aa50f.png)

**Comment by calequin** [comment]
PROMOTED ON 2.16.2020
