### ISSUE TITLE
Project - Blanket - Missing "Items" on the Blanket Details Page

### ISSUE THREAD

**Issue by ABonomo21** [dhenry-KCI/FredCo-Post-Go-Live-#385]
Source:
Repository: kcigeospatial / Fred_Co_Land-Management
Ticket #: 2338
Requested By: Ashlye Bonomo
[Jump to this repository](https://github.com/kcigeospatial/Fred_Co_Land-Management/issues/2338)

Request:
The remaining blanket items that are missing in IPS11 needed new codes because they were over 10 characters. A spreadsheet was provided. Need to confirm these items have made it into IPS11 post go-live.

**Comment by JuanitaMiles** [comment]
Use the "New Code" column for the highlighted items to confirm if these have been updated and now show in the IPS system. Spreadsheet attached below.

[Blanket_Codes.xlsx](https://github.com/dhenry-KCI/FredCo-Post-Go-Live-/files/4186939/Blanket_Codes.xlsx)

**Comment by pooldaddy** [comment]
Dan & I added these new codes to PROD Thursday
