### ISSUE TITLE
CDR Common - Bond Class Type Cleanup

### ISSUE THREAD

**Issue by ABonomo21** [dhenry-KCI/FredCo-Post-Go-Live-#386]
Source:
Repository: kcigeospatial / Fred_Co_Land-Management
Ticket #: 2321
Requested By: Ashlye Bonomo
Jump to this repository

Request:
Would like to clean up the available Bond Class types. This needs to be done in the Code Definition Management as a business as usual task. Types would be expired, not deleted.

Ensure Planning and Building look through these types.
![image](https://user-images.githubusercontent.com/47611580/74251389-11886180-4cba-11ea-91be-1d045606dbdb.png)

**Comment by JuanitaMiles** [comment]
Emily and Ashley Reed should review the lists of Bond Type and Classes below first to mark which ones they would like to keep.
[Bond_Types.xlsx](https://github.com/dhenry-KCI/FredCo-Post-Go-Live-/files/4186912/Bond_Types.xlsx)
[Bond_Classes.xlsx](https://github.com/dhenry-KCI/FredCo-Post-Go-Live-/files/4186916/Bond_Classes.xlsx)

**Comment by emilypearl1** [comment]
Emily needs the following Bond Types:
[Bond Type.pdf](https://github.com/dhenry-KCI/FredCo-Post-Go-Live-/files/4187227/Bond.Type.pdf)

For Bond Classes-  I would like to clean these up at a later time- we currently have bonds that are being held within the Towns (slowly dwindling) so we are unable to get rid of the Town Classes until all the Town Bonds are at zero balance. **### Is this something that Jeff (IIT) can clean up once all the town Bonds are gone?** 

Please check with Ashley Reed for her needs.

**Comment by MLWilkins** [comment]
Planning needs to keep APFO, CELL, and DRE as Bond Types.  Also recommend sharing the list with Vijay Kapoor and Eric Dodson to make sure they dont use some of these.
Based on above Planning will hold off on reviewing Bond Class

![image](https://user-images.githubusercontent.com/50637067/74767704-5a5d8e80-5255-11ea-8aa1-2cc62d54c539.png)

**Comment by pooldaddy** [comment]
Would like to do both Bond Type & Class at the same time.  
@MLWilkins can you review Bond Class.
@JuanitaMiles can you get input from Vijay Kapoor and Eric Dodson as Mike suggests above.

**Comment by JuanitaMiles** [comment]
@pooldaddy Both Mike and Emily have agreed to wait to assess the Bond Class options until a later time. I have already confirmed with Emily that Vijay and Eric do not handle bonds and that she has already taken into consideration the types that they would be involved in anyway.

Can we move forward with the Bond Types?

**Comment by pooldaddy** [comment]
Bond Class review delayed per Emily.  The following unused Bond Types expired in TEST with a 3/19/2019 expiry date.
![image](https://user-images.githubusercontent.com/47391482/77100405-f2cd6700-69eb-11ea-9198-2daa1ffc7351.png)

Please verify and I will complete in Production

**Comment by pooldaddy** [comment]
Correction 3/20/2020 expiry

**Comment by pooldaddy** [comment]
yikes 3/19/20  LOL!

**Comment by emilypearl1** [comment]
Confirmed- roll it to production!

**Comment by pooldaddy** [comment]
Done in PROD see below:
![image](https://user-images.githubusercontent.com/47391482/77101531-d9c5b580-69ed-11ea-969a-ca369a2d3a8c.png)
