### ISSUE TITLE
System Wide - Expiring Old Inspectors or Employee Records

### ISSUE THREAD

**Issue by ABonomo21** [dhenry-KCI/FredCo-Post-Go-Live-#387]
Source:
Repository: kcigeospatial / Fred_Co_Land-Management
Ticket #: 2180
Requested By: Ashlye Bonomo
Jump to this repository

Request:
Ticket originally addressed the need to expire old inspectors that are showing as available to assign and result inspections in IPS. (WSummer, JWilhelm).

This can be expanded to included any staff that does not work at the County any longer.

This should be moved to current github and assigned to Jeff Wisner, like to the log clean up. We should expire all old employee records..

**Comment by JuanitaMiles** [comment]
When old employees are expired, we need to ensure that the licenses they used up in IPS go back into the pool of available licenses. I don't know if this happens automatically or if they need their licenses manually removed.

**Comment by pooldaddy** [comment]
Created 2 Batch Manager Jobs to do the following:
1. Expire any employee which does not have a user record. One time only.
2, Expire users who have not logged into the system in 90 days.  Employee record to be expired and any associated roles/licenses removed.  This job scheduled to run the 1st of each month.

See SBM jobs below:

![image](https://user-images.githubusercontent.com/47391482/75583414-8807bc00-5a3b-11ea-9b57-c9adcd63f07d.png)

Need to promte to Production
