### ISSUE TITLE
System Wide - Log Type Clean Up

### ISSUE THREAD

**Issue by ABonomo21** [dhenry-KCI/FredCo-Post-Go-Live-#388]
Source:
Repository: kcigeospatial / Fred_Co_Land-Management
Ticket #: 995
Requested By: Ashlye Bonomo
[Jump to this repository](https://github.com/kcigeospatial/Fred_Co_Land-Management/issues/995)

Request:
Log types in IPS need to be cleaned up. Ashlye indicated a list was provided to County IIT to complete this task.

Due to changes in County IIT staff, we will need to confirm if this task was completed, if not, who will complete. (See original issue)

**Comment by JuanitaMiles** [comment]
The original list for cleanup may need to be provided again to Jeff W. Jeff please advise if you need the list and we can reach out to Ashlye to see if she still has it or if it needs to be recreated.

**Comment by pooldaddy** [comment]
@ABonomo21 just a reminder to resend the list to me Thanks.

**Comment by pooldaddy** [comment]
Attached a spreadsheet of active codes from PROD
[Active_Codes_By+Module_PROD_4022020.xlsx](https://github.com/dhenry-KCI/FredCo-Post-Go-Live-/files/4421968/Active_Codes_By%2BModule_PROD_4022020.xlsx)

**Comment by ABonomo21** [comment]
moved to future phase
