### ISSUE TITLE
System Wide - Expiring Hansen7 Milestones in IPS

### ISSUE THREAD

**Issue by ABonomo21** [dhenry-KCI/FredCo-Post-Go-Live-#389]
Source:
Repository: kcigeospatial / Fred_Co_Land-Management
Ticket #: 1241
Requested By: Ashlye Bonomo
Jump to this repository

Request:
This ticket was created as a reminder to expire the old stage progression statuses/milestones from Hansen7 post go-live.

**Comment by pooldaddy** [comment]
Reviewed All milestones across all ap types in all modules.
There were only 2 milestone records with a display order greater than the Complete milestone.  These 2 hi lited records below  (RESBLDG & DEMOLITION) expired with a date of 12/6/2019.
![image](https://user-images.githubusercontent.com/47391482/77096468-c1ea3380-69e5-11ea-9ca7-6d25f2f384be.png)

![image](https://user-images.githubusercontent.com/47391482/77096571-e6dea680-69e5-11ea-8606-e61ab6107b0f.png)

Will do in production once verified
