### ISSUE TITLE
P& I hold

### ISSUE THREAD

**Issue by ABonomo21** [dhenry-KCI/FredCo-Post-Go-Live-#39]
entered log did not create a condition 
![image](https://user-images.githubusercontent.com/47611580/71022781-4a97c180-20cf-11ea-9e63-68e62fe0c485.png)

**Comment by ABonomo21** [comment]
need condition type on all building a/ps

**Comment by ABonomo21** [comment]
U & O hold also

**Comment by ABonomo21** [comment]
THIS DID NOT WORK ! 190433 ADDED LOG AND IT DID NOT GENERATE THE CONDITION

**Comment by megisys** [comment]
BP_Hold_Notification_AAF - Promote to Prod
