### ISSUE TITLE
Planning - NID and VERIFY - Add Completeness Check Milestone

### ISSUE THREAD

**Issue by ABonomo21** [dhenry-KCI/FredCo-Post-Go-Live-#391]
Source:
Repository: kcigeospatial / Fred_Co_Land-Management
Ticket #: 2096
Requested By: Mike Wilkins, Ashley Reed
Jump to this repository

Request:
The Completeness Check/Intake Review milestone needs to be added to the workflow for the NID and VERIFY application types.

**Comment by MLWilkins** [comment]
@calequin can you explain upcoming release? This is already a function in other AP types. We were talked out of having this on these AP types during development but since go live we discovered we need this.

**Comment by calequin** [comment]
Hi Mike, it was added as Enhancement since the current configuration is not in the system. I plan on creating the configuration within the next day as have is a test ready for approval.

**Comment by calequin** [comment]
The label is a bit misleading my aplogies

**Comment by MLWilkins** [comment]
Please assign to MLWilkins and AREED when ready for testing.

**Comment by MLWilkins** [comment]
marking this as a High Priority because customers are submitting the wrong work types under Verification and therefore paying the wrong fees.

**Comment by megisys** [comment]
Email sent on this. Agree it is high urgency change. Need approval of hours for changes

**Comment by MLWilkins** [comment]
Reference ticket 2096 from previous repository.

**Comment by JuanitaMiles** [comment]
Identified as a short list enhancement item for Dan to indicate level of effort and potential work sooner rather than later. Assigning to Dan for tracking.

Meeting scheduled for 2/26 to discuss with team.

**Comment by JuanitaMiles** [comment]
Agreed this will be addressed and delivered March 9th. Taking the high priority label off.

**Comment by megisys** [comment]
PLN_INTAKEREVIEW_NMF - Needs to be promoted
Permissions need to be moved
New Milestones to be created
Milestone Expiration Updated
New Conditions Added
Notifications added
Status Checks Added

**Comment by megisys** [comment]
PLease Test this in Test and Let me know.

**Comment by MLWilkins** [comment]
got R4C error on NID submittal.

![image](https://user-images.githubusercontent.com/50637067/76530748-90ec8a80-644a-11ea-95bf-fee30c194839.png)



On Verify I could not save intake review result.  Save and Save/close buttons not functioning.

![image](https://user-images.githubusercontent.com/50637067/76531241-49b2c980-644b-11ea-9068-937886861d44.png)

**Comment by megisys** [comment]
Hi Mike,

Adjustment have been made..

**Comment by MLWilkins** [comment]
VERIFY looks good.



NID- got this error when trying to result the under review review.
![image](https://user-images.githubusercontent.com/50637067/76849091-2016eb00-681b-11ea-9687-76162b0a34ca.png)

Even though nothing is in logs and its still under review, I received two "application finalized" emails!
![image](https://user-images.githubusercontent.com/50637067/76849662-31acc280-681c-11ea-806f-bbcd997f2273.png)


R4C still shows under review
![image](https://user-images.githubusercontent.com/50637067/76849711-5143eb00-681c-11ea-9770-4297ca99714b.png)


R4C says under review
![image](https://user-images.githubusercontent.com/50637067/76849585-0cb84f80-681c-11ea-858b-5f3c233dc7c0.png)

**Comment by megisys** [comment]
Sorry Mike.. Can you try now.. I forgot about a milestone

**Comment by MLWilkins** [comment]
Both NID and Verify look good!
