### ISSUE TITLE
Planning - Update Application Status Check Names for R4C Display

### ISSUE THREAD

**Issue by JuanitaMiles** [dhenry-KCI/FredCo-Post-Go-Live-#394]
Rather than going the route of trying to change the product to allow the County to choose which status checks should display on R4C, we will try changing the description of the status check that shows on R4C to allow for more clarification to the applicant that the status checks are for internal county staff to complete.

Original ticket copied below for reference:
Source:
Repository: dhenry-KCI / FredCo-Post-Go-Live-
Ticket #: 285
Requested By: Mike Wilkins
Jump to this repository

Request:
This is a request to look into the ability to select which Status Checks we want to show to the applicant on R4C. Currently this is not possible, the only thing that can be done is to change the language of the status check.

**Comment by JuanitaMiles** [comment]
@MLWilkins @AReed327 Please determine what prefix you would like to add to your status check descriptions to tell the applicant the status check is for internal staff to complete. For example, "Internal Staff Only - All Reviews must be Resulted" Once this language is provided, we can assign to Jeff to complete.

**Comment by MLWilkins** [comment]
@calequin is there a way to get a list of all the status checks for each planning AP type? Otherwise we will need to create on of each AP type and monitor the status checks that are showing in the portal. Just wondering if there is a faster way.

**Comment by calequin** [comment]
@MLWilkins I can provide an excel sheet with the status checks listed via a sql database search. This should give you a nicer look on what status check we have. The pain comes with actually updating the verbiage. The update would require us to go into each of those in the application type workflow and update them per milestone. I can provide the sheet within the next day or so.

**Comment by MLWilkins** [comment]
Thank you Christian! That will be a big help!

**Comment by calequin** [comment]
email sent with excel document to @MLWilkins  and @AReed327 . Once updated please relabel it back to myself or @JuanitaMiles  for promotion

**Comment by JuanitaMiles** [comment]
[Frederick County Mileston Status Check_Planning.xlsx](https://github.com/dhenry-KCI/FredCo-Post-Go-Live-/files/4200593/Frederick.County.Mileston.Status.Check_Planning.xlsx)

**Comment by MLWilkins** [comment]
per 2/21/20 email with Juanita, Planning will go through spreadsheet when we can and ultimately assign this task to IIT

**Comment by ABonomo21** [comment]
moved to future phase
