### ISSUE TITLE
Building Permits - Capacity - Fee Needs to be Unexpired

### ISSUE THREAD

**Issue by JuanitaMiles** [dhenry-KCI/FredCo-Post-Go-Live-#395]
Jeff, please see below. We need to confirm that the fee mentioned below is no longer expired in the system.

Source:
Repository: kcigeospatial / Fred_Co_Land-Management
Ticket #: 2358
Requested By: Lauren Englar / Juanita Miles
Jump to this repository

Request:
Lauren E. reported that **RESIDENTIAL SEWER FEE 21400** is missing in IPS and needs to be made available with a value of **$7509.00**

Per email exchange with Dan (12/5/2019 11:49 AM), I communicated the following information:
FYI – The Fee exists in IPS it just shows as expired. I asked Lauren if it should be expired and she said it should not. I told her that if it comes over in the final migration as being expired still, we will unexpire it.

Marking as a post go live correction.

Need to confirm if this has been addressed.

**Comment by megisys** [comment]
This fee is up to date, but I am not sure if the formula will reflect this.. This will need to be monitored and if change is required Jeff will not be able to address this
