### ISSUE TITLE
Home Occupation for Daycare-Number of Children

### ISSUE THREAD

**Issue by awhite806** [dhenry-KCI/FredCo-Post-Go-Live-#396]
The box for Number of Children for a Home Daycare is not on the details page. We need to have this information for Home Daycares.
![image](https://user-images.githubusercontent.com/58981029/74266552-794aa680-4cd2-11ea-9d82-0f69ffc13aec.png)
![image](https://user-images.githubusercontent.com/58981029/74266644-a13a0a00-4cd2-11ea-9af1-2df88afeb026.png)

**Comment by calequin** [comment]
Added numerical field to detail page in test. Once tested and approved please promote the following:
Module: Use
Ap Type: Homeoccupation
Detail Page: Home occupancy Intake Details
Add edit box - If Home Daycare # of children
Show in portal = True
Bind to = NOCHILD
save and generate  to rhythm prod
InforClient.AgencyCDR.UseApplet.HomeOccupancyIntakeDetails

**Comment by ABonomo21** [comment]
![image](https://user-images.githubusercontent.com/47611580/74359690-b7f36600-4d91-11ea-943a-1436cc7456cb.png)

**Comment by calequin** [comment]
PROMOTED ON 2.16.2020
