### ISSUE TITLE
Non Res- New Tenant No Change-Building fee did not generate

### ISSUE THREAD

**Issue by awhite806** [dhenry-KCI/FredCo-Post-Go-Live-#397]
The minimum building fee ($49)for a New Tenant No Change permit did not generate. The only time it should not generate for this type of permit is if it is an EXP walkthough. This permit has the priority code of P2 and should have the building fee.
![image](https://user-images.githubusercontent.com/58981029/74271444-e82bfd80-4cda-11ea-90f7-036fdc6a0881.png)
![image](https://user-images.githubusercontent.com/58981029/74271741-6ab4bd00-4cdb-11ea-9e8a-62515edf6d04.png)

**Comment by JuanitaMiles** [comment]
reassigning to christian since Jeff is on vacation.

**Comment by calequin** [comment]
Fixed in test. once approved please promote
NONRESBLDG_Fee_BLDGMinimum_AOC

**Comment by ABonomo21** [comment]
failed tested in test permit 263356

**Comment by ABonomo21** [comment]
![image](https://user-images.githubusercontent.com/47611580/74834827-2ed8b380-52ea-11ea-964e-f0311b3e4c45.png)

**Comment by calequin** [comment]
sent email to Juanita to gather requirements on this. Need to know all possible scenarios on when this fee is added. Per formula there seems to be a bunch of different variables.

**Comment by ABonomo21** [comment]
FOR NON RES BLDG ONLY-  

the minimum building fee should add when the construction type is equal to NOCHANG or OWNERCH except when the priority code is equal to EXP

the minimum building fee should also add on construction types of FOUN-SLAB and MINOR

**Comment by calequin** [comment]
added the above logic to nonres blfg minimum fee. tested on 263356 by jumping milestone
Please test and once approved promote formula below:
NONRESBLDG_Fee_BLDGMinimum_AOC

**Comment by calequin** [comment]
promoted on 2.23.2020
