### ISSUE TITLE
Revision Fee Generating when Health Department Results as Resubmit

### ISSUE THREAD

**Issue by mlibbey131** [dhenry-KCI/FredCo-Post-Go-Live-#398]
Health Department resulted their review as a resubmit. They were the only agency to result their review as a resubmit and the $27.00 Revision fee generated. A revision fee should not generate if the Health Department is the only department to result their review as a resubmit. Permit# 260669

![260669](https://user-images.githubusercontent.com/58980189/74273490-8ec5cd80-4cde-11ea-8595-2c6356f03689.png)
![image](https://user-images.githubusercontent.com/58980189/74273713-e49a7580-4cde-11ea-8f36-771bbb9addda.png)

**Comment by calequin** [comment]
Fixed in test. Please promote once accepted
Formula: BLDG_PWDRNoRevisionFee_AOC

**Comment by ABonomo21** [comment]
tested on 261959

**Comment by calequin** [comment]
promoted on 2.16.2020
