### ISSUE TITLE
Grading Expired Notices- Added by Batch Manager

### ISSUE THREAD

**Issue by emilypearl1** [dhenry-KCI/FredCo-Post-Go-Live-#399]
The expired grading notices are being added by the batch manager every day at the same time on permits. 
Example: 189095
![image](https://user-images.githubusercontent.com/58855801/74333489-0985fb80-4d66-11ea-8f43-4177406d961a.png)

Also: 68005
![image](https://user-images.githubusercontent.com/58855801/74333585-376b4000-4d66-11ea-9868-f98e4d4342c3.png)

Are these notifications being sent out??

**Comment by JuanitaMiles** [comment]
Christian, this may be connected to Dan's work on extensions and expirations. Please confirm, and assign to Dan if it is.

**Comment by calequin** [comment]
need to promote once approved
Formula
BP_ExtensionRequest_AA

**Comment by calequin** [comment]
once formula BP_ExtensionRequest_AA is promoted need to add Batch_BP_Expiration_BCT back to the batch manager job = Expire Building Permits in PROD

**Comment by calequin** [comment]
promoted and enabled batch manager on 2.23.2020
