### ISSUE TITLE
Planning - BOE Reviewer on PWCONSTRUC in PDOX

### ISSUE THREAD

**Issue by AReed327** [dhenry-KCI/FredCo-Post-Go-Live-#400]
Project Number - PW257666
Observed behavior - BOE will not add to PWCONSTRUC
Expected behavior - Need to be able to add BOE as a reviewer on PWCONSTRUC. Unclear if this is IPS or PDOX causing the issue. 
Screenshot -
![image](https://user-images.githubusercontent.com/58854333/74365465-29d0ad00-4d9c-11ea-8ffd-e4f6d10dbfc6.png)

**Comment by calequin** [comment]
BOE was not a review type under PWCONSTRUC. I have added it as a available review and also added it to the ProjectDoxReviews in code definition management.
Live in PROD and Test

**Comment by AReed327** [comment]
It worked:)
