### ISSUE TITLE
PLANNING - adjusting due date - insufficient access

### ISSUE THREAD

**Issue by AReed327** [dhenry-KCI/FredCo-Post-Go-Live-#404]
Trying to change BOE due date because it didn't transfer from PDOX. I need access to view this review

![image](https://user-images.githubusercontent.com/58854333/74372164-33f8a880-4da8-11ea-9833-65793062f78b.png)
![image](https://user-images.githubusercontent.com/58854333/74372240-5094e080-4da8-11ea-98d2-29480268cbbd.png)

**Comment by JuanitaMiles** [comment]
Updated access control on the Super User role. Log out and back in and try again.

**Comment by AReed327** [comment]
it worked. Closing ticket.
