### ISSUE TITLE
System Wide - Notification Redesign Task

### ISSUE THREAD

**Issue by JuanitaMiles** [dhenry-KCI/FredCo-Post-Go-Live-#405]
Creating a general ticket assigned to Dan as a placeholder for the notification redesign task. For tracking purposes.

**Comment by megisys** [comment]
#245  Needs to be actioned as well during this task

**Comment by JuanitaMiles** [comment]
Identified as a short list enhancement item for Dan to indicate level of effort and potential work sooner rather than later. Assigning to Dan for tracking.

**Comment by JuanitaMiles** [comment]
Per discussion with Dan and Ashlye on 2/26...Notifications now appear to be stable and working. Ashlye has agreed to not move forward with the full notification redesign at this time. If we continue forward and something comes up in the future that makes us need to revisit we will do so. Closing this ticket, will reopen if staff decides it is needed in the future.

We will, however, need to move forward with the Inspector Photos notifications. I will reopen that ticket and assign to Dan for an updated level of effort. (ticket #245 )
