### ISSUE TITLE
Error Generating when Starting Case from Service Request

### ISSUE THREAD

**Issue by mlibbey131** [dhenry-KCI/FredCo-Post-Go-Live-#406]
When Kathy is trying to create a case from a service request she receives his error. When Ashlye and I tried to replicate the issues we were able to create the case. Can we check to see if this is a permissions issue for Kathy Evans

Service request 1729; Case created was 257686. 

![Case# 1729](https://user-images.githubusercontent.com/58980189/74447360-3a8a2d00-4e47-11ea-8eac-613d66a880aa.jpg)

**Comment by JuanitaMiles** [comment]
Added customer service license to Kathy's user. She'll need to log out and back in to Production and try again.

**Comment by ABonomo21** [comment]
Thank you.
