### ISSUE TITLE
New report request - variation of MDE Quarterly for ECS

### ISSUE THREAD

**Issue by TaraF** [dhenry-KCI/FredCo-Post-Go-Live-#407]
@pooldaddy - Jeff W:

This request is from Eric Dodson, they need another version of the MDE Quarterly report they can run in excel (just make the report, and deploy it as SSRS instead of PDF) - but it needs to be in the format of the attached PDF:
[6.4.2_2019_10.01.2019-12.31.2019_EDodson.xlsx](https://github.com/dhenry-KCI/FredCo-Post-Go-Live-/files/4200798/6.4.2_2019_10.01.2019-12.31.2019_EDodson.xlsx)

The existing report should NOT be overwritten, just another version made for this purpose.

MDE Quarterly Report (IPS report name) 
rpt_MDE_QrtRpt_Grading_Permits_Over_1AC  (SSRS report name)

thanks!

**Comment by pooldaddy** [comment]
![image](https://user-images.githubusercontent.com/47391482/78009154-98e37000-730e-11ea-9a66-4338320667eb.png)
[MDE_Qtr_Grading_Permits_excell.xlsx](https://github.com/dhenry-KCI/FredCo-Post-Go-Live-/files/4407899/MDE_Qtr_Grading_Permits_excell.xlsx)

**Comment by pooldaddy** [comment]
![image](https://user-images.githubusercontent.com/47391482/78027134-dbb34100-732a-11ea-973a-c16e481234fd.png)
