### ISSUE TITLE
Building Permits - Review of Under Review/Applicant Revisions Between IPS & PDox Needed

### ISSUE THREAD

**Issue by JuanitaMiles** [dhenry-KCI/FredCo-Post-Go-Live-#408]
We need a session to review the communication between IPS and ProjectDox when the application goes through the Awaiting Applicant Revisions milestone. 

Ashlye B. noted some issues where applications were requiring R4C Applicant Actions and PDox Applicant Resubmit tasks to be completed before progressing forward.

**Comment by JuanitaMiles** [comment]
I've let @dhenry-KCI know that a meeting has been requested.

**Comment by JuanitaMiles** [comment]
I will try to run a few tests to see if I can identify the issue Ashlye has mentioned above, then follow up with her to see if further action/bug fix needs to happen.

**Comment by ABonomo21** [comment]
closing for now will re-open if occurs
