### ISSUE TITLE
JHagy2 (DUSWM) cannot N/A other reviews on DUSWM-only plans

### ISSUE THREAD

**Issue by MLWilkins** [dhenry-KCI/FredCo-Post-Go-Live-#41]
this is a leftover paper ticket.  The paper ticket used DOLS as an example of an agency JHagy couldnt waive.  He can now waive DOLS but no others. He needs this ability on every review that generates on a PWConstruct.

![image](https://user-images.githubusercontent.com/50637067/71027191-bf232e00-20d8-11ea-9979-3c1eb377e252.png)

**Comment by calequin** [comment]
Added this ability to result the following reviews to his role DUSWM_WITH_FEES
![image](https://user-images.githubusercontent.com/47603568/71040015-35c92700-20eb-11ea-9e61-0326493b0679.png)
