### ISSUE TITLE
Planning-IPS not sending resubmit notification at intake review on Verification Letters-also not sending fee notification

### ISSUE THREAD

**Issue by MLWilkins** [dhenry-KCI/FredCo-Post-Go-Live-#410]
When resulting a intake review as "resubmit" the notification to the applicant stating more information is required is not sending.  Had a customer waiting three weeks on multiple verification letter APs not knowing they needed to do anything else.

FYI, this notification is working on Site, Plat, and PWCons.

![image](https://user-images.githubusercontent.com/50637067/74527494-d83b3600-4ef3-11ea-9f83-fa21a8572404.png)

![image](https://user-images.githubusercontent.com/50637067/74527523-eb4e0600-4ef3-11ea-9478-e80081240950.png)

**Comment by MLWilkins** [comment]
fee notifications are also not being sent on Verification letters

**Comment by JuanitaMiles** [comment]
In regards to the fees due notification not sending...this may be related to old GitHub issue 1798. I believe there may have been an issue where notifications weren't sending for fees if the application was submitted through R4C but they would send if it was being processed completely back office, it looks like the potential outcome was to create a fees reminder notification but this old ticket was never marked as "post go live correction" and therefore not tracked moving forward.

[Jump to old ticket](https://github.com/kcigeospatial/Fred_Co_Land-Management/issues/1798)

These are just my observations, please confirm to be sure this is still the case and we can decide if the fee reminder notification is still a desired item.

**Comment by MLWilkins** [comment]
We just need the standard fee notification to send on this ap type, same that is sent on all other AP types. I don’t think we need a different approach. Also need the “more infor is required” notification as noted above.

**Comment by calequin** [comment]
Hi Team,
Spoke to Dan about this ticket. This goes hand in hand with the completeness check enhancement for VERIFY ap types. This was configured in a different workflow because of the pay for service nature of these AP types. Constituents apply online, pay the fees, county verifies the letter and application closes. The Review portion was not designed to send out notifications like the other AP types. @JuanitaMiles a bigger discussion and review of this can be proposed with the county, solution architect and team.

Aside from this resubmittal portion, the pay fees notification is indeed active on this AP type and functioning.

**Comment by MLWilkins** [comment]
@calequin  every application type should have been configured to send a notification when the review is resulted as "resubmit".  We never discussed, or agreed, that Verification letters would not send out this type of notification.  If you look at Ticket 1798 that Juanita provided a link to in her comment above, you can see that this notification was created before go live.

**Comment by MLWilkins** [comment]
see below.  The fee notification was created and working in September 2019

![image](https://user-images.githubusercontent.com/50637067/74971713-895b3800-53ee-11ea-8c56-a74272ac70e0.png)

It worked for a day then it was broken.  Dan was to fix it.

![image](https://user-images.githubusercontent.com/50637067/74971832-b7d91300-53ee-11ea-91aa-8b6374a07c58.png)

**Comment by megisys** [comment]
Adjusted the Notifications as per other planning applications

**Comment by MLWilkins** [comment]
@megisys Was this change also made in test?

**Comment by megisys** [comment]
Yes, should be in test the same

**Comment by MLWilkins** [comment]
Tested in Test.  V258833.  

fee notification looks good.

![image](https://user-images.githubusercontent.com/50637067/75038164-d3422d80-5483-11ea-94aa-c8c33abc8f77.png)

**Comment by MLWilkins** [comment]
the "more information is required" notification still not working when resulting verification review as resubmit.

![image](https://user-images.githubusercontent.com/50637067/75038439-5e232800-5484-11ea-9415-0b959f38f24b.png)

![image](https://user-images.githubusercontent.com/50637067/75038481-72672500-5484-11ea-829e-1b94a74d0e18.png)

**Comment by megisys** [comment]
![image](https://user-images.githubusercontent.com/47392306/75039069-dd652b80-5485-11ea-8e58-c7344fd2a623.png)

**Comment by megisys** [comment]
Was not copied to test. My apologises.. See now..

**Comment by MLWilkins** [comment]
tested in test, V258834.  Did two resubs and got notifications for each. Approved project and closed and received approval notification.  All notifications are working smoothly.


![image](https://user-images.githubusercontent.com/50637067/75046954-012f6e00-5494-11ea-9cb2-bb38ff6f2be3.png)
![image](https://user-images.githubusercontent.com/50637067/75047195-59667000-5494-11ea-82df-4050f66d7190.png)
![image](https://user-images.githubusercontent.com/50637067/75047379-a6e2dd00-5494-11ea-85ee-76ab133be7d0.png)
