### ISSUE TITLE
Priority Codes for Use Permits

### ISSUE THREAD

**Issue by awhite806** [dhenry-KCI/FredCo-Post-Go-Live-#412]
Priority Code is not required for processing the reviews – L257944  The following is what comes up when you open priority on land use temp outdoor activity applications.
Reviews are defaulting to 1 week due date. 
 
Ashlye would prefer to use the priority codes but at a minimum the review for landuse needs to be 2 weeks ! 
![11](https://user-images.githubusercontent.com/58981029/74548220-71ca0e00-4f1b-11ea-8bd9-831f520783f9.png)

**Comment by calequin** [comment]
do we need to create workflow for the same priority codes as building or just set the normal due dates to reflect as 2 weeks by default?

**Comment by ABonomo21** [comment]
we can just set the normal due date to reflect two weeks by default.

**Comment by ABonomo21** [comment]
is this something we can do ourselves as review times may change in the future- otherwise this is something we can probably wait for IIT to attempt- there are not many use permits processed at this point in the season.

**Comment by ABonomo21** [comment]
@JuanitaMiles FYI see above.

**Comment by JuanitaMiles** [comment]
IIT can probably get some training on this then implement updated review windows in the future. Will leave for Jeff.

**Comment by megisys** [comment]
I would just leave this as standard date entry against the review types in workflow

**Comment by JuanitaMiles** [comment]
Reassigning to @calequin due to minimal work on 2/24

**Comment by calequin** [comment]
changed the review due dates to be 10 business days - 2 weeks
![image](https://user-images.githubusercontent.com/47603568/75187339-7b1f5b80-570f-11ea-9796-ff94c779f322.png)

**Comment by ABonomo21** [comment]
tested land use default due date to two weeks - L257925
