### ISSUE TITLE
HOLD to CONDITIONS

### ISSUE THREAD

**Issue by ABonomo21** [dhenry-KCI/FredCo-Post-Go-Live-#416]
It was my understanding that when a P & I hold is placed on a permit that the condition will automatically generate. That has not been occurring and was hoping Dan can confirm functionality. 

Holds are sending the correspondence. 

@megisys @JuanitaMiles

**Comment by megisys** [comment]
I need to know an AP Type. As it will likely be an Application with out theese conditions configured.

Christian can handle this. No need for me to get involved

**Comment by ABonomo21** [comment]
It is all a/p's for building and use

**Comment by megisys** [comment]
Updating the Priority on this. Christian you will need to review that the conditions exist, are named consistently and they are working for all AP Types. As you are doing the testing of this ticket for all building and use application to see which are working. I would expect this to be 4 hours effort

**Comment by calequin** [comment]
Ready for acceptance in test:
Once accepted please promote the following:
Make sure each AP type in Building Module has a PIHOLD and UOHOLD condition type available
Promote formula: BP_Hold_Notification_AAF

**Comment by ABonomo21** [comment]
tested on permit 263374
![image](https://user-images.githubusercontent.com/47611580/75069946-48cbef00-54c0-11ea-9b96-98381719b273.png)

**Comment by calequin** [comment]
Promoted on 2.23.2020

**Comment by ABonomo21** [comment]
P&I hold did not add as a condition on use permit. Added the log type of P & I hold to use permit in test
![image](https://user-images.githubusercontent.com/47611580/75463970-87e0c100-5954-11ea-8699-ee41a266711b.png)
