### ISSUE TITLE
Re-Inspection Fee did not generate

### ISSUE THREAD

**Issue by mlibbey131** [dhenry-KCI/FredCo-Post-Go-Live-#417]
Permit# 200623
Second footing inspection failed, Third footing inspection generated but no re-inspection fee generated. A $49.00 re-inspection fee should generate prior to being able to schedule the third inspection for each type of inspection. 

![image](https://user-images.githubusercontent.com/58980189/74669498-388cda80-5175-11ea-9a9c-8a36babeea20.png)

![image](https://user-images.githubusercontent.com/58980189/74669550-5ce8b700-5175-11ea-82a8-c42908456669.png)

![image](https://user-images.githubusercontent.com/58980189/74669570-696d0f80-5175-11ea-80b4-aa726115d358.png)

**Comment by calequin** [comment]
the code looks at the first of this inspection type as a failed and then if the inspection is the third one of its kind it adds a reinspection fee. In this case the first inspection type of Footing was Passed and another footing was added and failed. The code would not be able to handle this type of logic since this looks to be a one off occurrence. In a case like this a reinspection fee should manually be added.

**Comment by ABonomo21** [comment]
We will add something in the SOP that lets staff know they need to make sure if there is a manual insert that the fee must be manually added.

**Comment by ABonomo21** [comment]
I have added something to the SOP however, i would still think in this case that the system should recognize the this is the third inspection of that type and would charge the fee. the only time is should disregard the fee is if one of those inspection types is canceled or waived. 

Therefore, in this case it should have autogenerated the fee.

**Comment by megisys** [comment]
But you passed the first instance..  What happens if you have 4 inspections and we have a pass then a fail and then a pass and then a fail. Code will charge for a reinspection fee as it counts 2 failed.. If there is a pass in the history. The code will not add a reinspection fee. This will require a large change and was not previously discovered and this will need to be an enhancment and scheduled for a larger round of testing and acceptance.

**Comment by ABonomo21** [comment]
It does not matter if you pass the first two- it is charged not based on a fail it is charged based on the number of inspections for that type. 

Regardless of a partial pass, pass or fail if it is the third inspection of that type or higher it needs to charge the fee.

**Comment by megisys** [comment]
So 3 passes means a reinspection fee

**Comment by JuanitaMiles** [comment]
Christian feels this ticket will need a larger conversation surrounding the requirements of when the re-inspection fee should generate. Potentially group this in with any conversations to be had with ticket #325 .

**Comment by megisys** [comment]
This method has completely changed. If an inspection is up to its 3rd cycle reinspection fee is added regardless of previous outcomes.

**Comment by megisys** [comment]
PLease Test this and let me know your findings

**Comment by ABonomo21** [comment]
added another footing inspection to permit 200623- generated fees correctly 
![image](https://user-images.githubusercontent.com/47611580/76087875-06f17d00-5f85-11ea-882a-c89fc8d4bfcf.png)

tested an electrical by adding a new temp inspection after the previous passed - it started a new cycle count- after the 2nd it generated the fee-
![image](https://user-images.githubusercontent.com/47611580/76088280-b890ae00-5f85-11ea-990b-90481ec217e1.png)

tested another permit - with the first result as a partial pass, second as a failed, third generated the fee which is correct

![image](https://user-images.githubusercontent.com/47611580/76088382-f1308780-5f85-11ea-8c75-cc67b0e376a8.png)

then added a fourth of the same type and it generated the fee which is also correct ! 
![image](https://user-images.githubusercontent.com/47611580/76088447-132a0a00-5f86-11ea-9cc9-8f662a2f5b38.png)

**Comment by ABonomo21** [comment]
266617 tested and worked correctly first of type passed, added another of the same type went to cycle 2 - failed and the fee generated for the third of the same type
![image](https://user-images.githubusercontent.com/47611580/76089384-8da75980-5f87-11ea-9a5c-9de0e7977e13.png)

**Comment by ABonomo21** [comment]
266546 also worked 
![image](https://user-images.githubusercontent.com/47611580/76089546-d8c16c80-5f87-11ea-8ea6-6828f766a369.png)

**Comment by ABonomo21** [comment]
Juanita will double check the electrical on that did not appear to work right - if she is not able to replicate okay to be test accepted- 3 other a/p types tested appear to be working with a variation in the scenarios.

**Comment by JuanitaMiles** [comment]
Was not able to replicate the electrical on a couple examples. Marking as Test Accepted.

266744, 265433
