### ISSUE TITLE
ADU- Home builder requirement 

### ISSUE THREAD

**Issue by ABonomo21** [dhenry-KCI/FredCo-Post-Go-Live-#418]
Permit 264984 for an ADU within an accessory structure had to be supervisory override for bypass the homebuilder license requirement- a HB license is only required on Standalone/separate accessory structures - this permit was requiring the HB license on a ADU marked for within an accessory structure which should not be the case
![image](https://user-images.githubusercontent.com/47611580/74669756-cd8fd380-5175-11ea-97af-d088c6ecc313.png)

Referencing ticket # 1177 from the old repository entry from 6.24.19

![image](https://user-images.githubusercontent.com/47611580/74669642-98838100-5175-11ea-88ae-46584c0348ed.png)

**Comment by ABonomo21** [comment]
FYI this is a ticket that would normally be a high priority however, it is rare we will get another one anytime soon so I had it as a medium- i will drop to low possibly something we can have IIT attempt.

**Comment by calequin** [comment]
please test and if accepted promote
RESBLDG_LicReqResubmit_Req

**Comment by ABonomo21** [comment]
tested on 263375 worked

**Comment by calequin** [comment]
promoted on 2.23.2020
