### ISSUE TITLE
DPZ review on grading permit 

### ISSUE THREAD

**Issue by ABonomo21** [dhenry-KCI/FredCo-Post-Go-Live-#419]
We removed DPZ review from grading permits when related to a res SFD permit related to ticket #147  however, after a month of this, there have been a few issues that we found we need to make a change. 

Similar to the Driveway permits and rules set up under ticket #193 - we need to have a DPZ review on all RESBLDG permits with and occupancy types of RESSFD when not within a major subdivision.  

You will know if they are in a major subdivision because they will have an S# in the subdivision code section of the parcel details. 

We need this change because zoning has to verify FRO requirements and they do not need to do that when within a major subdivision because there would already be a mass grading plan that would have allowing the zoning reviewer to review these requirements.

**Comment by megisys** [comment]
Changing as it is not a bug and is net new discovery and a request that should be bundled

**Comment by megisys** [comment]
GRADING_DPZ_Review_AOC - Needs to be promoted once test accepted

**Comment by ABonomo21** [comment]
test confirmed- both scenarios worked ! 
Thanks 

tested within a subdivision ap 266797 related to building ap 266795
tested not in a subdivsion ap 266799 realreadt to building ap 266798

**Comment by megisys** [comment]
Deployed

**Comment by ABonomo21** [comment]
![image](https://user-images.githubusercontent.com/47611580/85032327-b249ca80-b14d-11ea-81d5-5712e0b09104.png)

**Comment by ABonomo21** [comment]
Zoning review did not generate on this grading permit until the second review. #268368

**Comment by ABonomo21** [comment]
should have generated on the first round of reviews this is not in a major subdivision
