### ISSUE TITLE
Withdrawl Request on R4C dashboard

### ISSUE THREAD

**Issue by ABonomo21** [dhenry-KCI/FredCo-Post-Go-Live-#420]
We need the request a withdrawal turned back on - i just had an applicant call me and I see it is no longer an option on the portal

**Comment by ABonomo21** [comment]
Is this something we can do ourselves from the application workflow system setup selection? @JuanitaMiles

**Comment by JuanitaMiles** [comment]
This is something I'm less knowledgeable about. If it can wait until Jeff W. comes back Christian can show him how to do it if it wasn't covered in their training. Otherwise, I would recommend Christian complete this task.

**Comment by ABonomo21** [comment]
Sounds good I have assigned it to Jeff

**Comment by JuanitaMiles** [comment]
Assigning to @calequin due to minimal work on 2/24.

**Comment by calequin** [comment]
i have added the WITHREQ log to be visible in R4C for applicants to request. Please test and if accepted needs to be manually added for each AP type in BLDG and PLN.
Application Workflow > Log Generation Links > add WITHREQ as the Log

**Comment by calequin** [comment]
if needed in USE and BL we would need to create a formula and AD-Hoc report for this log type

**Comment by ABonomo21** [comment]
tested on permit 263369 from r4c to ips test withdrawl request worked 

we need this back on all building permit a/p's - void requests on home occ and land use are minimal so we do not need for use and bl for now just building permits.
