### ISSUE TITLE
Extension requests duplicating 

### ISSUE THREAD

**Issue by ABonomo21** [dhenry-KCI/FredCo-Post-Go-Live-#421]
once we process an extension review - they are duplicating and should not 
![image](https://user-images.githubusercontent.com/47611580/74675345-5e1fe100-5181-11ea-85f6-48dff703e972.png)

See example # 189470, 188767, 189645, 189926, 169042, 161003, 153047, 147609, 188378

**Comment by ABonomo21** [comment]
the detail page should clear once the review is resulted as tested and approved on previous ticket

**Comment by ABonomo21** [comment]
@JuanitaMiles  can we make this a high priority to ensure it is done by the end of the week?

**Comment by calequin** [comment]
please test if accepted promote formula.
Test by adding an extension request log, then add the detail page information, approve review
BP_ExtensionReview_BUF

**Comment by ABonomo21** [comment]
tested in test permit 263290 worked

**Comment by calequin** [comment]
promoted on 2.23.2020
