### ISSUE TITLE
Applicant Actions page is unavailable to customers on R4C

### ISSUE THREAD

**Issue by awhite806** [dhenry-KCI/FredCo-Post-Go-Live-#422]
The Applicant Actions page is unavailable to customers for them to send in their resubmittals/change request even though the permit is in the milestone of Awaiting Applicant Revisions.
![image](https://user-images.githubusercontent.com/58981029/74678977-7f38ff80-518a-11ea-9783-6155d9b60290.png)
This is the screenshot our customer sent me. You can see the Applicant Actions page, but there is no option to edit/use the page.
![image](https://user-images.githubusercontent.com/58981029/74679012-9aa40a80-518a-11ea-952a-fedae3ea81ec.png)

**Comment by calequin** [comment]
Hi Abbie,
I believe that the person was looking up this record as opposed to being an actual applicant on this permit. When they look up an application as public they are not allowed to edit detail pages. If logged in the detail page will have the edit function available. I tried this by adding myself as an applicatn on an application that was NONRES 264678 in the Awaiting Applicant Revision milestone. The detail page is editable.
![image](https://user-images.githubusercontent.com/47603568/74752071-c0d1b500-5233-11ea-906b-a30d76d3f9d3.png)

**Comment by ABonomo21** [comment]
Christian the applicant actions detail page needs to be editable at any point in the project as an applicant can request changes at any time in the project.

**Comment by calequin** [comment]
Yes this is currently set up to take in any changes at any milestone if the user is logged in to r4c. Public cannot request or edit detail pages at all

**Comment by ABonomo21** [comment]
I confirmed with Maddison that it was available Thank you.
