### ISSUE TITLE
R4C SUBMISSION CLEAN UP 

### ISSUE THREAD

**Issue by ABonomo21** [dhenry-KCI/FredCo-Post-Go-Live-#423]
Please clean up the a/p name's on r4c some are capitalized and others are not.

**Comment by ABonomo21** [comment]
@JuanitaMiles is this something we can do ourselves in the application workflow ?

**Comment by JuanitaMiles** [comment]
Yes. It's something you can do as you have time. Practice in TEST before going into Prod if you need to. Would have given something like this to Jeff W. but he is currently out. We can give any additional ones to him once he comes back. Steps below:

1. Building Permits > Setup > Application Workflow
2. Expand Building Permits tree.
3. Right Click on the AP Type > Select 'Open Application Type'
4. Scroll down to the section for Portal Description and enter the desired name to show on the portal. If nothing is in this box, the portal is likely defaulting to the regular 'Description' field which is all caps.

![image](https://user-images.githubusercontent.com/31770504/74777681-f8f2eb00-5267-11ea-87d4-0116ffab2084.png)

**Comment by ABonomo21** [comment]
Thanks Done
