### ISSUE TITLE
PDox-batch stamp location

### ISSUE THREAD

**Issue by MLWilkins** [dhenry-KCI/FredCo-Post-Go-Live-#424]
One of the customer complaints Planning has received is the 4" x 4" area in the top left corner that must be left for our 2" x 2" batch stamp.  Can the batch stamp location be moved closer to the corner of the page?

![image](https://user-images.githubusercontent.com/50637067/74736968-dc33c480-5221-11ea-8bc5-f86cc5928c81.png)

**Comment by JuanitaMiles** [comment]
marking as an enhancement, low priority. I will compile a list of requests of this nature to send to Robert for his feedback this week.

**Comment by JuanitaMiles** [comment]
emailed Robert a list of questions, including this one, on 2/20/20 7:30pm. Will await a response.

**Comment by ABonomo21** [comment]
move to future phase list

**Comment by ABonomo21** [comment]
moved back from future list

**Comment by JuanitaMiles** [comment]
Was proposed to be part of zoom training. County IIT to coordinate zoom training with Avolve.

**Comment by AReed327** [comment]
Measured the "Planning Batch Stamp Approval" stamp. It is 3.5 inches by 3.5 inches. I believe this is the original

Measured "Planning Batch Stamp Approval Offset 2" and it is 3 inches from the top and 2 inches from the side at the lower right corner of the stamp. I don't particularly like this because it  isn't centered in the top left corner.

Can you give me some more information on which stamps I'm supposed to be testing? I tried Yociel Test and I think that's just the one you set up in the training because I couldn't get it to work. 3

Also Tested the engineering stamp and the FCPC stamp and no changes from the current one. Both 3.5 inches from the side and top.

Tested in PDOX Test PW257746

**Comment by Ycoto** [comment]
@AReed327 Sorry while I was posting the image, I noticed that the signature was missing. I am working on it, but I need the signature image to use for the batch stamp. 
![image](https://user-images.githubusercontent.com/63804011/86991044-1a4b6980-c16c-11ea-91ac-273d0ccdb3ff.png)

This is what I have at the moment

![image](https://user-images.githubusercontent.com/63804011/86991157-5bdc1480-c16c-11ea-9af1-602d76d6002f.png)

**Comment by Ycoto** [comment]
@JuanitaMiles @AReed327 @MLWilkins 

OK here is a sample image showing the original position vs the new position. They are on TestIPS and their name is Engineering Batch Stamp Approved Vijay Kapoor V2 and Planning FCPC Batch Stamp Approval V2. 

I only did 2 edits to the stamp
1) position
2) Same size logo just better resolution. 

If there is anything else you would like to add or change just let me know. Thanks

![Engineering Batch Stamp Approved Vijay Kapoor V2](https://user-images.githubusercontent.com/63804011/87049195-aab89700-c1ca-11ea-8419-f34451c27caf.JPG)

![Planning FCPC Batch Stamp Approval v2](https://user-images.githubusercontent.com/63804011/87049209-aee4b480-c1ca-11ea-8d4c-e3b6c03fbec8.JPG)

**Comment by MLWilkins** [comment]
@Ycoto  Dev Rev and Planning does not use an electronic signature.  We enter by hand the date and approver name as you can see below.

![image](https://user-images.githubusercontent.com/50637067/87056085-1d2d7500-c1d3-11ea-8862-2d1d547e3056.png)

**Comment by MLWilkins** [comment]
@Ycoto @AReed327   We will retest next week when AReed returns from vacation

**Comment by Ycoto** [comment]
Ok, Thanks.

**Comment by AReed327** [comment]
The V2's that I'm seeing now were not there last week. There was only one and it was the Planning Batch Stamp Approval Offset 2.

**Engineering Batch Stamp Approved Vijay Kapoor V2** - Looks good and measures 2x2 from top left with Vijay's signature. Test accepting this stamp.
![image](https://user-images.githubusercontent.com/58854333/87442372-39118c00-c5c2-11ea-96b4-1a461389fce8.png)

**Planning Batch Stamp Approval Offset 2** - Measures 2x2 but has Gary Hessong's signature on it and is pulling the stamp date/current date. This stamp needs to pull the approval from the edit button - Project Info --> Approval Date field. We manually enter the reviewers name and approval date there.
![image](https://user-images.githubusercontent.com/58854333/87443112-103dc680-c5c3-11ea-880f-af06b1017ad0.png)
![image](https://user-images.githubusercontent.com/58854333/87443246-39f6ed80-c5c3-11ea-94e9-3dc34f764022.png)

Planning FCPC Batch Stamp Approval v2 - Measures 2x2 but does not pull from the edit button - Project Info --> Approval Date field. We manually enter the reviewers name and approval date there.

![image](https://user-images.githubusercontent.com/58854333/87443724-d9b47b80-c5c3-11ea-8340-471c27ab62b1.png)

![image](https://user-images.githubusercontent.com/58854333/87443697-cdc8b980-c5c3-11ea-9d8d-67921e36962b.png)

Our Batch Stamps for Planning are designed for us to enter the approval date and project manager name. The approval date is not always the day it is stamped. It is the day it is approved by the Planning Commission.  The Engineering Stamp is correct that it pulls the date that Vijay stamps it.

**Comment by Ycoto** [comment]
@AReed327 Ok, they are edit and ready for Testing. Thanks

**Comment by AReed327** [comment]
Planning Batch Stamp Approval Offset 2 - **Didn't pull from the Approval Date Field** under EDIT --> Project Info - Retest Failed

![image](https://user-images.githubusercontent.com/58854333/87793967-f515c580-c813-11ea-90c7-f2554a931640.png)

Planning FCPC Batch Stamp Approval 2 - **Didn't pull from the Approval Date Field** under EDIT --> Project Info - Retest Failed

![image](https://user-images.githubusercontent.com/58854333/87794337-74a39480-c814-11ea-8c2d-8700fd931f0c.png)


![image](https://user-images.githubusercontent.com/58854333/87794486-b03e5e80-c814-11ea-9989-1b301b34470d.png)

Yaciel, Did you check to make sure that transferred before sending it back for testing? This is the 3rd time I've tested this ticked. Thanks, Ashley Reed

**Comment by Ycoto** [comment]
@AReed327 Sorry I did not add the date because I was under the impression you guys were doing it by hand, as per the message below. Also, I don't know if you recall but we talked about it on the Teams meeting and you agreed to remove the date from the stamp.

![image](https://user-images.githubusercontent.com/63804011/87795965-bf261080-c816-11ea-921c-1ee56aad930f.png)

**Comment by MLWilkins** [comment]
Sorry, by hand I meant we use the edit button and type in the approved name and date. We must have this functionality

**Comment by Ycoto** [comment]
Ready for Testing.

**Comment by AReed327** [comment]
Reviewed in PDOX Test PW257746
Planning Batch Stamp Approval Offset 2 - TEST ACCEPTED
![image](https://user-images.githubusercontent.com/58854333/88179253-9d9f9d00-cbf9-11ea-8591-a25a7b5748a1.png)

Planning FCPC Batch Stamp Approval 2 - Did not pull the Approval Date Field from Edit to the stamp. TESTING FAILED.
![image](https://user-images.githubusercontent.com/58854333/88179456-f3744500-cbf9-11ea-8383-d6c1dd1358ad.png)

**Comment by Ycoto** [comment]
Ready for Testing.

![image](https://user-images.githubusercontent.com/63804011/88180684-bd37c500-cbfb-11ea-9880-cc04a8e05f0c.png)

**Comment by AReed327** [comment]
Planning FCPC Batch Stamp Approval 2 - TEST ACCEPTED 

![image](https://user-images.githubusercontent.com/58854333/88291678-9f836200-ccc6-11ea-9f48-64c70f3c910d.png)

**Comment by Ycoto** [comment]
@MLWilkins @AReed327 @JuanitaMiles 
This 3 stamp are promoted to Production please let me know if is not working properly to fix it quickly, or if there is any way of testing it I would appreciate.  Thank you.

**Comment by JuanitaMiles** [comment]
closing this ticket since stamps were promoted to prod. if any additional issues come up with this please open a ticket in our current "Phase 2" github. this ticket can be referenced for history.
