### ISSUE TITLE
R4C-need it to be more printer friendly

### ISSUE THREAD

**Issue by MLWilkins** [dhenry-KCI/FredCo-Post-Go-Live-#425]
One of the complaints we received from customers is that printing the project record from R4C is not ideal.  The only option is to right-click  and print the page, which results in 5-7 pages (or more as the project goes thought its life cycle).  Everything is very spaced out, which is why so many pages print out. Applicants noted they need to print out the fee details to show clients each fee that is due on a project (ie showing each separate fee on an AP).  They will also need to print the agency comments, review cycle, conditions, etc.

Can R4C have a printer friendly option?  Or, can each "tab" (fees, reviews, hearings, conditions, etc.) have its own print function like Instructions currently has?  

![image](https://user-images.githubusercontent.com/50637067/74737705-616ba900-5223-11ea-8016-5c874e1a6977.png)

**Comment by ABonomo21** [comment]
moving to the project repository for monthly follow up with Mark Oliver- @JuanitaMiles @dhenry-KCI 
we need to make sure we find a way to schedule that follow up meeting with Mark Oliver to discuss what is placed in the product enhancement project. 

okay per a meeting with Ash, Gary and Juanita 3.4.2020

closing for now will track in the project
