### ISSUE TITLE
Distributor License Process

### ISSUE THREAD

**Issue by mlibbey131** [dhenry-KCI/FredCo-Post-Go-Live-#426]
Ashlye needs to go over the process for Distributor Licenses with Dan. 

License number DL10

**Comment by JuanitaMiles** [comment]
will reach out to get a meeting setup between Dan/Christian and Ashlye.

**Comment by megisys** [comment]
Christian will handle this.

**Comment by JuanitaMiles** [comment]
I've let @dhenry-KCI know that a meeting has been requested.

**Comment by dhenry-KCI** [comment]
@JuanitaMiles - i can schedule meeting. Should the meeting include Christian or Dan?

**Comment by ABonomo21** [comment]
Add renewal fees 
Pay fees
Renewal review and issue 
Complete review 

met with dan 2.26.19 confirmed in test
