### ISSUE TITLE
Planning - Unable to upload attachment from R4C

### ISSUE THREAD

**Issue by AReed327** [dhenry-KCI/FredCo-Post-Go-Live-#427]
Project Number - V258800
Observed behavior - Applicant was unable to add attachment when project was returned to them to attach documentation
Expected behavior - When the applicant has a request for resubmit, they need to be able to attach documentation
Screenshot -
![image](https://user-images.githubusercontent.com/58854333/74749166-bdd8c380-5237-11ea-9e13-bf1737637bba.png)
![image](https://user-images.githubusercontent.com/58854333/74749201-ca5d1c00-5237-11ea-87fe-1dbba94225f3.png)

**Comment by calequin** [comment]
fixed StopUploadAfterCompletenessCheck and tested on SP258797. The formula will now allow to upload attachments whenever an application is under an "AWAITING" milestone.

If accepted please promote:
Formula Name: StopUploadAfterCompletenessCheck

**Comment by MLWilkins** [comment]
test successful.  See V258828
Also tried to add attachment while under review and it did not allow me, which is correct.

**Comment by calequin** [comment]
promoted on 2.18.2020
