### ISSUE TITLE
Error when trying to result a completeness check

### ISSUE THREAD

**Issue by awhite806** [dhenry-KCI/FredCo-Post-Go-Live-#428]
permit 265020- there is an error when trying to result a completeness check.
![image](https://user-images.githubusercontent.com/58981029/74753758-96d1c000-523e-11ea-80ab-5067421b9c42.png)

**Comment by megisys** [comment]
Formula needs to be updated to have .Applicant.Contact for the Erroring Formula

**Comment by megisys** [comment]
BP_IssuePermitNotification - NEED to be Promoted
BP_FinalNotTown_AOC - Needs to be promoted

**Comment by calequin** [comment]
promoted on 2.18.2020
