### ISSUE TITLE
Planning - Fee notification did not send

### ISSUE THREAD

**Issue by AReed327** [dhenry-KCI/FredCo-Post-Go-Live-#429]
Project Number - PL258848
Observed behavior - No Fee notification went out.
Expected behavior - I expect fee notifications to be sent when the completeness check is resulted to eplans or internal review. 
This plan has two completeness checks because the first one required more information. I do not know if that has anything to do with this.
Screenshot -

![image](https://user-images.githubusercontent.com/58854333/74753791-a51fdc00-523e-11ea-8d30-0258e07ac5cf.png)

![image](https://user-images.githubusercontent.com/58854333/74754196-4313a680-523f-11ea-8cfa-7c3e84467be5.png)

**Comment by megisys** [comment]
Will need an outage tonight to address this

**Comment by megisys** [comment]
Rebuild All Required.

**Comment by MLWilkins** [comment]
Need ability to verify fix. Please label ready for test after promotion.

**Comment by MLWilkins** [comment]
confirmed that this fee notification is working in test. This ticket may be closed when promoted to prod.

![image](https://user-images.githubusercontent.com/50637067/74780359-710fdf80-526d-11ea-9075-07a0827bf1a4.png)

**Comment by calequin** [comment]
promoted on 2.18.2020
