### ISSUE TITLE
Major Grading Townhouse permits - Actual valuation issue

### ISSUE THREAD

**Issue by TMARTIN0926** [dhenry-KCI/FredCo-Post-Go-Live-#43]
When entering the major grading townhouse permit #258111 it red lined me to enter an actual valuation. On the back tab I selected not part of an overall plan which should not require an actual valuation to be entered. I had to enter $2.00 to progress it through to fees, then change the valuation to $0.00 and then waive the additional fee that was generated due to the valuation being entered. The screenshots are the corrected version. If needed, I can recreate this. 
![258111 a](https://user-images.githubusercontent.com/58991985/71028487-6012e880-20db-11ea-8018-687888391f16.PNG)
![258111 b](https://user-images.githubusercontent.com/58991985/71028488-6012e880-20db-11ea-808f-936ea5c86e73.PNG)
![258111 c](https://user-images.githubusercontent.com/58991985/71028489-6012e880-20db-11ea-8a3b-c9c2742e4a92.PNG)

**Comment by megisys** [comment]
Hi Dustin and Ashlye. As changes were made during Tiffany's absence, I am unsure what was a change in process and what is a bug. I really need a second set of eye here @dhenry-KCI @ABonomo21

**Comment by TMARTIN0926** [comment]
Dustin and I talked briefly yesterday regarding this. I’m hoping to discuss what changes were made during my absence since everything seemed to be working properly before I left and now there are a few issues I am coming across.

**Comment by ABonomo21** [comment]
The actual valuation should not be required if the check box
![image](https://user-images.githubusercontent.com/47611580/71211332-e7e42880-227c-11ea-8b00-852a940f240a.png)
 is marked on the details page.

**Comment by ABonomo21** [comment]
however, the check box should read "Part of an overall plan" because it is not part of an overall plan then a bond is required.

**Comment by calequin** [comment]
![image](https://user-images.githubusercontent.com/47603568/71216882-73f84f00-2281-11ea-89d0-edfd57f621b5.png)

**Comment by calequin** [comment]
migrate BP_GradingNewActualValuationCheck

**Comment by ABonomo21** [comment]
language corrected - will make sure next application that is processed works with check box
