### ISSUE TITLE
Customer was unable to pay and then received email address is not accurate

### ISSUE THREAD

**Issue by awhite806** [dhenry-KCI/FredCo-Post-Go-Live-#430]
Our Customer tried to pay online for a permit and got the notice that the transaction failed. Then he received an email from TEST that the permit was issued. And he also informed us that his card has been charged.
![1](https://user-images.githubusercontent.com/58981029/74765861-48c6b780-5252-11ea-886f-a4cec942421f.jpg)
<img width="847" alt="2" src="https://user-images.githubusercontent.com/58981029/74765866-49f7e480-5252-11ea-9d25-3c7128b89fa1.png">

**Comment by JuanitaMiles** [comment]
spoke with Christian, he is looking into this ticket now.

**Comment by megisys** [comment]
Email came from Production. The Address for web services was old. Actually been this way since Go Live.

**Comment by JuanitaMiles** [comment]
@ABonomo21 Ashlye please confirm there have been no additional email or payment issues reported by customers.

**Comment by ABonomo21** [comment]
none have been reported

**Comment by ABonomo21** [comment]
is the issue resolved

**Comment by calequin** [comment]
yes looks like they are coming in correctly and completed
![image](https://user-images.githubusercontent.com/47603568/74949867-ee4d6880-53c3-11ea-902b-9fa6d30bdc7d.png)
