### ISSUE TITLE
Grading Under Result Error Result

### ISSUE THREAD

**Issue by emilypearl1** [dhenry-KCI/FredCo-Post-Go-Live-#431]
Grading Permit #264993

intake Review- check status states "All conditions must be met":
![image](https://user-images.githubusercontent.com/58855801/74839018-8e3ac180-52f2-11ea-8fb6-7369b2f4db0c.png)

There are no conditions to meet:
![image](https://user-images.githubusercontent.com/58855801/74839047-a01c6480-52f2-11ea-928c-77cd207d3966.png)

We are unable to supervisor override  this is the error message:
![image](https://user-images.githubusercontent.com/58855801/74838958-76fbd400-52f2-11ea-8a2e-6be74e218066.png)

**Comment by emilypearl1** [comment]
per Juanita i have assigned to Christian and assigned a high priority.

**Comment by JuanitaMiles** [comment]
Worked with Emily and confirmed she is doing everything correctly. These errors are holding up several of her permits, therefore labeling as a high priority.

**Comment by megisys** [comment]
Someone removed the Occupancy Code.. This is a must. Please Add back and you will be fine. It is a required field during Intake

**Comment by megisys** [comment]
You can supervisor override once occupancy is back..

GRADING_ParentCondition3_SCF Needs Line 1 changes to StateCheck = False

**Comment by emilypearl1** [comment]
Conditions is ready for promotion to production (tested in test)

once the occupancy type was added in- it progressed correctly.

**Comment by calequin** [comment]
promoted on 2.23.2020
