### ISSUE TITLE
Expired Licenses showing on Plumbing permits.

### ISSUE THREAD

**Issue by awhite806** [dhenry-KCI/FredCo-Post-Go-Live-#433]
similar to issue #349   This contact has two expired licenses and they are both marked as inactive, yet they are still printing on the official issuance when they shouldn't. I highlighted the incorrect licenses on the official issuance. it even shows the expiration date on them
![image](https://user-images.githubusercontent.com/58981029/74971769-a0018f00-53ee-11ea-8572-3b113be3012d.png)
[265202 offical issuance.pdf](https://github.com/dhenry-KCI/FredCo-Post-Go-Live-/files/4232671/265202.offical.issuance.pdf)

**Comment by TaraF** [comment]
Noting this is a new request. Assigned, in progress.

**Comment by TaraF** [comment]
This is ready for testing in Test.

**Comment by ABonomo21** [comment]
TESTED IN TEST - 263396 
![image](https://user-images.githubusercontent.com/47611580/75452034-83f67400-593f-11ea-984b-0a5aab97c7dd.png)
