### ISSUE TITLE
Mobile locking up when looking at building permit details

### ISSUE THREAD

**Issue by TheBobEnsor** [dhenry-KCI/FredCo-Post-Go-Live-#434]
[When I click on Building Details.docx](https://github.com/dhenry-KCI/FredCo-Post-Go-Live-/files/4232684/When.I.click.on.Building.Details.docx)

**Comment by TheBobEnsor** [comment]
[When I click on Building Details.docx](https://github.com/dhenry-KCI/FredCo-Post-Go-Live-/files/4232750/When.I.click.on.Building.Details.docx)
Ashlye says, I need more descriptions with each screen shot :)

**Comment by TheBobEnsor** [comment]
Closed in error
Sorry

**Comment by calequin** [comment]
Infor Xtreme ticket has been created 14355497

**Comment by calequin** [comment]
followed up with support for an update

**Comment by ABonomo21** [comment]
@megisys Was this an item that was to be addressed with the patch update?

Christian last logged the follow up with support 28 days ago..

**Comment by calequin** [comment]
@ABonomo21 this should have been addressed with the latest mobile update of 11.2.2003
