### ISSUE TITLE
System Wide - DUSWM - Add Employees as Inspectors

### ISSUE THREAD

**Issue by JuanitaMiles** [dhenry-KCI/FredCo-Post-Go-Live-#436]
Source:
Repository: kcigeospatial / Fred_Co_Land-Management
Ticket #: 2357
Requested By: Brenda Teach / Juanita Miles
Jump to this repository

Request:
Brenda Teach has requested that **Kimberly Getzandanner** and **Cory Brandt** have the Inspector tag applied to their employee records. This is to allow their usernames to appear on the Inspector drop down list for Capacity permit final fixture inspections.

Upon further review of IPS, it does not appear that Kimberly or Cory have employee records in the TEST system. They will need employee records (with inspector applied) and user accounts created.

Need to confirm if these updates were made post go-live.

**Comment by pooldaddy** [comment]
Done
email to brenda below
![image](https://user-images.githubusercontent.com/47391482/77202262-5c20a900-6ac4-11ea-8f10-8981098f0f38.png)

**Comment by JuanitaMiles** [comment]
confirmed both are in the production environment with Inspector checked. Closing ticket.
