### ISSUE TITLE
Business License - Liquor License - Missing Endorsement Types

### ISSUE THREAD

**Issue by JuanitaMiles** [dhenry-KCI/FredCo-Post-Go-Live-#437]
Source:
Repository: kcigeospatial / Fred_Co_Land-Management
Ticket #: 2329
Requested By: Liquor Board / Tara Feaga
Jump to this repository

Request:
Endorsement types that are missing and need to be added:

Entertainment (no fee associated)
Patio (no fee associated)
Growler Permit Wine Beer/Wine
Growler Permit Wine Only
Need to confirm these have been added.

**Comment by pooldaddy** [comment]
Verified all 4 types listed above were defined in both TEST & PROD.  See screenshots from TEST below:
   
[Github # 437.docx](https://github.com/dhenry-KCI/FredCo-Post-Go-Live-/files/4250578/Github.437.docx)

**Comment by JuanitaMiles** [comment]
This was just a task for Jeff to confirm endorsements have been added to Prod and TEST. Jeff has confirmed, closing this ticket since no promotion needs to happen.
