### ISSUE TITLE
Permit Issued with review still marked as resubmit

### ISSUE THREAD

**Issue by awhite806** [dhenry-KCI/FredCo-Post-Go-Live-#438]
Permit #260914 issued while still having the review from the health department marked as resubmit. Permits should not issued if they have reviews that are not approved.
![image](https://user-images.githubusercontent.com/58981029/75186397-cfc5d500-5715-11ea-8735-6864d0fc6849.png)
![image](https://user-images.githubusercontent.com/58981029/75186408-d5231f80-5715-11ea-80a7-a75e0a49f9a0.png)

**Comment by JuanitaMiles** [comment]
could have something to do with the cycles of the EH review versus the PLNREV? Health wasn't added on the application until the 2nd cycle of review overall, so the review cycles don't match.

**Comment by calequin** [comment]
our code has comments indicating that EH reviews after a second cycle will be manually added. Is this not correct?
![image](https://user-images.githubusercontent.com/47603568/75188240-63e16d80-5711-11ea-82c8-8c2c804c7d94.png)

**Comment by JuanitaMiles** [comment]
talked to christian on the phone to clarify. he will follow up.

**Comment by calequin** [comment]
FIXED AND TESTED IN TEST WITH AP 260914 if accepted please promoted
Formula:
BP_ToTolerance_NSF

**Comment by ABonomo21** [comment]
Can you look into why the system generated this health review. It is a minor permit which should only trigger building plan review. 

![image](https://user-images.githubusercontent.com/47611580/75246084-085cc180-579d-11ea-9bdb-14b4fe17b822.png)
Regardless in the event of a resubmit all reviews will be manually added.

**Comment by awhite806** [comment]
this minor permit for a hot tub had a health review generate as well. minor permit should only have Building Plan Review generate.
![image](https://user-images.githubusercontent.com/58981029/75258681-dc4d3a80-57b4-11ea-84e2-c7b2c85a41f3.png)
![image](https://user-images.githubusercontent.com/58981029/75258727-ea02c000-57b4-11ea-8379-ac4d9375fa65.png)

**Comment by JuanitaMiles** [comment]
@ABonomo21 The issue of the Health Review adding when it shouldn't have should really be a different ticket. We need to test if the fix Christian put in place to prevent the application from moving forward when there is a difference in review numbers works.

**Comment by ABonomo21** [comment]
issuance of the permit cycle issue appears to be fixed via test on a/p 263391 in test
