### ISSUE TITLE
PDox- invitation email notification-add project name

### ISSUE THREAD

**Issue by MLWilkins** [dhenry-KCI/FredCo-Post-Go-Live-#439]
Can the PDOX invitation email include the project name?

![image](https://user-images.githubusercontent.com/50637067/75258632-c5a6e380-57b4-11ea-9fc4-6a686370db48.png)

**Comment by ABonomo21** [comment]
moved to future phase

**Comment by ABonomo21** [comment]
moved back from future list

**Comment by ABonomo21** [comment]
ticket 74

**Comment by JuanitaMiles** [comment]
Was proposed to be part of zoom training. County IIT to coordinate zoom training with Avolve.

**Comment by JuanitaMiles** [comment]
Adding another PDox email template request from Ashlye to remove the Priority from the "Applicant Upload Task is Past Due" email template.

We will need to confirm whether or not this change impacts planning as well and if it does, confirm with Ashley R that it is okay to remove from planning notices.

![image](https://user-images.githubusercontent.com/31770504/84078011-2d6ced00-a9a6-11ea-977b-d809705f35dd.png)

**Comment by AReed327** [comment]
Yes. Please remove.

**Comment by Ycoto** [comment]
Before
 
![image](https://user-images.githubusercontent.com/63804011/86136688-60dcfc00-baba-11ea-879d-a6e0d23f8e9c.png)

After
 
![image](https://user-images.githubusercontent.com/63804011/86136710-676b7380-baba-11ea-8c2b-a42adf20b283.png)


Priority task, identify and delete.
![image](https://user-images.githubusercontent.com/63804011/86136605-4acf3b80-baba-11ea-8731-70f17d946086.png)

**Comment by MLWilkins** [comment]
Have these changes been made in Test or Prod?

**Comment by Ycoto** [comment]
Prod.

**Comment by MLWilkins** [comment]
the email below came in at 10:45am and the project name isnt appearing.  Were these changes made to Planning projects?  The example above is a permit application.

![image](https://user-images.githubusercontent.com/50637067/86141916-9c7ac480-bac0-11ea-9a7c-aeff87215cc9.png)

**Comment by Ycoto** [comment]
Ok, it should work now give a try one more time. Thank you for your help.

**Comment by MLWilkins** [comment]
thank you @ycoto  We will monitor as notifications go out in prod.

**Comment by MLWilkins** [comment]
the pdox notification we have received over the past two days look good.  closing ticket.  Thanks all!
