### ISSUE TITLE
Review Due Date 

### ISSUE THREAD

**Issue by ABonomo21** [dhenry-KCI/FredCo-Post-Go-Live-#442]
I re-assgined reviews fro Justin Horman to Tolson DeSa that were due today and tomorrow. When i did that it changed the due date of the review to a week from today. 

The review due date should not change due to a re-assignment. I re-assigned them because the reviewer was out sick and the reviewers are due... 

![image](https://user-images.githubusercontent.com/47611580/75264734-d9a31300-57bd-11ea-95a3-ae1c3a52e0f8.png)

**Comment by megisys** [comment]
BP_RevisionDueDates_BU to be promoted

**Comment by ABonomo21** [comment]
tested with dan on permit 263387 confirmed fix- will promote to production
