### ISSUE TITLE
PLANNING - PWCONSTRUC - Fee Notification

### ISSUE THREAD

**Issue by AReed327** [dhenry-KCI/FredCo-Post-Go-Live-#444]
Project Number - PW257727
Observed behavior - No fee email generated when the per page fee was added on PWCONSTRUC
Expected behavior - Notification to the applicant should go out if/when fees generate after the first review cycle on PWCONSTRUC
Screenshot -
![image](https://user-images.githubusercontent.com/58854333/75346309-6ad0c300-586c-11ea-88c5-1f12a6533444.png)

![image](https://user-images.githubusercontent.com/58854333/75346153-19283880-586c-11ea-82fb-8be4493afbf9.png)

**Comment by MLWilkins** [comment]
see ticket 1656 in pre-go live github.

**Comment by megisys** [comment]
See in TEST. Addressed Issue.

**Comment by AReed327** [comment]
Test Accepted 
PW258842
![image](https://user-images.githubusercontent.com/58854333/75578006-0f9bfd80-5a31-11ea-8f56-7180987e5088.png)
