### ISSUE TITLE
Minor Permit - Health Review 

### ISSUE THREAD

**Issue by ABonomo21** [dhenry-KCI/FredCo-Post-Go-Live-#446]
when adding a minor permit under the resuses a/p if the minor permit check box is marked only BUILDING PLAN review should be a reviewing agency - 

no other agencies are required and more importantly health department should never add even if the property is on well and or septic if this minor check box is marked 

![image](https://user-images.githubusercontent.com/47611580/75360984-9069c680-5884-11ea-9078-4e7998d8578b.png)

![image](https://user-images.githubusercontent.com/47611580/75360814-5698c000-5884-11ea-9779-3023b0e72013.png)

also have the same issue in test review # 628015 system generated for permit 263391
![image](https://user-images.githubusercontent.com/47611580/75360878-6adcbd00-5884-11ea-9f5c-1228fc5e538e.png)

**Comment by megisys** [comment]
Promote RESUSES_EH_Review_AOC - When Test Accepted

**Comment by ABonomo21** [comment]
was in a meeting with Dan and this was a high priority - asked him what the code was written to say - there was just something missing in the code but the "requirement to exclude HD on minor permits was there" he just had to clean up the code took 30 seconds. Fixed 
tested in test 263392- worked ! please push to production.
