### ISSUE TITLE
Resuse Permit Inspections 

### ISSUE THREAD

**Issue by ABonomo21** [dhenry-KCI/FredCo-Post-Go-Live-#447]
Inspections for resuse permits not generating as provided via airtable 

in meeting with dan and jeff found the code has an error in it and it is a quick fix.

**Comment by ABonomo21** [comment]
inspections are generating correctly based on 3 test applications
263402 for addition 
263401 for alteration 
263400 for accessory

**Comment by pooldaddy** [comment]
RESUSES_BLDG-Insul_insp_AOC
RESUSES_BLDG-Frame_Insp_AOC

**Comment by JuanitaMiles** [comment]
Keeping labels as Test Accepted. This will let Dan know to promote to Prod.
