### ISSUE TITLE
Customers are unable to upload attachments.

### ISSUE THREAD

**Issue by awhite806** [dhenry-KCI/FredCo-Post-Go-Live-#448]
A customer was trying to upload attachments while submitting a new permit application and got the error that it would not accept her files. then when she tried to go back and change the files, it would not let her change them. (266519 and 266528)
![12](https://user-images.githubusercontent.com/58981029/75466558-61248980-5958-11ea-9667-65133d1bc2ad.png)

she also tried to upload new attachments for a revision, and the option to upload attachments was gone (205268) at the time this permit was in Awaiting Applicant Revisions.

**Comment by megisys** [comment]
I can not read this screenshot. In the interest of time. Ask Applicant to email you the files and upload back office and see if the issue persists

**Comment by awhite806** [comment]
closing for now, customer was able to upload attachment later on.
