### ISSUE TITLE
REVISION FEE 

### ISSUE THREAD

**Issue by ABonomo21** [dhenry-KCI/FredCo-Post-Go-Live-#45]
WHEN THE HEALTH REVIEW RESULTS AS RESUBMIT - AND THEY ARE THE ONLY REVIEWER TO RESULT AS A RESUBMIT IT  SHOULD NOT GENERATE THE $27.00 REVISION FEE- AB 
![SnipImage(2)](https://user-images.githubusercontent.com/47611580/71032646-c56ad780-20e3-11ea-86c1-ecd413d1e699.JPG)

**Comment by ScottVanSooy** [comment]
This formula need to be modified BP_REVISION_FEE_AOC but I need clarification on the requirements.

**Comment by ScottVanSooy** [comment]
Closed on error

**Comment by ScottVanSooy** [comment]
This formula needs to be promoted (Changed Or to And)  BP_REVISION_FEE_AOC

AddonCondition = False

For Each oReview as Hansen.CDR.Building.IReview in oBldgApp.Reviews

if oReview.IsRelevantReview and oReview.ReviewREsult.Code  = "RESUBMIT" then
	
	if oReview.ReviewType.Code <> "EH" And oReview.ReviewType.Code <> "DUSWM" then
		
		AddonCondition = True
		
	End if
	
	
End if

Next

**Comment by ScottVanSooy** [comment]
The issue is missing Add On Conditions for the Fee as well.  I need to find out if this is supposed to happen for all Permit Types or just RESUSES.

**Comment by ScottVanSooy** [comment]
Deployed to Production 12/18/19
