### ISSUE TITLE
Planning-APFO-need more information notification not sending

### ISSUE THREAD

**Issue by MLWilkins** [dhenry-KCI/FredCo-Post-Go-Live-#450]
Resulted APFO review as resubmit and the "need more information" notification did not send.  marking as high priority as this is a Turbo Fast Track project and the applicants arent being notified of the review result or of the action they need to take.

![image](https://user-images.githubusercontent.com/50637067/75551734-d77dc600-5a02-11ea-82e0-1e15c4d80c71.png)

**Comment by MLWilkins** [comment]
see related ticket in pre-go live repository 


![image](https://user-images.githubusercontent.com/50637067/75551971-4eb35a00-5a03-11ea-8434-cea517acf821.png)

**Comment by megisys** [comment]
See A258876 - Condition Formula for APFO Updated

**Comment by MLWilkins** [comment]
fixed

![image](https://user-images.githubusercontent.com/50637067/76529233-64d00a00-6448-11ea-9c12-4bb14358aa96.png)

![image](https://user-images.githubusercontent.com/50637067/76529263-70bbcc00-6448-11ea-8b2f-a657da93fa9f.png)
