### ISSUE TITLE
Planning-APFO-approved notification not sending

### ISSUE THREAD

**Issue by MLWilkins** [dhenry-KCI/FredCo-Post-Go-Live-#451]
notification for approved application not sending.

![image](https://user-images.githubusercontent.com/50637067/75566364-8b8c4a80-5a1d-11ea-883a-75019cc80c4f.png)

**Comment by megisys** [comment]
See  A258876 - Outcome Added

**Comment by MLWilkins** [comment]
fixed


![image](https://user-images.githubusercontent.com/50637067/76781125-9b798d80-6784-11ea-930c-fb9b9ad49ea1.png)
