### ISSUE TITLE
Error in Mobile

### ISSUE THREAD

**Issue by TheBobEnsor** [dhenry-KCI/FredCo-Post-Go-Live-#454]

**Comment by TheBobEnsor** [comment]
We have been seeing this error on occasion and just want to document it 
See picture of error attached
![Exception in Map Provider](https://user-images.githubusercontent.com/60886453/75673030-02108e80-5c50-11ea-9d77-eef52ef48031.jpg)

**Comment by TheBobEnsor** [comment]
A little more info, it appears when opening "Building Permits"/ Nearby open

**Comment by JuanitaMiles** [comment]
@pooldaddy Jeff as you investigate this issue, it might be related to ticket #452 - Map Functionality not working.

**Comment by pooldaddy** [comment]
@JuanitaMiles @TheBobEnsor #452 has been resolved in PRoduction.  That should also fix this issue.  Please verify in PROD and if ok close this ticket.

**Comment by JuanitaMiles** [comment]
@TheBobEnsor Bob can you confirm whether or not this error is still appearing for you or your guys? I believe it was linked to an overall map issue that has since been fixed. If this is no longer an issue. Please close the ticket.

**Comment by ABonomo21** [comment]
confirmed with Bob the error is no longer occurring. 
Thanks
