### ISSUE TITLE
Non-Residential Electrical Fee Generating Incorrectly

### ISSUE THREAD

**Issue by mlibbey131** [dhenry-KCI/FredCo-Post-Go-Live-#455]
Permit# 266659

Non-Res Service 100 Amp or Less fee generated incorrectly. Should be $40.00 for each service (total of $120.00) only (1) fee generated even though the quantity was (3).

![1](https://user-images.githubusercontent.com/58980189/75686109-b2d75780-5c69-11ea-8cf9-e795aaa382eb.png)
![2](https://user-images.githubusercontent.com/58980189/75686110-b4a11b00-5c69-11ea-8c35-8253d429087a.png)

**Comment by pooldaddy** [comment]
@ABonomo21 can you give me another ap#/fee where it is calculating quantity * fee correctly.  Can be a different ap type/fee just want a working example to compare to.

**Comment by ABonomo21** [comment]
worked - 

Just curios - is there a reason the service added the quantity and calculated when the motor generator calculated the fee correctly for 3 without putting a quantity? motor generator is $36 each there were 3 listed on the details page like the service which should have calculated at $36*3=108 but again didn't update the quantity. 

![image](https://user-images.githubusercontent.com/47611580/76452941-4d414480-63a8-11ea-94c9-20299fd5ebe2.png)

Just want to make sure as IIT in the future tries to fix fees or coding if it changes how will they know the difference? @megisys @JuanitaMiles
