### ISSUE TITLE
Residential Single Family Dwelling No Reviews Generated

### ISSUE THREAD

**Issue by mlibbey131** [dhenry-KCI/FredCo-Post-Go-Live-#456]
Permit# 265385 

Residential Single Family Dwelling. No reviews generated once the permit was paid for. 

![image](https://user-images.githubusercontent.com/58980189/75686200-d4384380-5c69-11ea-9705-2bfab5ba87dd.png)

**Comment by JuanitaMiles** [comment]
Megan manually added the two reviews that should have added automatically. See screenshot.

![image](https://user-images.githubusercontent.com/31770504/75688801-1f545580-5c6e-11ea-8194-19094b9cfb3f.png)

**Comment by megisys** [comment]
This issue was due to a GIS Error populating Plan Region. Previously addressed
