### ISSUE TITLE
System Generating Reviews

### ISSUE THREAD

**Issue by mlibbey131** [dhenry-KCI/FredCo-Post-Go-Live-#457]
Permit# 258450

During revision assignment I inserted the DPZ review and once I approved the Revision Assignment Condition the system generated a PWDR review. 

![image](https://user-images.githubusercontent.com/58980189/75686398-32fdbd00-5c6a-11ea-9147-fa5983a08035.png)
![image](https://user-images.githubusercontent.com/58980189/75686421-3729da80-5c6a-11ea-91f2-2e6060da557b.png)

**Comment by ABonomo21** [comment]
I have another example where i have approved the revision assignment condition and the milestone did not change permit 202843 had to manually change milestone back to under review
![image](https://user-images.githubusercontent.com/47611580/75715993-61948b80-5c9c-11ea-9e6b-8f0c5dfe1ad5.png)
![image](https://user-images.githubusercontent.com/47611580/75716010-68230300-5c9c-11ea-98ba-1728342c4058.png)

**Comment by pooldaddy** [comment]
once accepted promote to Production

NONRESBLDG_PWDR_Review_AOC

**Comment by ABonomo21** [comment]
Put permit 258450 back in the under review cycle and conduct the test and the additional reviews did not add automatically. test accepted
