### ISSUE TITLE
Health Review Fee 

### ISSUE THREAD

**Issue by ABonomo21** [dhenry-KCI/FredCo-Post-Go-Live-#459]
A health review fee did not generate on permit 265409- property served by well and septic. 
The only time health review fee should not generate is if the property is  is not on well and septic but food service is involved. this will trigger a health food service review but should not trigger a fee...
![image](https://user-images.githubusercontent.com/47611580/75686683-a99aba80-5c6a-11ea-9d59-989a1bb8fd8a.png)

**Comment by pooldaddy** [comment]
No changes required.  I reset milestone to Completeness Check in TEST.  Completed reviews and fee generated for $50.  I suspect the Planning Region filed was set to "FR" when the original set of fees were generated.

**Comment by pooldaddy** [comment]
@ABonomo21 please verify

**Comment by ABonomo21** [comment]
confirmed the fee generated when you put it back to completeness check like it should have - how do we address the PR issue as this was a know problem prior to go live that was resolved.

**Comment by ABonomo21** [comment]
@JuanitaMiles @pooldaddy see comment above.

**Comment by JuanitaMiles** [comment]
The issue of the planning region has since been addressed by Jeff and Dan via email. There was a meeting scheduled on 3/3/20 with IIT/GIS and Infor to discuss how the County could handle this issue in the future if bulk updates needed to be made again, however this meeting was declined by Infor last minute due to resource usage concerns.

**Comment by JuanitaMiles** [comment]
Since confirmation has been provided that the fee generated correctly, and no additional configuration change was needed, closing the ticket.
