### ISSUE TITLE
Town review for building permit 

### ISSUE THREAD

**Issue by ABonomo21** [dhenry-KCI/FredCo-Post-Go-Live-#46]
resuse permit did not trigger a town review. 

This permit is within city of Brunswick and the town contact did not populate which is supposed to notify the town/city that a permit has been submitted.

![image](https://user-images.githubusercontent.com/47611580/71032721-e92e1d80-20e3-11ea-88d6-37e4a92dd826.png)

**Comment by megisys** [comment]
Township code 02 is brunswick. This is listed on the address as Frederick City 01.
Addressing Issue

**Comment by megisys** [comment]
@ABonomo21 in Township of 01

**Comment by megisys** [comment]
![image](https://user-images.githubusercontent.com/47392306/71043636-39fe4000-20fd-11ea-8d35-7712068623e6.png)

**Comment by ABonomo21** [comment]
still getting the error on town reviews assigned to building permits
![image](https://user-images.githubusercontent.com/47611580/71109217-c1e25980-2192-11ea-983d-622607995d1e.png)

@dhenry-KCI dustin we need to tell GIS about the one with the wrong township code

**Comment by ABonomo21** [comment]
dustin i have review this and we need to make sure the towns are getting the reviews in their portals and we do not run into this issue.

**Comment by dhenry-KCI** [comment]
@ABonomo21 - the township code is correct. Because it was incorrect, the system will not add the Brunswick contact at this point. This would need to be manually added. Confirm - and i will add.

**Comment by megisys** [comment]
Closing due to age. Reopen if this happens again

**Comment by ABonomo21** [comment]
it happened again.... 
![image](https://user-images.githubusercontent.com/47611580/71519315-11a4dd00-2885-11ea-8b1b-edf81d5aa03c.png)
![image](https://user-images.githubusercontent.com/47611580/71519327-1bc6db80-2885-11ea-823f-ee822f22b88e.png)

**Comment by megisys** [comment]
This Issue is related to Brunswick addressed with a township code of 01 again. GIS data issue.

**Comment by pooldaddy** [comment]
Not sure where the disconnect is but 01 is township code for Brunswick.   Frederick City is 04.

**Comment by ABonomo21** [comment]
![image](https://user-images.githubusercontent.com/47611580/71990991-655ae300-3202-11ea-87a4-74d63500cbd5.png)

![image](https://user-images.githubusercontent.com/47611580/71991068-8a4f5600-3202-11ea-9f6f-7d986a62d2ed.png)

check on code for when town reviewer generates

**Comment by megisys** [comment]
BP_AddTownReviewer_AAF to be Promoted from TEST

**Comment by calequin** [comment]
promoted on 1.8.2020

**Comment by ABonomo21** [comment]
will re-open if this happens again

**Comment by ABonomo21** [comment]
error is still generating if there is a town, have to enter the stop not log to bypass error in screenshot originally added. 

![image](https://user-images.githubusercontent.com/47611580/72267063-6b2f3a80-35ed-11ea-9f9b-5cfccd354ee6.png)

**Comment by megisys** [comment]
Yes it is the Opt out stuff. This is my focus today.

**Comment by megisys** [comment]
Closing as same issues as Notification Error Message. Original Ticket Solved.

**Comment by ABonomo21** [comment]
what is the other ticket number ?

**Comment by megisys** [comment]
Here it is https://github.com/dhenry-KCI/FredCo-Post-Go-Live-/issues/153

But the inital ticket is solved. this was spawned into another issue. So please close and reopen. or close and be happy the notification issue will be solved on the other ticket

**Comment by ABonomo21** [comment]
tested in 259438
