### ISSUE TITLE
License Still Active After Bond Cancellation

### ISSUE THREAD

**Issue by mlibbey131** [dhenry-KCI/FredCo-Post-Go-Live-#460]
EM2219
License still showing as Active even after the date has passed for the Bond Cancellation. 

![image](https://user-images.githubusercontent.com/58980189/75687077-3f364a00-5c6b-11ea-8298-40cf56accc8c.png)

![image](https://user-images.githubusercontent.com/58980189/75687166-60973600-5c6b-11ea-94a5-22fe12251a15.png)

**Comment by JuanitaMiles** [comment]
@pooldaddy This could be similar to the setup that de-activates a license if the State License expiration date has passed. I believe this is a batch manager job?

**Comment by pooldaddy** [comment]
System not currently designed to do this.  This is an enhancement,

**Comment by ABonomo21** [comment]
tested trade permit ER404 added bond crenelation date as yesterday and the license remained active..

**Comment by ABonomo21** [comment]
batch manager needed to run - test accepted

**Comment by megisys** [comment]
Deployed to Production
