### ISSUE TITLE
Test Applications Not Moving to Test PDox

### ISSUE THREAD

**Issue by JuanitaMiles** [dhenry-KCI/FredCo-Post-Go-Live-#462]
In the TEST environment, applications that have been created in IPS and resulted with EPLANS are showing as "General Success" in the ProjectDox Messages, but they are not showing up in the test ProjectDox site.

Application 266707 was created in Test and showed as successful in the ProjectDox Messages on 3/2 at 8:12 pm. As of 8:45 pm, the project still has not been added to Test ProjectDox.

![image](https://user-images.githubusercontent.com/31770504/75734685-9b7a8780-5cc6-11ea-8120-6a85c2af0144.png)

![image](https://user-images.githubusercontent.com/31770504/75734740-c533ae80-5cc6-11ea-9009-47e219cb952e.png)

**Comment by JuanitaMiles** [comment]
Marking as a high priority since this needs to be working ahead of ProjectDox training next week so we can create sample applications. We need to have the time to create and provide them to the PDox trainer asap.

**Comment by megisys** [comment]
Please let me know, if this is addressed.. I believe it may have been pointing to production still. If so please clean up this project from Production..

**Comment by JuanitaMiles** [comment]
Confirmed fixed with 266710. Closing Issue.

![image](https://user-images.githubusercontent.com/31770504/75796127-331cbc00-5d41-11ea-9e77-57c8b0171198.png)

![image](https://user-images.githubusercontent.com/31770504/75796051-24360980-5d41-11ea-979f-d329a3c835a5.png)
