### ISSUE TITLE
Awaiting Applicant Revision 

### ISSUE THREAD

**Issue by ABonomo21** [dhenry-KCI/FredCo-Post-Go-Live-#463]
We have a permit that was under review was asked by a resubmit by zoning moved to awaiting applicant revisions, - applicant actions log was completed reviews assigned and did not move out of awaiting applicant revisions. permit 259326
![image](https://user-images.githubusercontent.com/47611580/75784300-0318ed00-5d30-11ea-9581-0f850ed108a1.png)

we have seen this on a few other permits but assumed it was a glitch from migrated data, clearly from this permit example it is not - there is a system error. 

manually moved to under review.

**Comment by JuanitaMiles** [comment]
Was able to replicate this on this application in the Test environment. Upon approving the 2nd cycle DPZ review the application should have issued rather than move back to Awaiting Applicant Revisions. 

![image](https://user-images.githubusercontent.com/31770504/75788510-54c47600-5d36-11ea-8606-294aec29cdf2.png)

**Comment by mlibbey131** [comment]
This is also occurring on Permit# 261959

![image](https://user-images.githubusercontent.com/58980189/75790277-f220a980-5d38-11ea-849e-75fafbd8310e.png)

**Comment by pooldaddy** [comment]
BP_ToTolerance_NSF to promote tonight

**Comment by ABonomo21** [comment]
can you give us a status on if this formula was promoted? @pooldaddy

**Comment by pooldaddy** [comment]
@ABonomo21  Dan was supposed to promote last night but it appears he did NOT.
@megisys

**Comment by megisys** [comment]
No it didn't happen, didn't have availability, staff were using the system late and we have no official window of outage.. Will try tonight..

**Comment by awhite806** [comment]
Still Occurring...Seems to happen with every permit that has a revision done on it.
262110
![image](https://user-images.githubusercontent.com/58981029/75990144-70f51e00-5ec2-11ea-99f9-475fc63ae43f.png)
263268
![image](https://user-images.githubusercontent.com/58981029/75990216-8ff3b000-5ec2-11ea-94e3-0ae28526a77d.png)

**Comment by megisys** [comment]
THis issue was moved to production. please let me know if it continues to happen.. I refreshed this dll just now
