### ISSUE TITLE
Revision Assignment Condition being held up by other conditions.

### ISSUE THREAD

**Issue by awhite806** [dhenry-KCI/FredCo-Post-Go-Live-#464]
#264627 - A revision was done for this permit due to a resubmit result on a review. After the revision was completed and the Revision Assignment Condition approved, the permit never moved out of Revision Assignment Milestone and into Under Review Milestone because of the PIHold condition that still needed to be approved. Other open conditions should not hold up a Revision Assignment because the revision will need to done and go to under review. I had to briefly approve the other condition and then unapprove it in order for the permit to go to Under Review Milestone.

![1](https://user-images.githubusercontent.com/58981029/75786580-86880d80-5d33-11ea-81ff-c5520b86e2a1.png)
![2](https://user-images.githubusercontent.com/58981029/75786587-87b93a80-5d33-11ea-8090-e1d0be7270d9.png)
![3](https://user-images.githubusercontent.com/58981029/75786591-8a1b9480-5d33-11ea-8743-7ec1cb27c888.png)

**Comment by JuanitaMiles** [comment]
@pooldaddy It looks like there is no formula that looks for only a certain type of condition (ASSIGN) to be approved. So the system is likely just looking to see if all conditions are approved. You may need to add a formula that ensures that only the ASSIGN condition has been approved at this Revision Assignment milestone.

![image](https://user-images.githubusercontent.com/31770504/75790966-e386c200-5d39-11ea-9f28-545c506fb76b.png)

**Comment by ABonomo21** [comment]
I will test this in test but wanted to document another example just in case - this is in production. 
![image](https://user-images.githubusercontent.com/47611580/75981148-e3113700-5eb1-11ea-84e4-6c46c1396f3f.png)

**Comment by ABonomo21** [comment]
Tested in test - permit 265198 

Added a P&I hold on this permit to trigger the additional condition- 

did the revision and approved the revision assignment condition and it did not bypass 
![image](https://user-images.githubusercontent.com/47611580/76086783-d01a6780-5f82-11ea-9f70-b1880f32a34d.png)

once i approved the other condition for the P&I hold the permit progressed as it should have. 
![image](https://user-images.githubusercontent.com/47611580/76086819-df011a00-5f82-11ea-9f0f-7c7b45c02c1f.png)

**Comment by awhite806** [comment]
This happened again in Production. Permit 200594. Once I approved the other condition, it went to the correct Under Review milestone. then I  had to remove my temp approval.
![Annotation 2020-03-09 115644](https://user-images.githubusercontent.com/58981029/76233797-2398e980-61ff-11ea-8a10-2ff1c31ecfd8.png)
![Annotation 2020-03-09 115644 2](https://user-images.githubusercontent.com/58981029/76233802-25fb4380-61ff-11ea-899f-3488105403e2.png)

**Comment by awhite806** [comment]
Happened again with Permit 202593
![image](https://user-images.githubusercontent.com/58981029/76311913-534ffc00-62a8-11ea-8fed-20cc44bec9c0.png)

**Comment by megisys** [comment]
It is happening in Production still as it hasnt passed testing in Test.. Please retest a RESUSE or RESBLDG in Test and let me know..

See 265198

**Comment by ABonomo21** [comment]
tested 266747 worked ! 

![image](https://user-images.githubusercontent.com/47611580/76454775-8af39c80-63ab-11ea-8b0b-f29fb5380dd7.png)
