### ISSUE TITLE
Reporting- Home Builders Report

### ISSUE THREAD

**Issue by emilypearl1** [dhenry-KCI/FredCo-Post-Go-Live-#465]
Looking for this report-I don't recall discussing it, however I believe it was on the very initial report list

"S:\IIT All-County Share\Software Integration\Hansen\Hansen_Crystal\Production\DailyCashReportOneAcct.exe"

**Comment by JuanitaMiles** [comment]
@TaraF Please review the initial list of reports that was coordinated with Jeff Tirschman. If we don't have anything on it, we may need to have a discussion to make sure all requirements are gathered for it.

**Comment by TaraF** [comment]
@emilypearl1  - sorry for the delay, I was out sick last week.

Could you please attach an example PDF to this thread? 

I can actually get to the drive location, but getting an error when trying to print/export the report. Thanks.

**Comment by emilypearl1** [comment]
Thanks Tara! Hope you are feeling better.

[Transaction Detail Report.pdf](https://github.com/dhenry-KCI/FredCo-Post-Go-Live-/files/4308584/Transaction.Detail.Report.pdf)

**Comment by TaraF** [comment]
@emilypearl1  - thanks!  Ok, so we have Daily Cash reports that were created for Dan Lewis' group, that are very similar, but slightly different.

It looks like your report is using one specific Account #.  Do you have the new account string it corresponds with for IPS?  Should I pull Jeff W in so he can look at the cross walk table?

Current Daily Cash report:
![image](https://user-images.githubusercontent.com/4104464/76253657-76839880-6221-11ea-81f4-41523754bcdf.png)

Account # from example report:
![image](https://user-images.githubusercontent.com/4104464/76253729-961ac100-6221-11ea-893b-3b69d1efa034.png)

**Comment by emilypearl1** [comment]
the budget # is 10.98.998.999.20640.0000
![image](https://user-images.githubusercontent.com/58855801/76308617-8a6edf00-62a1-11ea-8fba-73a85dcc8a80.png)

**Comment by TaraF** [comment]
Assigned, in progress.

**Comment by TaraF** [comment]
@emilypearl1  - this is ready for review in Test.   Please let us know if there are any revisions or if it should be promoted to Prod.  In Test, it is under Building Permits - Lookup Applications, called "Home Builders Report".

**Comment by ABonomo21** [comment]
Tested in TEST- looks good. 

Please promote to PRODUCTION- EP 4/3/2020

**Comment by TaraF** [comment]
Promoted to Production 4/3/2020.

![image](https://user-images.githubusercontent.com/4104464/78399134-5cd83580-75c2-11ea-83d5-bc32a51787e1.png)
