### ISSUE TITLE
Building Permits - Major Logging - Incorrect Final Inspection

### ISSUE THREAD

**Issue by JuanitaMiles** [dhenry-KCI/FredCo-Post-Go-Live-#466]
Eric has reported the following issue with the Major Logging permit.

![image](https://user-images.githubusercontent.com/31770504/75798768-09659400-5d45-11ea-85d6-48e19a7dcfea.png)

![image](https://user-images.githubusercontent.com/31770504/75799040-7bd67400-5d45-11ea-940f-6c611bda9bef.png)

**Comment by pooldaddy** [comment]
The logging final will come up in the final milestone.  The SWM inspection was generted beacuse VJ resulted a PWDR review with APPROVEDNS, should have been APPROVED.

**Comment by JuanitaMiles** [comment]
@emilypearl1 @ABonomo21 See Jeff's comments above. Can you ladies confirm the workflow for when Vijay uses these Approved - Structual or Approved - NonStructural review results? Also the overall inspection requirements for Major Logging to make sure they align with what Jeff has explained above from the code?

**Comment by ABonomo21** [comment]
The only time Vijay should use the result code of Approved Structural or Approved Non Structural is on Grading permits with a work type of MN for Minor Grading - This will spawn the SWMESD permit that vijay is completed a review for pursuant to Res SFD's that require a SWM Standard Plan Agreement - all other reviews by vijay should be either approved or resubmit.

**Comment by emilypearl1** [comment]
That is correct and how he is resulting

**Comment by ABonomo21** [comment]
educated staff- updated SOP's will confirm issued was staff error and then close. Juanita will re-test

**Comment by JuanitaMiles** [comment]
Tested with resulting the PWDR review with the standard Approved review and the SWM inspection did not populate. The reviews populated as Eric outlined above. Closing ticket as a training issue. Will follow up with Eric for his information.

![image](https://user-images.githubusercontent.com/31770504/76014677-035be880-5ee8-11ea-9c67-5ce57c38581a.png)

![image](https://user-images.githubusercontent.com/31770504/76014721-179fe580-5ee8-11ea-80c6-6f778d0a9339.png)
