### ISSUE TITLE
Use Permits - LandUse - Workflow/Status Progression Issues (Issued/Inspections)

### ISSUE THREAD

**Issue by JuanitaMiles** [dhenry-KCI/FredCo-Post-Go-Live-#467]
Land use permit L257944 issued (went through the permit issued milestone and generated an Issued date) without the inspection milestone occurring which should have generated prior to issuance, inspection milestone should trigger building inspection and life safety inspection which should assign to Kim Connor for both. Once passed permit should have issued and moved to final inspection at which time the building follow up inspection should generate (building follow up generated because the Temporary Construction Structure box is checked on the Land Use Intake Details page) . – follow up inspection should be scheduled and assigned a week after the event end date.

![image](https://user-images.githubusercontent.com/31770504/75802245-6b74c800-5d4a-11ea-92d0-f0d091cefb9d.png)

The following tickets and airtable information can be referenced for confirmation of this process outlined above:
(https://github.com/kcigeospatial/Fred_Co_Land-Management/issues/1672) 
(https://github.com/kcigeospatial/Fred_Co_Land-Management/issues/1127) 
![image](https://user-images.githubusercontent.com/31770504/75802620-feadfd80-5d4a-11ea-9f1a-426fe3d48835.png)

**Comment by pooldaddy** [comment]
Please promote once test accepted
Use_FromUnderReview_NMF

**Comment by ABonomo21** [comment]
tested- L257967

worked with one error-  created a/p, went to completeness check, approved completeness check review, went to fees, paid fees, went to inspections generated building and ols inspection..

passed both inspections and got an email that said a re-inspection fee was due?? this should only happen if there is a third inspection of the type that requires a re-inspection fee, no fee generated which is accurate but the notification of re-inspection fee due should not have sent. 

![image](https://user-images.githubusercontent.com/47611580/76091797-3fe12000-5f8c-11ea-8c4d-d9d3bd228930.png)

at the same time i got notification that the permit was issued which is the correct notification. 

the building follow up inspection generated as it should -once building follow up inspection was passed permit closed which is correct 

okay to promote - tested accepted as long as the re-inspection fee notification is corrected @JuanitaMiles @pooldaddy

**Comment by JuanitaMiles** [comment]
Was able to replicate the re-inspection notification problem in test: L257968. 

As Ashlye noted, the re-inspection fee and notification should not add/send unless there are three of the same type of inspection. The notification seemed to send when there were three inspections total on the application.

![image](https://user-images.githubusercontent.com/31770504/76422793-2e2cbd80-637c-11ea-9543-d2cdded32fed.png)

![image](https://user-images.githubusercontent.com/31770504/76422920-5c120200-637c-11ea-9e17-0fdd44f496e8.png)

**Comment by JuanitaMiles** [comment]
Tested L257969. Did not receive a Re-Inspection Fee Due email upon entering Final Inspection.

![image](https://user-images.githubusercontent.com/31770504/76991286-b2a0b280-691f-11ea-84c1-402d8da514f9.png)

Then failed the followup inspection twice and got the re-inspection fee notification as expected.
![image](https://user-images.githubusercontent.com/31770504/76991833-a1a47100-6920-11ea-95f8-e6b417536151.png)


Need to follow up with Ashlye to confirm if all of the inspections should be assigning to Kim Connor. If they should, will create a new ticket for it to be corrected.

**Comment by JuanitaMiles** [comment]
Marking as test accepted. creating a new ticket for jeff to update the inspection assignments for land use permits.
