### ISSUE TITLE
TEST R4C IS DOWN

### ISSUE THREAD

**Issue by JuanitaMiles** [dhenry-KCI/FredCo-Post-Go-Live-#468]
Per the email I sent:

![image](https://user-images.githubusercontent.com/31770504/75805178-5189b400-5d4f-11ea-9253-846ea1c03b46.png)

**Comment by pooldaddy** [comment]
Dan and I looked yesterday and coould not determine cause.  He suspects it is on their end.  Opened an extreme ticket # 14392463 with Infor yesterday around noon.  No response until today.  But still no resolution yet

**Comment by JuanitaMiles** [comment]
Followed up with Jimi 3/5 AM. Email below:

![image](https://user-images.githubusercontent.com/31770504/75996571-0a74fd80-5ecc-11ea-9e2e-393d9dcc485c.png)

**Comment by JuanitaMiles** [comment]
IIT has worked with Infor Extreme to resolve the issue. I did a quick test to confirm I was able to login and view my dashboard. County staff will need to provide confirmation all is working as expected when they are available to test.

**Comment by ABonomo21** [comment]
Able to log in to R4C test and have been able to see my dashboard, submit an application (266746) and look up records

**Comment by MLWilkins** [comment]
I was able to log on and see my dashboard items.  Still super slow.

@ABonomo21  was it slow for you or ok?

**Comment by ABonomo21** [comment]
was able to submit a plat PL258908

**Comment by MLWilkins** [comment]
this morning I logged into R4C test and got this error message.

![image](https://user-images.githubusercontent.com/50637067/76515496-0ac34a80-6430-11ea-81d1-0657a1df9963.png)

@JuanitaMiles @pooldaddy @AReed327 @ABonomo21

**Comment by MLWilkins** [comment]
went ahead and tried to submit an application and got this different error

![image](https://user-images.githubusercontent.com/50637067/76516055-25e28a00-6431-11ea-9709-0a58014ae66f.png)

**Comment by JuanitaMiles** [comment]
Looks like a sync needs to be done for test environment.  DLL errors.

**Comment by JuanitaMiles** [comment]
will this cause a disturbance in PDox/IPS for training?

**Comment by MLWilkins** [comment]
It shouldn’t. We aren’t using R4C for training

Sent from my iPhone

On Mar 12, 2020, at 8:00 AM, Juanita Miles <notifications@github.com> wrote:

﻿
[EXTERNAL EMAIL]


will this cause a disturbance in PDox/IPS for training?

**Comment by MLWilkins** [comment]
Gary Ashlye and I just successfully submitted a electrical permit but then tried an APFO exemption and got the error

Sent from my iPhone

On Mar 12, 2020, at 8:06 AM, Wilkins, Michael <MWilkins@frederickcountymd.gov> wrote:

﻿ It shouldn’t. We aren’t using R4C for training

Sent from my iPhone

On Mar 12, 2020, at 8:00 AM, Juanita Miles <notifications@github.com> wrote:

﻿
[EXTERNAL EMAIL]


will this cause a disturbance in PDox/IPS for training?

**Comment by MLWilkins** [comment]
fixed

![image](https://user-images.githubusercontent.com/50637067/76523014-0a31b080-643e-11ea-8cbf-35a1863c42b0.png)
