### ISSUE TITLE
Reviews Dissapearing

### ISSUE THREAD

**Issue by emilypearl1** [dhenry-KCI/FredCo-Post-Go-Live-#469]
Vijay approved PWDR review and the reviews dissappeared under permit #266730. SCD review was still there (unresulted). 

![image](https://user-images.githubusercontent.com/58855801/75805995-dfb26a00-5d50-11ea-869d-1f7e144b109a.png)

**Comment by JuanitaMiles** [comment]
Tried to replicate in Test but could not. My application is staying at under review and the reviews are still there. 

I also have no way of knowing what might have happened to the reviews if they were once there just by looking at the application.

![image](https://user-images.githubusercontent.com/31770504/75809433-c44a5d80-5d56-11ea-9f21-175950487570.png)

**Comment by emilypearl1** [comment]
Result PWDR as APPROVEDStructural

**Comment by JuanitaMiles** [comment]
Retesting today with the additional review result criteria emily provided above to try to replicate.

**Comment by JuanitaMiles** [comment]
Was able to replicate in Test! Review and Condition information should NOT be removed from the application. This issue appears when the PWDR review is resulted with APPROVEDS. Resulting with a regular Approved result does not produce the issue. See steps to replicate below. Application # 266718.

Steps to replicate:
1) Grading application spawned from a RESBLDG permit.

2) Began in Awaiting Applicant Resubmit. I completed the Grading Intake details page, then the Applicant Actions detail page.

3) Application progressed to Intake Review where I completed the Grading Details page, approved the Parent condition, and resulted Complete review with Internal Review.

4) Application progressed to Under Review, where I resulted the PWDR review with APPROVEDS. This review result is standard practice for this Grading permit work type.

5) Upon resulting the PWDR review, all reviews and conditions were cleared from the application and the application progressed to Pending Issuance. The SCD review was still awaiting to be resulted. The application DID however spawn the child ESD application like it was supposed to.

![image](https://user-images.githubusercontent.com/31770504/76000146-48285500-5ed1-11ea-9281-41d6dd8e2b71.png)

![image](https://user-images.githubusercontent.com/31770504/76000253-6e4df500-5ed1-11ea-83dc-57762c7c4960.png)

**Comment by JuanitaMiles** [comment]
Confirmed with Gary Hessong on 3/5 11:20 am that we would Dan to address.

**Comment by JuanitaMiles** [comment]
No change in issue. Reviews and Condition are still being wiped out once approving PWDR with APPROVEDS.

Before APPROVEDS result.
![image](https://user-images.githubusercontent.com/31770504/76005136-99881280-5ed8-11ea-8d52-9c38bcf715eb.png)

After APPROVEDS result:
![image](https://user-images.githubusercontent.com/31770504/76005275-c9371a80-5ed8-11ea-91a5-865ecb34c9f3.png)

**Comment by megisys** [comment]
Give that a go please.

**Comment by JuanitaMiles** [comment]
Slight improvement in the issue. Upon resulting PWDR with APPROVEDS the PARENT condition and the COMPLETE review did not get wiped out but the PWDR and SCD reviews still disappeared and the application moved to Pending Issuance.

Before APPROVEDS result:
![image](https://user-images.githubusercontent.com/31770504/76016753-6ac76780-5eeb-11ea-81a1-fd1328bcb1a8.png)
![image](https://user-images.githubusercontent.com/31770504/76016815-83378200-5eeb-11ea-8fb4-515c01820ffc.png)

After APPROVEDS result:
![image](https://user-images.githubusercontent.com/31770504/76017050-ee815400-5eeb-11ea-98f4-b08886815518.png)
![image](https://user-images.githubusercontent.com/31770504/76017140-15d82100-5eec-11ea-975a-c7ef984b749d.png)

**Comment by megisys** [comment]
SOrry Juanita.. Very last time and we should be good..

**Comment by JuanitaMiles** [comment]
I think we have a winner. Approved Structural PWDR review remained in Under Review, did not clear reviews or conditions, and spawned the ESD permit appropriately. Test accepted.

Before APPROVEDS result:
![image](https://user-images.githubusercontent.com/31770504/76021101-a3b70a80-5ef2-11ea-918b-367f33ee35eb.png)
![image](https://user-images.githubusercontent.com/31770504/76021128-afa2cc80-5ef2-11ea-87dc-f2eb55c0aff2.png)

After APPROVEDS result:
![image](https://user-images.githubusercontent.com/31770504/76021263-fabcdf80-5ef2-11ea-89d6-795f3960b3c5.png)
![image](https://user-images.githubusercontent.com/31770504/76021279-04dede00-5ef3-11ea-876b-85b961449366.png)
