### ISSUE TITLE
Building Permits - BP_HOLD Notification/Cannot Find Application Number

### ISSUE THREAD

**Issue by JuanitaMiles** [dhenry-KCI/FredCo-Post-Go-Live-#47]
A BP_HOLD notification was sent to ALL AROUND PLUMBING INC (customer # PM681) and the AP number did not generate on the notification. Only the source business object shows. 

The template for the notification looks correct. However, when I look up the contact to view communications, try to click on the AP #/Record Key I get an error. I also cannot search for this application number. I get no results.

![image](https://user-images.githubusercontent.com/31770504/71093381-1081fa80-2177-11ea-8ddc-c3c09d3d3677.png)

![image](https://user-images.githubusercontent.com/31770504/71093402-1aa3f900-2177-11ea-9f51-570dc2aa8be1.png)

**Comment by megisys** [comment]
Can not open log communications AP = 184177

**Comment by megisys** [comment]
Notification template updated

**Comment by JuanitaMiles** [comment]
@emilypearl1 @ABonomo21 - FYI for this ticket...Looks like the way I tried to identify the application AP # will not work for hold log communications. Dan has updated the notification template further to help with this issue.

@megisys - Can you explain how you knew the hold log was for 184177 rather than the 221539 number listed in the communication log record? It would be good for all of us to know how to do this.

**Comment by megisys** [comment]
I had to SQL it. That number is the LogKey.. You could do a quick adhoc based on the log table.
