### ISSUE TITLE
Trade License-Void Log does not work

### ISSUE THREAD

**Issue by awhite806** [dhenry-KCI/FredCo-Post-Go-Live-#470]
I put in this Void Log but the license did not void? Going to manually change the status to void.
![image](https://user-images.githubusercontent.com/58981029/75809741-4175d280-5d57-11ea-9c8d-011abbff38c0.png)

**Comment by JuanitaMiles** [comment]
@pooldaddy Please look at the logic behind the VOID log for Building Permits. I believe the Void log should push the application to a Status = Void, Milestone = Closed/Complete, and waive reviews and fees.

**Comment by megisys** [comment]
USE_VOID_AAF - Needs to be replicated for Trade Licenses

**Comment by megisys** [comment]
TRADE_VOID_AAF to be added to Prod once test is accepted

**Comment by ABonomo21** [comment]
tested EM257854 and PM257839- 

status check shows the milestone is complete and the status is void. 

The expiration date did not change and the status bar still show as active -will this have any negative impact i would think the status bar on the summary page would move to closed? @megisys 

![image](https://user-images.githubusercontent.com/47611580/78358176-bddf1980-7580-11ea-9931-9437cdf215a1.png)

**Comment by ABonomo21** [comment]
spoke with Dan - test accepted

**Comment by ABonomo21** [comment]
status bar will not change because it did not go through those milestone it skipped them

**Comment by megisys** [comment]
deployed
