### ISSUE TITLE
Inspections- Fire Suppression Permit 

### ISSUE THREAD

**Issue by ABonomo21** [dhenry-KCI/FredCo-Post-Go-Live-#471]
No inspections generated on multiple fire suppression permit once it entered the inspection milestone

263362
263260
260660

**Comment by JuanitaMiles** [comment]
These three permits are a type of Alarm, not suppression. From what I see in AirTable Alarms only get an Alarm Final? So these require the electrical permit to be added as a related record at the Inspections milestone, then will likely go to Final Inspection for the alarm final.

This is the way 260665 seemed to work...

![image](https://user-images.githubusercontent.com/31770504/75814147-3cb51c80-5d5f-11ea-942f-130741828ea9.png)
![image](https://user-images.githubusercontent.com/31770504/75814195-535b7380-5d5f-11ea-8a90-19a7ea62799d.png)

This is the way 260665 seemed to work...

**Comment by ABonomo21** [comment]
Good job Juanita! Closed
