### ISSUE TITLE
Grading Permit Extension and Expiration Process

### ISSUE THREAD

**Issue by ABonomo21** [dhenry-KCI/FredCo-Post-Go-Live-#473]
We would like the grading permit extension and expiration process to mimic the building permit workflow. 

Currently the "extension log" needs to be manually added however, we would like this to be added at the 11mth for extensions via the batch manager process as we have set up for building permits. 

Workflow: Bolded needs to be configured...

**Batch manager** added EXT log, 
Notification and Correspondence generate (this is already occurs if manually added)
Adds extension detail page (already occurs based on log being added)
once the extension detail page is completed by the applicant, the ext review should generate (already set up )
fees are manually added prior to review being completed - (will continue)
then review is resulted (manual process)
once fees are paid - expiration date needs to be automatically updated (it will always be for one year) - **this will need to configured** 
once expiration date changes which means fees have been paid - **the new placard needs to be sent out**

expired should also run via the batch manager once the permit expiration date hits. 
**Notification and Correspondence generate - I think this is partially configured but needs work as it should only send one letter the first day after expiration , not continuously.**

**Comment by megisys** [comment]
In Town to not have expiration
Check on Driveway
Grading has own correspondence
Fee to be added before resulting Review
Review to through reminder

**Comment by megisys** [comment]
EXTRequest_MusthaveFee_BU - to be promoted
Fee_ProcessExtension_BU - to be promoted

**EXT Fee to be used for Grading Extensions** As has to be consistent fee

**Comment by ABonomo21** [comment]
permit 265136 waived back fill ips system but did not waive foundation 

same with 265022

![image](https://user-images.githubusercontent.com/47611580/81334807-9e05ae80-9074-11ea-8971-c6e2341a258f.png)

**Comment by JuanitaMiles** [comment]
This was not working when we attempted to test on Thursday 5/7. Ashlye, Emily and Dan saw this not working when we were on a call.

**Comment by megisys** [comment]
Addressed the Issue - Ran the 11Month Process in Test..

**Comment by ABonomo21** [comment]
The correspondence does not appear to be running when it should be **
Ext Log adds- Correspondence sends
Extension detail page generates-applicant completes detail page
generates review and then manually add fees

**Comment by ABonomo21** [comment]
date did not change for permit 194606

**Comment by ABonomo21** [comment]
correspondence for the placard did not generate- we manually ran the batch manager at 11:17

**Comment by megisys** [comment]
You have to use the EXT Fee. This is the only way it will work..

**Comment by ABonomo21** [comment]
Using the EXT fee will not work there are associated renewal fee and account strings that are specifically tied to grading extensions.

Also  another reason we cant use the EXT Fee – that is associated with building extensions (49.00) that would mean I would need to modify every extension fee (after already having to add it)

EP 5/26/20

**Comment by megisys** [comment]
Hi All,

I will need to know the fees you want to use. Is it one or many ?

Dan

**Comment by ABonomo21** [comment]
Minor Grading AND Minor Logging Extensions
account string 10.98.998.999.40770.0000 (this should automatically add twice) value of $96.00 each= equalling a total of $192.00.

Major Logging Extensions
account string 10.98.998.999.40770.0000 value of $424.00

Major Grading & SWM (priority 1-active)
account string 10.98.998.999.40770.0000 value of $424.00 (admin fee) AND 
account string 10.98.998.999.40770.0000 value equals percentage (2.75%)of remaining surety balance.

Major Grading & SWM (priority 2 & 3-inactive)
account string 10.98.998.999.40770.0000 value of $424.00 (admin fee) ONLY

**Comment by megisys** [comment]
[Standard.xlsx](https://github.com/dhenry-KCI/FredCo-Post-Go-Live-/files/4729640/Standard.xlsx)

**Comment by megisys** [comment]
Hi Ashlye, I need to know the Fees by name to be used, as they are manually entered by Emily and I need to only update once the fees by name are paid.

**Comment by ABonomo21** [comment]
[Standard - Grading Extensions.xlsx](https://github.com/dhenry-KCI/FredCo-Post-Go-Live-/files/4733523/Standard.-.Grading.Extensions.xlsx)

**Comment by ABonomo21** [comment]
Please see the highlighted fee names in the Standard- Grading Extensions.

**Comment by megisys** [comment]
This has been updated.

**Comment by megisys** [comment]
Promoted - Record Review Results Changes - Formula for Fee Payment.

**Comment by megisys** [comment]
PLease let me know

**Comment by megisys** [comment]
Batch_AddExpireRequestLog_BCT - To be Promoted
Batch_BP_Expiration_BCT - To be Promoted

Take before and After screenshots and send to Juanita as confirmation

**Comment by JuanitaMiles** [comment]
Test accepted per review session on 6/25. Plan in place to babysit the batch jobs when they are run manually on 6/29. Batch jobs will only run for future applications to avoid data migration errors.
