### ISSUE TITLE
PLANNING - PDOX - Can't route plan

### ISSUE THREAD

**Issue by AReed327** [dhenry-KCI/FredCo-Post-Go-Live-#474]
Project Number - PL258814
Observed behavior - Reviews only routed to half of the reviewers. Once it got to the EH on the PDOX list, it didn't route to them or any agency after them (EH,FRO,PWDR,STRNAME)
Expected behavior - I expect the plan to route as designed. 
Screenshot -
![image](https://user-images.githubusercontent.com/58854333/75924538-237e9f80-5e35-11ea-9c4f-a3b82a742602.png)
![image](https://user-images.githubusercontent.com/58854333/75924634-4b6e0300-5e35-11ea-9d1f-978636f536c3.png)

**Comment by MLWilkins** [comment]
created the same application type in TEST and the due dates transferred from PDOX to IPS.
![image](https://user-images.githubusercontent.com/50637067/75979692-0a1a3980-5eaf-11ea-9837-645b20ba14bf.png)


![image](https://user-images.githubusercontent.com/50637067/75979758-32099d00-5eaf-11ea-88d1-77fe831440d9.png)

**Comment by AReed327** [comment]
Attempted to route plan again in production this morning 3/5/2020. Same error. AReed
![image](https://user-images.githubusercontent.com/58854333/75981882-6e3efc80-5eb3-11ea-84d7-178a13ef2c06.png)

**Comment by AReed327** [comment]
Juanita fixed this. Issue was that AEvangelista was expired as a user in IPS. Likely due to a new tool to expire old users. However she is not an old user.
