### ISSUE TITLE
Health Review - Did not generate

### ISSUE THREAD

**Issue by ABonomo21** [dhenry-KCI/FredCo-Post-Go-Live-#475]
The health review did not generate on a resuse accessory structure served by well and septic when the permit first spawned reviews. 

it had to go through a revision and health automatically added. 

The review should have added the first time and it should not automatically add the second time... 
![image](https://user-images.githubusercontent.com/47611580/75980590-c88a8e00-5eb0-11ea-8ad3-ba8d64876c93.png)

**Comment by megisys** [comment]
See 260782 in Test 

Promoted RESUSES_EH_Review_AOC once accepted

**Comment by ABonomo21** [comment]
retested in test 266748 - fee and review generated 
![image](https://user-images.githubusercontent.com/47611580/76445256-82936580-639b-11ea-8a98-bc7dfc92c306.png)

**Comment by JuanitaMiles** [comment]
Reopening Ticket - EH review automatically adding on second cycle of review is still a problem.

RESUSE Permit # 257808 - The EH review and fee did not generate when progressing through to the first round of review when it should have. Ashlye then manually added DPZ for a second cycle of review and approved the Assign condition. Upon progressing back to Under Review, the system automatically added an EH review to the application. NO reviews should automatically add after the initial round of reviews.

![image](https://user-images.githubusercontent.com/31770504/78572015-ed965780-77f4-11ea-9ddc-469aa932f8c8.png)

![image](https://user-images.githubusercontent.com/31770504/78572049-f8e98300-77f4-11ea-9d77-3823223ae31b.png)

**Comment by megisys** [comment]
@JuanitaMiles There is nothing to fix here. This is just a case which was broken before the fix and all new ones will not have this problem.. There is not much i can fix here. Can you confirm this is not happening for net new ?

**Comment by JuanitaMiles** [comment]
Scrolled through a bunch of applications, the one below appears to have worked properly (from beginning of April). Closing.

@ABonomo21 You'll just need to keep an eye on the older applications that had an issue prior to the fix being pushed on 3/22.

![image](https://user-images.githubusercontent.com/31770504/78578621-c3956300-77fd-11ea-9066-3deda58f32d0.png)
