### ISSUE TITLE
Electric Cut Ins Report duplicating permits

### ISSUE THREAD

**Issue by awhite806** [dhenry-KCI/FredCo-Post-Go-Live-#476]
On the Electrical Cut Ins some of the permits are duplicating on the report. They only had the one inspection so they should only be there once.
[Electric Cut Ins.pdf](https://github.com/dhenry-KCI/FredCo-Post-Go-Live-/files/4293719/Electric.Cut.Ins.pdf)

**Comment by TaraF** [comment]
Assigned, in progress.

**Comment by TaraF** [comment]
This is ready for review in Test, for both Electrical Cut In reports (Thurmont/Non Thurmont).
