### ISSUE TITLE
Planning - Review Problems - Problem Resolution Code - DO NOT USE was removed from Transfer

### ISSUE THREAD

**Issue by AReed327** [dhenry-KCI/FredCo-Post-Go-Live-#478]
Project Number - 19855
Observed behavior - Transfer used to say "do not use" but it has been removed. Reviewers are now using transferred and they shouldn't be.
Expected behavior - Add the note back to transfer
Screenshot -
![image](https://user-images.githubusercontent.com/58854333/76117682-3ec6e780-5fba-11ea-83ea-69084dbf6efa.png)

**Comment by MLWilkins** [comment]
Need to check all planning AP types

**Comment by MLWilkins** [comment]
See ticket 2255 from original repository.

**Comment by pooldaddy** [comment]
@MLWilkins  I can expire this PRC, to prevent it from being used as opposed to just changing the description.  Let me know

**Comment by MLWilkins** [comment]
Hi Jeff,

Per Dan it has to stay for system generated transfers. That’s why we added “do not use” so staff wouldn’t use it.

Mike

Sent from my iPhone

On Mar 9, 2020, at 1:14 PM, pooldaddy <notifications@github.com> wrote:

﻿
[EXTERNAL EMAIL]


@MLWilkins<https://github.com/MLWilkins> I can expire this PRC, to prevent it from being used as opposed to just changing the description. Let me know

**Comment by pooldaddy** [comment]
Hi Jeff, 

Per Dan it has to stay for system generated transfers. That’s why we added “do not use” so staff wouldn’t use it.

**Comment by pooldaddy** [comment]
@mwi lkensChange made in TEST.  Please verify.  if ok I can me change in PROD.
Hi Jeff, 
![image](https://user-images.githubusercontent.com/47391482/76242564-4f22d080-620d-11ea-9a27-6ff345447d3f.png)

**Comment by MLWilkins** [comment]
checked Site, Plat, FRO, PWCon, PrePlat, and Rezone.  All look good.

@pooldaddy ready to change in Prod.

**Comment by pooldaddy** [comment]
Completed in PROD

![image](https://user-images.githubusercontent.com/47391482/76248186-37e8e080-6217-11ea-9693-6fe22787f5c4.png)
