### ISSUE TITLE
Public Improvements Permit - related records

### ISSUE THREAD

**Issue by TMARTIN0926** [dhenry-KCI/FredCo-Post-Go-Live-#48]
The PWConstruct AP# is linked as a related record, however, there is still a red line for this. See screenshots - permit #197168 - this will not allow me to move forward with the permitting process

![197168 1](https://user-images.githubusercontent.com/58991985/71097474-06afc580-217e-11ea-97fb-7e083a9d4240.PNG)
![197168 2](https://user-images.githubusercontent.com/58991985/71097477-07e0f280-217e-11ea-9282-5030ad321585.PNG)

**Comment by ABonomo21** [comment]
I have reviewed this ticket and it is a bug. If the PW construct is related as a related record, the condition should not hold up the application from progressing.

**Comment by calequin** [comment]
there was an in life issue on the PWCONSTRUC Causing the red-line to stop. Basically the PWCONSTRUC Application was open but finalized causing the system to think that the application was not active. Epearl progressed the PWCONSTRUC application to the correct milestone but no CFIN log was created therefore it did not read it correctly.

![image](https://user-images.githubusercontent.com/47603568/71208667-1fe46f00-226f-11ea-80e9-6f57e07eec0e.png)

**Comment by emilypearl1** [comment]
Closing Ticket- this has been resolved.

**Comment by ABonomo21** [comment]
Reopening Ticket- Permit #161826

![image](https://user-images.githubusercontent.com/47611580/72168980-38dace80-339c-11ea-8e44-8eb04c723b96.png)

![image](https://user-images.githubusercontent.com/47611580/72169010-46905400-339c-11ea-85a5-8d5340798778.png)

**Comment by calequin** [comment]
I replicated in test. PWCONSTRUC application is finalized in the system and not in a complete milestone. Need to add a CLFIN log to the pwconstruc app to get it in the correct milestone. Delete the planning application as an other in prod and readd. It is like this because of the inlife progress.

**Comment by calequin** [comment]
dan will look into it further
