### ISSUE TITLE
Building Fee did not generate for Garage permit.

### ISSUE THREAD

**Issue by awhite806** [dhenry-KCI/FredCo-Post-Go-Live-#480]
This garage permit did not generate a building fee. all the required fields were complete. the fee should have been the Garage/Pole Building fee of $177
![garage fee error](https://user-images.githubusercontent.com/58981029/76241911-20f0c100-620c-11ea-8faa-d16adc9ec8cb.png)
![garage fee error 2](https://user-images.githubusercontent.com/58981029/76241914-22ba8480-620c-11ea-89f2-d1e3fd9cb894.png)

**Comment by megisys** [comment]
See 266747
