### ISSUE TITLE
Building Permits - Health Review Fees when Water/Sewer = TOWN

### ISSUE THREAD

**Issue by JuanitaMiles** [dhenry-KCI/FredCo-Post-Go-Live-#481]
Ashlye Bonomo reported the following issue in ticket #435, but creating a new ticket as it is unrelated to the ticket 435. This issue here appears to be how the AOC formula is written to add the Health Review fee to building permit applications. The formula appears to have the Health Review fee add when the Sewer Type and Water Type do not equal Public. According to what Ashlye has reported as an issue, the logic in the formula may need to change.

Will follow up with Ashlye to confirm whether or not it is sufficient to say the Health Review fee should ONLY generate when Water/Sewer Type equals Well/Septic. Or are there any other water/sewer types that would require health review fee?

Ticket #12 was referenced when updating the AOC formula.

![image](https://user-images.githubusercontent.com/31770504/76255732-14c52d80-6225-11ea-8ccb-23d954c9adc6.png)

![image](https://user-images.githubusercontent.com/31770504/76254485-eb0b0700-6222-11ea-9301-aaa20535ac25.png)

**Comment by JuanitaMiles** [comment]
Spoke with AB, 3/19/20

The formula above appears to add the health review fee when the water type and sewer type do not equal Public. This is not always the case and does not capture the accurate requirements surrounding the health review fee. The health fee and health review should add if the Water/Sewer types are Well **and/or** Septic. There may be many combinations of Well Water/Public Sewer; Town Water/Septic Sewer; etc. These combinations would also require health fees and review. 

There have also been other parameters identified (minor permits, etc) that would impact when the health fee and review should add.

**Comment by megisys** [comment]
RESBLDG_Fee_HealthReview_AOC - Promote once tested

**Comment by ABonomo21** [comment]
266872 did not add health fee
