### ISSUE TITLE
DLL Error When Trying to Assign Building Reviews in Test PDox

### ISSUE THREAD

**Issue by JuanitaMiles** [dhenry-KCI/FredCo-Post-Go-Live-#482]
During training we are getting the following error when trying to assign reviewers for a Fire Permit. This appears to be a dll error that may require a sync of environments.

This is occuring in the TEST pdox environment.
High Priority due to the interruptions it is causing during official ProjectDox training.

![image](https://user-images.githubusercontent.com/31770504/76441329-9cca4500-6395-11ea-8162-a05d6c972f9e.png)

**Comment by ABonomo21** [comment]
tested 266750 from ips test to pdox test - all communications worked
