### ISSUE TITLE
Mobile - Users Not Able to Login

### ISSUE THREAD

**Issue by JuanitaMiles** [dhenry-KCI/FredCo-Post-Go-Live-#483]
Several mobile users are not able to login to the application. They are getting errors.

**Bob to provide screenshot of errors as well as any additional details regarding timing, etc of the issue. 

Brief details gathered from Bob include: those users that logged in super early this morning got logged in and stayed logged in, however, users that tried log in a little later in the day have not been able to and are getting an error message.

**Comment by TheBobEnsor** [comment]
Started this morning 
those that were logged in and were able to stay logged in had no problem.  Only those that tried logging in later or for some reason got kicked off could not get logged back in 
error message  is attached 
![Error sending request](https://user-images.githubusercontent.com/60886453/76451755-4fa29f00-63a6-11ea-8a25-796e5867879f.jpg)

**Comment by megisys** [comment]
Which Users.. Details are important in trying to work through issues.

**Comment by TheBobEnsor** [comment]
Inspectors have all logged in this morning
Bob
