### ISSUE TITLE
Processed Date and Issued Dates

### ISSUE THREAD

**Issue by emilypearl1** [dhenry-KCI/FredCo-Post-Go-Live-#484]
Permit 259225 was a spawned permit that was added on 1/9/20

Justin was the last to approve his review and the processed and issued dates generated when he resulted his review. 

![image](https://user-images.githubusercontent.com/58855801/76517244-59261880-6433-11ea-996a-06660e327fca.png)

The processed date should be the date it started the process.
issued- is correct.

**Comment by JuanitaMiles** [comment]
The Processed date should populate with the date the Completeness Check was approved/completed.

![image](https://user-images.githubusercontent.com/31770504/76521670-a9a17400-643b-11ea-9d8a-b3c76b0e1faf.png)

**Comment by megisys** [comment]
Hi @JuanitaMiles this instance has been overriden and bounced so much. Why is this happening.. The Issued date is correct. The processed date is anyone guess due to the manually manipulation here. I believe this is an isolated incident and there is nothing here to fix.

**Comment by emilypearl1** [comment]
268193 just completed completeness check no processed date 
![image](https://user-images.githubusercontent.com/58855801/76523129-4238f380-643e-11ea-88c7-7695333ab977.png)

**Comment by JuanitaMiles** [comment]
The established process is as follows: The processed date should populate once the application moves out of the Intake/Completeness Check milestone. Standard process should have the Completeness Check review resulted as the last step taken in the Intake Review milestone so it would USUALLY be the same time the completeness check review is completed.

I will test to see if I can replicate any issues that Emily might be seeing here.

**Comment by megisys** [comment]
Juanita,  i double checked just now.. So I think it is right

**Comment by JuanitaMiles** [comment]
Replicated the grading permit above and the processed/issued date/times generated as they should. Closing ticket for now. Will reopen if problem occurs when an application has not been manually changed multiple times.

![image](https://user-images.githubusercontent.com/31770504/76869847-42bafb00-683f-11ea-9995-dc32a9c9309e.png)
![image](https://user-images.githubusercontent.com/31770504/76869904-5ebe9c80-683f-11ea-87d5-9475a77acb7f.png)
