### ISSUE TITLE
U&O hold preventing permit issuance

### ISSUE THREAD

**Issue by awhite806** [dhenry-KCI/FredCo-Post-Go-Live-#485]
Justin put a U&O hold on this permit but it is holding up the issuance of the permit, when it shouldn't. the U&O hold should only hold up the permit at the Pending Certificate Stage.
![U o HOLD](https://user-images.githubusercontent.com/58981029/76530927-cf824500-644a-11ea-92e5-5a752946cd0a.png)
![U o HOLD 2](https://user-images.githubusercontent.com/58981029/76530934-d01adb80-644a-11ea-97a5-2a1fe7e132ce.png)

**Comment by JuanitaMiles** [comment]
This was previously discussed with Ibti back in March 2019 old github 318. U&O should only be for the Pending Certificate milestone.

![image](https://user-images.githubusercontent.com/31770504/76533940-36a1f880-644f-11ea-9785-929ce98260df.png)

**Comment by megisys** [comment]
BP_HoldLog_SCF to be promoted
BP_UOHoldLog to be copied and placed on Pending Certification

**Comment by JuanitaMiles** [comment]
Progressed this application in Test. The permit issued without the U&O condition being approved or the event log being stopped. Then progressed to Pending Certificate and received the status check that hold log must have a valid stop date. Added a stopped date to the event log and the status check was satisfied.

@ABonomo21 @awhite806 Before marking as test accepted, want to confirm with Abbie and Ashlye regarding the established workflow surrounding the Condition that generates as a result of adding the UOHOLD event log. Currently the status check at pending certificate is satisfied by entering a stopped date on the event log. Does anything need to be done on the Condition? Should approving the condition satisfy the status check instead or can the current configuration using the event log be kept as is?

![image](https://user-images.githubusercontent.com/31770504/76988361-f7761a80-691a-11ea-8930-53bce36b919e.png)
