### ISSUE TITLE
Revision fee did not add when review is marked as resubmit.

### ISSUE THREAD

**Issue by awhite806** [dhenry-KCI/FredCo-Post-Go-Live-#486]
permit 266470 did not generate a revision fee when the review for plan review is marked as resubmit.
![266470 revision fee did not add 2](https://user-images.githubusercontent.com/58981029/76547071-f77da280-6462-11ea-8f76-49567da705da.png)
![266470 revision fee did not add](https://user-images.githubusercontent.com/58981029/76547072-f77da280-6462-11ea-91c0-a309b2215081.png)

**Comment by megisys** [comment]
Hi All,

What are the revision rules. I have that only PWDR and Health reviews kick off revision fees. PLNREV was never included. Not for Res or NonREs. PLease advise

**Comment by megisys** [comment]
Needed to take into consideration the Completeness check resubmits.. Changed in TEST. 

BLDG_PWDRNoRevisionFee_AOC

**Comment by JuanitaMiles** [comment]
Progressed this application in Test, marked plan review for resubmit, and the revision fee added.
![image](https://user-images.githubusercontent.com/31770504/76977205-6481b400-690b-11ea-9e5c-adc08a89c3c6.png)

Also tested an EH review as a resubmit only, to ensure the fee would not add, as expected. This worked.
![image](https://user-images.githubusercontent.com/31770504/76980858-1b802e80-6910-11ea-8fbd-97500d854670.png)
