### ISSUE TITLE
PLANNING - APFO holding up Site Plan closure

### ISSUE THREAD

**Issue by AReed327** [dhenry-KCI/FredCo-Post-Go-Live-#487]
Project Number - SP257714/A257678 & SP257610/A257608. 
Observed behavior - Site plan will not close. It says APFO not approved as a Child Application. However the APFO is Closed/Complete
Expected behavior - I expect Site Plan to close with an approved APFO Exemption worktype or an approved APFO worktype that is in Admin Closure.
Screenshot -
![image](https://user-images.githubusercontent.com/58854333/76763365-5bf17800-6769-11ea-8220-8abaae6f50d1.png)
![image](https://user-images.githubusercontent.com/58854333/76763396-6875d080-6769-11ea-964e-6a6975ffbe4e.png)

**Comment by megisys** [comment]
The APFO has no approval date.

**Comment by AReed327** [comment]
Can you make it so that the approval date populates when the application closes on APFO exemptions?

**Comment by AReed327** [comment]
Where is the APFO Approval date supposed to go? I initially thought you were talking about the expires date under job description but that's not approval and it didn't close with the expiration date being filled in.

**Comment by megisys** [comment]
Approval is set at Admin Closure.. I think Exempts bypass this milestone

**Comment by megisys** [comment]
Please test Exempt APFO. Should set approved date after last review is approved during under review

**Comment by AReed327** [comment]
Verified approved date populated and SITE plan associated to APFO closed upon completion
SP258933/A258932
![image](https://user-images.githubusercontent.com/58854333/76854740-0c24b680-6826-11ea-9db4-df4857c501c0.png)
****
