### ISSUE TITLE
planning-APFO- no LOU selected but in awaiting LOU milestone and LOU required notification going out

### ISSUE THREAD

**Issue by MLWilkins** [dhenry-KCI/FredCo-Post-Go-Live-#488]
this is in test-assuming it is also doing this in Prod.

selected "no lou"  but went to awaiting LOU milestone and emailed customer for an LOU.  When "no lou" is selected it should not ask for an LOU

![image](https://user-images.githubusercontent.com/50637067/76768042-dd003d80-6770-11ea-950f-1261b86286c2.png)

![image](https://user-images.githubusercontent.com/50637067/76768131-f7d2b200-6770-11ea-8152-409fdc48325e.png)

**Comment by MLWilkins** [comment]
also, a condition for LOU received isnt populating

![image](https://user-images.githubusercontent.com/50637067/76768472-70d20980-6771-11ea-8207-703b0d7def3e.png)

**Comment by megisys** [comment]
@JuanitaMiles please assign this t me.. It is a redesign

**Comment by JuanitaMiles** [comment]
@megisys done

**Comment by megisys** [comment]
IF no LOU - Go to Hearing Preparation.

**Comment by megisys** [comment]
APFO Exemptions to go to pre closed and have the approved date set.

**Comment by AReed327** [comment]
A258942 - Worked as expected when No LOU was selected on Additional Detail.

![image](https://user-images.githubusercontent.com/58854333/77924096-43a55100-7271-11ea-9dbe-8d4aa748d900.png)

A258943 - Worked as expected still when Minor LOU was selected on Additional Details. Awaiting LOU for applicants submission and went to LOU Review when the applicant resubmitted. 
![image](https://user-images.githubusercontent.com/58854333/77933583-f9c26800-727c-11ea-94d4-50a5a10ba6c4.png)

**Comment by AReed327** [comment]
Adding for additional documentation. LOU Notification did not go out when no LOU was selected A258942 and did go out when Minor LOU was selected A258943. AREED

**Comment by megisys** [comment]
Deployed
