### ISSUE TITLE
PROJECT DOX FILE UPLOAD ERRORS

### ISSUE THREAD

**Issue by ABonomo21** [dhenry-KCI/FredCo-Post-Go-Live-#489]
We are having applicant struggle to get plans uploaded in to project dox- Mara was on site and thinks this may be a job processing error - can we please escalated this to the support team with Avolve 

there is a current permit in pdox that has erroed files and the applicant is in I.E. , files are less than 1MB  and they are PDF files. It is preventing an applicant from submitting and he has uploaded multiple times. 

Permit # 266492-

**Comment by pooldaddy** [comment]
@ABonomo21 can you attach one of the problem files to this ticket

**Comment by pooldaddy** [comment]
@ABonomo21 @JuanitaMiles I can open a ticket with Avolve, but should have the errored upload file to attach.

**Comment by JuanitaMiles** [comment]
Will follow up directly with both Ashley's to get the examples sent directly to Jeff and Rick for an Avolve ticket to be created.

**Comment by ABonomo21** [comment]
assigning this back to Jeff because we have provided example and he is currently working with Avolve.

**Comment by ABonomo21** [comment]
Closing ticket meeting with Avolve 4.21.20 - resolved the issue- issues with the firewall async was turned off and that allowed the plans to upload.

**Comment by pooldaddy** [comment]
![image](https://user-images.githubusercontent.com/47391482/79902448-81644800-83df-11ea-933e-668de1dc8e2d.png)
![image](https://user-images.githubusercontent.com/47391482/79902652-d2743c00-83df-11ea-9816-bead906e80db.png)
Screenshot from Project dox Admin above

**Comment by JuanitaMiles** [comment]
Reopening for Tracking - A. Reed encountered another instance of this upload error on 4/24. County IIT has followed up on existing Avolve ticket.

![image](https://user-images.githubusercontent.com/31770504/80498965-63946700-893a-11ea-9bd4-b7483ddef83a.png)

**Comment by pooldaddy** [comment]
@JuanitaMiles @AReed327 @ABonomo21   Since our initial fix from the meeting 2-3 weeks ago, there have only have 2 occurrences. one which we never determined cause and one where the 2 files from the user were corrupt and unable to be opened in adobe.  At this point, I suggest we close this ticket out.

**Comment by JuanitaMiles** [comment]
Closing. Will monitor and reopen if additional issues arise.
