### ISSUE TITLE
Resbldg - Blanket approval 

### ISSUE THREAD

**Issue by ABonomo21** [dhenry-KCI/FredCo-Post-Go-Live-#49]
we are adding approved blanket projects under related records and the system is not recognizing it. still generates the condition that an approved blanket is required. 

once an approved blanket is added it should satisfy the condition

![image](https://user-images.githubusercontent.com/47611580/71097569-2a730b80-217e-11ea-884e-7115d8e20f0a.png)

we keep having to override these and it stopping progression of the milestone

**Comment by ScottVanSooy** [comment]
The formula is called  BlanketCheckFormula it still needs debugging.

**Comment by ScottVanSooy** [comment]
The reason this is happening is because there are no Related Building apps of type BPREVIEW in the Associated Project.

Looking for guidance on how to proceed.

**Comment by ABonomo21** [comment]
scott we can talk about this on the 3 pm

**Comment by ABonomo21** [comment]
![image](https://user-images.githubusercontent.com/47611580/71203118-6b951980-226b-11ea-9a1c-99b8342fa0c1.png)

**Comment by ScottVanSooy** [comment]
Promote BP_BlanketReview

From Test to Prod
[BP_BlanketReview.txt](https://github.com/dhenry-KCI/FredCo-Post-Go-Live-/files/3985945/BP_BlanketReview.txt)

**Comment by ScottVanSooy** [comment]
![Capture](https://user-images.githubusercontent.com/58946969/71378445-a903ea80-257c-11ea-8957-7c63851f4c63.PNG)
![Capture 2](https://user-images.githubusercontent.com/58946969/71378447-aacdae00-257c-11ea-9411-ff619682e2ed.PNG)

Formula need to we reworked.  I  will do that this evening

**Comment by ABonomo21** [comment]
Thank you scott please let me know if you have questions. 

again if the blanket plan is checked on the details page then they system should check to make sure the attached blanket in the related records (which is a project) is approved.

**Comment by ScottVanSooy** [comment]
Promote BP_BLANKETREVIEW from Test to Prod

**Comment by ScottVanSooy** [comment]
BP_BLANKETREVIEW Promoted from test to Prod 12/23/19.  Please Re-test

**Comment by ABonomo21** [comment]
will re-open when we come across another blanket permit
