### ISSUE TITLE
Business License - Liquor License - Add Hotel Lobby Fee

### ISSUE THREAD

**Issue by JuanitaMiles** [dhenry-KCI/FredCo-Post-Go-Live-#490]
See issue/request from Dawn's email below. Need to confirm whether or not the Hotel Lobby fees exists and is expired, and therefore needs to be unexpired, or if the fee needs to be created as new.

![image](https://user-images.githubusercontent.com/31770504/76883688-ea8df400-6852-11ea-93c1-3901e146e00c.png)

![image](https://user-images.githubusercontent.com/31770504/76883826-1a3cfc00-6853-11ea-91b6-4ae460cb651d.png)

**Comment by pooldaddy** [comment]
@JuanitaMiles currently there is only a fee with description of HOTEL   fee  amount is $2000
formula prorates based on date fee assessed
if month fee created is 8, 9, or 10 prorates quantity to .75
if month fee created is 11 12, or 1 prorates quantity to .50
if month fee created is 2,3, or 4 prorates quantity to ..25
if month fee created is 5, 6 or 7  prorates quantity to .75

GL # is 10.98.998.999 40501 0000

For New Hotel Lobby Fee what is full rate, gl , and is proration same as HOTEL FEE above.

Emailed above questions to Dawn ,Penny, And Ashlyee

**Comment by pooldaddy** [comment]
![image](https://user-images.githubusercontent.com/47391482/77074868-d61f3800-69c7-11ea-96c6-3fbf04531272.png)
 Email to liquor board

**Comment by pooldaddy** [comment]
Waiting on Liquor Board Reply

**Comment by JuanitaMiles** [comment]
@pooldaddy Jeff - If you haven't received a response from the Liquor Board regarding this, can you follow up with them again to get the ticket addressed and closed?

**Comment by pooldaddy** [comment]
![image](https://user-images.githubusercontent.com/47391482/82362239-0c822f00-99da-11ea-8879-bee13799ef6b.png)

**Comment by pooldaddy** [comment]
@jaunita Added to Both TEST & PROD notified liquor board

**Comment by JuanitaMiles** [comment]
I looked in both Test and Prod - The Hotel Lobby fee is added to the Fee Library. However, there are a few more steps that will need to happen...Although the fee is listed in the License Fee Library, it has not yet been associated to any particular application type, and therefore will not be a selectable fee when processing the application. So:

1) Fee needs to be added to the Standard Fees grid for the Liquor License AP type. (Can be found via the License Workflow window. See second screenshot.) At this point the "Add On" milestone and formula do not appear to be necessary.

2) Permissions will likely need to be updated to allow this fee to be accessible to Liquor Board and Admins/Super Users/Cashiers. I can provide some training on how to update permissions once number 1 has been completed.

![image](https://user-images.githubusercontent.com/31770504/82367431-cc26af00-99e1-11ea-9d2d-3f8d5004f692.png)
![image](https://user-images.githubusercontent.com/31770504/82368270-25431280-99e3-11ea-8b35-50413a3d409b.png)

**Comment by pooldaddy** [comment]
Item 1 completed in prod and test

**Comment by JuanitaMiles** [comment]
Provided training on how to add the permissions for the Hotel Lobby fee today (5/20) in Test.

@Ycoto to complete the permission update in production. Yaciel, once complete, please label this ticket as "Deployed to Production" and assign me so I can check it and close if there are no issues.
