### ISSUE TITLE
Use Permits - Land Use - Assign All Land Use Inspections to Kim Connor

### ISSUE THREAD

**Issue by JuanitaMiles** [dhenry-KCI/FredCo-Post-Go-Live-#493]
Confirmed with Ashlye B - 3/19/2020

All inspections for Land Use permits should auto assign to Kim Connor. Kim should be able to perform all inspections for these permits. In the event she feels she cannot perform an inspection she will re-assign to the appropriate inspector.

(issue identified as a result of #467 ) 

![image](https://user-images.githubusercontent.com/31770504/77104600-a0437900-69f2-11ea-80b1-7a5e79f6bc09.png)

**Comment by pooldaddy** [comment]
The following inspections in LandUse assigned to KCONNOR in TEST for all election districts.
![image](https://user-images.githubusercontent.com/47391482/77162870-4fc82c00-6a83-11ea-9015-b1b0a93317d1.png)

**Comment by JuanitaMiles** [comment]
All of the inspections on my Land Use permit have auto-assigned to Kim. Test Accepted.

@pooldaddy go ahead and make the change in production

![image](https://user-images.githubusercontent.com/31770504/77188135-ead4fc00-6aab-11ea-886f-251a7dbb6017.png)

**Comment by pooldaddy** [comment]
Done
