### ISSUE TITLE
Gaming - Monthly Tip Jar Report - Missing Gaming Report Details Information

### ISSUE THREAD

**Issue by JuanitaMiles** [dhenry-KCI/FredCo-Post-Go-Live-#494]
Ashlye has reported the following issue via email:

![image](https://user-images.githubusercontent.com/31770504/77336125-785b5a80-6cfd-11ea-9a77-9c7e6a402683.png)

[20200323102520834.pdf](https://github.com/dhenry-KCI/FredCo-Post-Go-Live-/files/4370459/20200323102520834.pdf)

**Comment by TaraF** [comment]
Assigned, in progress.

**Comment by TaraF** [comment]
@ABonomo21  - this is ready in TEST.  Please note that for 9045, no data will show in Test, since there isn't any recorded.

**Comment by ABonomo21** [comment]
All after review- It looks like the report in production is not generating details of the monthly reports that have been processed. When I tested, I selected a few at random and at the time there were no reports submitted for those organizations, I could have swore some of those organizations were showing reports when I ran it in test.  When I went to run the report in production none of the gaming reports showed up for any organization. 

The reports submitted can be found under the  gaming REPORT details page for example a/p 9008 shows a report submitted in the details page but it does not show up on the report.

Any report submitted either for an on premise or off premise detail should show up on the report. 

I apologize for the confusion on this one. Any way to expedite this, thank you! Ash @JuanitaMiles @TaraF

**Comment by TaraF** [comment]
@ABonomo21  - deployed in Prod, appears to be functioning now.

**Comment by JuanitaMiles** [comment]
@ABonomo21 Take a look at the report in Production to see if it shows the expected data. If all looks good, we can close the ticket.

**Comment by ABonomo21** [comment]
checked 6 random and all accurate - thanks tara
