### ISSUE TITLE
Master Electrician - Restricted License Category

### ISSUE THREAD

**Issue by ABonomo21** [dhenry-KCI/FredCo-Post-Go-Live-#495]
Need to add a category box on the 
Electrical - Restricted Licenses 

1. Electrically operate heating/air conditioning and refrigeration equipment
2. Motor repairs and services
3. Low Voltage- 50 Volts or Less
4. Any other electrical equipment to be specified on license (need a free form box) 

![image](https://user-images.githubusercontent.com/47611580/77344746-03425200-6d0a-11ea-9641-42048deff0b1.png)
[20200323133514971.pdf](https://github.com/dhenry-KCI/FredCo-Post-Go-Live-/files/4371193/20200323133514971.pdf)

**Comment by JuanitaMiles** [comment]
Discussed this item during 3/23 webex meeting. 

Assigning to Dan for inclusion in April release.

**Comment by megisys** [comment]
PLease test in Test.

**Comment by ABonomo21** [comment]
Elec Restricted Type is now on the details page once the license category is Restricted but can you move it up under the license details instead of under the section complete @megisys 

once moved this can be accepted

![image](https://user-images.githubusercontent.com/47611580/78359454-1a433880-7583-11ea-9e29-0bd85d67eca1.png)

**Comment by ABonomo21** [comment]
![image](https://user-images.githubusercontent.com/47611580/78365578-45cb2080-758d-11ea-98b7-dcd77108091f.png)
fixed

**Comment by ABonomo21** [comment]
Dan- the restricted detail page does not show up on r4c..
![image](https://user-images.githubusercontent.com/47611580/78369665-8ded4180-7593-11ea-872d-8d0a53a0422c.png)
@megisys
