### ISSUE TITLE
Expired applications not expiring after 6 months

### ISSUE THREAD

**Issue by awhite806** [dhenry-KCI/FredCo-Post-Go-Live-#496]
Applications are only valid for 6 months, then they should expire.
![image](https://user-images.githubusercontent.com/58981029/77351183-cda26680-6d13-11ea-83d1-57ed3c9293f4.png)
![image](https://user-images.githubusercontent.com/58981029/77351222-dd21af80-6d13-11ea-8fcc-06fa0ea8b72d.png)

**Comment by JuanitaMiles** [comment]
Requirements surrounding this type of expiration has been discussed in the past but I'm unsure if this made it into a configuration item. Need to confirm if it is part of the current expiration batch job that exists.

This is where an application has sat unissued for an extended period and should expire due to inactivity.

@megisys Do you have any thought/confirmation on this?

**Comment by pooldaddy** [comment]
@megisys  

Has not run since 2/11. Why?
See screenshots below:
 
 
Jeff Wisner

**Comment by pooldaddy** [comment]
![image](https://user-images.githubusercontent.com/47391482/77438020-b454f500-6dbb-11ea-90c6-d90b7e926c28.png)

**Comment by megisys** [comment]
Job was left of schedulde. PLease review in Test and i will run in Production and scehdule daily

**Comment by pooldaddy** [comment]
@JuanitaMiles @megisys 197075 still not expired in TSET

**Comment by megisys** [comment]
197075 - Is not yet an application.. It has no expiry date. IT is not a permit yet

**Comment by megisys** [comment]
@pooldaddy

**Comment by ABonomo21** [comment]
All- 

Once application fees have been paid and there is a process date then it is an Application and they should expire 6 months from the process date unless an extension is granted or it becomes an issued permit, at which time there would be an issued date generate and the expiration date should populate as one year from the issuance date. 

@megisys @pooldaddy

**Comment by megisys** [comment]
@ABonomo21 When does the expiry date get set ?

**Comment by megisys** [comment]
This is sitting waiting for them to pay.. This is all part of abandonment.. - I will work on this this week as a total solution

**Comment by megisys** [comment]
Sent email to meet on this as the Adhoc report I wrote, shows that we have a slightly larger issues we need to address. I have solutions for this piece.

**Comment by ABonomo21** [comment]
set up meeting to focus on application expiration @dhenry-KCI

**Comment by megisys** [comment]
Abandoned Permits Task - Batch Manager Task..

**Comment by ABonomo21** [comment]
This one is going to need more time and thought, pushing to future phase list. 

we should really have it set that application processed set an expiration date of 6 month and then once it is issued the expiration date is overwritten by the new expiration date 1 year from the issuance date
