### ISSUE TITLE
Planning Staff - My Infor Dashboard Issue - Multiple reports go to the bottom of My Infor page when you click on them. - Extreme Ticket # 14623649

### ISSUE THREAD

**Issue by JuanitaMiles** [dhenry-KCI/FredCo-Post-Go-Live-#497]
When Shannon Walters turns on the out of the box Building Reviewer TO-DO List to view on her My Infor page, the dashboard item adds all the way at the bottom of the screen and cannot be moved up to be grouped with the other dashboard items.

As a work-around we have created a copy of the to-do list and it adds to dashboard without issue. We need to understand why the original to-do list is not functioning the way it should and how it can be fixed. 

![image](https://user-images.githubusercontent.com/31770504/77351732-8d8fb380-6d14-11ea-868c-40304afdd0f4.png)

![image](https://user-images.githubusercontent.com/31770504/77351804-abf5af00-6d14-11ea-8dc8-b3cbfa46b814.png)

![image](https://user-images.githubusercontent.com/31770504/77352012-e7907900-6d14-11ea-8202-71c276075d10.png)

**Comment by JuanitaMiles** [comment]
@pooldaddy This may be a good candidate to send to Infor Extreme.

**Comment by JuanitaMiles** [comment]
This is also happening to Tolson DeSa.

**Comment by pooldaddy** [comment]
@JuanitaMiles works in TEST when logged in as Shannon.  But not in PROD

**Comment by JuanitaMiles** [comment]
Adding Terry May (DUSWM) to list of those who are being impacted by this glitch in the system. Her explanation of her issue is below.

![image](https://user-images.githubusercontent.com/31770504/78160209-987fcd80-7411-11ea-9534-6589acfea15c.png)

**Comment by ABonomo21** [comment]
will need to re-open if this is something that occurs when back in the office. working remotely is when the issue was noticed.

**Comment by AReed327** [comment]
This was an issue when we were still in the office. I called Juanita when it occurred on Tolson Desa's office computer. He is still having the problem. It is happening on my dashboard with the PWCONSTRUC # of PAGES Dashboard. The report that is a problem on Tolson's is Building Reviewer to do list. Mike Wilkins is also having it happen to the Withdraw request dashboard. 
Tolson's
![image](https://user-images.githubusercontent.com/58854333/80209017-4a6c7d00-85ff-11ea-9a59-0152c824d560.png)
Ashley's
![image](https://user-images.githubusercontent.com/58854333/80209225-aafbba00-85ff-11ea-96d1-cc173e299df2.png)
When you click on the report to move it, it continues to almost "page down" and it continues to go down every time you try to move it back where it should be.

**Comment by MLWilkins** [comment]
Went to office and confirm that it happens in the office as well as remote.

**Comment by MLWilkins** [comment]
@JuanitaMiles @pooldaddy   This is happening to me in test as well as prod.

**Comment by JuanitaMiles** [comment]
@pooldaddy Jeff to create an Infor Xtreme ticket for this issue.

**Comment by AReed327** [comment]
@JuanitaMiles 
Using SAM "My Infor Configuration" --> Action ---> Clear all preferences 
This process clears all preferences in IPS but has also corrected my report that continued to page down. I don't know why it was paging down but this has corrected the issue so far. The important thing to document is that if you have this problem and use it as the fix, you must know what all of your preferences and dashboard reports are so you can put them back. 
![image](https://user-images.githubusercontent.com/58854333/81562202-6e9bbe00-9362-11ea-952b-215255ecf6e1.png)

**Comment by pooldaddy** [comment]
@JuanitaMiles I propose we close this.

**Comment by JuanitaMiles** [comment]
@pooldaddy @Ycoto  If you'd like to use the "Clear All Preferences" option as the resolution you'll need to ensure you understand what occurs when this option is selected and that IIT can support walking staff through how to reconfigure their dashboards they way they had them if/when this occurs again in the future.

**Comment by AReed327** [comment]
I agree that IIT will need to be able to support this. Before this method is used, IIT needs to confirm the names of all dashboards and any preferences the user has ex.  Contact and Property Browser set as page to load on start up
![image](https://user-images.githubusercontent.com/58854333/81855791-cdf9f980-952d-11ea-8838-e81972f58b64.png)

**Comment by JuanitaMiles** [comment]
Met with Yaciel and went over all of the functionality on the My Infor preferences page. He should now have an understanding the overall functionality and how to help staff re-setup their dashboards if/when they need to be cleared. Closing this ticket.

**Comment by JuanitaMiles** [comment]
Per discussion during morning meeting on 5/21 this issue continues to happen even after the preferences have been reset. Ashley Reed has been able to replicate.

@megisys  @AReed327  Dan can you look into this apparent glitch with the dashboard widgets jumping to the bottom of the page? If  you would like a webex with Ashley to demonstrate the problem, please let us know. Afterwards, if you feel it should be an Infor Extreme ticket, we can have IIT submit that with as much detail as possible. Thanks.

**Comment by megisys** [comment]
@JuanitaMiles  - This will need to be an Xtreme ticket for sure.

**Comment by megisys** [comment]
@pooldaddy @Ycoto - Please log with Infor Development. I can not fix this as it is a base product issue

**Comment by MLWilkins** [comment]
This is happening again on my dashboard, again with the withdraw request dashboard.  I moved it earlier today (before lunch) and tried moving it at 3:30 and it jumps to the bottom.

**Comment by pooldaddy** [comment]
Added extreme ticket # 14623649

**Comment by MLWilkins** [comment]
now completeness check and withdraw dashboard are behaving this way.  Cant even expand the dashboard report to read it.

![image](https://user-images.githubusercontent.com/50637067/84378958-03d4e100-abb3-11ea-969b-243d2963ed1f.png)

**Comment by JuanitaMiles** [comment]
@pooldaddy In recent communications with Terry May, you provided an update regarding this extreme ticket. Can you document that update here for everyone's knowledge please. If this is to be fixed with a future patch, please find out the expected release date for that patch and provide as well.

**Comment by pooldaddy** [comment]
This issue will be fixed in the IPS11.2 2007 (July) patch. Clearing the users My Infor Preferences may help for now. The intstall date for above patch is TBD.

**Comment by JuanitaMiles** [comment]
Anticipated to be fixed with 07 patch. Will address this ticket when planning for the 07 update. Moved to future phase list, closing.
