### ISSUE TITLE
PDox Error - Wendy Cochran Cannot Accept Task

### ISSUE THREAD

**Issue by JuanitaMiles** [dhenry-KCI/FredCo-Post-Go-Live-#498]
Wendy is getting the following error when trying to accept her department review task in ProjectDox.

![image](https://user-images.githubusercontent.com/31770504/77440705-fdf30f00-6dbe-11ea-8635-430ce7f8f8db.png)

**Comment by pooldaddy** [comment]
Her Hansen ID was blank in USER META DATA in PROD Added it see below
![image](https://user-images.githubusercontent.com/47391482/77444598-70b1b980-6dc2-11ea-8df2-adbccb7517f0.png)
  Please have her retry now

**Comment by JuanitaMiles** [comment]
@pooldaddy I will respond to Wendy to have her try again, but please update the spelling of her Hansen ID: WCOCHRAN

**Comment by pooldaddy** [comment]
Done

Jeff Wisner
Staff Software Integrator
Frederick County Government, IIT
301-600-1811

**Comment by pooldaddy** [comment]
@JuanitaMiles done fixed spelling

**Comment by JuanitaMiles** [comment]
![image](https://user-images.githubusercontent.com/31770504/77450998-77442f00-6dca-11ea-9328-46148a8fba13.png)
