### ISSUE TITLE
Release County Escrow Report issue

### ISSUE THREAD

**Issue by TaraF** [dhenry-KCI/FredCo-Post-Go-Live-#499]
Putting this here for tracking purposes:

[Release - County Escrow 134293.pdf](https://github.com/dhenry-KCI/FredCo-Post-Go-Live-/files/4389067/Release.-.County.Escrow.134293.pdf)

![image](https://user-images.githubusercontent.com/4104464/77681318-857d8100-6f6b-11ea-9dc1-7d98812e68ec.png)

**Comment by TaraF** [comment]
Assigned, in progress.

**Comment by TaraF** [comment]
@emilypearl1  - We determined a while back that only the latest release would be shown.  According to the time stamp in the database, it appears that bond # 4299 was input last.  If that is no longer the correct logic, do you have something we would know by looking at IPS which one to use if there are multiple?

![image](https://user-images.githubusercontent.com/4104464/78400588-03253a80-75c5-11ea-8119-df87eca7070b.png)

**Comment by ABonomo21** [comment]
emailed Emily 4.20.20

**Comment by emilypearl1** [comment]
Ok. I think I can live with this. Moving forward i will remember to print all the documents prior to releasing the second BT. This shouldnt be a problem. If I notice that this needs to be changed- I will reopen... but I can work with knowing this.

Thanks Tara. closing ticket.
