### ISSUE TITLE
PLANNING - Permissions - Craig Terry

### ISSUE THREAD

**Issue by AReed327** [dhenry-KCI/FredCo-Post-Go-Live-#5]
Craig Terry has insufficient access to be able to add an attachment to a plat in IPS.
PL257643
![image](https://user-images.githubusercontent.com/58854333/70826948-2cbc1b00-1db6-11ea-8e0f-d18dee551f2f.png)

**Comment by megisys** [comment]
HE is not picking the right Attachment Catalog. Are you sure this user is in Production ??

**Comment by AReed327** [comment]
I did this on my computer signed in as him. I did it properly.

**Comment by megisys** [comment]
Attachment catalog is Attachments. The screen shot says correspondence

**Comment by MLWilkins** [comment]
Craig gets this error when trying to change correspondence to attachment.

![image](https://user-images.githubusercontent.com/50637067/70916125-2366c480-1fe9-11ea-9898-463c751a7555.png)

**Comment by megisys** [comment]
Hi Mike,

I have a meeting at 10am. I will come up and look at this. Where is Craig located please

@MLWilkins

**Comment by MLWilkins** [comment]
Near me on 3rd floor.  I just got the same error on my account/PC

**Comment by megisys** [comment]
PLease Just type Attachments in the Catalog Name and then drag a file. It will save for future attachments
