### ISSUE TITLE
SCD Fee

### ISSUE THREAD

**Issue by ABonomo21** [dhenry-KCI/FredCo-Post-Go-Live-#50]
the SCD fee is generating as a quantity of 60 and the value of 0 

should have a fee value of 60 and quantity of 1

![image](https://user-images.githubusercontent.com/47611580/71097725-732ac480-217e-11ea-8085-88f67fd197f0.png)

**Comment by calequin** [comment]
Can I get an AP #? I tried to replicate in test and the fee populates correctly.
![image](https://user-images.githubusercontent.com/47603568/71131966-d2f39080-21bb-11ea-806a-97b1be917e79.png)

**Comment by dhenry-KCI** [comment]
@ABonomo21 - see comment from Christian

**Comment by ABonomo21** [comment]
fee has been working correctly will close for now.

**Comment by ABonomo21** [comment]
now the fee is not generating again?? added and came up as $0

![image](https://user-images.githubusercontent.com/47611580/72080112-2abc7d80-32ca-11ea-9946-8fb53e85870b.png)

**Comment by calequin** [comment]
Added new fee called RESBLDG SCD MINOR REVIEW FEE to resbldg applications. Expired the grading in prod.
