### ISSUE TITLE
Inspection Schedule Override Log

### ISSUE THREAD

**Issue by ABonomo21** [dhenry-KCI/FredCo-Post-Go-Live-#500]
Would like to be able to use the Inspection Schedule Override Log -
![image](https://user-images.githubusercontent.com/47611580/77752014-210b0200-6ffd-11ea-9f0c-f21e2d3243f0.png)

When the log is added it should allow for inspections to be scheduled until a stop date is entered on the log even if there are fees due on a permit. 

After a discussion with Dan and Gary yesterday we found that there will be times when we need to allow applicants to be able to schedule inspections even if re-inspections fees are due. This would our in the event there is a large project such as a school that may take time for payment to be received however, inspections still need to be scheduled and allowed to be requested via the portal. 

@TheBobEnsor @megisys

**Comment by megisys** [comment]
Hi There. So here is how it is coded.. If you add a INSPSCHED log to an Inspection (Not AP). The start date of the log will be the scheduled time.. And the log by will be the scheduled by.. You will get a message saying you need to open the inspection again.. Please try this out

**Comment by ABonomo21** [comment]
tested with Dan - confirmed work-
![image](https://user-images.githubusercontent.com/47611580/78364343-4b276b80-758b-11ea-86b9-fd518b79d220.png)

Dan will write up instructions for Jeff to know how to do the process. @JuanitaMiles

**Comment by ABonomo21** [comment]
spoke with Dan he will make the fixes

**Comment by ABonomo21** [comment]
Log does not add

**Comment by megisys** [comment]
INSPSCHED Needs to be added against the inspection.. Then the inspection can be scheduled.

**Comment by TheBobEnsor** [comment]
new part works and  now old part does not?

Failed

[Log add and remove insp ( Fees ).docx](https://github.com/dhenry-KCI/FredCo-Post-Go-Live-/files/4451717/Log.add.and.remove.insp.Fees.docx)

**Comment by ABonomo21** [comment]
What Bob was trying to say was.... 
When we originally asked for the inspection override log, the intended use was for use to be able to schedule an inspection when some pre-requisite inspection was still "required" i..e if a rough in inspection was only partially passed and we wanted to schedule a framing inspection, the system would stop us from being able to schedule, in production now... the override log allows us to bypass that condition that the pre-requisite inspection must be completed. 

When Bob tested the new changes in test, that functionality for the override log stopped working however, it DID allow us to schedule the inspection when a fee is still due on the permit. (which is what we want) however, we also need it to work as is does currently in production. 

The log as it was tested was entered against the inspection itself per dan's comment 7 days ago. 

Also another issue we found is that while we want to be able to force the inspections  via the override log, we  may also  have a need to remove that schedule date i.e. someone cancels. Currently as it is in production as well as in test, we are not able to remove the scheduled date once a override log has been entered on that inspection.  be able to removed it. 

Can we make it function that if we need to remove the scheduled date we can simply add a stop date on the override log and then remove the date? 

Thanks, 

Ash

**Comment by megisys** [comment]
Log allows you to do pretty much anything on that inspection. Once finished doing what is need please remove the log.
