### ISSUE TITLE
Awaiting Payment Notification Sending with Incorrect Amount

### ISSUE THREAD

**Issue by JuanitaMiles** [dhenry-KCI/FredCo-Post-Go-Live-#501]
Electrical Permit 270247

This application progressed into Awaiting Applicant Payment once the Completeness Check was approved and system generated 3 fees totaling $168.00. None of these fees were manually added by staff. The notification that sent to each applicant, however, only showed that the fees due totaled $57.00.

How could this have happened? From looking at the application it seems like the notification could have been created and started to send before the final minimum fee of $111.00 officially added to the application. The minimum fee has an applied date of 8:51 while the other two fees added at 8:50 and the notifications on the logs tab showed that they began to send at 8:50.

![image](https://user-images.githubusercontent.com/31770504/77770302-6ccca400-701b-11ea-9d7e-18976214eed9.png)
![image](https://user-images.githubusercontent.com/31770504/77770357-8110a100-701b-11ea-9fad-927ed4dd5700.png)
![image](https://user-images.githubusercontent.com/31770504/77770443-a3a2ba00-701b-11ea-8882-89357c45317c.png)

**Comment by megisys** [comment]
This change is much needed.. And Will require a new milestone called.. Add Minimum Fees. Will develop over the weekend for a full roundof testing

**Comment by megisys** [comment]
3 to 4 hours for this. but need to be done.

**Comment by megisys** [comment]
Added New Milestone for minimum Fees

**Comment by JuanitaMiles** [comment]
I can't possibly test the timing to replicate the minute change, but I see that all three fees added, there is a new milestone that it passed through in the Status Logs called Add Minimum Fees, and the email that generated showed the correct amount. Marking as test accepted.

![image](https://user-images.githubusercontent.com/31770504/78281437-a94f4280-74e8-11ea-83cb-a1ed28a6bde2.png)
![image](https://user-images.githubusercontent.com/31770504/78281465-b5d39b00-74e8-11ea-98ee-c152e9c7e119.png)
![image](https://user-images.githubusercontent.com/31770504/78281569-dd2a6800-74e8-11ea-8c16-2693be56a532.png)

**Comment by megisys** [comment]
Deployed to Production
