### ISSUE TITLE
Clean Up Grading Duplicate Review Types

### ISSUE THREAD

**Issue by megisys** [dhenry-KCI/FredCo-Post-Go-Live-#502]
Grading Reviews need to be merged where there are duplicates.

**Comment by megisys** [comment]
Update CDR_Building.BLDGREVIEW
Set APBLDGREVIEWTYPEKEY = 2340
Where APBLDGREVIEWTYPEKEY in (Select APBLDGREVIEWTYPEKEY from CDR_Building.BLDGREVIEWTYPE
Where APBLDGDEFNKEY = 1017 and REVIEWTYPE like 'DPZ%')


Update CDR_Building.BLDGREVIEW
Set APBLDGREVIEWTYPEKEY = 1851
Where APBLDGREVIEWTYPEKEY in (Select APBLDGREVIEWTYPEKEY from CDR_Building.BLDGREVIEWTYPE
Where APBLDGDEFNKEY = 1017 and REVIEWTYPE like 'SIGNATURE%')


Update CDR_Building.BLDGREVIEW
Set APBLDGREVIEWTYPEKEY = 1642
Where APBLDGREVIEWTYPEKEY in (Select APBLDGREVIEWTYPEKEY from CDR_Building.BLDGREVIEWTYPE
Where APBLDGDEFNKEY = 1017 and REVIEWTYPE like 'SIGNATREC%')

Update CDR_Building.BLDGREVIEW
Set APBLDGREVIEWTYPEKEY = 1624
Where APBLDGREVIEWTYPEKEY in (Select APBLDGREVIEWTYPEKEY from CDR_Building.BLDGREVIEWTYPE
Where APBLDGDEFNKEY = 1017 and REVIEWTYPE like 'ATTORNEY')

**Comment by ABonomo21** [comment]
moved to future phase
