### ISSUE TITLE
Application Fee Library Clean Up

### ISSUE THREAD

**Issue by megisys** [dhenry-KCI/FredCo-Post-Go-Live-#503]
Need to run a report and clean up the fee libraries as much as possible to make administration easier on the county. Especially building module

**Comment by megisys** [comment]
![image](https://user-images.githubusercontent.com/47392306/77834287-0c705c00-711a-11ea-8f3e-cff8fa86cee1.png)

**Comment by ABonomo21** [comment]
moved to future phases
