### ISSUE TITLE
Inspections on the r4c

### ISSUE THREAD

**Issue by ABonomo21** [dhenry-KCI/FredCo-Post-Go-Live-#51]
This one is scheduled for today and does not show who it is assigned to.

the portal is not showing who is assigned to the inspection this is important for our customers to know. 

![image](https://user-images.githubusercontent.com/47611580/71098442-b9345800-217f-11ea-892f-8417752ca7cb.png)

**Comment by calequin** [comment]
This is currently not supported in the product for R4C. We have created the assignment emails in order to instruct the constituent of the inspector assigned to the inspections. I can add this as an enhancement and we can submit to development for review.
