### ISSUE TITLE
Planning - Zoning Verification - Application has no milestone.

### ISSUE THREAD

**Issue by AReed327** [dhenry-KCI/FredCo-Post-Go-Live-#510]
Project Number - V259977  --> See it working correctly in TEST V258950
Observed behavior - Application has no Milestone. This is not happening in TEST only in PRODUCTION. Applicant got errors trying to submit online. I processed back office. The application came through but says "Application has no milestone". It is unclear what happened to make TEST and PRODUCTION not mirror one another. 
Expected behavior - I expect application to go to intake review milestone once submitted by the applicant
Screenshot -
![image](https://user-images.githubusercontent.com/58854333/78171290-3a0f1b00-7422-11ea-8278-d9fc54705a44.png)
![image](https://user-images.githubusercontent.com/58854333/78171386-56ab5300-7422-11ea-8dae-5608ce578e50.png)

**Comment by AReed327** [comment]
Created another new project in production to support that this did not happen from restarting services on 4/1/2020 around 2:10 - 2:15pm.
V259980
![image](https://user-images.githubusercontent.com/58854333/78172405-ffa67d80-7423-11ea-8c93-2f0ce6c4d924.png)
![image](https://user-images.githubusercontent.com/58854333/78172484-249af080-7424-11ea-874a-7ab0c0b91190.png)

**Comment by AReed327** [comment]
V259981 - submitted through R4C - the milestone is corrected but the fees didn't populate after the completeness check. The Fee is $118. Again, this is working in Test but not in Production
![image](https://user-images.githubusercontent.com/58854333/78244767-493ea900-74b4-11ea-88e9-09a933bf560e.png)
V259981 - PRODUCTION
![image](https://user-images.githubusercontent.com/58854333/78245194-0d581380-74b5-11ea-85c2-5510f2a8a27f.png)
TEST
![image](https://user-images.githubusercontent.com/58854333/78245231-21037a00-74b5-11ea-9bf4-c5b7ced2ac96.png)

**Comment by megisys** [comment]
Will fix this tonight ASAP. During outage.. Formula error during migration

**Comment by megisys** [comment]
Should I delete the AP ? @AReed327

**Comment by AReed327** [comment]
I can void it once it's fixed or you can delete it. I took the applicant off of it so it wouldn't show on their portal.

**Comment by AReed327** [comment]
Verified corrected as fees populated on V259983.
![image](https://user-images.githubusercontent.com/58854333/78359264-b882ce80-7582-11ea-849c-7436481d35a8.png)
