### ISSUE TITLE
ECS - Inspections Completed and Time Spent By WorkType and Inspection Type Report

### ISSUE THREAD

**Issue by TaraF** [dhenry-KCI/FredCo-Post-Go-Live-#512]
@emilypearl1  - documenting this here.  You have emailed that it is not running for you.  I am still able to run it.  Can you please provide some details - such as what environment, what specific date range, what browser you are using etc, and any screen captures - would greatly help me figure out why you can't see it.  Thank you!

![image](https://user-images.githubusercontent.com/4104464/78398628-6b721d00-75c1-11ea-9b43-1f62bc0a0989.png)

**Comment by ABonomo21** [comment]
i am using Chrome. 
i tried 7/1/2018-6/30/2019 (NO TIMES) 
![image](https://user-images.githubusercontent.com/47611580/78567082-25e66780-77ee-11ea-99e4-2df5748e1f77.png)
Tried using 7/1/2018 (time 00:01)  6/30/2019 (time 23:59)
![image](https://user-images.githubusercontent.com/47611580/78567189-4f9f8e80-77ee-11ea-96c8-9fa6800de02c.png)
![image](https://user-images.githubusercontent.com/47611580/78567253-65ad4f00-77ee-11ea-957b-f6119098db1b.png)

**Comment by TaraF** [comment]
@ABonomo21, @emilypearl1  - this is a glitch with the IPS product when using a Chrome browser (reports work fine in IE).  There are some character limitations that are not defined when chrome passes the name with the request.  INFOR needs to define the limits so the report can be named appropriately by your team.  If that is defined by INFOR, and the name is provided, I can implement.  

For now, I have renamed the report in TEST to be: ECS - Inspections By Work Type, Inspection Type, and it is working in Chrome.  That is probably not an ideal name, but I wanted to provide the fix so you could see there isn't a problem with the report itself.  Also, you can run in IE without problems.  

This likely has happened in other places not discovered yet, so a proper character limitation definition should be determined.  I can put this request in to Infor if you feel it is necessary.  Thanks!

**Comment by ABonomo21** [comment]
it looks fine in test. Can you promote to production so it will work with Chrome???

**Comment by TaraF** [comment]
@ABonomo21 

This has been promoted to prod with the same name as above.

Noting this will continue to be a problem for other reports until we understand the character limit.

**Comment by TaraF** [comment]
Closing issue on behalf of Emily Pearl (email 4/14/20).
