### ISSUE TITLE
Planning - PWCONSTRUC - Per Page Fee Notification not sending

### ISSUE THREAD

**Issue by AReed327** [dhenry-KCI/FredCo-Post-Go-Live-#513]
Project Number - PW258877
Observed behavior - Email Notification for the per page fee that is inserted during the first review did not send.
Expected behavior - An email proving the outstanding fees should be sent when fees are owed. If no fees are owed, no email should send.
(if it is 1 page, no fee will populate because the first page is paid with initial submission) This is on the PWCONSTRUC worktype when fees populate after the first review.
Screenshot -

![image](https://user-images.githubusercontent.com/58854333/78704253-96b67e00-78d9-11ea-8bbf-8eee6dc7fffd.png)

This is the notification from another plan PW257666.

![image](https://user-images.githubusercontent.com/58854333/78705123-011bee00-78db-11ea-8a34-65be543801c5.png)

**Comment by AReed327** [comment]
This is sending in Test. Ex: PW258953 but not production, unless you just fixed it. 
More Production examples of notification not sending: PW258818, PW258868, PW258871

**Comment by megisys** [comment]
We really need to build a Pay Fees reminder.. We talked about it.. We need to revisit this piece. Still invesitgating cause


Dan

**Comment by megisys** [comment]
OK The issue here is Pdox moved it in milestones and the PL_PayFees Notification was not defined for web services.. This has since been done. I HIGHLY recommend we do a payment reminder for the whole solution. I also as a side note put an email to the director of product that Notifications should not be defined in 3 places..

**Comment by megisys** [comment]
Fixed in Production.. Working in Test. See Email on Payment Reminders

**Comment by AReed327** [comment]
Working in test PW258953. Changed to test accepted.

**Comment by megisys** [comment]
Addressed in Production Too
