### ISSUE TITLE
PATCH TESTING - PLANNING - FRO - Internal review, end of review cycle notification of resubmit request

### ISSUE THREAD

**Issue by AReed327** [dhenry-KCI/FredCo-Post-Go-Live-#514]
Project Number - F258956
Observed behavior - Missing email notification after review cycle complete and resubmit requested. 
Expected behavior - Notification should be sent to the applicant indicating we are waiting for them to resubmit and to check the portal for review comments. 
Screenshot -
![image](https://user-images.githubusercontent.com/58854333/78813983-ee1d2280-799b-11ea-81c1-f0ac935e71f6.png)
Notification sent when project goes under review, but not after review cycle is complete and resubmit is requested.
![image](https://user-images.githubusercontent.com/58854333/78814085-17d64980-799c-11ea-9a90-6283844f761a.png)

**Comment by JuanitaMiles** [comment]
Assigning to Dan since he's done extensive work on planning notifications recently.

**Comment by AReed327** [comment]
I believe this notification may be called Planning/Zoning Resubmit Required

**Comment by AReed327** [comment]
Verified Corrected and notification received F258962

![image](https://user-images.githubusercontent.com/58854333/78995448-5ab92e00-7b10-11ea-832f-2a92995a21b7.png)
