### ISSUE TITLE
 PATCH TESTING-PLANNING - APFO - LOU FEE Populating after each resubmit 

### ISSUE THREAD

**Issue by AReed327** [dhenry-KCI/FredCo-Post-Go-Live-#515]
Project Number - A258957
Observed behavior - LOU Fee populated after first, second, and third review cycles
Expected behavior - Fee should only generate after the first review cycle when the box is checked on the details page. They only owe it one time.
Screenshot -
![image](https://user-images.githubusercontent.com/58854333/78818296-70104a00-79a2-11ea-856c-b258433eb88f.png)
![image](https://user-images.githubusercontent.com/58854333/78818338-83bbb080-79a2-11ea-8bea-dff210457c20.png)
3rd review
![image](https://user-images.githubusercontent.com/58854333/78818584-e44aed80-79a2-11ea-9c35-9fed813b4949.png)
Populated a 3rd time
![image](https://user-images.githubusercontent.com/58854333/78818635-f6c52700-79a2-11ea-829a-d8f4379fd3d3.png)

**Comment by megisys** [comment]
PLN_APFO_MinorLou_Fee_AOC - to be promoted when accepted

**Comment by AReed327** [comment]
A258961 Verified fee did not populate again after first resubmit. 

![image](https://user-images.githubusercontent.com/58854333/78993988-15dfc800-7b0d-11ea-9b9d-4972df927b8a.png)

![image](https://user-images.githubusercontent.com/58854333/78994012-22fcb700-7b0d-11ea-82e4-6840685a809e.png)
