### ISSUE TITLE
PATCH TESTING - PLANNING - Planning Outcome Notification did not send on APFO

### ISSUE THREAD

**Issue by AReed327** [dhenry-KCI/FredCo-Post-Go-Live-#516]
Project Number - A258958
Observed behavior - Planning Outcome Notification did not send on APFO
Expected behavior - When an application closes on an internal review, a notification should send. See example from FRO application below.
Screenshot -
![image](https://user-images.githubusercontent.com/58854333/78820554-0134f000-79a6-11ea-8135-a26e0c6dbf6d.png)
Notification example
![image](https://user-images.githubusercontent.com/58854333/78820745-56710180-79a6-11ea-8c8d-e7b79d2d0b33.png)

**Comment by megisys** [comment]
PLN_APFO_FROMUnderREview - Needs to be promoted once accepted

**Comment by AReed327** [comment]
Verified closed notification sent # A258961 
![image](https://user-images.githubusercontent.com/58854333/78994390-ed0c0280-7b0d-11ea-99f0-0a20c843d8e7.png)
