### ISSUE TITLE
Mobile Code Violations - Extreme Ticket # 14623660

### ISSUE THREAD

**Issue by ABonomo21** [dhenry-KCI/FredCo-Post-Go-Live-#518]
Kim Connor brought it to my attention yesterday that when an inspector results an inspection in back off and there was a previous inspection that failed resulting in code violations, the system asks you to confirm those code violations have been resolved prior to completing the new inspection result. However, in mobile it does not have the same functionality and it should.

**Comment by ABonomo21** [comment]
@TheBobEnsor

**Comment by megisys** [comment]
@JuanitaMiles - Can you create an example on this in the Test environment

**Comment by megisys** [comment]
I am told this is by design. As mobile are in the field and looking at the issues in person and confirming visually that everything is to be passed.. In the back office it is this way as the user is passing by way of being on location and it is a check

**Comment by JuanitaMiles** [comment]
@ABonomo21 Can you review Dan's response above regarding the intentions of the functionality and provide your thoughts.

**Comment by ABonomo21** [comment]
This functionality should work the same in both back office and mobile.

**Comment by megisys** [comment]
There is nothing i can do here. Mobile is a different platform. @JuanitaMiles @ABonomo21  - What would you like to do here. You can ask IIT to put in an enhancement request

**Comment by JuanitaMiles** [comment]
Spoke with Ashlye...Yes, @pooldaddy or @Ycoto please submit an enhancement request to Infor per Dan's suggestion above.

**Comment by pooldaddy** [comment]
Added extreme ticket #14623660

**Comment by JuanitaMiles** [comment]
This item will not be addressed prior to July 1. A Future Phase Ticket has been created for tracking in the next phase of the project.
[Ticket 97](https://github.com/JuanitaMiles/FredCo_Future_Phases/issues/97)
