### ISSUE TITLE
Planning - PDOX - Reviews showing late should exclude weekends.

### ISSUE THREAD

**Issue by AReed327** [dhenry-KCI/FredCo-Post-Go-Live-#519]
Project Number - PW257666 but I believe it's all PWCONSTRUCT in PDOX.
Observed behavior - Due date is including weekends. Project was submitted after 4 on Friday should not show due on Saturday. (Only focus on the one circled. The other has a different problem)
Expected behavior - Weekends should be excluded from due dates. Project should not show late (salmon color change) when it is not a business day.
Screenshot -
![image](https://user-images.githubusercontent.com/58854333/79121112-8b90a180-7d62-11ea-9363-d76cf64b3e89.png)

**Comment by JuanitaMiles** [comment]
@pooldaddy Jeff - I thought there was a setting to change this in PDox (?) to only count business days...if not we'll need to submit with Avolve support.

**Comment by pooldaddy** [comment]
@JuanitaMiles submitted a ticket to Avolve

**Comment by pooldaddy** [comment]
@JuanitaMiles @AReed327 @ABonomo21 @megisys 
Per Avolve the workflows can be set to Business or Calendar Days.
ALL workflows in TEST pdox were already set to Business Days
Of the four Project workflows in PROD see below only 1 was set to Calendar days (hi-lighted)
![image](https://user-images.githubusercontent.com/47391482/81399956-08acfd80-90fa-11ea-93ad-a5b79a34d04e.png)

I changed this one to Business days in PROD.

Note: Any changes only affect workflows going forward.  I am not convinced this is the solution to Ashley Reed's problem, but for sure all workflows should be set to Business Days.  Notifying Dan on this one for his input.

**Comment by pooldaddy** [comment]
@AReed327 @JuanitaMiles Take a look at above fix done in PROD,  that was the only workflow with days set to calander.  Suggest we close for now and reopen if issue resurfaces.

**Comment by JuanitaMiles** [comment]
@AReed327 Have you had any additional instances of this occurring?

**Comment by AReed327** [comment]
The only way I will know is if a plan is resubmitted on a Friday and it shows due on a Saturday. I will try one in Test on Friday to see if the Resubmit Received on a PWCONSTRUC is showing due on Saturday. AREED

**Comment by AReed327** [comment]
Also - doesn't make sense that the only change was to a building workflow. I agree with Jeff. That doesn't make sense that it would be the solution to what I am seeing.

**Comment by pooldaddy** [comment]
@AReed327 Can u test this Friday? If still an issue I will update ticket with Avolve

**Comment by AReed327** [comment]
I have a note to test this on Friday in test. Your previous comments lead me to believe Test may not mirror Prod. I'll let you know once it's tested.

**Comment by AReed327** [comment]
I replicated in Test and it does not show the weekend due date. I'm going to close this and I will let you know if it happens in PRODUCTION in the future. @pooldaddy 
![image](https://user-images.githubusercontent.com/58854333/82087377-f7e22600-96bd-11ea-942a-c19d433b4ecc.png)
