### ISSUE TITLE
inspection result 

### ISSUE THREAD

**Issue by ABonomo21** [dhenry-KCI/FredCo-Post-Go-Live-#52]
inspection comments are not showing up for applicants if they are logged in or anonymous. 
![image](https://user-images.githubusercontent.com/47611580/71098938-7a52d200-2180-11ea-9579-1786221665c4.png)

customers need to be able to see the comments and code violations

**Comment by megisys** [comment]
Click View Details @ABonomo21

**Comment by calequin** [comment]
fixed in prod. Turned on the comments for public view as well as Code Violations in the rhythm portlet
