### ISSUE TITLE
Zoning Review on Parcel in Town of Woodsboro

### ISSUE THREAD

**Issue by ABonomo21** [dhenry-KCI/FredCo-Post-Go-Live-#520]
Permit 271440 and associated grading permit 271473 generated a zoning review and fee however, this should not have happened because the parcel details clearly indicate it is located in the town limits of woodsboro.

**Comment by pooldaddy** [comment]
@ABonomo21 @JuanitaMiles 
As you can see below on parcal info thi spoperty has township code = 12
![image](https://user-images.githubusercontent.com/47391482/80134628-016be880-856d-11ea-9433-620c91e3dd37.png)
But on parcel details tab check box for incorp town is not checked

![image](https://user-images.githubusercontent.com/47391482/80134721-28c2b580-856d-11ea-9249-8f8330957430.png)


That is why review and fee for DPZ generted

Comments?

**Comment by JuanitaMiles** [comment]
@pooldaddy My first suggestion would be to check with County GIS (Mary M) to try to understand how that Incorp Town checkbox gets updated. Does GIS update it? or does Infor run some sort of script to populate it based on the Township code being something other than 00. If GIS doesn't maintain that field, then you'd follow up with Dan.

**Comment by JuanitaMiles** [comment]
@pooldaddy In addition, the code that tells the ResBldg DPZ review to add or not is not written the same way for the Grading permit DPZ review. DPZ Review AOC  on grading does not look for IncorpTown = true.

**Comment by pooldaddy** [comment]
@JuanitaMiles Both Town Code and Intown fields are updated by GIS provided the parcel is linked

**Comment by pooldaddy** [comment]
@JuanitaMiles @ABonomo21  When review and fee were generated on 4/1 for permit 271440, the towncode was set = 00 in error, and intown box was unchecked.  This data issue cause erroneous review and fee to be generted for DPZ.  Since has been corrected on 4/24 by GIS.  Closing issue.  For a sample ressfd permit see test # 266745 was did not generate DPZ review or fee.

**Comment by pooldaddy** [comment]
@JuanitaMiles would like to close as this was a data issue.

**Comment by JuanitaMiles** [comment]
Will monitor moving forward. If issue occurs again we will reopen.
