### ISSUE TITLE
R4C - Permit & Planning Application Submission Issues - Extreme Ticket #14547500

### ISSUE THREAD

**Issue by JuanitaMiles** [dhenry-KCI/FredCo-Post-Go-Live-#521]
A customer has had consistent issues when trying to submit her ResUse - Deck permit via the R4C portal. See the applicant's description of her issue below.
![image](https://user-images.githubusercontent.com/31770504/79248750-3def6400-7e4a-11ea-906d-077a6e56162b.png)

It appears as though the application submits successfully when the submit button is clicked for the first time but potential loading and timeout issues are causing R4C to not load correctly and makes the applicant think it wasn't submitted. As a result applicant continue to try to upload multiple times. A few more examples are visible in the Lookup Application window.
![image](https://user-images.githubusercontent.com/31770504/79249038-acccbd00-7e4a-11ea-9e21-8006f63a3eb5.png)

**Comment by JuanitaMiles** [comment]
@megisys @pooldaddy - Not sure which one of you would be better equipped to address this issue but it's causing significant duplication of permit application coming in through R4C.

**Comment by megisys** [comment]
I think we need a rest server weekly reboot. 3am on a Friday Morning. See if this helps

**Comment by Ycoto** [comment]
We try recreating this on the Test server and we were not able to recreate this problem.

**Comment by JuanitaMiles** [comment]
Tracking Ashlye's duplicated permit emails here:

![image](https://user-images.githubusercontent.com/31770504/81325756-d30b0480-9066-11ea-84f0-6a5dd3fb8066.png)
![image](https://user-images.githubusercontent.com/31770504/81325665-b40c7280-9066-11ea-95cd-b45af1e3c436.png)

**Comment by JuanitaMiles** [comment]
![image](https://user-images.githubusercontent.com/31770504/81326046-3137e780-9067-11ea-90e4-e1e0aab90dde.png)

**Comment by JuanitaMiles** [comment]
![image](https://user-images.githubusercontent.com/31770504/81326234-883dbc80-9067-11ea-95ab-c3c077050ece.png)
![image](https://user-images.githubusercontent.com/31770504/81326137-5f1d2c00-9067-11ea-8ff9-af182e344602.png)

**Comment by JuanitaMiles** [comment]
![image](https://user-images.githubusercontent.com/31770504/81326558-069a5e80-9068-11ea-987f-6f0359a48f17.png)
![image](https://user-images.githubusercontent.com/31770504/81326509-f2566180-9067-11ea-9566-eece1175876f.png)

**Comment by JuanitaMiles** [comment]
![image](https://user-images.githubusercontent.com/31770504/81326755-43665580-9068-11ea-8cb8-e9395b905e1e.png)

**Comment by ABonomo21** [comment]
@pooldaddy - Jeff can you provide me with an update about this ticket it is a large issue.

**Comment by JuanitaMiles** [comment]
Another instance where the system was spinning and impacted attachments.

![image](https://user-images.githubusercontent.com/31770504/81413669-d0b2b400-9113-11ea-85e2-592778aab3ae.png)

**Comment by ABonomo21** [comment]
more duplicate permits- 279476 & 279484
279515&279516, 279517&279518

What is the status of this problem with R4C spinning?? This ticket was created a month ago @pooldaddy

**Comment by Ycoto** [comment]
@JuanitaMiles Infor ticket# 14547500

**Comment by ABonomo21** [comment]
more duplicates... 
![image](https://user-images.githubusercontent.com/47611580/82245159-733b1600-9910-11ea-9189-ae628b57b879.png)

**Comment by JuanitaMiles** [comment]
Email from Megan regarding a customer reporting a duplicate permit application.

![image](https://user-images.githubusercontent.com/31770504/82250627-cf566800-9919-11ea-9f70-93e08dc9db21.png)

**Comment by pooldaddy** [comment]
@juanita Not us

**Comment by JuanitaMiles** [comment]
assigning Dan as he is the one leading the efforts and updates on this.

**Comment by JuanitaMiles** [comment]
Update from Dan 5/29:

Aiming for a special June release to address this issue.

**Comment by AReed327** [comment]
I am getting a lot of duplicates today. 
![image](https://user-images.githubusercontent.com/58854333/83534469-dacf9480-a4be-11ea-9748-ee94294b8639.png)
![image](https://user-images.githubusercontent.com/58854333/83534582-08b4d900-a4bf-11ea-90a4-6ae769e59634.png)
The plat came through 8 times. PL260113, PL260114, PL260115, PL260116, PL260117, PL260118, PL260119, PL260120
The NID came through 3 times. N260121, N260122, N260123

This needs to be corrected as soon as possible.

**Comment by ABonomo21** [comment]
More duplicates for permits today 
282228
282227
282226
282225

**Comment by AReed327** [comment]
More duplicates today for planning 
SP260128
SP260129
SP260130
SP260131
SP260132
B260126

**Comment by MLWilkins** [comment]
tried to provide a screen shot of the completeness check dashboard but the bug reported in ticket 497 is preventing me from doing so.  The applications Ashley reported above (F260155-158), as well as an additional one that generated after Ashely's comment above (F260159) all came in 1 minute apart.

**Comment by MLWilkins** [comment]
Planning had 19 duplicate BOA applications this morning, B260161-B260182. Unable to take screen shot again due to dashboard bug

**Comment by MLWilkins** [comment]
more


![image](https://user-images.githubusercontent.com/50637067/84901062-f15a1c00-b078-11ea-9c68-ac1311b5f512.png)

**Comment by AReed327** [comment]
Additional duplicates today.
RZ260229
RZ260230
are both duplicates of RZ260228. None of these projects have attachments.

**Comment by MLWilkins** [comment]
18 of the same application populated on the evening of 6/26/20

![image](https://user-images.githubusercontent.com/50637067/85850289-84cad580-b77a-11ea-91dd-aed06aa09a3e.png)

**Comment by MLWilkins** [comment]
more duplicates.

![image](https://user-images.githubusercontent.com/50637067/85887921-a21d9500-b7b6-11ea-9c34-2094c2e0583c.png)

**Comment by MLWilkins** [comment]
more duplicates.

![image](https://user-images.githubusercontent.com/50637067/85997819-04a1ab80-b9d8-11ea-89c1-a962fb8e2554.png)

**Comment by megisys** [comment]
Believe Duplicates have now stopped

**Comment by AReed327** [comment]
I have not seen duplicates since contact details disabled.

**Comment by JuanitaMiles** [comment]
No additional reports of duplication have occurred since contact details functionality has been disabled. Closing ticket.
