### ISSUE TITLE
Zoning Review on Parcel in Town of New Market

### ISSUE THREAD

**Issue by ABonomo21** [dhenry-KCI/FredCo-Post-Go-Live-#523]
A zoning review generated on a grading permit located in the town of new market clearly marked on the parcel details. Grading #272952

**Comment by Ycoto** [comment]
@ABonomo21 it was generated because OccupancyType is RESSFD and this point in the code the only thing could stop it from generated is if SubDivisionCode wold StartsWith "S".

**Comment by ABonomo21** [comment]
Zoning Review should not generate on any permit when it is located in the town limits. The town reviewer additional application should add. We can discuss tomorrow. @Ycoto @JuanitaMiles

**Comment by megisys** [comment]
GRADING_DPZ_Review_AOC - Updated. Moved the Township code lower in the formula.

**Comment by ABonomo21** [comment]
tested 266871 no zoning review generated
