### ISSUE TITLE
Service Request - New sub category 

### ISSUE THREAD

**Issue by ABonomo21** [dhenry-KCI/FredCo-Post-Go-Live-#524]
Can we please have a new subcategory added under Service Request Type : Zoning - ZFEMA- Unapproved Activity within the FEMA Floodplain

![image](https://user-images.githubusercontent.com/47611580/79383387-1627fb00-7f33-11ea-9b1e-d8c9248261f3.png)

Adding Mike to the ticket to follow up if any thing is needed @MLWilkins

**Comment by MLWilkins** [comment]
FYI, floodplain is already listed as a type under zoning case details


![image](https://user-images.githubusercontent.com/50637067/79458617-0c98a480-7fc0-11ea-92b4-344fb3018e69.png)

**Comment by ABonomo21** [comment]
moved to future phases
