### ISSUE TITLE
IPS attachment date

### ISSUE THREAD

**Issue by ABonomo21** [dhenry-KCI/FredCo-Post-Go-Live-#525]
Is there a way to add the date field on the attachments to know when they were uploaded in IPS? Applicants are submitting documents via the portal and they are not following the attachment naming convention, it is not practical to send it back- it would be more useful to staff to have a date field so they know when the upload was attached.

**Comment by MLWilkins** [comment]
We would like this for Planning as well please!

**Comment by megisys** [comment]
Yes. This was pushed with Development.. Coming in Future release !! I pushed this a month ago FYI

**Comment by megisys** [comment]
I can not do anything here.. has been added as a request.

**Comment by ABonomo21** [comment]
Would it also be possible to add to this ticket or maybe we need a new one to add a field for who added the attachment, I.E applicant or staff? @megisys @JuanitaMiles

**Comment by megisys** [comment]
THis is coming

**Comment by megisys** [comment]
July 2020 - IS the projected date for this

**Comment by megisys** [comment]
@ABonomo21 - Can we close this.. Nothing we can do until newer release

**Comment by JuanitaMiles** [comment]
I've got this ticket in our "Product Enhancements" project for follow up. Will close this ticket, and it will still show for us as a follow up item in the project.
