### ISSUE TITLE
Minor Grading Permits with a Subdivision 

### ISSUE THREAD

**Issue by ABonomo21** [dhenry-KCI/FredCo-Post-Go-Live-#527]
Per the email sent on 4.13.20 - For those minor grading permits related to a SFD located within a subdivision, the applications should ultimately be reviewed and closed as they are covered under a mass grading plan. 

 Do any of you recall us setting up these applications to automatically close if they were within a subdivision? I am thinking we didn't and now that we are 4 months post go live we are starting to see the new dwellings being held up on COO because the grading permits are not closed out.

These permits would close automatically after approved reviews. 

Those located within subdivision and covered under a mass grading plan would have an S code in the subdivision code on the parcel details.

**Comment by megisys** [comment]
BP_UnderReview_NMF - te be promoted if accepted.. 

Minor Grading on an address with subdivision starting with S

**Comment by ABonomo21** [comment]
tested 266869 zoning review did not generate S1163

**Comment by ABonomo21** [comment]
tested 266870 after review went to close related to S1163
