### ISSUE TITLE
Deck Permit Inspections 

### ISSUE THREAD

**Issue by ABonomo21** [dhenry-KCI/FredCo-Post-Go-Live-#528]
Adding a github ticket per attached email with Jeff and Juanita on 4.13.20

{"Attachments":[{"__type":"ItemIdAttachment:#Exchange","ItemId":{"__type":"ItemId:#Exchange","Id":"AAMkADY4MmFlMTNiLWRhMTAtNGVlYi1hN2M3LTIzOGRhNDQzZTM2OABGAAAAAADtok+iNkSOR7FHlbRiA1CGBwA6ZJyWpgFeSL3151bz0sZdACkZun5UAAD9Sa20WXy5S6sqxCDewopUAAN+RrMeAAA=","ChangeKey":null},"Name":"Inspections ","IsInline":false}]}

Ashlye,
Ok to add Github for tracking.
Unfortunately, per our support contract with Infor, NO updates to PROUCTION data via scripts are allowed.
 
 
Jeff Wisner
Staff Software Integrator
Frederick County Government, IIT
301-600-1811

Bonomo, Ashlye
Mon 4/13, 3:40 PM
Yes only those that are not complete... i was hoping the script could clean them up at least for item # 1 because that is the problem now inspectors are doing each one manually. We want to be more efficient. Time frame the sooner the better but it is not a
Wisner, Jeff (IIT)
Mon 4/13, 3:32 PM
Yes. I assume only those where status is NOT Compete.
 
For item 1 – the waives would have to entered individually, unless we get Infor to script it.
For Item 2- this can be done.
How soon do you need this?
 
 
Jeff Wisner
Staff Software Integrator
Frederick County Government, IIT
301-600-1811

Bonomo, Ashlye
Mon 4/13, 3:26 PM
FYI - Working on trying to get this done. Ash
Bonomo, Ashlye
Wisner, Jeff (IIT);Miles, Juanita
You forwarded this message on 4/13/2020 3:26 PM
Hey Jeff - 
 
**I was wondering if you could run a script that would pull all RESUSE permits with a work type of ADDITION and a construction type (on the residential use details page of )
DECK>500 and DECK500. 
 
From there - we would like to do a couple of things. 
 
Waive all inspection types of  BLDG-BACK (backfill) and BLDG-FOUND (foundation). 
Possibly change the code to make those inspection types not generate on this combination of app, work and construction types... 
 
I know # 2 will be a part of the inspection matrix so we can hold off on that one but at least would like to accomplish # 1...** 
 
Let me know.
 
Thanks, 

Ashlye

**Comment by ABonomo21** [comment]
Ask Dan for time to complete

*I was wondering if you could run a script that would pull all RESUSE permits with a work type of ADDITION and a construction type (on the residential use details page of )
DECK>500 and DECK500.

From there - we would like to do a couple of things.

Waive all inspection types of BLDG-BACK (backfill) and BLDG-FOUND (foundation).
Possibly change the code to make those inspection types not generate on this combination of app, work and construction types...

**Comment by megisys** [comment]
See Batch Job OneTimeCleanUP- DeckPermits - Run in Test.. Let me know

**Comment by ABonomo21** [comment]
permit 265136 waived back fill ips system but did not waive foundation

same with 265022

![image](https://user-images.githubusercontent.com/47611580/81334921-c1c8f480-9074-11ea-8ca7-b99f0976cbbf.png)

**Comment by megisys** [comment]
Fixed
