### ISSUE TITLE
Tank Permit - Parent Child Condition 

### ISSUE THREAD

**Issue by ABonomo21** [dhenry-KCI/FredCo-Post-Go-Live-#529]
This plumbing permit has a Tank attached as the Parent but it is still asking for a building permit to be associated.

Permit# 270184 for Plumbing

Permit# 270182 for Tank

![image](https://user-images.githubusercontent.com/47611580/79626079-605bd880-80fb-11ea-9fdf-80a1b66db9d4.png)
![image](https://user-images.githubusercontent.com/47611580/79626080-6487f600-80fb-11ea-80d4-b5fcf3375aec.png)

**Comment by megisys** [comment]
PLUMBPERM_ParentBldAP_SCF - Updated - Was missing the S from Tanks. I am doing this to move as much as possible tomorrow night. Will be meeting with Jeff at 1pm today and we will review

**Comment by ABonomo21** [comment]
tested 266868 added a tank permit as parent worked correctly
