### ISSUE TITLE
townhouses not issuing with parent 

### ISSUE THREAD

**Issue by ABonomo21** [dhenry-KCI/FredCo-Post-Go-Live-#53]
204874 to 204877. The parent 204874 issued but the other houses in the row did not

the children were still held up stating pending parent to be issued but the parent was issued.

**Comment by ScottVanSooy** [comment]
Formula is RESBLDG_ParentAptCondoPermitIssued_SCF
This snippet of code if keeping it from progressing

If NOT parent.ParentApplication.PermitIssuedDateTime.Year = 1 Then
  StateCheck = False
End If

The Parent Application is not Issued,  so the Year does =1 and StateCheck = False is never set.  I'll need clarification on what needs to happen here;

**Comment by ScottVanSooy** [comment]
Sorry, that was in test, I need to review in Prod too.  Stay tuned.

**Comment by ScottVanSooy** [comment]
I'm just not seeing the same thing Ashlye.  Maybe we can Webex on Monday.

Scott

**Comment by ABonomo21** [comment]
try to duplicate in test

**Comment by ABonomo21** [comment]
duplicate ticket number 146 created !
