### ISSUE TITLE
Report for CIP/Municipal Fees Waived 

### ISSUE THREAD

**Issue by ABonomo21** [dhenry-KCI/FredCo-Post-Go-Live-#530]
Planning and permits would like to have a report created that will provide a list of CIP and Municipal applications for which fees were waived. 

we developed the system for the purpose that if asked by the CE’s office, we would have a way to determine the total fees waived for CIP’s/Municipalities. I believe this should probably be configured by the check box selection on the details page in combination with waived fees. A combination of both fields would be needed to get the desired results for CIP/Municipality projects. 
 
Perhaps we need a quick meeting with AR and AB, and Jeff to review total scope of what the report should cover.

**Comment by JuanitaMiles** [comment]
may want to look into using this as a training opportunity for new IIT staff. will follow up with Tara.

**Comment by JuanitaMiles** [comment]
Spoke with Jeff and Yaciel today (5/20) regarding this report. They said they were going to begin working on it, gathering additional requirements with Ash R & B and Tara's assistance may not be needed. Will initially assign to IIT only.

**Comment by JuanitaMiles** [comment]
Assigning to Tara for completion.

**Comment by JuanitaMiles** [comment]
Had meeting on 6/26 to kickoff requirements gathering with Tara, Ash R, Ash B, Dustin and Yaciel. Tara will mock up a version of the report for Ashlies to review and provide additional feedback.

Ticket will carry into next phase of the project.

**Comment by ABonomo21** [comment]
moved
