### ISSUE TITLE
PLANNING - SHA didn't add on SITE PLAN TYPE II

### ISSUE THREAD

**Issue by AReed327** [dhenry-KCI/FredCo-Post-Go-Live-#532]
Project Number - SP259997
Observed behavior - SHA didn't add automatically. Parcel reflects State Road, but I had to add manually.
Expected behavior - SHA should add automatically with Parcel Details Road - S
Screenshot -
![image](https://user-images.githubusercontent.com/58854333/79895154-735cfa00-83d4-11ea-930f-68ee8292b9d6.png)

![image](https://user-images.githubusercontent.com/58854333/79895047-4a3c6980-83d4-11ea-9e9c-68829958b1ec.png)

**Comment by megisys** [comment]
HI There,

The Matrix said no SHA on Type2 or Type3 or ADMCON and these would be added manually..

PLease let me know the change you would like to the above.. I removed TYPE2 for testing if this is what you are after

PLN_SITE_SHA_AOC - To be promoted
