### ISSUE TITLE
PLANNING - NID - completeness check resulted NFC and application didn't close.

### ISSUE THREAD

**Issue by AReed327** [dhenry-KCI/FredCo-Post-Go-Live-#533]
Project Number - N260016
Observed behavior - Resulted completeness check as NFC because it was a duplicate. Project didn't close the way NFC was designed. It progressed to under review.
Expected behavior - NFC to close application the same as it does other applications. 
Screenshot -
![image](https://user-images.githubusercontent.com/58854333/79990456-1407f400-847f-11ea-931d-c77658a10314.png)

**Comment by AReed327** [comment]
This application did have a withdraw request on it. I don't think that would make a difference. Just an observation.

**Comment by megisys** [comment]
This will be a gap in formula. Are you sure you dont want me to take this one ? @JuanitaMiles

**Comment by megisys** [comment]
PLN_NIDVERIFY_NSF - Move once tested

**Comment by AReed327** [comment]
N258968 Completeness Check resulted as NFC and the application moved to closed. 
![image](https://user-images.githubusercontent.com/58854333/81102224-526ccc80-8edd-11ea-93fc-bc587f06d8b4.png)
N258969 ![image](https://user-images.githubusercontent.com/58854333/81102363-89db7900-8edd-11ea-8360-8c82a6ddd496.png)

Test Accepted
