### ISSUE TITLE
P&I HOLDs

### ISSUE THREAD

**Issue by ABonomo21** [dhenry-KCI/FredCo-Post-Go-Live-#534]
P&I HOLDS on permits should stop the progression of permits within the system, i.e. requesting, scheduling and resulting inspections. We had a plumbing permit 268637 which i added a hold on the permit on 4.17.20 and it allowed an inspection to be scheduled on 4.20.20. 

Can we please make sure the condition is stopping all inspection action on permits-

**Comment by megisys** [comment]
I will have to built this in test.. I dont think we ever tested this out.. Do you have any history on this in the past please. @JuanitaMiles @ABonomo21 . Is this net new and we Thought we tested this ?

**Comment by JuanitaMiles** [comment]
I think Dan is correct, and the portion of the requesting/scheduling was not incorporated into the rules for holds. I believe we had the more generic rules that say the permit can't progress to the next milestone if there is a P&I hold. I'm looking specifically back at current repository ticket #485 and old github repository ticket # 318 for some history.

**Comment by ABonomo21** [comment]
I recall having this discussion while Ibti was still on the project and could have sworn we tested the P&I holds to make sure they stopped progression prior to the fix Dan made to generate the condition portion. 

Perhaps there is some confusion or misinterpretation because in H7 when this was a condition it would stop the stage progression of a permit, if it was in the inspections status it would prevent any action from being taking on those inspections because that is considered "progression" on the permit....

With that said, what needs to be corrected is that if a P&I hold is placed on a permit it should prevent the progression of the permit from one milestone to the next until such time the hold condition is satisfied. If it is in the **inspection or final inspection milestone** it should NOT ALLOW inspections to be requested, scheduled or resulted until the condition is satisfied

A U&O hold is different in the regard that the only thing it prevents is the issuance of a COO or COC. Therefore, as you can see on the previous ticket, this hold condition should only require the condition be stopped once in the pending certificate milestone but it can be added at ANY milestone of the project. 

Hopefully this helps clear things up.

**Comment by megisys** [comment]
BP_ManageInspection_BUF - Move once tested

**Comment by ABonomo21** [comment]
This did not work - Tested tank permit 264562 added p&i hold- and was able to request and schedule an inspection with a P&I hold

Was able to request and inspection for 266679 but was not able to schedule.

**Comment by ABonomo21** [comment]
This should work for all a/ps please

**Comment by megisys** [comment]
Sorry.., This has been adjusted

**Comment by ABonomo21** [comment]
re-test worked -
 
![image](https://user-images.githubusercontent.com/47611580/81334343-ebcde700-9073-11ea-8902-2dc430507612.png)
