### ISSUE TITLE
R4C - Allowing Double Payment of Fees

### ISSUE THREAD

**Issue by JuanitaMiles** [dhenry-KCI/FredCo-Post-Go-Live-#535]
Dan Lewis (treasury) has reported a couple of occasions where applicants have been able to make duplicate payments on R4C. I have included Emily and Dan's description of the problem below. It appears there may be a timing issue as one applicant paid 1 minute after the other and the system accepted both payments. A payment of the same fee by two different applicants should not be able to occur.

There are two examples of this occurring in the emails below.
![image](https://user-images.githubusercontent.com/31770504/79995219-f5a4f700-8484-11ea-8948-d22db53a9855.png)

**Comment by megisys** [comment]
![image](https://user-images.githubusercontent.com/47392306/80011938-8e923d00-849a-11ea-8c05-aafabd342d6e.png)
Cashiering setup allowed overpayment

**Comment by megisys** [comment]
Turned off now in Production

**Comment by emilypearl1** [comment]
Will monitor. Satisfied at this time with the change Dan has made in production... will monitor and advise if this is again an issue
