### ISSUE TITLE
Patch Updates - Summary Page Site Widget (GIS)

### ISSUE THREAD

**Issue by JuanitaMiles** [dhenry-KCI/FredCo-Post-Go-Live-#536]
Comments from Mike Wilkins and Ashlye Bonomo regarding the Site Widget on the application summary page:

**Ashlye B 4/19/20:**
![image](https://user-images.githubusercontent.com/31770504/80003822-91d3fb80-848f-11ea-8fb5-6d923a2fa9b3.png)

**Mike W 4/20/20 (also includes comments from Dan/Rick M in response):**
![image](https://user-images.githubusercontent.com/31770504/80003659-5802f500-848f-11ea-83a2-7fe329f3dd98.png)

![image](https://user-images.githubusercontent.com/31770504/80003606-43266180-848f-11ea-86b1-7ec2a42288a0.png)

**Comment by megisys** [comment]
Awaiting Meeting with Austin and Rick on Monday

**Comment by megisys** [comment]
Aiming to be complete this week

**Comment by megisys** [comment]
Added in all GIS Available layers - Couple provided by GIS are not available to use via IPS. But Test has a number of new layers Production currently doesnt have

**Comment by MLWilkins** [comment]
Planning comments have been addressed. I am marking test accepted but also tagging @ABonomo21  as she had two question/comments in this ticket as well.

**Comment by ABonomo21** [comment]
good to go.
