### ISSUE TITLE
Patch Updates - Summary Page Application Header Updates

### ISSUE THREAD

**Issue by JuanitaMiles** [dhenry-KCI/FredCo-Post-Go-Live-#537]
Comments from Ashlye Bonomo and Mike Wilkins regarding the summary page application header configuration.

**Ashlye B 4/19/20:**
![image](https://user-images.githubusercontent.com/31770504/80004516-6bfb2680-8490-11ea-847b-f4ac9e7f34c0.png)

**Mike W 4/20/20 (also includes comments from Dan in response):**
![image](https://user-images.githubusercontent.com/31770504/80004605-86cd9b00-8490-11ea-80ca-614d93acbd4b.png)

![image](https://user-images.githubusercontent.com/31770504/80004701-a795f080-8490-11ea-8201-8cb3f45797fe.png)

**Comment by AReed327** [comment]
# 4 is not an issue. 
#3 Main issue is customization on all Planning Application types. See screenshots below. Highlighted is what is in production and missing in test.

PRODUCTION 
![image](https://user-images.githubusercontent.com/58854333/80012561-7ec72880-849b-11ea-89c0-3cb6d6cd0ff9.png)

**Comment by megisys** [comment]
Added Back.. Status is no Longer available as by default ti orginially didn't have milestone, but they added that in this release and removed status

**Comment by AReed327** [comment]
SDAT button is only showing half and when you click on it, it doesn't work.
![image](https://user-images.githubusercontent.com/58854333/80402577-15c12580-888c-11ea-8b2c-bed7b2647663.png)


VERIFY - Needs: This application is an internal/eplan review line based on completeness check result. I know this application is always internal but summary screen should be consistent. (It was updated on NID which is also always internal)
![image](https://user-images.githubusercontent.com/58854333/80404424-29ba5680-888f-11ea-8729-dadea89e20bb.png)

**Comment by megisys** [comment]
PLN_ProjectDoxCheck - To be Promoted
