### ISSUE TITLE
Non-Residential Re-Application 50%

### ISSUE THREAD

**Issue by mlibbey131** [dhenry-KCI/FredCo-Post-Go-Live-#538]
When submitting a Non-Res Re-Application 50% a Status Check comes up to add the Building Fee. However even when you add the Building fee the permit doesn't progress. You have to Supervisor Override the permit to get it to add the rest of the fees and move forward. 
There should be a log or a condition to progress the permit forward. Permit# 274351 old GitHub issue number is 1880

![image](https://user-images.githubusercontent.com/58980189/80022847-a40f6300-84aa-11ea-857f-deee836d290c.png)

![image](https://user-images.githubusercontent.com/58980189/80022817-9a85fb00-84aa-11ea-8bad-50bae0058d01.png)

**Comment by megisys** [comment]
BP_REAP50_BuildingFee_SCF - to be Promoted

**Comment by ABonomo21** [comment]
tested 266866 and the permit progressed to fees after the building fee was manually added. worked correctly
