### ISSUE TITLE
Milestone Progression for Building Permit

### ISSUE THREAD

**Issue by ABonomo21** [dhenry-KCI/FredCo-Post-Go-Live-#539]
I have seen a few permits that are not appearing to progress milestone accurately, I have been assuming it was because of a batch manager issue however, I finally inquired to IIT about permit 275451 that is stuck in awaiting applicant payment- all fees have been paid. i know if i click check status it will roll to the issued and inspections milestone but I have left it for Dan to take a look per Email with Jeff W. 

Today, 4:08 PM
Ashlye,
 
Two things…
 
1.       Milestone progression is not part of batch Manager.
2.       I looked at configuration and see nothing preventing progression, this should have occurred immediately after final fee paid.
 
I think you can status check to progress if applicant is waiting or leave for Dan to look at in it’s current state.
Either way you should probably create a Github ticket for Dan.
 
Jeff Wisner
Staff Software Integrator
Frederick County Government, IIT
301-600-1811

Bonomo, Ashlye
Wisner, Jeff (IIT);Miles, Juanita
Please look at permit 275451- did not progress to issued and everything is completed. If I hit check status it will roll, I have not done this yet because I wanted you to see the issues.
 
Should have rolled with the batch manager…
 
Ash

**Comment by ABonomo21** [comment]
Another permit - 268442 I had to check the status on to make it move from awaiting applicant revisions to under review when the Pdox resubmission task was already accepted and new reviews assigned.

**Comment by ABonomo21** [comment]
here is another example of a fire permit that was suck in awaiting applicant revisions even though they submitted through project dox - 274239

![image](https://user-images.githubusercontent.com/47611580/80995810-dc993000-8e0c-11ea-8ca5-9376a1cd3021.png)

**Comment by megisys** [comment]
New Batch JOb - Progress Building Permits - Runs every two hours for any application in an Awaiting Milestone to check if it should move.

Dan

**Comment by ABonomo21** [comment]
275636 did not change milestones even with checking status

**Comment by ABonomo21** [comment]
stuck to awaiting applicant revisions- new review generate in pdox - did not ever change milestone.

**Comment by JuanitaMiles** [comment]
Progress Building Permits batch has not run since 5/4. Potentially why this permit did not get progressed forward and needed to be manually done.

![image](https://user-images.githubusercontent.com/31770504/81571448-f63bf980-936f-11ea-8332-a86dbf226f57.png)

**Comment by ABonomo21** [comment]
Another example of a permit that did not change milestones as it should have is permit 266492- resubmit received in pdox permit stayed in awaiting applicant revisions 
![image](https://user-images.githubusercontent.com/47611580/81998639-0a5a5200-9621-11ea-92f8-d6db1438f72b.png)
![image](https://user-images.githubusercontent.com/47611580/81998657-13e3ba00-9621-11ea-8749-8b96b68f6b59.png)

had to check status on the permit to move to under review. @JuanitaMiles @megisys @pooldaddy

**Comment by megisys** [comment]
Hi All, The Batch Job was not running.. Fixed Schedule in Prodcution

**Comment by ABonomo21** [comment]
I have had a permit stuck in pending issuance 275630 since 5.11.20 - This needs to work for all permits in each milestone - this permit did not progress until I checked the status. @JuanitaMiles

**Comment by megisys** [comment]
OK This one is different, AS it was pending Issuance, and I guess it was waiting on a child permit. Can you tell me why it was sitting in pending issuance, so i can address that issue.

Dan

**Comment by megisys** [comment]
@JuanitaMiles @ABonomo21

**Comment by pooldaddy** [comment]
@megisys @coto @JuanitaMiles The formula only progress ap's that begin with 'AWAITING'

**Comment by ABonomo21** [comment]
Here are townhouse permits that are not progressing on their own either... they had to be check status 
269050
--
269052
269056
269060
269067

**Comment by megisys** [comment]
Updated formula - Move to Production due to Urgency and ran !

Milestones.Add("Pending Issuance")
Milestones.Add("Pre-Issue COO")
Milestones.Add("Awaiting More Information")
Milestones.Add("Awaiting Applicant Resubmit")
Milestones.Add("Awaiting Applicant Revisions")
Milestones.Add("Awaiting Applicant Payment")

**Comment by megisys** [comment]
Moved 27 More building permits on

**Comment by ABonomo21** [comment]
will monitor - as of now there are no issue
@pooldaddy - Jeff please make sure you are checking this daily.
