### ISSUE TITLE
PLANNING - PWCONSTRUC - Worktype SWMDEVPLN - fee error

### ISSUE THREAD

**Issue by AReed327** [dhenry-KCI/FredCo-Post-Go-Live-#54]
$148 fee populated in error with data migration on PWCONSTRUC - SWMDEVPLN.  Please remove fee from this worktype as it is not a fee for this plan type. 

![image](https://user-images.githubusercontent.com/58854333/71098765-395abd80-2180-11ea-9c55-6b09603f1f87.png)

**Comment by megisys** [comment]
But it is right above it as Paid ?? It is the same fee.

**Comment by AReed327** [comment]
The $403 is correct. The 148 is incorrect. I don't know why the fees are the same description.

**Comment by AReed327** [comment]
I guess this is one of those fees with all the ifs, ands, and buts. This per sheet fee should be 403 not 148.

**Comment by calequin** [comment]
the fee per sheet for SMMDEVPLN defaults to "Other" in the fee rate table.

**Comment by MLWilkins** [comment]
created a new SWMDEVPLN application in test.  No fee error.  May be a problem with just in life projects?

**Comment by calequin** [comment]
Yes. I have also sent a request to our data migration team to get the fee code corrected from v7. This should fix the issue of the duplicate fee populating

**Comment by AReed327** [comment]
A/P 20084 - When final review was resulted the 148 fee populated again. At the time, the worktype was NEW. PLease update so that 148 does not populate under worktype NEW.

![image](https://user-images.githubusercontent.com/58854333/71528392-8f7cde80-28ad-11ea-9302-0327119181ce.png)

**Comment by calequin** [comment]
please promote PLN_PWCONSTRUC_EngrPerSheetFee_AOC

**Comment by ScottVanSooy** [comment]
Promoted 2020-01-05

**Comment by MLWilkins** [comment]
tough one to retest since this fee seemed to pop up randomly.  Will close ticket and monitor.
