### ISSUE TITLE
R4C - General Database Error - Applying for Home Occupation Permit

### ISSUE THREAD

**Issue by JuanitaMiles** [dhenry-KCI/FredCo-Post-Go-Live-#540]
See attachment for the lengthy "General Database Error" message received by an applicant when trying to apply for a Home Occupation permit on R4C.

[Error-General Database Error.pdf](https://github.com/dhenry-KCI/FredCo-Post-Go-Live-/files/4566001/Error-General.Database.Error.pdf)

I've double checked the IPS system for the Project Name recorded in the attachment and confirmed that it did not officially submit the record, so it does not appear to be related to the duplication issue we've been having in R4C for building permits.

**Comment by megisys** [comment]
Something is too long for the field length. Working on this now

**Comment by megisys** [comment]
Regeneration of Detail Page in Production. Fixed

**Comment by JuanitaMiles** [comment]
Reopening. Applicant is still reporting problems trying to submit. @megisys Dan if you make a change in production, please do not close the ticket until the County can confirm the applicant can successfully submit. Just assign back to myself and Ashlye and we will close if confirmed. Thanks.

**Comment by JuanitaMiles** [comment]
I am also having Abbie/Ashlye follow up with the customer to see if we can get any confirmation that it is the same error occuring.

**Comment by megisys** [comment]
@JuanitaMiles - Can you also ask for the data they are trying to add to the row. Something is too long

**Comment by JuanitaMiles** [comment]
Abbie has tried to follow up but has not received a reply. Assigning Abbie so she can provide information once received.

**Comment by megisys** [comment]
Change made in TEST - Extended what is being sold from 30 characters to 70.

**Comment by ABonomo21** [comment]
![image](https://user-images.githubusercontent.com/47611580/85044355-7e75a180-b15b-11ea-9ba9-b5b763311b02.png)
