### ISSUE TITLE
Health Review on Building Permit 

### ISSUE THREAD

**Issue by ABonomo21** [dhenry-KCI/FredCo-Post-Go-Live-#541]
We had a health review generate on a building permit when health had already approved their review. A second review was added manual for DPZ at the revision assignment because they were the only agency asking for a resubmit. when it moved back to under review the health  review automatically spawned. 

All reviews should be manually added at revision assignment and not additional review should spawn when it goes back to under review. 

![image](https://user-images.githubusercontent.com/47611580/81028539-e3956200-8e4f-11ea-93ae-b7d400e097a6.png)

**Comment by megisys** [comment]
RESUSES_EH_Review_AOC - To be promoted

**Comment by ABonomo21** [comment]
tested 266865 approved - error did not occur
