### ISSUE TITLE
PLANNING - PROJECT won't transfer to PDOX - ERROR

### ISSUE THREAD

**Issue by AReed327** [dhenry-KCI/FredCo-Post-Go-Live-#542]
Project Number - SP260017
Observed behavior - Project won't transfer to PDOX - gives error code
Expected behavior - Project should go to PDOX with no error when completeness check resulted EPLANS
Screenshot -
Original Error 4/22/2020
![image](https://user-images.githubusercontent.com/58854333/81106168-1b011e80-8ee3-11ea-96a8-75972bf0775a.png)
Manual Push (PDOX LOG) error 5/5/2020
![image](https://user-images.githubusercontent.com/58854333/81106249-41bf5500-8ee3-11ea-81ff-62fd017dfc12.png)
Could it be the / in the Name?
![image](https://user-images.githubusercontent.com/58854333/81106280-4edc4400-8ee3-11ea-970e-892b57c3ff52.png)

**Comment by megisys** [comment]
There name was just too long - I split over the two name fields

**Comment by AReed327** [comment]
So, is this corrected for future projects? Do we need to adjust the character limit of existing accounts and future accounts on R4C for the contact record? @megisys

**Comment by megisys** [comment]
Hopefully it isnt a recurring issue. Is a very long name. We can handle this later if it happens again
