### ISSUE TITLE
Planning - Dashboard not showing unassigned FRO review

### ISSUE THREAD

**Issue by AReed327** [dhenry-KCI/FredCo-Post-Go-Live-#543]
FRO Review is not assigned and it is not showing on the assign reviewers dashboard. I've started assigning the completeness check review at the time it is completed so our reports will show accurate info. FRO should still show unassigned once that review populates after fees are paid for an internal review.

![image](https://user-images.githubusercontent.com/58854333/81180265-c6a87e00-8f78-11ea-8661-c155ed92f7a4.png)

![image](https://user-images.githubusercontent.com/58854333/81180335-df189880-8f78-11ea-9eca-29e620fbfc0e.png)

**Comment by JuanitaMiles** [comment]
Spoke with @AReed327 , we are going to create a version of the report that shows the pdox projects as well and see how it goes. Closing ticket for now and will work through this with Ashley.
