### ISSUE TITLE
PLANNING - FRO Miscellaneous condition holding application from completeness check resubmit loop

### ISSUE THREAD

**Issue by AReed327** [dhenry-KCI/FredCo-Post-Go-Live-#544]
Project Number - F260037
Observed behavior - Resubmit requested on Completeness Check. Application didn't progress because of miscellaneous condition that project "Needs a previously approved/submitted FRO application"
Expected behavior - This condition cannot hold up completeness check loop because it is that previous application that I am requesting a resubmit for. 
Screenshot -
![image](https://user-images.githubusercontent.com/58854333/81186820-45a1b480-8f81-11ea-8bb1-99da54cc5e7d.png)
![image](https://user-images.githubusercontent.com/58854333/81186885-57835780-8f81-11ea-838d-80c1ea97f085.png)
![image](https://user-images.githubusercontent.com/58854333/81186933-65d17380-8f81-11ea-8eac-bf8c4ab70a0d.png)

**Comment by megisys** [comment]
PLN_FRO_FROParentReq_SCF - To be promoted once tested

**Comment by AReed327** [comment]
F258972 Completeness check still being held up by condition. Condition should not hold up a resubmit request on completeness check being returned to the applicant.

![image](https://user-images.githubusercontent.com/58854333/81296200-89f38a00-903f-11ea-8508-31a361db2147.png)
![image](https://user-images.githubusercontent.com/58854333/81296291-aabbdf80-903f-11ea-985c-476226000868.png)

**Comment by megisys** [comment]
I really sorry.. Loook like I forgot to hit save !!

**Comment by JuanitaMiles** [comment]
Doing a test for Ashley. Running through it in IPS only. Did not use R4C. Flow looks good. Started with the status check, resulted review with resubmit, application progressed to awaiting applicant resubmit, completed applicant actions detail page, then progressed back to Intake review and the status check appeared again as expected.

![image](https://user-images.githubusercontent.com/31770504/81339200-c6dd7200-907b-11ea-8d2e-be50eec74fdf.png)
![image](https://user-images.githubusercontent.com/31770504/81339315-f4c2b680-907b-11ea-809e-8a84a5d8c814.png)
