### ISSUE TITLE
R4C - Update "Reset Password" Support Number

### ISSUE THREAD

**Issue by JuanitaMiles** [dhenry-KCI/FredCo-Post-Go-Live-#545]
The window that tells users their password has been reset shows a generic phone number. This needs to be changed to the County's support number.

![image](https://user-images.githubusercontent.com/31770504/81212174-7e05ba80-8fa2-11ea-8656-74e2e4566beb.png)

**Comment by pooldaddy** [comment]
@JuanitaMiles Done in PROD & TEST
![image](https://user-images.githubusercontent.com/47391482/81310005-91239380-9051-11ea-8088-69900bed05e3.png)

**Comment by JuanitaMiles** [comment]
@pooldaddy Confirmed in Prod that the phone number has changed. However, the address at the bottom of this page has somehow reverted back to the generic address of "Mainstreet Anytown, ZZ"

Can we get this updated back to what it was please? (30 N. Market St. Frederick, MD 21701)

![image](https://user-images.githubusercontent.com/31770504/81313846-6425af80-9056-11ea-92ab-42772b698a57.png)

**Comment by pooldaddy** [comment]
@JuanitaMiles should be good now.

**Comment by JuanitaMiles** [comment]
Confirmed in Prod

![image](https://user-images.githubusercontent.com/31770504/81324383-e2894e00-9064-11ea-8dab-df8444f7f77f.png)
