### ISSUE TITLE
Please Promote Plannning/Use/Building Recalc Fees to PROD Tonight

### ISSUE THREAD

**Issue by pooldaddy** [dhenry-KCI/FredCo-Post-Go-Live-#547]
@JuanitaMiles  @megisys 
BATCH_RecalcFees_Planning
Batch_UseRecalc

And the one for Building is

BATCH_RecalcFees

Should probably should have a more meaningful name

**Comment by Ycoto** [comment]
@JuanitaMiles @megisys

Batch_CodeReCalFees
Batch_LincReCalFees
Batch_TraLicReCalFees
