### ISSUE TITLE
When uploading multiple attachments from R4C to IPS not all files upload EXTREME # 14563132

### ISSUE THREAD

**Issue by pooldaddy** [dhenry-KCI/FredCo-Post-Go-Live-#550]
@JuanitaMiles 
Here is a list of permits from Maddison that failed to upload an attachment, well the system was spinning and did not appear to be uploaded.  

LOT 740, #278055 – BUILDING PLANS
LOT 741, #278057- BUILDING PLANS
LOT 742, #278056- BUILDING PLANS
LOT 743, #278059- PLANS, SITE PLAN & BLANKET
LOT 744, #278060- PLANS, SITE PLAN & BLANKET

===========================================================

We open an Infor ticket for this uploading problem.
Infor ticket # 14563132

**Comment by megisys** [comment]
@pooldaddy  - Can you add you xtreme ticket numbers to the header, that way i can explore where they are.

**Comment by pooldaddy** [comment]
@megisys added ticket # to header

**Comment by JuanitaMiles** [comment]
Adding another instance of an attachment issue being reported by a customer. The attachments section is missing completely from permit details view. Will forward the full email chain that contains the screenshots provided by the applicant to County IIT for inclusion on Extreme ticket. 

![image](https://user-images.githubusercontent.com/31770504/82234269-2ef34a00-98ff-11ea-8c32-08a2df5182f5.png)

**Comment by JuanitaMiles** [comment]
Three additional examples of attachments not showing.

![image](https://user-images.githubusercontent.com/31770504/82244582-71248780-990f-11ea-8e4d-eb216231284c.png)

![image](https://user-images.githubusercontent.com/31770504/82244635-8d282900-990f-11ea-8479-dc30c99a0666.png)

![image](https://user-images.githubusercontent.com/31770504/82244695-a4671680-990f-11ea-99a9-cfef17b36869.png)

**Comment by JuanitaMiles** [comment]
assigning Dan as he is the one leading the efforts and updates on this.

**Comment by JuanitaMiles** [comment]
Update from Dan 5/29:

Aiming for a special June release to address this issue.
