### ISSUE TITLE
IPS Summary Page Site Widget - Not Functioning

### ISSUE THREAD

**Issue by JuanitaMiles** [dhenry-KCI/FredCo-Post-Go-Live-#551]
Site Widget is not on the summary page is not functioning for any modules.

This was initially a problem for Planning staff this morning but has since become a problem for Ashlye and Juanita this afternoon as well (noticed around 1pm).

Screenshots from Juanita's IPS
![image](https://user-images.githubusercontent.com/31770504/81432076-4298f680-9130-11ea-865b-e8a58607c7dc.png)
![image](https://user-images.githubusercontent.com/31770504/81432098-4c225e80-9130-11ea-9726-90c2e39ee928.png)
![image](https://user-images.githubusercontent.com/31770504/81432132-5fcdc500-9130-11ea-9e72-aeb246be7ba0.png)

**Comment by pooldaddy** [comment]
@JuanitaMiles @ABonomo21 Rick Monterio is looking into this issue for us. Awaiting response

**Comment by megisys** [comment]
This issue is a Browser Cache issue

**Comment by Ycoto** [comment]
@JuanitaMiles @ABonomo21 @AReed327 @MLWilkins 
We discover that this was a Browser Cache issue and we made some simple guidelines to help you clear the Cache.

[Clearing browser cache procedure internet explorer.pdf](https://github.com/dhenry-KCI/FredCo-Post-Go-Live-/files/4611021/Clearing.browser.cache.procedure.internet.explorer.pdf)
[Clear Browsing Data procedure Chrome.pdf](https://github.com/dhenry-KCI/FredCo-Post-Go-Live-/files/4611022/Clear.Browsing.Data.procedure.Chrome.pdf)

**Comment by JuanitaMiles** [comment]
@AReed327 @MLWilkins @ABonomo21 Please try this out with Production, if all appears fixed, we can close.

**Comment by MLWilkins** [comment]
works for me using Chrome after clearing cache

![image](https://user-images.githubusercontent.com/50637067/81598248-00bcba00-9395-11ea-8f8c-c2cc8e49eebf.png)

**Comment by JuanitaMiles** [comment]
Works for me as well. Closing Ticket.

![image](https://user-images.githubusercontent.com/31770504/81704094-70858000-943b-11ea-9e2f-ef44fc4a5028.png)
