### ISSUE TITLE
Placard/Official Issuance not auto attaching to permit

### ISSUE THREAD

**Issue by awhite806** [dhenry-KCI/FredCo-Post-Go-Live-#554]
on almost every permit that has issued since the new update, the placard and official issuance of the permit are not auto attaching. We are having to manually add them to every permit. These screenshots are an example of one.

<img width="1627" alt="Screen Shot 2020-05-12 at 11 32 18 AM" src="https://user-images.githubusercontent.com/58981029/81750057-d2190f00-947a-11ea-93b8-f4dd1170550a.png">
<img width="1627" alt="Screen Shot 2020-05-12 at 11 34 16 AM" src="https://user-images.githubusercontent.com/58981029/81750069-d80ef000-947a-11ea-97ba-39377a2366e2.png">

**Comment by JuanitaMiles** [comment]
@awhite806 Jeff has gotten the batch job running regularly again as of 5/12 14:30. All permits that were issued between 5/7 - 5/12 will likely need the official issuance and placards manually attached.

**Comment by JuanitaMiles** [comment]
Spoke with Ashlye B on the phone. Staff are adding correspondence manually. Closing ticket since batch job is running now.
