### ISSUE TITLE
Health Department Reviews from PDOX

### ISSUE THREAD

**Issue by ABonomo21** [dhenry-KCI/FredCo-Post-Go-Live-#555]
The health department reviews going to pdox should follow the same due date guidelines established based on the priority code as the other reviews due. 

HD reviews are not setting the correct due date, see example below.
This is for all building permits. 

![image](https://user-images.githubusercontent.com/47611580/81814957-69bc4300-94f7-11ea-8fa4-e79c804ee34b.png)

**Comment by JuanitaMiles** [comment]
I believe this is in relation to when the due date needs to be manually changed in PDox, and that change not being reflected in IPS or PDox. The manual change seems to stick for DPZ and PLNREV, but  does not for EH.

**Comment by pooldaddy** [comment]
@juanita can you point me in the right direction as to where the priory codes are defined?

**Comment by JuanitaMiles** [comment]
@pooldaddy @Ycoto Code Definition Management

![image](https://user-images.githubusercontent.com/31770504/82247198-fca01780-9913-11ea-99dc-4abb95dbd3a8.png)

**Comment by pooldaddy** [comment]
@megisys Need your help on this one.

**Comment by JuanitaMiles** [comment]
Assigning to Dan as well (@megisys ) since IIT needs assistance.

**Comment by megisys** [comment]
BP_RevisionDueDates_BU - To be promoted once tested

**Comment by ABonomo21** [comment]
in the middle of testing 278194- error in pdox when trying to assign

**Comment by ABonomo21** [comment]
test accepted
