### ISSUE TITLE
Planning - STOPNOT Log but notifications still sent

### ISSUE THREAD

**Issue by AReed327** [dhenry-KCI/FredCo-Post-Go-Live-#556]
Why did notifications send on this even though I put a STOPNOT log on it before the completeness check was resulted?
PW260050
![image](https://user-images.githubusercontent.com/58854333/81842174-8e291700-9519-11ea-8b80-3a95f83a88f1.png)

**Comment by JuanitaMiles** [comment]
@AReed327 the log has a stopped date on it. It looks like the stopped date was filled in when the log was initially being created and submitted by you. If the log has a stop date it will allow notifications to send.

**Comment by AReed327** [comment]
When I put a void log in I must include the stop date or the Void won't work.
