### ISSUE TITLE
Bypass of status checks for completeness check resubmit

### ISSUE THREAD

**Issue by ABonomo21** [dhenry-KCI/FredCo-Post-Go-Live-#557]
We have been having permit held up in the completeness check milestone for building permits because the status check of license required is not being bypassed. 
![image](https://user-images.githubusercontent.com/47611580/82105354-e5311680-96e8-11ea-9672-a7815ead77c7.png)

**Comment by ABonomo21** [comment]
![image](https://user-images.githubusercontent.com/47611580/82104581-769e8980-96e5-11ea-8cfb-17bbc905a644.png)

**Comment by ABonomo21** [comment]
![image](https://user-images.githubusercontent.com/47611580/82105358-eb26f780-96e8-11ea-845d-3d784a27d64f.png)

**Comment by ABonomo21** [comment]
also found a permit that was held up for a details page being completed.

All status checks should be bypassed if a resubmission is asked for at completeness check

**Comment by ABonomo21** [comment]
![image](https://user-images.githubusercontent.com/47611580/82106314-14965200-96ee-11ea-926e-99ae325feddb.png)
Another for building parent permit being required

**Comment by megisys** [comment]
BLD_ProgressOnResubmit_BU - Promote - Once Tested

**Comment by ABonomo21** [comment]
278164 resbdlg- hb license required- bypassed 
278134 resuse- priority code set - bypassed
278128- resuse need lic contact did not bypass
278126 electrical failed did not by pass building permit attached

**Comment by megisys** [comment]
BP_LicensedContact_SCF - to be promoted also
ElecPerm_ParentRequired_scf
BLD_ProgressOnResubmit_BU

**Comment by ABonomo21** [comment]
retested all four above and was sucessful
