### ISSUE TITLE
Health Department Review - Reassignment 

### ISSUE THREAD

**Issue by ABonomo21** [dhenry-KCI/FredCo-Post-Go-Live-#558]
Putting this one in to keep on our radar, we will need to reassign all the health reviews. Karen Amoss is retiring June 12, 2020- waiting for her to let me know who to start re-assignment permit review too.

**Comment by ABonomo21** [comment]
As of 6.12.20 please make all building permit health department reviews auto assign to Kim Dillman

**Comment by JuanitaMiles** [comment]
@Ycoto 

It does not appear that the Review Assignment setup has an effective date field, so the final Production configuration for this will have to wait until 6/12. You can practice the setup in TEST ahead of time however.

The configuration for this is within the Review Assignment windows for the respective module (I've highlighted the form codes in the screenshot below). I believe the automatic assignment to Karen Amoss is setup on Building Permits and Use Permits. For each of the application types you will need to update the Reviewer from Karen Amoss (KAMOSS) to Kim Dillman (KDILLMAN) on Review Types equal to "EH" and "HEALTH-FD" for the DEPTTYPE and APTYPE categories.

*Not all application types will have the EH or Health-FD reviews, such as Plumbing and Electrical Permits.

![image](https://user-images.githubusercontent.com/31770504/82257319-d71c0980-9925-11ea-8a2f-3516ee64f7df.png)
![image](https://user-images.githubusercontent.com/31770504/82257400-f450d800-9925-11ea-9b99-30073c731f6c.png)

**Comment by Ycoto** [comment]
@JuanitaMiles 
   Thank you, I was able to update them I did saw other "EH" and  "HEALTH-FD". The only thing I haven't done is testing it. You think tomorrow after the meeting we could meet for like 10 min.

**Comment by pooldaddy** [comment]
Kamos changed to kdillman in PROD for future review assignments, any existing reviews not completed by kamos will require reassignment.
