### ISSUE TITLE
Payment Provider Updates (R4C Payment Issues)

### ISSUE THREAD

**Issue by JuanitaMiles** [dhenry-KCI/FredCo-Post-Go-Live-#559]
Creating a placeholder ticket for tracking the R4C payment posting issues reported by Dan Lewis and the subsequent investigation of changing the "hand shake" settings between Govolution and IPS. Dan G. and Dustin will lead the efforts to coordinate with the necessary parties. Snippet of initial plan forward below:

![image](https://user-images.githubusercontent.com/31770504/82489505-c3041380-9aaf-11ea-95e2-cde156dc0e3c.png)

**Comment by megisys** [comment]
County has decided to test with the 15 Second Time out turned off.

**Comment by JuanitaMiles** [comment]
Copying Jeff's most recent update with path forward. IIT will need to continue to provide updates on progress of this item.

![image](https://user-images.githubusercontent.com/31770504/83158931-6ae29800-a0d3-11ea-8486-c58297bc76b9.png)

**Comment by JuanitaMiles** [comment]
Spoke with County IIT on 6/22/20. They will test this item post July 1 fee updates. Migrated ticket to future phase repository to be accounted for in next phase of the project.
[Ticket 99](https://github.com/JuanitaMiles/FredCo_Future_Phases/issues/99)
