### ISSUE TITLE
MINOR GRADING PERMIT - reviews 258248

### ISSUE THREAD

**Issue by TMARTIN0926** [dhenry-KCI/FredCo-Post-Go-Live-#56]
permit number 258248 did not populate a DPZ review. This review should have populated on the grading permit. This is something that was working previously. 
![258248](https://user-images.githubusercontent.com/58991985/71106025-9492ad00-218c-11ea-9368-7df878e06bca.PNG)

**Comment by ABonomo21** [comment]
dpz does not need a review on the grading permit when the permit is associated with a building permit because the dpz review is completed under the building permit. We do not want to duplicate reviews.
