### ISSUE TITLE
Bob Button Notifications When Rescheduling in Back Office

### ISSUE THREAD

**Issue by JuanitaMiles** [dhenry-KCI/FredCo-Post-Go-Live-#560]
Bob has noticed a potential gap in the functionality of when the "Bob Button" sends notifications. It appears that when an inspection is cancelled and/or rescheduled via R4C, the notification will send again once the new time has been requested and scheduled, as expected. However, when the inspection is "cancelled" in IPS (meaning the scheduled date has been manually changed or removed by back office staff), a second notification does not go out to the applicant via the Bob Button once the new scheduled date is input by staff.

While Bob agrees with the strategy to push applicants to the portal to cancel their inspections rather than calling or emailing as much as possible, we would still like to look into closing this gap in functionality. A new notification should send from the Bob Button if the inspection scheduled date has been changed to a new date like it does when this process is completed via the portal.

Bob provided two example applications where this happened:
275664
203412

**Comment by megisys** [comment]
If the back office is rescheduling. Remove the INSPBOOK log from the inspection. and it will be the same as all the other inspections The log is a safe guard to not over email. @JuanitaMiles

**Comment by JuanitaMiles** [comment]
@TheBobEnsor  Bob can you try this out and let me know if it's the result your looking for?

**Comment by choreboy** [comment]
I will try it and let you know

**Comment by TheBobEnsor** [comment]
Test acceptable
Passed
