### ISSUE TITLE
Reviewer Contact information 

### ISSUE THREAD

**Issue by ABonomo21** [dhenry-KCI/FredCo-Post-Go-Live-#561]
We need to have the notifications for review comments generate the reviewers name and contact information, similar to ticket #215 for the inspectors contact information. 

Applicants do not know who to reach out to when the reviews are generated.

**Comment by megisys** [comment]
Can you send me a sample of the notification in question please ? @ABonomo21

**Comment by JuanitaMiles** [comment]
The notification template: BLDG_Resubmittal is used for all resubmit request notifications. Example from test is below. I believe it's used for both completeness check and under review resubmittals.

![image](https://user-images.githubusercontent.com/31770504/82678515-ba2e5180-9c17-11ea-8dc5-626fd0f3a14c.png)
![image](https://user-images.githubusercontent.com/31770504/82678725-15604400-9c18-11ea-8206-cf9a9d40929a.png)

**Comment by megisys** [comment]
This is not going to be a straight forward request. As we sent the building application details to this notification and not the review details. Am I adding all reviewers names. Only those against resubmits. What happens if it is 2 rounds of resubmit. Am I leaving off the previous reviewer details. Do you want phone numbers and names ? This is an enhancement. But please be specific in what you would it to do. @JuanitaMiles

**Comment by megisys** [comment]
Is this for More Information Only ? or is it for the review resubmit too !

**Comment by ABonomo21** [comment]
Reviewer name and contact information being email address -yes for more information only should only pull those contacts when a re-submission is request

**Comment by megisys** [comment]
BP_AwaitingResubmitNotification - to be promoted if accepted

**Comment by ABonomo21** [comment]
do not want to implement into production - we need to work on the notifications as a whole-do not want a formula based notification and i do not like the look of how it generates contact information, 
![image](https://user-images.githubusercontent.com/47611580/85042880-be3b8980-b159-11ea-9383-5e9bcfb85521.png)
![image](https://user-images.githubusercontent.com/47611580/85043342-3bff9500-b15a-11ea-93a6-b71b1824c9d5.png)
will have staff add a signature to all reviews for now and will work out in the future phases.
