### ISSUE TITLE
Treasury Receipts to Print Site address for permits

### ISSUE THREAD

**Issue by ABonomo21** [dhenry-KCI/FredCo-Post-Go-Live-#562]
I have copied Juanita and Jeff on this email to see where they can help. I am assuming your back office cashiering IPS looks just like mine...Jeff and Juanita can you confirm? 

If that is the case there should be an option under the documents section when you look up the building permit to print the building details report. 

I should have walked through this with you all today when I was at the office, but slipped my mind ! 

I’m not sure how the receipts print and where they pull the data from. I have put a GitHub ticket in for Jeff and Yaciel to work with us on getting this corrected.

To print the report: 
Click Documents, then select the Building Application Details 
 
 

Thank you,

Ashlye 

On May 20, 2020, at 8:31 AM, Lewis, Daniel <DLewis@frederickcountymd.gov> wrote:
 
Good Morning Ashlye,
 
No worries!  We would definitely like to explore getting the premise address related to the permit added to the receipt we provide the customers if possible.  In the meantime, please feel free to provide us with the steps necessary to generate the information report you mentioned.  We can also continue to print the screen we have been until the receipt is updated.  Let us know if you need anything else from us in order to move forward with this request.  Thanks for your help!
 
Dan Lewis, CPFO
Treasury Manager
301-600-1113
 
From: Bonomo, Ashlye <ABonomo@FrederickCountyMD.gov> 
Sent: Tuesday, May 19, 2020 9:37 PM
To: Pradeep, Jyothi <JPradeep@FrederickCountyMD.gov>
Cc: Lewis, Daniel <DLewis@FrederickCountyMD.gov>
Subject: Re: IMPACT AND CAPCITY FEES FOR CITY
 
Hi Jyothi ! So sorry for my delayed response.  What we have discussed with Mary and Debbie with the City, is that we can provide the applicant with a copy of the “information report” this was the reports that we used to print and applicants used to bring to the Treasury Counter. Once the fees are paid we can email them to the applicant, if in fact they are asking for the receipts right away, I can show you all how to run those reports? Or we can certainly explore why the receipts printed by Treasury staff do not have the address. 
Let me know what option would be best for Treasury and I will make it happen! 
Thank you,
 
Ashlye 
 

On May 18, 2020, at 9:16 AM, Pradeep, Jyothi <JPradeep@FrederickCountyMD.gov> wrote:
Hi Ashley:
 
Just a quick question to clarify something.
When we collect impact /capacity fees for a city property, customers are asking us for an address printout for each permit number.  For capacity, addresses are shown on the capacity receipts.  
But that’s not the case with impact fees. Address is not shown on the receipt and so we are pulling up the address of each impact fees and giving them a separate printout as well.
They do  have the application with the address. They have informed us that Mary at the City Office is rejecting them, if they don’t have a separate printout from the county with the property address.
We never had to do this before and just want to check with you to confirm. Maybe you can Check with Mary if this is required when they already have the application with address for each receipt.
 
 
Thank you,
 
JYOTHI PRADEEP
Frederick County Government
30 N. Market Street
Frederick, MD 21701
Phone 301-600-1111

**Comment by megisys** [comment]
HI All,

Modification to the Receipt is very limiting and permits paid are not all for one address. Some have no address at all. I guess we should talk process options here first.

@JuanitaMiles @ABonomo21 

Dan

**Comment by JuanitaMiles** [comment]
Will look to get a meeting with Dan L, AB, Dan G, and Tara if possible to understand the requirements surrounding the receipts and how the Capacity are configured to show the address. Will have Dustin schedule, maybe with Dan's webex to allow for screen sharing? @dhenry-KCI

**Comment by JuanitaMiles** [comment]
Migrated to the Future Phase repository for consideration in the next phase of the project.
[Ticket 95](https://github.com/JuanitaMiles/FredCo_Future_Phases/issues/95)
