### ISSUE TITLE
PLANNING - Adding additional parcel screent  - formatting overlapping

### ISSUE THREAD

**Issue by AReed327** [dhenry-KCI/FredCo-Post-Go-Live-#564]
Formatting overlapping under action - change sites.  Also under the Associated sites. See screenshots
![image](https://user-images.githubusercontent.com/58854333/83138202-707eb480-a0b8-11ea-9cc8-53cf61a6fbf6.png)

![image](https://user-images.githubusercontent.com/58854333/83137847-d6b70780-a0b7-11ea-9eca-ce36167ddfb9.png)

**Comment by megisys** [comment]
I think you internet zoom is off. Ensure it is 100%

**Comment by megisys** [comment]
![image](https://user-images.githubusercontent.com/47392306/83139113-d9b2f780-a0b9-11ea-85a2-6543348b7da3.png)

**Comment by AReed327** [comment]
So the 100% works but I have zoomed in and out a lot. On this little laptop screen I'm always much smaller and at work I think we are set at 200 or more with the size of the screen. Probably only an issue when going less than 100. Closing ticket,
