### ISSUE TITLE
Test PDox Error at Assign Reviewers Task

### ISSUE THREAD

**Issue by JuanitaMiles** [dhenry-KCI/FredCo-Post-Go-Live-#565]
I am trying to test and create documentation on a topic for permits using the TEST PDox and IPS systems. Upon trying to complete the Assign Reviewers task in Test Pdox, I get the following error and cannot progress forward.

![image](https://user-images.githubusercontent.com/31770504/83180528-91173080-a0f1-11ea-958e-346cf27f0a26.png)

**Comment by JuanitaMiles** [comment]
Dan to resync web services when available.

**Comment by megisys** [comment]
in Sync

**Comment by JuanitaMiles** [comment]
was able to get past the assign reviewers task, no error. thanks
