### ISSUE TITLE
Permit of $20,000 in Fees- No Re-inspection fees

### ISSUE THREAD

**Issue by ABonomo21** [dhenry-KCI/FredCo-Post-Go-Live-#566]
We have a permit that paid over 20k in fees and should not generate re-inspection fees, 
![image](https://user-images.githubusercontent.com/47611580/83367001-49f29f00-a380-11ea-8849-c8e91f213864.png)

I checked the transactions and do not see where is was manually added ? 

Please check the coding to make sure permits where permit fees paid over 20k do not charge re-inspection fees. 

Thanks

**Comment by megisys** [comment]
ReInspection 20,000 was set up for the Trades and Not the Non Res. You sure you want this ?
@ABonomo21

**Comment by megisys** [comment]
Needs to be NON RES - For ALL Occupancy > 20,000 of Fees
