### ISSUE TITLE
Septic Inspection - RESBLDG 

### ISSUE THREAD

**Issue by ABonomo21** [dhenry-KCI/FredCo-Post-Go-Live-#568]
A septic Final did not generate on a RESBLDG SFD permit on well and septic and should have. 

267987 did not generate a septic final - inspection had to be manually added.

**Comment by JuanitaMiles** [comment]
Let's fix this specific inspection within the current configuration now, as we continue to work through the overall inspection redesign.

**Comment by ABonomo21** [comment]
Did we move the septic inspections to generate at the inspection milestone instead of the final inspection milestone? @JuanitaMiles

**Comment by megisys** [comment]
It is moved to INspections now
