### ISSUE TITLE
Permit  Attachment not generating on IPS11

### ISSUE THREAD

**Issue by Ycoto** [dhenry-KCI/FredCo-Post-Go-Live-#569]
![image](https://user-images.githubusercontent.com/63804011/83409857-46dcca80-a3e3-11ea-8530-0522fca54ffe.png)

**Comment by megisys** [comment]
This is REsolved. Please check Again

**Comment by pooldaddy** [comment]
@megisys What if anything did u change??????

**Comment by megisys** [comment]
I just reset them and ran batch manager again- Its under actions

**Comment by Ycoto** [comment]
@megisys RESUSES - APPLICATION #  280863 didn't generate a permit.

**Comment by Ycoto** [comment]
Here is another one that didn't generate the permit. 
APPLICATION # 280736

**Comment by megisys** [comment]
Batch Manager scheduling was off

**Comment by JuanitaMiles** [comment]
Dan, Yaciel, and Jeff have worked to establish a process for identifying correspondence that is being held up and releasing that correspondence. Closing this ticket with the understanding that there will be an ongoing process and implementation of standard operating procedures surrounding checking batch tasks, identifying errors, reporting and resolving them.
