### ISSUE TITLE
Total Paid Amount Not Generating On Plumbing Permit.

### ISSUE THREAD

**Issue by awhite806** [dhenry-KCI/FredCo-Post-Go-Live-#57]
The Total Paid is generating as $0, when it should be showing the total paid on the permits. This only happening on Plumbing permits.
[258411.pdf](https://github.com/dhenry-KCI/FredCo-Post-Go-Live-/files/3979721/258411.pdf)

**Comment by awhite806** [comment]
per Ashlye-assign to Dustin so it can go to Tara

**Comment by TaraF** [comment]
This is fixed. Ready for re-test.
