### ISSUE TITLE
MPDU code in parcel not generating fee

### ISSUE THREAD

**Issue by awhite806** [dhenry-KCI/FredCo-Post-Go-Live-#570]
This parcel has the MPDU code in the parcel however it did not generate the MPDU fee for the permit.
<img width="1193" alt="Screen Shot 2020-05-29 at 12 56 49 PM" src="https://user-images.githubusercontent.com/58981029/83419337-eb1a3d80-a3f2-11ea-9f86-44db98ccb5ae.png">
<img width="1193" alt="Screen Shot 2020-05-29 at 12 56 03 PM" src="https://user-images.githubusercontent.com/58981029/83419349-f1101e80-a3f2-11ea-93c3-36260b781df0.png">

**Comment by megisys** [comment]
The Address Needs the Subdivision Code .

![image](https://user-images.githubusercontent.com/47392306/83420248-5adcf800-a3f4-11ea-8c75-175b77137be9.png)

**Comment by pooldaddy** [comment]
Subdivision NOT populated at SDAT  see below:
![image](https://user-images.githubusercontent.com/47391482/83439467-317e9500-a411-11ea-8123-56ce96993e59.png)

**Comment by pooldaddy** [comment]
Emailed Mary in GIS to research

**Comment by Ycoto** [comment]
it has been updated.

![image](https://user-images.githubusercontent.com/63804011/83442333-fdf23980-a415-11ea-9de3-76387778a9ad.png)

**Comment by megisys** [comment]
@Ycoto - Just this address. or is there an issue with GIS mappng here ?

**Comment by Ycoto** [comment]
@megisys It was just this address.
