### ISSUE TITLE
SERVICE REQUESTS ON R4C

### ISSUE THREAD

**Issue by ABonomo21** [dhenry-KCI/FredCo-Post-Go-Live-#571]
PLEASE FIX RIGHT AWAY - ON R4C UNDER SERVICE REQUEST IT SAYS CITY REQUESTS,,, SHOULD SAY COUNTY REQUESTS

![image](https://user-images.githubusercontent.com/47611580/83534160-80cecf00-a4be-11ea-91d2-efc1fe8dae80.png)

HERE IS A SCREENSHOT FROM A PREVIOUS TICKET WERE IT WAS COUNTY. NOT SURE WHEN IT CHANGED. 

![image](https://user-images.githubusercontent.com/47611580/83534282-a65bd880-a4be-11ea-99b2-48b98f9daa14.png)

**Comment by JuanitaMiles** [comment]
@pooldaddy @Ycoto This looks to require a language change on the formlet(?) for this page. Can you look into asap. Dan is currently out of office, if we absolutely NEED to call him you can.
