### ISSUE TITLE
Planning - General Comment under Problems is missing for BOE reveiw

### ISSUE THREAD

**Issue by AReed327** [dhenry-KCI/FredCo-Post-Go-Live-#572]
A/P 19080
Please add General Comment to the Grid so comments can be logged under problems by BOE

Should look like this
![image](https://user-images.githubusercontent.com/58854333/83682634-30d13480-a5b2-11ea-9845-d32e143c9b74.png)

It is missing under BOE reveiew'
![image](https://user-images.githubusercontent.com/58854333/83682769-60803c80-a5b2-11ea-8fa2-464187a07859.png)

**Comment by AReed327** [comment]
BOE is trying to enter comments to finish a reivew that was due on 5/15/2020. I put medium on this but this should be done as soon as possible.

**Comment by megisys** [comment]
![image](https://user-images.githubusercontent.com/47392306/83752435-8b13d900-a636-11ea-8d74-cf3cc6e6e738.png)

**Comment by megisys** [comment]
This is where this is done. If you @Ycoto would like to do in Test. I did in Production as I was already in there

**Comment by megisys** [comment]
PWCONSTRUC - BOE

**Comment by Ycoto** [comment]
Thank you @megisys  I will do it in Test.

**Comment by MLWilkins** [comment]
BOW was able to add problems under ap 19080 but the comments are in code. Elevating this to high priority because applicants cannot read the comments and it is delaying projects.

![image](https://user-images.githubusercontent.com/50637067/84140521-c3912980-aa1f-11ea-81ba-1dfc5ba78439.png)

**Comment by MLWilkins** [comment]
thought there was an error with comments but we believe it was due to how the reviewer added the problems. took off test failed.

**Comment by MLWilkins** [comment]
Planning is good to go on this ticket 

@Ycoto once you have what you need from this ticket it can be closed.
