### ISSUE TITLE
Building Permits - NonRes - Blank Certificate of Completion Report

### ISSUE THREAD

**Issue by JuanitaMiles** [dhenry-KCI/FredCo-Post-Go-Live-#573]
Inputting on behalf of Emily and Ashlye:

When running the Certificate of Occupancy / Completion report for AP # 191419 the report is blank. The correspondence that automatically ran and attached to the permit is also blank.

![image](https://user-images.githubusercontent.com/31770504/84156669-cbf55e80-aa37-11ea-96d6-0ed5666de3e7.png)

![image](https://user-images.githubusercontent.com/31770504/84156747-e596a600-aa37-11ea-9ca6-b31562d1634c.png)

This is a high priority issue as the customer requires a valid COC.

**Comment by TaraF** [comment]
Investigating.

**Comment by TaraF** [comment]
The Construction type of "ACC500" did not exist/ was not provided when the report was originally written, but it has now been added to the applicable types for NONRESBLDG.  Full list for NONRESBLDG is as follows:  **('FULL', 'COMPLETE' , 'ADDITION', 'CHANGE','FITOUT','NOCHANG','OWNERCH','ACC500')**   This change has been made in TEST and PROD. 

If there are other 'new' construction types that should be included for either RESBLDG or NONRESBLDG please provide and we can update. 

List we were given for both types is provided in the image below for reference:
![image](https://user-images.githubusercontent.com/4104464/85026875-3cdafb80-b147-11ea-86f5-924f574c14be.png)

**Comment by ABonomo21** [comment]
worked 191419

**Comment by JuanitaMiles** [comment]
also confirmed in prod. closing
