### ISSUE TITLE
GIS - Address / Parcel Update Logic Request

### ISSUE THREAD

**Issue by JuanitaMiles** [dhenry-KCI/FredCo-Post-Go-Live-#574]
Inputting on behalf of Mary McMullough. She sent the following request to Juanita, Rick Little, Dan G, and Austin WIlliams on 6/8/2020. We will need to understand the feasibility of this request and the effort involved. Dan, if you can provide your initial thoughts, that would be great in helping to determine next steps.

"Can you please log in the request to change some logic.  I would like when I push an address with the TAXID field (which is the Parcel) to use that field to replace the Parcel if a Parcel is already linked and if no Parcel is linked to add the TAXID parcel.  We have to go in and manually remove the Parent Parcels due to the parent’s holding old information and this causes many tickets.  Also, if a Parcel is wrong that is linked and we push an address with a good parcel all it does is add the good parcel not remove the bad one."

**Comment by JuanitaMiles** [comment]
Emailed Mary M. to perform a test in TEST environment on 6/15. Will update with her results when received.

**Comment by JuanitaMiles** [comment]
Mary tested and provided the attached document with her tests and results.

[ipstest.docx](https://github.com/dhenry-KCI/FredCo-Post-Go-Live-/files/4794216/ipstest.docx)

![image](https://user-images.githubusercontent.com/31770504/84930193-e7e3aa80-b09e-11ea-8c6b-e08197ac2ce7.png)

**Comment by megisys** [comment]
PLease Retest.. I tried on the Posey Address. Ensure you open and close after the test.

**Comment by JuanitaMiles** [comment]
Emailed Mary to retest 7/7/20 10:34am.

**Comment by megisys** [comment]
Redeployed to TEST

**Comment by JuanitaMiles** [comment]
Juanita,

That works but I still have and issue with the address-parcel logic.  This is an example to explain the issue: 

Day 1: the Address with TaxID value of 1234 is pushed, however Parcel 1234 has not been added yet thus there is an Address without a Parcel linked but has a TAXID (which is the Parcel) value.  Day 2: Parcel 1234 is pushed, however, Address does not have the Parcel linked because the Address was added before the Parcel.  

Can logic be added so when a Parcel is pushed an Address is looked for to link up to?  Much like when an Address is pushed a Parcel is looked to link up to?  It needs to work both ways.

-Mary

**Comment by megisys** [comment]
Parcel_AddRelatedRecords_AA - Added

**Comment by JuanitaMiles** [comment]
Emailed Mary to retest on 7/12/20 10:53pm.
