### ISSUE TITLE
Health Review generated on Town water/sewer

### ISSUE THREAD

**Issue by awhite806** [dhenry-KCI/FredCo-Post-Go-Live-#58]
Health review generated when this permit is located within Brunswick. Brunswick has their own town water/sewer and should not have a health review.
![image](https://user-images.githubusercontent.com/58981029/71110005-716bfb80-2194-11ea-9e8d-c23d73ccc5c1.png)

**Comment by calequin** [comment]
PROMOTE = RESBLDG_EH_Review_AOC

**Comment by ScottVanSooy** [comment]
Deployed to Production 12/18/19
