### ISSUE TITLE
REVPISIG Review

### ISSUE THREAD

**Issue by ABonomo21** [dhenry-KCI/FredCo-Post-Go-Live-#580]
when a revpisig review is added and marked as a resubmit on ANY building permit type it is triggering the $27.00 revision fee and is should not be can we please correct this ASAP

**Comment by megisys** [comment]
Which AP Type and Number did this occur on please

**Comment by megisys** [comment]
@JuanitaMiles @ABonomo21

**Comment by megisys** [comment]
BLDG_PWDRNoRevisionFee_AOC - To be promoted once accepted

**Comment by ABonomo21** [comment]
![image](https://user-images.githubusercontent.com/47611580/85039941-41f37700-b156-11ea-8bef-42194c68248c.png)

We need to make a PIREV available for all building and use a/p types 
This review will be manually added at the revision assignment milestone in the event that a revision is received and the applicant did not provide the details and information needed to submit a review back to the requesting agency. 

There should not be a revision fee assessed if this review is resulted as a resubmit and therefore should be excluded from the fee generation similar to health review resubmits. 

Adding to future phase for enhancement - REVSIGPI - did not work in testing.
