### ISSUE TITLE
Historic Reviews 

### ISSUE THREAD

**Issue by ABonomo21** [dhenry-KCI/FredCo-Post-Go-Live-#581]
282129 generated a historic review only after a resubmit was asked for and did not generate the first time - should have generated the first round of reviews if the parcel was marked historic. 
![image](https://user-images.githubusercontent.com/47611580/84678664-4887b180-aefe-11ea-9574-b3868e0c60d3.png)

**Comment by megisys** [comment]
![image](https://user-images.githubusercontent.com/47392306/84699349-5994ea80-af1f-11ea-8def-8e37a8cd4a3a.png)

Someone updated this address after the initial creation., See Test. Historic = N

**Comment by megisys** [comment]
![image](https://user-images.githubusercontent.com/47392306/84699405-73363200-af1f-11ea-81a5-2013c86ae356.png)

**Comment by ABonomo21** [comment]
GIS updated parcel information for historic registry- will close for now.
