### ISSUE TITLE
Planning- items randomly appearing in Admin Closure dashboard report-and some are not populating

### ISSUE THREAD

**Issue by MLWilkins** [dhenry-KCI/FredCo-Post-Go-Live-#582]
applications are randomly showing up in the admin closure dashboard without any actions having been taken on the applications.  These were not in admin closure a week or so ago.  How and why did this happen?  Applications that should be under resubmit now appear to the applicants to be approved!

![image](https://user-images.githubusercontent.com/50637067/84696951-4a13a280-af1b-11ea-80b2-f8b0c67cabcc.png)

![image](https://user-images.githubusercontent.com/50637067/84697095-8d6e1100-af1b-11ea-8a11-d5fd40b0ccb8.png)

![image](https://user-images.githubusercontent.com/50637067/84697461-2a30ae80-af1c-11ea-81a7-af8e21a86e2b.png)

**Comment by MLWilkins** [comment]
here is a PWConst 

![image](https://user-images.githubusercontent.com/50637067/84697929-fc983500-af1c-11ea-87da-203dd7c4435b.png)

**Comment by MLWilkins** [comment]
log below.  These projects were not in admin closure since go live as I have monitored all items in this dashboard from the start.

![image](https://user-images.githubusercontent.com/50637067/84698345-a7105800-af1d-11ea-8825-4c422cc50389.png)

**Comment by megisys** [comment]
Hi Mike,

I worked with Ashley on this and we bulk moved these again on 12/7. See Logs where you can see we added STOPNOT Log and moved them to Admin Closure. I dont have the history of why we landed here

REVPISIG
![image](https://user-images.githubusercontent.com/47392306/84698969-af1cc780-af1e-11ea-8f39-b2e2ab6565a3.png)

**Comment by megisys** [comment]
This will take a working party. As we moved all of these during GO LIve activities. @JuanitaMiles

**Comment by MLWilkins** [comment]
@megisys we added stopnot to every in life application. I am pretty sure we would not have moved these to admin closure knowingly.

**Comment by megisys** [comment]
Items were moved pre go live with AREED as the user. I remember us sitting down and making some broad decisions, these could be caught up in that. Will need AREED assistance here.

**Comment by MLWilkins** [comment]
below is a screen shot I took of the admin closure dashboard on February 24th.  Note that the applications I reported above that are now appearing on the dashboard were not there in February.


![image](https://user-images.githubusercontent.com/50637067/84775182-dc17bb80-afac-11ea-9fa8-23092fea8f3f.png)

**Comment by megisys** [comment]
Hi Mike,

What adhoc Report is this one please. ? I do see the Admin Closure Adhoc Report. It only should be showing Admin CLosures after June 1st 2019
![image](https://user-images.githubusercontent.com/47392306/84778510-15eac100-afb1-11ea-9f8a-2c6b09eda97c.png)
I didnt write this, so i am in the dark to this

**Comment by MLWilkins** [comment]
@megisys  the screen shot is of the admin closure report

**Comment by JuanitaMiles** [comment]
@megisys @MLWilkins The screenshot Mike has of a dashboard report appears to be the out of the box Planning Reviewer To-Do list. Our Admin Closure ad hoc does not have these fields on it. The planning reviewer to do list shows the reviews that were once assigned to Mike and seeing as this screenshot was taken back in February, it makes sense they were showing because Mike didn't result one of the reviews until March of this year.

Clarification may still be needed from Ash R, to confirm the decision to bulk move applications to admin closure, but the reports Dan is looking at and Mike has a screenshot of are two different things.

**Comment by MLWilkins** [comment]
manually adjusted milestones on Dev Rev projects that recently appeared in this dashboard and were incorrectly in admin closure.   Screenshot below is to document current dashboard to help monitor any projects that were in admin closure as of 12/7/19 that show up on the dashboard in the future. 


![image](https://user-images.githubusercontent.com/50637067/84892050-e5675d80-b06a-11ea-8534-962749cdd2eb.png)

**Comment by MLWilkins** [comment]
Ran a query for all projects in admin closure from June 1 2019 to present.  Found three projects that do not appear on dashboard.
 

Dashboard:
![image](https://user-images.githubusercontent.com/50637067/84912339-587ecd00-b087-11ea-926f-beac21a257da.png)



query 
![image](https://user-images.githubusercontent.com/50637067/84912486-7ba97c80-b087-11ea-96fe-186392237822.png)

**Comment by MLWilkins** [comment]
Closing this. Will reopen if issue arises again.

**Comment by MLWilkins** [comment]
the project below is not appearing in the admin closure dashboard.  I think there is something wrong with this report.  It is missing projects and as noted above they populate on the dashboard randomly 


![image](https://user-images.githubusercontent.com/50637067/85401699-72f1f400-b528-11ea-9d86-105aa3f25aa7.png)

**Comment by AReed327** [comment]
My understanding is that the Admin Closure Adhoc Report shows Admin Closures for applications created after June 1st 2019.
A/P  19359 was processed 4/18/2019. That's why it's not showing.
As discussed previously, we need to phase these old projects out. If you prefer a date other than June 1, 2019, it can be changed, but you will likely get additional projects that you don't want to see. 
If you prefer another date, please let Juanita/Dan know.

**Comment by MLWilkins** [comment]
we have quite a few projects from hansen that were created before June 1 2019 that are still moving forward.  I need to see when they are stuck in admin closure.  A better approach is to choose a date after which they go to admin closure verses basing this admin closure report on a process date.  Example, have it populate projects that were in the admin closure milestone on or after June 1 2019.  This way a project will show on this dashboard no matter when it was processed when it moves to the  admin closure dashboard report.  Dont know if this is a Dan or Tara thing
