### ISSUE TITLE
Grading Permits - Resubmittal Notification Not Sending at Awaiting Applicant Revisions

### ISSUE THREAD

**Issue by JuanitaMiles** [dhenry-KCI/FredCo-Post-Go-Live-#583]
Resubmittal notifications are not generating and being sent to customers when grading applications enter the Awaiting Applicant Revisions milestone.

It appears this has been an issue since late January and was not noticed until recently. I did a search of all current Grading applications in the Awaiting Applicant Revisions milestone and 260734 was the last application in the list to have received the resubmit notification.

A few examples of applications that did not receive the resubmit notification are:
283483, 282223, 282042

![image](https://user-images.githubusercontent.com/31770504/84717371-9ecb1380-af43-11ea-8850-0621bb67f68e.png)
![image](https://user-images.githubusercontent.com/31770504/84717406-b3a7a700-af43-11ea-9578-7c739ab9d756.png)

Was also able to replicate in TEST with application 278274.

**Comment by megisys** [comment]
BP_AwaitingResubmitNotification - to be promoted -

**Comment by JuanitaMiles** [comment]
confirmed in test

![image](https://user-images.githubusercontent.com/31770504/84913432-8ca6bd80-b088-11ea-824f-a3104df8da94.png)
