### ISSUE TITLE
Building Permits - Hold Notification Showing Business Objects

### ISSUE THREAD

**Issue by JuanitaMiles** [dhenry-KCI/FredCo-Post-Go-Live-#584]
The "Building Permits on Hold" notification is showing all of the business objects rather than the data they should be pulling when it is sent to the applicant. This notification was sent from application # 282223.

![image](https://user-images.githubusercontent.com/31770504/84718291-3a5d8380-af46-11ea-84a5-dc5d89006e44.png)
![image](https://user-images.githubusercontent.com/31770504/84718359-61b45080-af46-11ea-930a-ef7a72297838.png)

**Comment by megisys** [comment]
Issue addressed in both environments - can be tested in Test. Close once tested, as copied across to Production following my testing

**Comment by JuanitaMiles** [comment]
Confirmed in production.

![image](https://user-images.githubusercontent.com/31770504/84910702-33895a80-b085-11ea-86e9-685e91363e02.png)
