### ISSUE TITLE
Building Permit Extensions Not Auto-Generating Fee

### ISSUE THREAD

**Issue by JuanitaMiles** [dhenry-KCI/FredCo-Post-Go-Live-#585]
When processing application extensions, various staff have recently reported that the building extension fee is no longer automatically adding to the application once the EXT review is approved.

Some permit examples that are not adding the fee automatically include:
RESBLDG - 193465
ELECPERM - 193631, 194339
RESUSES - 194338

![image](https://user-images.githubusercontent.com/31770504/84720019-e4d7a580-af4a-11ea-8ed2-4502b27c2723.png)
![image](https://user-images.githubusercontent.com/31770504/84720073-0cc70900-af4b-11ea-9181-1fc0b553bde2.png)

Some examples that did auto-add the fee include:
194664, 192399, 190319

I was not able to replicate in test on permit 193465.

**Comment by ABonomo21** [comment]
164621 did not auto generate the fee today. I had to manually add it.

**Comment by megisys** [comment]
@ABonomo21 @JuanitaMiles , I can not duplicate this issue in TEst. It works for me everytime. I even used the examples in the ticket. I will run tonight to add the EXTREQ logs.. and I have added a message box if it goes wrong, so people can report the error

**Comment by megisys** [comment]
Adding a Version which will exclude Grading.. Or are we ok to now run these again ??

**Comment by ABonomo21** [comment]
this was working and not it is not again ! had a group of permits 193430 193431-193458 that all were resulted and did not auto generate the fee. Also permit 193401 did not generate the fee- reopening ticket 
also

**Comment by megisys** [comment]
Fixed. Jeff added in readiness for July 1 fee increases. Formula needs an adjustment. Removed July 1 revision
