### ISSUE TITLE
Fee Estimation Detail Pages 

### ISSUE THREAD

**Issue by ABonomo21** [dhenry-KCI/FredCo-Post-Go-Live-#586]
Fee Estimation detail pages for all building permits.

**Comment by megisys** [comment]
PLease Log into TEST and on RESBLDG (Only at this Point). PLease add the detail page to an existing Building Permit which the fees are not yet added.. OR... Start a fresh RESBLDG and see the Estimate Page. - Access Contol will need to be updated

**Comment by megisys** [comment]
![image](https://user-images.githubusercontent.com/47392306/86929929-682c8700-c104-11ea-8c02-0cf3ea3418a6.png)

**Comment by ABonomo21** [comment]
move
