### ISSUE TITLE
R4C- submit application header missing Planning/Zoning

### ISSUE THREAD

**Issue by MLWilkins** [dhenry-KCI/FredCo-Post-Go-Live-#589]
Bold header should read " Licences, Permits, Planning, and Zoning" and the descriptor below it should read "Apply for or renew a  license,  permit, Planning, or Zoning application"

![image](https://user-images.githubusercontent.com/50637067/85281982-e88e8f00-b458-11ea-8ccd-df774cb71a95.png)

**Comment by Ycoto** [comment]
@JuanitaMiles is done :)
![image](https://user-images.githubusercontent.com/63804011/85298031-8beb9e00-b471-11ea-9d88-5bfbec3516e5.png)

**Comment by MLWilkins** [comment]
header language still excludes Planning and Zoning


![image](https://user-images.githubusercontent.com/50637067/85301499-e4bd3580-b475-11ea-9d46-40e97fa4eaac.png)

@Ycoto

**Comment by Ycoto** [comment]
@MLWilkins I did miss that one, done now :)
![image](https://user-images.githubusercontent.com/63804011/85308025-b2fc9c80-b47e-11ea-9b54-9e3e9f176e7f.png)

**Comment by MLWilkins** [comment]
looks good, thank you @Ycoto
