### ISSUE TITLE
PLANNING - APFO - AWAITING LOU milestone

### ISSUE THREAD

**Issue by AReed327** [dhenry-KCI/FredCo-Post-Go-Live-#591]
Project Number - A258763
Observed behavior - LOU Review resulted Approved and application went back under awaiting LOU milestone. It was previously at Awaiting LOU. We processed a resubmit, the LOU Review populated. IT was resulted approved. It should have moved forward. It seems it's stuck in a loop. It should only go back to Awaiting LOU milestone if LOU Review is resulted as Resubmit.
Expected behavior - Application should proceed to next milestone.
Screenshot -
![image](https://user-images.githubusercontent.com/58854333/85741981-e0d91f80-b6d0-11ea-8e47-62e911625d06.png)

**Comment by MLWilkins** [comment]
I tested this in TEST and it works in TEST.  Bug in Production.

![image](https://user-images.githubusercontent.com/50637067/85779844-032f6500-b6f2-11ea-83af-c3369a9eec93.png)


![image](https://user-images.githubusercontent.com/50637067/85779954-1e9a7000-b6f2-11ea-9725-6836fd7602dd.png)

**Comment by megisys** [comment]
Hi Ashley,

The code was so bad. I made changes in both Test and Prod. As in Prod it never would work as it was.

**Comment by AReed327** [comment]
Worked in production A258763

**Comment by AReed327** [comment]
I think this can be closed.
