### ISSUE TITLE
Land Use Permits

### ISSUE THREAD

**Issue by ABonomo21** [dhenry-KCI/FredCo-Post-Go-Live-#593]
Land Use permits are not progressing correctly. 

Example L260017- did not add the fire final inspection prior to moving to complete. It bypassed the milestone of active and final inspection.,

**Comment by megisys** [comment]
This is now sitting at Final Inspection. Status Check was not holding hte inspection. I recreated it.

**Comment by ABonomo21** [comment]
Will monitor
