### ISSUE TITLE
Gaming Permit - Mostly Blank Issuance Report

### ISSUE THREAD

**Issue by JuanitaMiles** [dhenry-KCI/FredCo-Post-Go-Live-#595]
Gaming Permit G260023 - The Gaming Permit - Official Issuance report is running with only the Name of the applicant. None of the other typical language/formatting is appearing. 

Can you help us understand why this might be happening? I know that the permit is missing some typical information like start/end date, but I've been able to run the report in test without these dates and the report formatting will still look good, the dates will just be missing.

![image](https://user-images.githubusercontent.com/31770504/86078057-3c9e0280-ba5b-11ea-8112-8087cd112a8a.png)

**Comment by ABonomo21** [comment]
moved to future
