### ISSUE TITLE
Land Use Placard Missing Start/End Dates

### ISSUE THREAD

**Issue by JuanitaMiles** [dhenry-KCI/FredCo-Post-Go-Live-#596]
Issue reported by Abbie White:

I’ve got a Land Use permit  L260017 that we issued this morning but the placard will not show the start/end dates for the event. I’ve got the dates added in both the details page and on the job description but they still won’t show. They just say “NA”

![image](https://user-images.githubusercontent.com/31770504/86131773-10fb3680-bab4-11ea-9ecc-749709c8427b.png)
![image](https://user-images.githubusercontent.com/31770504/86131865-2e300500-bab4-11ea-9a0f-5674d1f23c8a.png)

**Comment by ABonomo21** [comment]
moved to future phase
