### ISSUE TITLE
PLANNING - Water and Sewer - Applications should be accepted from tax ID's within Municipalities

### ISSUE THREAD

**Issue by AReed327** [dhenry-KCI/FredCo-Post-Go-Live-#597]
Project Number - WS260291 I have provided a work around to get this application submitted, but this should be fixed ASAP.
Observed behavior - R4C will not accept applications in municipalities. It gives the error message that we do not accept this type of application on this parcel. This is the first water/sewer application for a property in a municipality
Expected behavior - There should be no parcel restrictions on R4C for properties in Municipalitites.
Screenshot -
![image](https://user-images.githubusercontent.com/58854333/86611768-291ff980-bf7d-11ea-9f26-bb5025f279f8.png)

**Comment by megisys** [comment]
Hi There,

How do I know this.. What is the parcel attribute I am checking for. OR are all Water and Sewer accepted from R4C

Dan

@AReed327 @JuanitaMiles

**Comment by AReed327** [comment]
all Water and Sewer accepted from R4C. No constraints.

**Comment by megisys** [comment]
PLN_ValidateTwnshipCode_CVPI - Updated

**Comment by AReed327** [comment]
Verified on WS260294 in Test. Set up through R4C with no error.
