### ISSUE TITLE
PLANNING - Water and Sewer Plan Amendment - Need to add associated site

### ISSUE THREAD

**Issue by AReed327** [dhenry-KCI/FredCo-Post-Go-Live-#598]
Project Number - WS260291 (Need this to be able to property process this application)
Observed behavior - Unable to add associated sites under WSPLANA Water and Sewer Plan Amendment
Expected behavior - Need to be able to add associated sites.
Screenshot -
Should look like this: 
![image](https://user-images.githubusercontent.com/58854333/86612914-d34c5100-bf7e-11ea-9f85-323f9e4503de.png)
But it actually looks like this. I am not able to add another site.
![image](https://user-images.githubusercontent.com/58854333/86613211-405fe680-bf7f-11ea-9c19-c58013ade4cd.png)

**Comment by megisys** [comment]
Addressed in Production.. As it was a constraint.. Can be changed during Intake Review, Awaiting Applicant resubmit Only. Unless you tell em otherwise

**Comment by AReed327** [comment]
Added in production to WS260291. Test accepted
