### ISSUE TITLE
Condo Home Builder Fees

### ISSUE THREAD

**Issue by JuanitaMiles** [dhenry-KCI/FredCo-Post-Go-Live-#599]
The home builder fee did not auto generate on condo units 287772-287780

![image](https://user-images.githubusercontent.com/31770504/86967617-e014a480-c138-11ea-8519-5af9dc713f40.png)

however it did on 2877771

![image](https://user-images.githubusercontent.com/31770504/86967679-f6bafb80-c138-11ea-9ece-044e9867d6b1.png)

home builder fee should be assessed on all CONDO units not the parent. and not on apartments.

**Comment by ABonomo21** [comment]
retested same permits and the fee generated. - AB
