### ISSUE TITLE
PLANNING/PDOX Due Dates from PDOX to IPS

### ISSUE THREAD

**Issue by AReed327** [dhenry-KCI/FredCo-Post-Go-Live-#6]
I do not have the ability to adjust the due date in PDOX. IPS over writes the due dates that are manually entered in PDOX. I do not have a way to change the due dates in PDOX once IPS has assigned them. 
I can manually change the due date in IPS but I need that due date to show in Project Dox.
You can see that I manually changed Health Department in IPS. 
![image](https://user-images.githubusercontent.com/58854333/70829738-6bed6a80-1dbc-11ea-8008-31ebf488e6a0.png)
![image](https://user-images.githubusercontent.com/58854333/70829761-7b6cb380-1dbc-11ea-80dc-44bd4d2f8c7b.png)

**Comment by megisys** [comment]
This fix will need to be tested and thought out in TEST. Not an isolated fix I can make over night. Due to the impact. this will need to be managed

**Comment by megisys** [comment]
I was wrong on this ticket.. IPS is allowing the update. Pdox is the one holding up the ability to change.

@dhenry-KCI . Can you ask Robert about this on his side. AS for these we will just update both sides when we hit one of these

**Comment by megisys** [comment]
@AReed327  Is this now solved ?

**Comment by AReed327** [comment]
Will monitor moving forward.

**Comment by AReed327** [comment]
This has turned into a large issue. Robert showed me how to change the due date in PDOX, When I do that, it sends another review to IPS. We need to have a way to make the due dates sync both ways. 
When I receive a plan, the due date is to be set from the time the plan is received. If I don't get to it until the following day because of workload, it sets the due date from the day I complete my task. I manually enter the correct due date based on when the project was received from the applicant and IPS overwrites the due date to the table that was created. I think this is a big, confusing issue that needs more discussion to come to a reasonable solution. AREED
PL257597 - example - you will see DPZ populated again. 
![image](https://user-images.githubusercontent.com/58854333/72081485-90116e00-32cc-11ea-8cd8-ea1abe40d1f7.png)

**Comment by MLWilkins** [comment]
can we get this ticket resolved today please?  This issue is the primary cause of the duplicate reviewers populating in IPS (due to the way Robert told Ashley to change the due dates in PDOX be deleting reviews and adding new ones), which is a separate ticket. This issue is causing a huge additional workload on Ashley.

**Comment by JuanitaMiles** [comment]
Dan is converting the formulas involved here to be "after update" formulas to not generate due dates in IPS until the assign reviewers (and due dates) task in PDox is completed.

**Comment by megisys** [comment]
PLN_ASSIGNREVIEWDUEDATE_BUF - PLease Promote

**Comment by ScottVanSooy** [comment]
Promoted 2020-01-13

**Comment by AReed327** [comment]
The change did not work. PL257695 - I changed the due dates to 2/4/2020 in PDOX and IPS changed them to 2/5/2020
![image](https://user-images.githubusercontent.com/58854333/72437606-174d5e80-3771-11ea-95f3-708bbd7d2694.png)
![image](https://user-images.githubusercontent.com/58854333/72437635-28966b00-3771-11ea-827f-e1bd9c104ddf.png)
![image](https://user-images.githubusercontent.com/58854333/72437653-31873c80-3771-11ea-959c-27d03d9d4892.png)

**Comment by megisys** [comment]
I am now letting all duedates be set from PDox

**Comment by AReed327** [comment]
IPS is not accepting and inserting the due dates on the IPS side of the review from PDOX. 
PW257696
SHA due date came over because that review was not generated in IPS. I added them in PDOX.
![image](https://user-images.githubusercontent.com/58854333/72537394-12a8a900-384a-11ea-986a-a3fd110578e2.png)

![image](https://user-images.githubusercontent.com/58854333/72537299-e42ace00-3849-11ea-975d-fed21efd20de.png)

**Comment by megisys** [comment]
I turned it back on.. I have tried everything. How many times do we need to update the default due dates. If it is only rarely, I might have another option ?

**Comment by AReed327** [comment]
It's very frequent. Any time a project is not routed on the day received it needs adjusted. All Fast Track projects need adjusted. 
When we went live, it was understood that we would be able to adjust these dates and the same date would be reflected in IPS and PDOX. 
I have also verified with PDOX that there is no other way to change the due date on their side than to pull back the review and set the due date. This adds another review to IPS so their functionality doesn't work for the combined systems. Again, I can set it when I assign reviewers but IPS overwrites that date.

**Comment by megisys** [comment]
Pdox Issue ? They are not passing Due Dates. Need a working party. Awaiting this to be managed by County

**Comment by JuanitaMiles** [comment]
We will be setting up a meeting between all parties involved to discuss our options for best resolving this issue. Meeting to include Avolve, Infor, County Staff, and KCI.

**Comment by megisys** [comment]
Formula PLN_ASSIGNREVIEWDUEDATE_BUF - will need to be disabled- If Test Accepted

**Comment by megisys** [comment]
Requires a Pdox production change for this to work.  This will be completed over the weekend.

**Comment by MLWilkins** [comment]
Tested with Ashely AReed, KCI, Avolve, and Infor staff via WebEx 2/5/20 with success

**Comment by AReed327** [comment]
Reviewed with Robert and Alejandro. Adjustment works. Dan to update IPS.

**Comment by megisys** [comment]
DO NOT PUSH UNTIL WEEKEND !

**Comment by calequin** [comment]
promoted on 2.9.2020
