### ISSUE TITLE
ResUse - DOLS Review

### ISSUE THREAD

**Issue by JuanitaMiles** [dhenry-KCI/FredCo-Post-Go-Live-#600]
DOLS review generated on a resuse permit and should not. 288182

![image](https://user-images.githubusercontent.com/31770504/86967826-2e29a800-c139-11ea-8d5c-c27f79c14dfd.png)

**Comment by megisys** [comment]
This Formula has been in place since go live. 

What are the rules for DOLS. Currently it is 

if Occupancy is in the list below

Case "RESACC", "RESAPT", "RESCAP", "RESCON", "RESMFD", "RESNRS"

**Comment by megisys** [comment]
PLease Update when you can !

**Comment by ABonomo21** [comment]
Dan- are these  there is no occupancy type of RESACC?
![image](https://user-images.githubusercontent.com/47611580/87083163-2a118f00-c1fa-11ea-9de3-3e93f4380ec5.png)

Are there additional rules on the remaining occupancy types as this review should only generate when it is a "PARENT" when occupancy type RESAPT, RESCAP, RESCON, RESMFD and RESNRS
@megisys

**Comment by megisys** [comment]
Huh.. This is a RESUSE permit. i dont see Parent ?

**Comment by ABonomo21** [comment]
Disregard - No RESUSE permit should have DOLS review regardless of the review. 

Thanks

**Comment by ABonomo21** [comment]
@megisys

**Comment by megisys** [comment]
DONE in Production !!

**Comment by megisys** [comment]
As this is only a data change. No Config here.

**Comment by megisys** [comment]
Hi Ashlye,

Make sure you review the ones that are out there

![image](https://user-images.githubusercontent.com/47392306/87087052-6f38bf80-c200-11ea-8105-70eacfe4c6bf.png)

**Comment by megisys** [comment]
![image](https://user-images.githubusercontent.com/47392306/87087259-cccd0c00-c200-11ea-9654-c1d87b8f2757.png)

**Comment by ABonomo21** [comment]
Thank you - The permits that are currently pending with this review have been cleaned up in production.
