### ISSUE TITLE
Health Review 

### ISSUE THREAD

**Issue by ABonomo21** [dhenry-KCI/FredCo-Post-Go-Live-#61]
Can someone help me understand why the health review shows it was approved by bhuffman when it was resulted by kamoss?? 
![image](https://user-images.githubusercontent.com/47611580/71114608-20610500-219e-11ea-82ba-c6147914b53a.png)

**Comment by megisys** [comment]
You will have to ask BHuffman

**Comment by calequin** [comment]
was resulted in hansen 7 by brenda as incomplete.
