### ISSUE TITLE
SRM Report - General - Building Permits - Building InfoViewer - Certificate of Completion

### ISSUE THREAD

**Issue by TaraF** [dhenry-KCI/FredCo-Post-Go-Live-#63]
On demand report only that needs to be moved to production from test.  Formula needs to go as well.

![image](https://user-images.githubusercontent.com/4104464/71115473-fc062800-219f-11ea-94fe-fd930f7f97a7.png)

![image](https://user-images.githubusercontent.com/4104464/71115490-07f1ea00-21a0-11ea-99fb-508eeb2caac8.png)

**Comment by megisys** [comment]
@TaraF , please do not assign to me. I am on leave and the team will miss. Leave them unassigned and the Team will assign when they pick it up

**Comment by ScottVanSooy** [comment]
Deployed to Production 12/18/19
