### ISSUE TITLE
SRM Report - General - Building Permits - Building InfoViewer - Certificate of Occupancy

### ISSUE THREAD

**Issue by TaraF** [dhenry-KCI/FredCo-Post-Go-Live-#64]
On demand report only that needs to be moved to production from test.  Formula needs to go as well.

![image](https://user-images.githubusercontent.com/4104464/71115701-864e8c00-21a0-11ea-8e76-74ff5062010a.png)

![image](https://user-images.githubusercontent.com/4104464/71115720-91092100-21a0-11ea-86c1-40e100a788e8.png)

**Comment by ScottVanSooy** [comment]
Deployed to Production 12/18/19
