### ISSUE TITLE
Migrate Code Violations 

### ISSUE THREAD

**Issue by ABonomo21** [dhenry-KCI/FredCo-Post-Go-Live-#66]
Christian talked to bob this morning - the code violations did not all migrate correctly - for questions please talk to bob ensor. 

jaensor@frederickcountymd.gov

![SnipImage](https://user-images.githubusercontent.com/47611580/71118345-e85dc000-21a5-11ea-8d1d-f981dc23cb82.JPG)

**Comment by calequin** [comment]
fixed in prod
