### ISSUE TITLE
R4C-Site Location-add language above comment box

### ISSUE THREAD

**Issue by MLWilkins** [dhenry-KCI/FredCo-Post-Go-Live-#67]
Please add the language highlighted below in as large a font as possible and in bold.

![image](https://user-images.githubusercontent.com/50637067/71171339-89db2500-222b-11ea-8c25-f8a6f5a18190.png)

**Comment by calequin** [comment]
@MLWilkins we got the issue fixed last night. It will now stop the applicant from going forward with a red line letting them know that they need to Search and Add a Primary site. Unfortunately R4C doesn't allow me to change fonts on this page which in turn makes the label unusable. The fix has been deployed in prod but feel free to test in R4C Test as well.
![image](https://user-images.githubusercontent.com/47603568/71181129-20621300-2239-11ea-82a3-395bd0aae3b6.png)

**Comment by MLWilkins** [comment]
tested fix on a FRO and a Site and issue is resolved.

![image](https://user-images.githubusercontent.com/50637067/71187069-58bf1c80-224c-11ea-8084-18b994b0d561.png)
