### ISSUE TITLE
Minor Logging - Under Review

### ISSUE THREAD

**Issue by TMARTIN0926** [dhenry-KCI/FredCo-Post-Go-Live-#68]
Minor Logging permit #205186 did not populate DPZ review. This is a required review for this type of permit.

![205186](https://user-images.githubusercontent.com/58991985/71176007-d710c400-2236-11ea-8968-5ac694526d4f.PNG)

**Comment by ABonomo21** [comment]
DPZ should generate as a review agency for logging. This was working prior to go live in test. 

Thanks, 

Ashlye

**Comment by calequin** [comment]
migrate GRADING_DPZ_Review_AOC
