### ISSUE TITLE
Major Logging Permit - Awaiting Applicant Revisions

### ISSUE THREAD

**Issue by TMARTIN0926** [dhenry-KCI/FredCo-Post-Go-Live-#69]
Permit #204151 is under the milestone of awaiting applicant revisions, however, there is not an applicant actions option in order to progress the permit forward.

![204151](https://user-images.githubusercontent.com/58991985/71182280-d16dab00-2243-11ea-973b-141bebf73d44.PNG)

**Comment by calequin** [comment]
this was migrated over. I have manually added the applicant actions detail page to this ap type. This will automatically add during milestone progressions
