### ISSUE TITLE
R4C- QUESTION

### ISSUE THREAD

**Issue by AReed327** [dhenry-KCI/FredCo-Post-Go-Live-#7]
Is it possible to add Project/Phase name to My Projects line? Customers with a large number of projects are having a hard time figuring out which project is which.

![image](https://user-images.githubusercontent.com/58854333/70831437-8f1a1900-1dc0-11ea-93fb-e9667f5bf4a5.png)

**Comment by megisys** [comment]
This is coming in future release. Not possible for now on the current level of software

**Comment by megisys** [comment]
Can you please let the county know which release this will be in ? @calequin

**Comment by calequin** [comment]
January Release with a 11.2 update of backoffice

**Comment by megisys** [comment]
closing as will need to be a project
