### ISSUE TITLE
minor grading permits - under review

### ISSUE THREAD

**Issue by TMARTIN0926** [dhenry-KCI/FredCo-Post-Go-Live-#70]
The ECS review is not populating under minor grading permits and it should be. Permit #258244

![258244](https://user-images.githubusercontent.com/58991985/71184962-8ace7f80-2248-11ea-915a-712c8edb4575.PNG)

**Comment by ABonomo21** [comment]
ECS reviews do not need to generate on minor grading permits any longer. SCD  is completing their  own reviews now.
