### ISSUE TITLE
Distributor Reports-Unable to insert Value of Bag 

### ISSUE THREAD

**Issue by mlibbey131** [dhenry-KCI/FredCo-Post-Go-Live-#71]
When I am inputting distributor reports I cannot input the “Value of Bag” it gives me an error of “Invalid Value for DistributorValueofBags” when I open the pop-up box it gives codes with different ranges of costs.

![1](https://user-images.githubusercontent.com/58980189/71185941-58258680-224a-11ea-8cbe-2f158fa916be.jpg)

![2](https://user-images.githubusercontent.com/58980189/71185949-59ef4a00-224a-11ea-9912-9c37b5538de9.jpg)

Christian send me a webx or call me when you are ready to look at this per Ashlye
301-600-6727 mlibbey@frederickcountymd.gov

**Comment by calequin** [comment]
spoke to megan via email.
-------------------------------------
Christian, 

I talked to Ashlye and she said this was good. 


If you have any questions, or need anything else, please do not hesitate to contact me. 


Thank you, 
Megan Libbey
Permits & Inspections
30 North Market Street
Frederick, MD 21701
P: 301-600-6727



From: Christian Alequin <Christian.Alequin@infor.com> 
Sent: Thursday, December 19, 2019 10:54 AM
To: Libbey, Megan <MLibbey@FrederickCountyMD.gov>
Cc: Bonomo, Ashlye <ABonomo@FrederickCountyMD.gov>
Subject: [FredCo] Distributor Report

[EXTERNAL EMAIL] 
Hi Megan,
Sorry I’ve been stuck on back to back calls but I did briefly look at your ticket. The distributor report uses the same format as the original paper copy the only difference is that in order for Backoffice to know which projected profit we had to add Lettering to the code. For example, Letter A = With a projected profit of $0-$100. On Rhythm this displays correctly with the description. Do we need to change it in back office to show the description in the detail page?
I can call you after the 11am meeting we have. 

Thanks

**Comment by dhenry-KCI** [comment]
@mlibbey131 - if this is no longer an issue please close.
