### ISSUE TITLE
Building Permits - Grading and FRO - Disable Inspection Result Notifications

### ISSUE THREAD

**Issue by JuanitaMiles** [dhenry-KCI/FredCo-Post-Go-Live-#75]
Please disable the inspection result notifications for the Grading Permit and FRO Permit application types. 

The two notification templates are BP_InspectionResulted and BP_PARTIALPASS.

These will be temporarily disabled until these applications are made available electronically.

**Comment by calequin** [comment]
@JuanitaMiles  BP_InspectionResultNotification_BU has been disabled for a couple of days. Are they getting new ones with notifications?

**Comment by ABonomo21** [comment]
re-enable formula make sure formula is updated not to send notification for grading and fro

**Comment by calequin** [comment]
promote BP_InspectionResultNotification_BU and enable

**Comment by calequin** [comment]
promoted on 1.9.2020

**Comment by JuanitaMiles** [comment]
Upon investigation it appears inspection result notifications are still sending to applicants. Screen shots of a FRO Permit below show an inspection was passed on 1/15/20 and the inspection result notification shows as sent to the applicant on the Communications tab on the contact record.

![FRO_Insp_1](https://user-images.githubusercontent.com/31770504/72756232-9dffa280-3b9a-11ea-9579-b76e487593a6.jpg)
![FRO_Insp_2](https://user-images.githubusercontent.com/31770504/72756233-9dffa280-3b9a-11ea-9816-b3af47efc80e.jpg)
![FRO_Insp_3](https://user-images.githubusercontent.com/31770504/72756234-9dffa280-3b9a-11ea-94fd-f1213a75ab03.jpg)

**Comment by calequin** [comment]
FIXED APPLICATION TYPE AS FROPERM INSTEAD OF FRO
Once tested please promote formula: BP_InspectionResultNotification_BU

**Comment by ABonomo21** [comment]
tested 1058555, permit 203156

no notification sent

**Comment by ABonomo21** [comment]
![image](https://user-images.githubusercontent.com/47611580/72991464-0b404d00-3dc0-11ea-945d-50874750a4fb.png)
