### ISSUE TITLE
Planning - Permissions - JHAGY2

### ISSUE THREAD

**Issue by AReed327** [dhenry-KCI/FredCo-Post-Go-Live-#76]
JHAGY2 and DLU should not be able to process payments. Please update permissions. Thanks.
![image](https://user-images.githubusercontent.com/58854333/71198801-9af35880-2262-11ea-83b4-1320e44f44d1.png)

**Comment by calequin** [comment]
Per meeting on 12/19 3pm. Discussion needed by county. CALEQUIN waiting on county to proceed with Access Control change

**Comment by AReed327** [comment]
Discussed with Ashlye. Remove DUSWM with Fees from PLANNING reviewers JHAGY, DLU and add the ability to waive fees and waive reviews to DUSWM regular.
We think most of the building users are in the DUSWM with fees, so adding the ability to waive fees and waive reviews to duswm regular would not really give other users additional privileges. 
We may need to discuss further if this is not the case. AREED

**Comment by calequin** [comment]
@AReed327 need clarification on this. DUSWM with Fees has the following users: Who needs to be able to waive fees? and do we remove the rest from this profile?
![image](https://user-images.githubusercontent.com/47603568/71749279-9b7f1800-2e3a-11ea-84d4-a1367f186908.png)

DUSWM_REGULAR has the following:
![image](https://user-images.githubusercontent.com/47603568/71749316-b05bab80-2e3a-11ea-8523-c7fa57d550ff.png)

**Comment by MLWilkins** [comment]
not able to test this.  Will close and monitor.
