### ISSUE TITLE
Techs need to see Expired Permit Info

### ISSUE THREAD

**Issue by awhite806** [dhenry-KCI/FredCo-Post-Go-Live-#77]
Per Ashlye-Permit Techs (Liz, Leslie, Linda, Brenda, Susan) need to be able to see the information for expired applications/permits.
![expired permit screenshot](https://user-images.githubusercontent.com/58981029/71202950-21ac3380-226b-11ea-8979-dee1423cf0f9.png)

**Comment by calequin** [comment]
fixed
