### ISSUE TITLE
Extension request 

### ISSUE THREAD

**Issue by ABonomo21** [dhenry-KCI/FredCo-Post-Go-Live-#78]
processed an extension request and the permit did not add the new official issuance or send the correspondence. 
![image](https://user-images.githubusercontent.com/47611580/71202990-37215d80-226b-11ea-9bb0-0c9dd9841be6.png)

**Comment by ScottVanSooy** [comment]
I'm going to need some clarification on this.  I think the issue is the detail page does not have Required Fields filled out, but  I'm  unclear what is expected to happen after that.

**Comment by ScottVanSooy** [comment]
Check coding with Dan.

**Comment by ScottVanSooy** [comment]
Fix correspondence in test.

**Comment by calequin** [comment]
spoke to scott and fixed in test

**Comment by ABonomo21** [comment]
working out process with Dan there is another ticket for this
