### ISSUE TITLE
Building - Elec. Perm

### ISSUE THREAD

**Issue by dhenry-KCI** [dhenry-KCI/FredCo-Post-Go-Live-#8]
Non-Res Service coming up as 39.00. Non Res-Service fee sohudl be $40.00

See permit 258144

Logged by Ashlye B.

![image001](https://user-images.githubusercontent.com/4129185/70876642-59c02780-1f88-11ea-94e2-acbb68e37860.png)

**Comment by megisys** [comment]
ElecPerm_NonresServLt100 - Needs to be updated to Use a Rate Table

**Comment by megisys** [comment]
PLease recalculate for today
