### ISSUE TITLE
Building Permits - NONRESBLDG - Fees Notification Generating Random Fee

### ISSUE THREAD

**Issue by JuanitaMiles** [dhenry-KCI/FredCo-Post-Go-Live-#80]
AP # 258078

Upon progressing to Awaiting Plan Review Payment the system sent the awaiting fee payment notification. The notification indicated that $199.00 was due but we do not know where/how this amount generated. Three of the fees automatically generated, totaling $81.00 which is the amount we would have expected to see on the notification. The two remaining fees were manually added to the application after the email sent.

![image](https://user-images.githubusercontent.com/31770504/71203633-579de780-226c-11ea-89e7-f1a3bc44d85c.png)

![image](https://user-images.githubusercontent.com/31770504/71203678-756b4c80-226c-11ea-8159-e15ad04bb8d3.png)

![image](https://user-images.githubusercontent.com/31770504/71203710-81efa500-226c-11ea-949d-78e195671fc5.png)

**Comment by JuanitaMiles** [comment]
![image](https://user-images.githubusercontent.com/31770504/71278471-b5dad100-2325-11ea-8c8f-d68a3eda11a5.png)

**Comment by ScottVanSooy** [comment]
Add Plan Review Fees milestone, this section of code would add the Fee.  Looks like this is the cause, but I need furthere analysis.


If (oBldgApp.WorkType.Code.Trim() = "NEW" OR oBldgApp.WorkType.Code.Trim() = "ADD" OR oBldgApp.WorkType.Code.Trim() = "ACCESS" ) AND NOT oBldgApp.OccupancyType.Code = "AGCULT" AND Ols = False  AND ZoneCert=False Then
			AddOnCondition = True
End If

**Comment by ScottVanSooy** [comment]
Check App for values.

**Comment by calequin** [comment]
I replicated this in test and I get the amount of $199. Which fees are correct? need to look during webex

**Comment by calequin** [comment]
the zoning fee populated different in test

**Comment by ABonomo21** [comment]
possible work type change
