### ISSUE TITLE
SFD Grading in Town

### ISSUE THREAD

**Issue by emilypearl1** [dhenry-KCI/FredCo-Post-Go-Live-#81]
permit #258424
Property is located in Town of Walkersville- there should not be a DPZ review

Reviewed by Ashyle

**Comment by emilypearl1** [comment]
[town grading sfd.pdf](https://github.com/dhenry-KCI/FredCo-Post-Go-Live-/files/3985598/town.grading.sfd.pdf)

**Comment by calequin** [comment]
fixed with another ticket.

**Comment by ScottVanSooy** [comment]
Deployed 2020-01-05
