### ISSUE TITLE
Reporting - School and Library Impact Fees Reports Not Allowing Date Range

### ISSUE THREAD

**Issue by JuanitaMiles** [dhenry-KCI/FredCo-Post-Go-Live-#82]
Both School and Library Impact Fee on-demand reports are not requiring a date range to be input before running. It just generates a report with February 2018 dates.

![image](https://user-images.githubusercontent.com/31770504/71211510-49a49280-227d-11ea-8fe7-0597a0c15f24.png)

![image](https://user-images.githubusercontent.com/31770504/71211526-50cba080-227d-11ea-9547-cd0f8cb57bb5.png)

**Comment by TaraF** [comment]
@JuanitaMiles  - this is fixed now.  Can you pass it on to whoever needs to re-test?  Also I am putting a request into Infor to drop the second report above from PROD as it is a duplicate, they are exactly the same.

**Comment by JuanitaMiles** [comment]
I have tested myself. Confirmed fixed 12/23/19
![image](https://user-images.githubusercontent.com/31770504/71367678-c3859600-2573-11ea-9abf-e3e0dee3b05b.png)
