### ISSUE TITLE
Service Heavy Up Electrical Permit 

### ISSUE THREAD

**Issue by ABonomo21** [dhenry-KCI/FredCo-Post-Go-Live-#85]
the res minimum fee is generating on a service heavy up permit but the fee is blank and is not required. Res min fee should be met if the total fees are less than $49

please let me know if you have questions. 

![image](https://user-images.githubusercontent.com/47611580/71253789-e6efdd00-22f6-11ea-8e58-a2bc40ee1edb.png)

**Comment by calequin** [comment]
this was fixed with a formula change in another ticket
