### ISSUE TITLE
Hold Report and Correspondence 

### ISSUE THREAD

**Issue by ABonomo21** [dhenry-KCI/FredCo-Post-Go-Live-#86]
i put a hold on this permit yesterday and it did not send the correspondece with the hold report and it is not an attachment... ?

![image](https://user-images.githubusercontent.com/47611580/71254802-1522ec00-22fa-11ea-9fc5-25fdba7ce408.png)

**Comment by calequin** [comment]
batch manager was not running on this day. This has been corrected by @ScottVanSooy

**Comment by ABonomo21** [comment]
will run a test on this
