### ISSUE TITLE
PLANNING - PDOX - Quick Review Summary Report - not working

### ISSUE THREAD

**Issue by AReed327** [dhenry-KCI/FredCo-Post-Go-Live-#87]
Highlighted report not working
![image](https://user-images.githubusercontent.com/58854333/71257869-cc236580-2302-11ea-880e-63ba8af5984e.png)

**Comment by JuanitaMiles** [comment]
I've tried to run the report and get just get a white screen. I emailed Robert for his investigation on this report. (1/7/20 4:06 PM)

**Comment by AReed327** [comment]
Elected to remove this report because we are not using this feature. AREED
