### ISSUE TITLE
Map Browser- Action button?

### ISSUE THREAD

**Issue by emilypearl1** [dhenry-KCI/FredCo-Post-Go-Live-#88]
Is there  a purpose for the Action Button? It doesn't do anything?

**Comment by emilypearl1** [comment]
[Capture.pdf](https://github.com/dhenry-KCI/FredCo-Post-Go-Live-/files/3988681/Capture.pdf)

**Comment by calequin** [comment]
yes but this is also security driven. The action button on this screen will allow users to start applications on a map etc. Do we need it enabled? if so, for who?

**Comment by emilypearl1** [comment]
WE don't need this.
