### ISSUE TITLE
Rhythm Delay when using signed out look up feature

### ISSUE THREAD

**Issue by AReed327** [dhenry-KCI/FredCo-Post-Go-Live-#89]
Rhythm Delay - customer complaint - I verified long delays.  
Trying to look up project comments. Engineer is accessing Lookup Record (A/P 20067) when they get in and click on View Details, it spins and spins every time you try to look up something.
![image](https://user-images.githubusercontent.com/58854333/71264151-6be7f000-2311-11ea-9f40-2356803b26bc.png)

![image](https://user-images.githubusercontent.com/58854333/71264191-85893780-2311-11ea-8e82-dc47d6011bfe.png)

**Comment by calequin** [comment]
reviews on public had some constraints for visibility. This was causing a speed issue. Fixed the public view and now it loads much faster.

**Comment by AReed327** [comment]
Thanks Christian.

Ashley Reed
Development Review Technician II
Department of Development Review
Frederick County Government
30 North Market Street
Frederick, Maryland 21701
(301)-600-1139
AReed@FrederickCountyMD.gov<mailto:AReed@FrederickCountyMD.gov>

**Comment by AReed327** [comment]
Christian corrected
