### ISSUE TITLE
R4C - Site Address

### ISSUE THREAD

**Issue by dhenry-KCI** [dhenry-KCI/FredCo-Post-Go-Live-#9]
In addition to the Planning modules, Ashlye B. emailed that citizens continue to populate the comments box with the site address which is preventing the applicant from submitting. 

Can we update:
- Update the language to be more clear about selecting an address using the button ?
- dynamically display the comment box only after an address is selected?
- Other thoughts?

**Comment by megisys** [comment]
Logged with our Support Team. - Christian pleas mock up some new language on the TEST site so we can see if we like the stronger language

**Comment by calequin** [comment]
![image](https://user-images.githubusercontent.com/47603568/70917768-8fdec500-1fe3-11ea-9f83-5fea93f2b889.png)

**Comment by calequin** [comment]
added this verbiage in test rhythm site. If approved I can deploy to R4C Prod

**Comment by megisys** [comment]
Deploy to Production Please.  But make the change. Comment box below is only for additional site details once an address is selected. @calequin

**Comment by calequin** [comment]
added to prod r4c
![image](https://user-images.githubusercontent.com/47603568/70925109-4f397880-1ff0-11ea-9ca4-74acf18b420e.png)
