### ISSUE TITLE
All Permits - Add Milestone Column to "Other Applications and Cases" Related Records Grid

### ISSUE THREAD

**Issue by JuanitaMiles** [dhenry-KCI/FredCo-Post-Go-Live-#90]
Can we please add a column for the Milestone to the Other Applications and Cases grid on the Related Records tab?

![image](https://user-images.githubusercontent.com/31770504/71264545-532c0a00-2312-11ea-9de4-1d6ddc48ea39.png)

**Comment by calequin** [comment]
the other application and cases field doesnt allow for milestone grid since it is on different product families. keeping this as enhancement

**Comment by JuanitaMiles** [comment]
added to future phases list, closing per ashlye
