### ISSUE TITLE
Plumbing R4C Details page 

### ISSUE THREAD

**Issue by ABonomo21** [dhenry-KCI/FredCo-Post-Go-Live-#92]
please move the section complete to the box to the bottom of the details page- 
plumbing permits 
![image](https://user-images.githubusercontent.com/47611580/71266342-2ed22c80-2316-11ea-95e0-b47a2ea3b48d.png)

**Comment by calequin** [comment]
fixed
![image](https://user-images.githubusercontent.com/47603568/71284610-bc1e7c80-2328-11ea-8472-69271f500def.png)
