### ISSUE TITLE
DUSWM REVIEW - BUILDING PERMIT 

### ISSUE THREAD

**Issue by ABonomo21** [dhenry-KCI/FredCo-Post-Go-Live-#93]
Duswm review generated on a non- res building permit when even though the capacity permit already generated. 

the review is completed under the capacity permit not the building permit. 
![image](https://user-images.githubusercontent.com/47611580/71266887-54ac0100-2317-11ea-85f7-6fd12e663542.png)

**Comment by ABonomo21** [comment]
this permit went to resubmit and did not generate a duswm review in pdox but did in back office and i am not able to bypass it. 

![image](https://user-images.githubusercontent.com/47611580/71489985-7d8c3480-27f6-11ea-8951-873fa9551959.png)

![image](https://user-images.githubusercontent.com/47611580/71489991-8846c980-27f6-11ea-852b-f2579a570f67.png)

**Comment by ABonomo21** [comment]
failed, i am not able to by pass the Duswm review still

**Comment by calequin** [comment]
fixed. added REVOVER to ABONOMO Employee record under job classification.
@ABonomo21 which staff members need to have this review override ability. This will allow users to override eplans review in backoffice. Need a list of employees

**Comment by ABonomo21** [comment]
fixed

**Comment by JuanitaMiles** [comment]
Re-opening per Ashlye's request. Her comments and screenshot are below:
AP # 265420
![image](https://user-images.githubusercontent.com/31770504/75281945-2f87b300-57de-11ea-9429-9b25a7c88b34.png)
![image](https://user-images.githubusercontent.com/31770504/75282057-61007e80-57de-11ea-9eb5-8ab21696486d.png)

**Comment by ABonomo21** [comment]
adding another example of a permit on well and septic now that generated a duswm review 
![image](https://user-images.githubusercontent.com/47611580/75686498-57599980-5c6a-11ea-8114-6e18892a4f87.png)

**Comment by pooldaddy** [comment]
Expired review DUSWMF for Non ResBLDG in TEST
![image](https://user-images.githubusercontent.com/47391482/76223004-9d29db00-61f1-11ea-81bc-88405e3f746f.png)

**Comment by ABonomo21** [comment]
retested 266752 
![image](https://user-images.githubusercontent.com/47611580/76453926-1a984b80-63aa-11ea-895a-8ed3748e1c7c.png)
