### ISSUE TITLE
Building Permits - Capacity - Spring View Estates Subdivision Fees

### ISSUE THREAD

**Issue by JuanitaMiles** [dhenry-KCI/FredCo-Post-Go-Live-#94]
CAPACITY - RESIDENTIAL SINGLE FAMILY DWELLING
AP # 258425

The Spring View Estates subdivision code 041244 needs to automatically add the RESIDENTIAL SEWER FEE 20400 ($7509.00) when it is a residential occupancy type.

Terry manually added these fees to the application in PROD.

![image](https://user-images.githubusercontent.com/31770504/71267012-9046cb00-2317-11ea-99e4-ca769f5fd546.png)

![image](https://user-images.githubusercontent.com/31770504/71267050-a5bbf500-2317-11ea-81a7-5f649d2ee1e3.png)

**Comment by calequin** [comment]
Fixed in test. please promote CAPACITY_ResSewer20400_Fee_AOC

subdivsion 041244 was missing

**Comment by JuanitaMiles** [comment]
Email DUSWM to confirm the issue is fixed. Closing for now.
