### ISSUE TITLE
CORRESPONDENCE IS NOT RUNNING!

### ISSUE THREAD

**Issue by ABonomo21** [dhenry-KCI/FredCo-Post-Go-Live-#95]
![image](https://user-images.githubusercontent.com/47611580/71267921-c1c09600-2319-11ea-94e8-7ee8eb649ac1.png)

WE ARE GETTING CALLS AGAIN THAT PEOPLE ARE NOT GETTING THEIR CORRESPONDENCE....

**Comment by ScottVanSooy** [comment]
I've sent the correspondence that was delayed.. There is still more research to be done.  In the meantime, I'll have to ensure the schedule is running daily.

**Comment by ScottVanSooy** [comment]
This is continually working now

**Comment by ABonomo21** [comment]
opened a new ticket for what was not running - will work with dan
