### ISSUE TITLE
Building Permits - Capacity - Application Cannot Progress ERROR MESSAGE

### ISSUE THREAD

**Issue by JuanitaMiles** [dhenry-KCI/FredCo-Post-Go-Live-#96]
CAPACITY - RESIDENTIAL SINGLE FAMILY DWELLING
AP # 258425, 258423

This application is stuck in the Add Fees milestone. Terry has added the necessary fees. When she checks the check status button, she gets the error below. 

This is an application in Walkersville. This is the same notification error that was supposedly resolved by Dan the first week of Go-Live. The application cannot progress forward. It needs to be fixed ASAP.

![image](https://user-images.githubusercontent.com/31770504/71267854-99389c00-2319-11ea-9a77-7952d3620d28.png)

![image](https://user-images.githubusercontent.com/31770504/71267879-a5bcf480-2319-11ea-868d-b6e7f2e191ae.png)

![image](https://user-images.githubusercontent.com/31770504/71267902-b2414d00-2319-11ea-8ec0-7a7d1470c047.png)

**Comment by calequin** [comment]
added stopnot log for now while we fix the formula

**Comment by dhenry-KCI** [comment]
@ScottVanSooy - removed Christian from the assignee list since he is out. Please look into this in the am.

**Comment by megisys** [comment]
This issue has been addressed with a custom Formula Update.

**Comment by JuanitaMiles** [comment]
Requested DUSWM to confirm error is fixed the next time a Walkersville application comes in. Closing for now, will reopen if another error is reported.
