### ISSUE TITLE
Missing issuance name 

### ISSUE THREAD

**Issue by ABonomo21** [dhenry-KCI/FredCo-Post-Go-Live-#97]
i have being seeing applications issued without an issued by name.. 
![image](https://user-images.githubusercontent.com/47611580/71268242-7e1a5c00-231a-11ea-85aa-6480ef8990d6.png)

**Comment by ScottVanSooy** [comment]
This is odd, there really isn't any formulas I can find that might be setting this wrong.  I'll dig in more on Thursday.

**Comment by ABonomo21** [comment]
why is the issued name still missing ? 

![image](https://user-images.githubusercontent.com/47611580/71531429-9c54fe80-28bc-11ea-80e8-944cc219bab5.png)

**Comment by ScottVanSooy** [comment]
The best I can determine at this point is it appears to be a product issue.  I will bring it up with Infor Development.  I can't find any reason why that wouldn't be set .

**Comment by ScottVanSooy** [comment]
I think I found it.  The employee record for AVOLVE is invalid.  I will fix that now.

**Comment by ScottVanSooy** [comment]
Could someone tell me what the first name for Employee AVOLVE would be?
I’m assuming the  last name  is VOLVE and the email is AVolve@FrederickCountyMD.gov<mailto:AVolve@FrederickCountyMD.gov>?  Can you please confirm?

Thanks,

Scott

**Comment by ScottVanSooy** [comment]
Or am I just being stupid and AVOLVE is a software product?

From: Scott VanSooy
Sent: Friday, December 27, 2019 12:39 PM
To: dhenry-KCI/FredCo-Post-Go-Live- <reply@reply.github.com>; dhenry-KCI/FredCo-Post-Go-Live- <FredCo-Post-Go-Live-@noreply.github.com>
Cc: Assign <assign@noreply.github.com>
Subject: RE: [dhenry-KCI/FredCo-Post-Go-Live-] Missing issuance name (#97)

Could someone tell me what the first name for Employee AVOLVE would be?
I’m assuming the  last name  is VOLVE and the email is AVolve@FrederickCountyMD.gov<mailto:AVolve@FrederickCountyMD.gov>?  Can you please confirm?

Thanks,

Scott

**Comment by ABonomo21** [comment]
Avolve is PDox

**Comment by ScottVanSooy** [comment]
AVOLVE has a valid Employee and Contact record now.  I believe the the problem will be resolved.  Let me know if you experience this again.

**Comment by ABonomo21** [comment]
will re-open a new ticket for any permits that have this issue moving forward.
