### ISSUE TITLE
extension reviews on building permits 

### ISSUE THREAD

**Issue by ABonomo21** [dhenry-KCI/FredCo-Post-Go-Live-#98]
we are getting the error again on resulting an extension review. 

Dan fixed this twice already since going live... we are attempting to deny the request 

![image](https://user-images.githubusercontent.com/47611580/71268765-b79f9700-231b-11ea-8b06-eee5faee3bfe.png)

**Comment by ABonomo21** [comment]
this is still a problem and needs to be corrected I have been trying to result this review and this ticket is 7 days old. Please make this a priority @dhenry-KCI 

![image](https://user-images.githubusercontent.com/47611580/71518851-d6a1aa00-2882-11ea-804e-96a71dc292d1.png)

**Comment by megisys** [comment]
@ScottVanSooy - I THink you addressed this one for me. Do you recall this ?

**Comment by ScottVanSooy** [comment]
I don’t recall Dan, I will look at it this morning.

**Comment by calequin** [comment]
please promote BP_ExtensionReviewSetDateFee_BUF

**Comment by ScottVanSooy** [comment]
Promoted 2020-01-05
