### ISSUE TITLE
Building Permit - Foundation only 

### ISSUE THREAD

**Issue by ABonomo21** [dhenry-KCI/FredCo-Post-Go-Live-#99]
the building review did not generate on a foundation only permit and should have 
![image](https://user-images.githubusercontent.com/47611580/71269739-03ebd680-231e-11ea-9c57-22aaa9221972.png)

**Comment by ScottVanSooy** [comment]
I'm going to need some clarification on this one before making changes.

**Comment by ScottVanSooy** [comment]
PLN-REV review needs to generate.

**Comment by ScottVanSooy** [comment]
remove FOUN-SLAB

**Comment by ScottVanSooy** [comment]
Promote 
NONRESBLDG_PLNREV_Review_AOC

**Comment by ScottVanSooy** [comment]
Promote 2020-01-09
